### ISSUE TITLE
Where is the source code for sphinx-mqtt?

### ISSUE THREAD

**Issue by tyler-nguyen** [stakwork/sphinx-tribes#10]
I see that mqtt has been decoupled in commit 11d70b868f08dc62ca1cdaafc1925539ce1e5e49. Where is the source code for `sphinx-mqtt` now?

**Comment by kevkevinpal** [comment]
looks like its in a private repo now https://github.com/stakwork/sphinx-mqtt

@Evanfeenstra is there any reason why this cant be open sourced?
