### ISSUE TITLE
Change "add" button to "select" when adding a new member

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1000]
When adding a new member, we have buttons to the right that say "add". We also have a large "add user" button. Let's change the word "add" to "select" instead so it's not confusing or redundant. 

<img width="927" alt="Screenshot 2023-11-27 at 11 09 43 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/8611c643-f98e-40f8-bbbf-cb5dda0413ec">

### Acceptance Criteria

- [ ] I have tested on Chrome
- [ ] I posted a video of me adding a new user with "select"

**Comment by Khaalid-oh** [comment]
Test

**Comment by ecurrencyhodler** [comment]
Closed by #1017
