### ISSUE TITLE
Host SuperAdmin on community.sphinx.chat/admin

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1002]
Just make an empty white page that appears on community.sphinx.chat/admin

Also create a Superadmin folder under the frontend/app/src/admin.

### Acceptance Criteria

- [ ] I've tested on Chrome
- [ ] I've posted a video of my going to the website community.sphinx.chat/admin and displaying a blank page.

**Comment by gouravmpk** [comment]
Assign

**Comment by gouravmpk** [comment]
This is done please check PR : https://github.com/stakwork/sphinx-tribes/pull/1022
@ecurrencyhodler

**Comment by ecurrencyhodler** [comment]
Closed by #1031
