### ISSUE TITLE
Enable access to superadmin pt.1

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1003]
There will be two parts to this ticket. In the beginning, we will open up access to superadmin to anyone with a sphinx chat account to make it easier for contributors to test. This will be hosted on community.sphinx.chat/admin. 

Use this code for reference: https://github.com/stakwork/sphinx-tribes/tree/master/frontend/app/src/people/auth

Pt.2 will restrict login to authorized users only. 

Here's the [link to figma.](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=8979%3A29806&mode=design&t=puTATqcQ10WeYYbO-1)

![Log in](https://github.com/stakwork/sphinx-tribes/assets/32662508/a0465b9c-a35d-46a4-b608-6d915b72ee8b)

**Comment by gouravmpk** [comment]
@ecurrencyhodler I have some queries
 1.do we need to host this under /admin 
 if Yes then
 2. do we need to implement the same functionality mentioned it in 
  https://github.com/stakwork/sphinx-tribes/tree/master/frontend/app/src/people/auth

**Comment by ecurrencyhodler** [comment]
@gouravmpk not right now. If we did then contributors wouldn't be able to test locally for future prs. This will be the last step which is addressed in #1004 . Thanks for double-checking though.

**Comment by ecurrencyhodler** [comment]
Done!

**Comment by ecurrencyhodler** [comment]
We decided this was no longer necessary. If someone is logged into the platform and have the right permissions, they can go straight to the /admin page and see it.
