### ISSUE TITLE
[Date Range] Implement default time filters

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1008]
Implement the frontend and api calls for the date range filters of 7/30/90 days. We will handle "custom" in a separate issue( #1009 ).

### User Story
As a user, I log into superadmin and get the latest data from postgres.

### Technical Details
1. Once a user logs-in and call is returned successfully, make two calls to the backend to get the data.
2. The two calls are `metrics/bounty_stats` and `metrics/bounties`. 

The default window is 7 days. The API is called again when the user changes the filter to 30 or 90 or custom. 

### Design
Here is an image of the dashboard. See the next image below that for what the basic dropdown menu will look like.

![Bounties V1 (5)](https://github.com/stakwork/sphinx-tribes/assets/32662508/08acc2e4-2779-41a0-b450-c1d283e70830)

Default date range menu. You can leave the "Custom" button unclickable:
![Type=Dropdown (1)](https://github.com/stakwork/sphinx-tribes/assets/32662508/b5aaab90-64bf-4003-b9dd-2a9f003cdf43)

The 7/30/90 days are clickable. And when they are clicked, the same api calls are made again to refresh the stats.

Here's the [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=9392%3A16431&mode=design&t=ig7uLBR7ObccrfVU-1). Use dev mode for specific dimensions.

### Acceptance Criteria
- [ ] I've tested on chrome desktop
- [ ] I've posted a recording of me going through each of the 7/30/90 day default filters and the dashboard correctly displaying data
- [ ] I have created mockdata for the component test
- [ ] I have created a component test to click on the button for the date time filter and then clicking on the 7/30/90 default time ranges
- [ ] I have created a component test to show that stats are appearing
- [ ] Here is an example of a [component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by Vayras** [comment]
Hi @ecurrencyhodler I have addressed this issue , can you please assign this to me

**Comment by ecurrencyhodler** [comment]
@Vayras your video doesn't show the dropdown ui in figma. Make sure to include that in your PR.

**Comment by ecurrencyhodler** [comment]
Make sure to include tests as outlined in the ticket as well.

**Comment by Vayras** [comment]
@ecurrencyhodler  Okay I will update the Design

**Comment by Vayras** [comment]
have updated the ui and the test file as well ,also tested the new ui on chrome and firefox
 https://drive.google.com/file/d/1_tkO1b74kX59NvECXS8fj9pL1IJHDcit/view?usp=sharing

**Comment by ecurrencyhodler** [comment]
GJ with the dropdown UI! Thanks! Let's get a code review.

**Comment by Vayras** [comment]
> GJ with the dropdown UI! Thanks! Let's get a code review.

Thanks

**Comment by ecurrencyhodler** [comment]
Closed by #1223
