### ISSUE TITLE
[Date Range] Implement custom time filters

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1009]
Implement the custom date range option in the button "7 days" on the top right. Call postgress to grab the data. Below are the API calls.

- Metrics (top dashboard): metrics/payments
- Bounty (bottom dashboard): metrics/bounties

Here is an image of the dashboard. See the next image below that for what the basic dropdown menu will look like.
![Bounties V1 (5)](https://github.com/stakwork/sphinx-tribes/assets/32662508/08acc2e4-2779-41a0-b450-c1d283e70830)

First click "custom". The 30 days is emphasized because it has been selected.
![Type=Dropdown](https://github.com/stakwork/sphinx-tribes/assets/32662508/8e994b54-2926-40ee-978e-4cd74d4bba1a)

Then they'll move to this date selection screen.
![Type=Dropdown Date (1)](https://github.com/stakwork/sphinx-tribes/assets/32662508/0fd60af1-e041-41f0-aff2-57fc3637d2c1)

Once they click on a date range, a calendar will appear like below:
![Type=Dropdown Calendar](https://github.com/stakwork/sphinx-tribes/assets/32662508/a4bc65d9-a6ca-449f-96b9-c67a5be168ac)

You can find the [figma here](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=9392%3A16431&mode=design&t=ig7uLBR7ObccrfVU-1). Use dev mode for specific dimensions.

### Acceptance Criteria

- [ ] I have tested on Chrome Desktop
- [ ] I have posted a video of me setting a custom date range and the dashboard showing the correct data
- [ ] Create two component tests for the date selection screen and the calendar scene

**Comment by ecurrencyhodler** [comment]
Blocked by #1008

**Comment by Vayras** [comment]
hey @ecurrencyhodler can I work on this issue , if this is available?

**Comment by ecurrencyhodler** [comment]
Hey @Vayras yes let me scope this first.

**Comment by Vayras** [comment]
> Hey @Vayras yes let me scope this first.

Thanks, let me know

**Comment by Vayras** [comment]
@ecurrencyhodler Is this available to work on now? , if so can you assign me to this.

**Comment by ecurrencyhodler** [comment]
hey it is! But I see that you're working on 3 bounties. Let's keep this open for another hunter for now. I'll ping you if anything changes.

**Comment by Vayras** [comment]
@ecurrencyhodler Yeah sure no problem , Let me know if it is still available after my PR is merged ,Thanks 👍

**Comment by vishnu552** [comment]
@ecurrencyhodler i came across this issue,let me know if i can work on this if you can assign me this.

**Comment by ecurrencyhodler** [comment]
Hey @vishnu552 welcome! I'd love to assign this to you. 

Are you on sphinx chat? We have a bitcoin bounty for this if you're interested!
https://community.sphinx.chat/bounty/1042

**Comment by vishnu552** [comment]
i am not on sphinxchat can you tell me more about it or onboard me

**Comment by ecurrencyhodler** [comment]
Absolutely!

You can download the app here: https://buy.sphinx.chat/

Use those code to sign up as a new user: 
connect::relay.swarm4.sphinx.chat::02fe0c09166d8bb2a9ab589fb3b00a4683ead88a35d7000efad1b3900903df14e3

Then log into this website and I'll add you to the bounty: https://community.sphinx.chat/bounties

BTW how did you find our project?

**Comment by vishnu552** [comment]
@Vayras told me about this project and issue

**Comment by ecurrencyhodler** [comment]
Amazing! You should've received an email update from github but I'll email you directly.

**Comment by vishnu552** [comment]
@ecurrencyhodler  i cannot  scan the QR from the app i have logged in the app.

**Comment by ecurrencyhodler** [comment]
Are you trying to log in to the bounties website?

**Comment by vishnu552** [comment]
@ecurrencyhodler just signed in to the website

**Comment by ecurrencyhodler** [comment]
@vishnu552 do you have an update? Would like to get this wrapped up ASAP

**Comment by vishnu552** [comment]
<img width="334" alt="filter-calendar" src="https://github.com/stakwork/sphinx-tribes/assets/110402767/2781b18a-0916-4d9b-bb6c-71f8ddacf45f">
@ecurrencyhodler sorry for delay, calendar design is ready and there are some errors that i am fixing it by the end of this week i'll push a request.

**Comment by ecurrencyhodler** [comment]
Thanks!
