### ISSUE TITLE
Implement left and right arrow adjustments of timebox

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1010]
Once a date range is selected on the top right through the "last 7 days" button, the left and right arrow will help me quickly jump forward or backward in dates by using the same date range criteria.

Use moments to do pagination between dates. Functions to subtract or add from both start and end date: 
- Right arrow: moment().add(7, 'd').unix();
- Left arrow: moment().substract7, 'd').unix();

The .unix() ending automatically converts the date into unix timestamp. This then gets sent to the backend through this call: metrics/bounty_stats

This affects not just the stats on the top of the dashboard but also the bounties displayed below. Use moments to do these manipulations.

You must also display the correct date, month, and year displayed to the right of the buttons.

![Bounties V1 (5)](https://github.com/stakwork/sphinx-tribes/assets/32662508/08acc2e4-2779-41a0-b450-c1d283e70830)

### Acceptance Criteria

- [ ] I've tested on Chrome
- [ ] I've posted a video of toggling the left and right button between dates
- [ ] I've created a component test when the left arrow backward is clicked, the start date that the moment has selected should match the text of the start date displayed to the right of the buttons.
- [ ] I've created a component test when the left arrow backward is clicked, the end date that the moment has selected should match the text of the the end date displayed to the right of the buttons.

**Comment by Vayras** [comment]
@ecurrencyhodler , I have Implemented this functionality with mock bounty data,  during my implementation of the page , I have tested this.

**Comment by Vayras** [comment]
@ecurrencyhodler Follow up on the this task have completed most of the work just have to fix some minor bugs, will finish this soon
https://github.com/stakwork/sphinx-tribes/assets/89837102/456d6d50-b286-4ce2-9b3b-f29a02db7a46

**Comment by ecurrencyhodler** [comment]
Thanks! Looks good so far.

It looked like you had to click on the arrow for the site to update again after you selected 30 days. But that should be addressed in #1008

**Comment by Vayras** [comment]
@ecurrencyhodler I have fixed that as well

**Comment by ecurrencyhodler** [comment]
Closed by #1223
