### ISSUE TITLE
Implement Logout of SuperAdmin

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1011]
When a user clicks "Sign Out", delete the token from the browser in local storage. This triggers logging out of super admin.
![Bounties V1 (5)](https://github.com/stakwork/sphinx-tribes/assets/32662508/08acc2e4-2779-41a0-b450-c1d283e70830)

### Acceptance Criteria

- [ ] I've tested on Chrome
- [ ] I've posted a video of this function working

**Comment by dranoid** [comment]
Hey @ecurrencyhodler, i'd like to sort this one out

**Comment by ecurrencyhodler** [comment]
Amazing! Good to see you contribute again. You can find the field we created in the PR linked to this issue: https://github.com/stakwork/sphinx-tribes/issues/1134

I'll assign the bounty to you as well.

Welcome back dranoid. :)

**Comment by ecurrencyhodler** [comment]
@dranoid actually I'm so sorry. I met with the team and it looks like we're going to embed this into the bounties website. Therefore a log out system already exists. So I'm going to close this ticket. 

If you want, I can do a small bounty of 50k sats to remove the signout button if you'd like. Would you be open to that?

**Comment by gouravmpk** [comment]
@ecurrencyhodler Can I take this one if you just want remove signout button

**Comment by ecurrencyhodler** [comment]
Let's see if dranoid responds. @dranoid do you want to take this one? If, not gourav you can take it. Let's wait 2 days.

**Comment by ecurrencyhodler** [comment]
@gouravmpk I'm going to close this issue but create a separate one for you.
