### ISSUE TITLE
Implement "sort by" in the bottom half of the dashboard

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1012]
The default selection when viewing bounties is newest to oldest. But also add the ability to see oldest to newest. 

Create a dropdown menu that says "newest" first and then "oldest" second when they click on "date". 

### Technical details

You can use the following query parameter: created&direction=DESC&open=true&assigned=true&paid=true

The second part of this parameter includes the status of the bounty. Don't worry about setting the status of tickets for now. Just default to all as true as that is the default query. 

### Design

Here is the design. Here's the link to [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=9955%3A15473&mode=design&t=qS9KPeJQmBx6jB5u-1). Use [devmode](https://www.figma.com/dev-mode/) for exact requirements. We want this to be pixel perfect. 
![Dashboard button Super Admin filter](https://github.com/stakwork/sphinx-tribes/assets/32662508/a21239a6-a41a-498e-b958-bedfe6c53eb9)

![Bounties V1 (5)](https://github.com/stakwork/sphinx-tribes/assets/32662508/08acc2e4-2779-41a0-b450-c1d283e70830)

### Acceptance Criteria

- [ ] I've tested on Chrome
- [ ] I've posted a video of sorting oldest and newest

@elraphty will create a separate ticket to create mockdata and a unit test for this component.

**Comment by VividhPandey003** [comment]
Hey @ecurrencyhodler , I wanted to have a look on the superadmin v1 codebase. Could you please tell me more about it wrt this issue

**Comment by ecurrencyhodler** [comment]
Hey vividh! This issue is currently blocked so it's not ready to go yet. You can see the "blocked" label on the issue. 

Take a look at our home page to find some bounties you can take! https://community.sphinx.chat/bounties

**Comment by VividhPandey003** [comment]
oh okay, didn't notice that. Thanks for informing

> Hey vividh! This issue is currently blocked so it's not ready to go yet. You can see the "blocked" label on the issue.
> 
> Take a look at our home page to find some bounties you can take! https://community.sphinx.chat/bounties

**Comment by kapildadhich075** [comment]
hi, @ecurrencyhodler   I would like to work on this issue, can you please assign me to this?

**Comment by ecurrencyhodler** [comment]
Hey @kapildadhich075 you've responded on several tickets asking to be assigned. Let's have you complete one first and then assign more if it goes well. This issue is still open.

**Comment by kapildadhich075** [comment]
Hey @ecurrencyhodler can you please assign me this issue.

**Comment by ecurrencyhodler** [comment]
No. See my previous comment.

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler 
Please could you assign this to me?

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler 
Got it.
I'll be watching my inbox for the design

**Comment by kapildadhich075** [comment]
hi, @ecurrencyhodler   I would like to work on this issue, can you please assign me to this?

**Comment by ecurrencyhodler** [comment]
@Ekep-Obasi we are good to go! The description in the issue has the update design.

**Comment by Ekep-Obasi** [comment]
@elraphty on the admin page I keep receiving 401 API response 
Could you help?
