### ISSUE TITLE
Freeze bounties overview section of super admin

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1014]
When I first land on the super admin page, I see this:
![Bounties V1 (5)](https://github.com/stakwork/sphinx-tribes/assets/32662508/08acc2e4-2779-41a0-b450-c1d283e70830)

I also am able to scroll down the page as there are 20 bounties per pagination at the bottom, however only the first 10 queried initially. As I scroll down, the bounties section freezes while I continue to scroll through the bounties to see all 10 bounties.

![Bounties V1 - Sticky Header](https://github.com/stakwork/sphinx-tribes/assets/32662508/7f26536b-10c8-495e-bc21-794f58d41e55)

Use a sticky nav bar to enable this feature.

### Acceptance Criteria

- [ ] I have tested on Chrome
- [ ] I have posted a video of me scrolling down the super admin page and seeing the nav bar freeze while I still am able to scroll through rest of the 20 bounties. 
- [ ] I've created a component test that tests when a page is scrolled, only the bounties section (including the sortby and open status area) gets displayed.

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler 
Please could you assign this task to me?

**Comment by ecurrencyhodler** [comment]
Yup.
