### ISSUE TITLE
Create prototype for new bounty layout on the home page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1020]
One of the lessons based on user interviews is that hunters click on bounties based off the title and description of a bounty. I've discovered this through user interviews with a few hunters and Ivana has said she would want to learn more about the bounty before clicking on the "I can help" button. 

We should include exploring the "contact provider" CTA and see how that might fit into the new layout. One insight from user interviews is that most hunters scan the QR code on desktop to reach out to a provider.

I also discovered that users look at the amount of a bounty second. In fact, the price of a bounty may have unintended second-order effects. For example a high priced bounty may attract hunters who don't actually read the description but say they can do it just so that they can get the bounty. Or a hunter may shy away from large priced bounties because they assume the amount of work is too complicated for them. The insight here is that while price is important, it isn't the primary factor a hunter chooses to take a bounty.

Lastly, there are two ways to measure work: Hours and Value. Right now our "est. work" is based on hours but it can be difficult to accurately reflect that. One thing I would like to test is moving it towards a "value-based" system with a S/M/L/XL. Then we can see how both providers and hunters respond to that. 

### Acceptance Criteria

- [ ] Create a prototype that prioritizes the details of a bounty first. 
- [ ] Include in the prototype A/B versions to test around estimated work. One is with our current hour system. One is with the S/M/L/XL system.

**Comment by carrington-115** [comment]
@ecurrencyhodler this sounds like an interesting task. I will love to do it.

**Comment by ecurrencyhodler** [comment]
Hi! This is a design bounty but has been backlogged for now.
