### ISSUE TITLE
Org page temporarily displays bounty home page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1028]
**Describe the bug**
When I open a bounty on the home page, the site briefly displays the home page before reverting back to the home page. Here's the org page on staging: https://people-test.sphinx.chat/org/bounties/ck95pe04nncjnaefo08g

https://github.com/stakwork/sphinx-tribes/assets/32662508/5159cd31-55e6-42bd-a359-b063b071aab2

**Expected behavior**
There shouldn't be a flicker or switch. It should naturally go back to the org page.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video of the flicker not happening

**Comment by VividhPandey003** [comment]
Hey could you please tell me about the staging branch
