### ISSUE TITLE
Remove small white module that appears before viewing a bounty from profile

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1029]
**Describe the bug**
When I view a bounty that I created from my profile, a small white module and my profile appears before I see the full bounty. 

https://github.com/stakwork/sphinx-tribes/assets/32662508/83f80471-edcb-4cd6-bcc6-d7353e48baa5

**Expected behavior**
I should be taken directly to the bounty.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video of me looking at a bounty I created from my profile

**Comment by Vayras** [comment]
Hey @ecurrencyhodler , I would like to contribute towards this issue.

**Comment by ecurrencyhodler** [comment]
Okay i'll assign the bounty to you too.

**Comment by ecurrencyhodler** [comment]
@elraphty Can you help @Vayras here?

**Comment by Vayras** [comment]
@elraphty @ecurrencyhodler let me know the fix ,I wish to solve this issue ,Thanks

**Comment by ecurrencyhodler** [comment]
Hey @Vayras we believe this is a router issue where it's going to a page ID but it may be opening multiple.

**Comment by Vayras** [comment]
Hey @ecurrencyhodler fixed the issue , the issue was the modal was loaded even before data is fetched , will be raising the PR for this now
