### ISSUE TITLE
Fix 404 when looking at an assigned ticket from my profile

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1030]
**Describe the bug**
When I click on an assigned ticket, I get a 404. 

https://github.com/stakwork/sphinx-tribes/assets/32662508/2fe846a7-3c12-44f6-8ba8-3bd4e2e7f160

**Expected behavior**
I should be able to view the bounty I was assigned to.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video of viewing a bounty that has been assigned from profile

**Comment by ecurrencyhodler** [comment]
@gouravmpk check "assigned" bounties. Not created bounties. It's the next tab over to the right.

**Comment by gouravmpk** [comment]
> @gouravmpk check "assigned" bounties. Not created bounties. It's the next tab over to the right.


https://github.com/stakwork/sphinx-tribes/assets/20900042/0309becf-7090-41fe-9f33-6beceb63ad2a

Yep I check the both tabs

**Comment by ecurrencyhodler** [comment]
Is that local or on staging?

**Comment by ecurrencyhodler** [comment]
Okay. Actually kevin did a quick fix and assigned bounties are now displayed. However the text "container" is now displayed. Do you see that locally?
<img width="704" alt="Screenshot 2023-12-04 at 11 32 34 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/2db4dbf3-2460-4859-bcc0-344a6239c0c9">

**Comment by gouravmpk** [comment]
No

**Comment by ecurrencyhodler** [comment]
Closing this issue. Will create a separate issue for the container text.
