### ISSUE TITLE
Fix glitch when moving from a tab on my profile to default profile view

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1034]
**Describe the bug**
When I'm looking at any tab inside my profile and click on my profile icon on the top right, a small glitch appears before settling on the default profile view page. 

Here is a video of me looking at the bounties I created in my profile and then clicking on my profile on the top right.

https://github.com/stakwork/sphinx-tribes/assets/32662508/91bc1910-7b68-4c55-87f0-cf586dcc0955

You can see that the "people" section on the left temporarily flashes. That should not happen.

**Expected behavior**
The screen should gracefully transition to the default profile view which is viewing the org tab.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video transitioning from a tab to my default profile view by click on my profile on the top right

**Comment by Khaalid-oh** [comment]
Fix glitch screen

**Comment by Khaalid-oh** [comment]
PR: [](https://github.com/stakwork/sphinx-tribes/pull/1117#issue-2044778735)

**Comment by YLeight** [comment]
I've suggested solution above. Ready for review
