### ISSUE TITLE
Fix "I can help button" to display QR code to connect

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1038]
**Describe the bug**
When I click on "I can help" the button on staging, the bounty page appears. This shouldn't happen. 

https://github.com/stakwork/sphinx-tribes/assets/32662508/09d1631b-cc52-4e96-896d-7502071e55f0

**Expected behavior**
What should appear is the "connect with provider" modal. 

https://github.com/stakwork/sphinx-tribes/assets/32662508/323d7a08-f70a-4354-b529-898ced20a08a
This is currently live in prod.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video of the changes

**Comment by gouravmpk** [comment]
@kevkevinpal I was looking into this I wasn't able to recreate this.
