### ISSUE TITLE
Bounty Superadmin

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#1039]
@ecurrencyhodler Here is a preview of how sticky header would look like.
In this version, once user starts scrolling, statistics would scroll out, while the rest of the header would remain sticky on top.
As you requested, there are 20 bounties per page, with pagination on bottom.

https://github.com/stakwork/sphinx-tribes/assets/13258550/7060d51d-140a-4107-8d5a-26b0c3fe0913

**Comment by ecurrencyhodler** [comment]
Okay this looks perfect. Thank you milan!
