### ISSUE TITLE
Fix saving details in the profile

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1040]
**Describe the bug**
Currently details in a profile isn't being saved.

https://github.com/stakwork/sphinx-tribes/assets/32662508/5372017a-4db1-4df3-810b-2bf76c48f7de

**Expected behavior**
Details should be saved and displayed in the profile like this:
<img width="269" alt="Screenshot 2023-12-04 at 10 01 58 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/99bd243d-c9ab-4c27-9023-0c98c80cf044">

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video of me saving my profile and the profile displaying the information.

**Comment by VividhPandey003** [comment]
@ecurrencyhodler Could you please assign this issue to me, would try fixing this.

**Comment by VividhPandey003** [comment]
@kevkevinpal - the commit id where the saving profile works fine is - `f7c194212425bc713fbc486fe358e42a26a91dcd` 

Hope this helps. Thanks.

**Comment by ecurrencyhodler** [comment]
Thanks for trying to take a stab at it. I'll pay you partially for finding the commit.
