### ISSUE TITLE
Add default text in bounty creation flow

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1041]
Add the following text inside the description area when creating a bounty and if github selected:
<img width="526" alt="Screenshot 2023-12-04 at 12 36 50 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/9af9154b-4f0e-413e-a01c-d2f1009d7130">

----

Description *

_Provide some context and be as detailed as possible. The more information you provide the better. This will allow the hunter to have a fuller picture of the amount of work that is required to complete the task. Screenshots and screen recordings help a lot too!_ 

----

When you click into the box for the description, the text should disappear and the word "Description *" should float up and become the title of the box like you see in this video:

https://github.com/stakwork/sphinx-tribes/assets/32662508/1c04d832-c50e-4a4c-adc5-bee2414d1501

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video of the text being visible and then disappearing when I click into the description

**Comment by gouravmpk** [comment]
Assign
@ecurrencyhodler

**Comment by VividhPandey003** [comment]
@ecurrencyhodler is this issue up for grabs? I would like to work on it

**Comment by VividhPandey003** [comment]
@ecurrencyhodler, I had some doubts regarding this. So do you want the default text to only get displayed when the "Get description from github is selected. " or just everytime.


https://github.com/stakwork/sphinx-tribes/assets/91251535/7970c6b7-6e9b-43e9-aafa-a94494db54bd

Also this is how it looks like right now.

**Comment by ecurrencyhodler** [comment]
OH wow okay. 

Text should only get displayed when "Get github description" is NOT displayed. 

Is there anyway to have the text appear below the "Description" text that eventually moves up to the top of the box?

**Comment by VividhPandey003** [comment]
> Text should only get displayed when "Get github description" is NOT selected. Text should disappear when user clicks inside the box.
Okay I'll add a check to that

> Is there anyway to have the text appear below the "Description" text that eventually moves up to the top of the box?

I could add spaces so that it looks like it is below "Description" text

**Comment by ecurrencyhodler** [comment]
Okay cool. Post a screenshot and let's see how it looks.
