### ISSUE TITLE
Remove "container" text on staging when looking at assigned tickets

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1047]
**Describe the bug**
For some reason I see the word "container" on assigned bounties on staging.
<img width="1123" alt="Screenshot 2023-12-05 at 2 39 08 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/13e7f8f7-6db5-4790-8480-e08200013c12">

**Expected behavior**
The word should not appear.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video if it is a change in the front end

**Comment by VividhPandey003** [comment]
@ecurrencyhodler Could I look into this. I have also encountered this error while solving other bugs.
