### ISSUE TITLE
Adding tipping options

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-tribes#105]
- add field for lightning address (email address for lightning payments)
- ability to tip a specific blog post
- the recurring payments link (send tip button on people profile) is showing up blank
<img width="778" alt="Screen Shot 2021-11-02 at 9 09 27 AM" src="https://user-images.githubusercontent.com/814886/139874385-bd387f32-0de2-4476-8747-6a8616d07f31.png">

**Comment by plell** [comment]
ok, moved widget package to s3, this is working again. will close once deployed
