### ISSUE TITLE
Setup history bucket to export CSV file of bounties

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1050]
Create history bucket to export CSV file of bounties. This will be hosted in S3.

**Comment by kevkevinpal** [comment]
ok I made a bucket `sphinx-tribes` and a folder in that bucket `/metrics` and put a sample file in there. The bucket policy is public rn so we'll need to change that

sample link to download the example csv
https://sphinx-tribes.s3.amazonaws.com/metrics/addresses.csv

**Comment by kevkevinpal** [comment]
we might want to use this to only allow our sphinx-tribes server to download csv files from the bucket

we should add the IP of sphinx-tribes prod and staging
https://stackoverflow.com/questions/56915684/s3-access-policy-to-allow-download-to-a-specific-ip-address

**Comment by ecurrencyhodler** [comment]
Thanks Kevin! @elraphty pinging you on this. Not sure if csv export is ready to go yet though cuz there might be some more work we need to do.
