### ISSUE TITLE
Update "invite" in bounty modal to "assign"

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1063]
Let's change the word "invite" in the bounty modal to "assign when assigning a developer to a bounty.

Let's assign change the title on this modal "Invite Developer" to "Assign Developer".

https://github.com/stakwork/sphinx-tribes/assets/32662508/2eb7e739-9559-4dd9-88a8-2e9648d0a400

### Acceptance criteria

- [ ] I have tested on Chrome
- [ ] I have posted a screen recording in my PR of me showing the words "assign"

**Comment by gouravmpk** [comment]
Assign

**Comment by gouravmpk** [comment]
I see a condition there @ecurrencyhodler 
Just want to confirm you want Assign whatever the case is ?

**Comment by ecurrencyhodler** [comment]
Hmmm do you know where else this module pops up?

**Comment by ecurrencyhodler** [comment]
If you're not sure let me sync with the team tomorrow and get back to you

**Comment by gouravmpk** [comment]
Its used here only for people search I am 80% confident !

**Comment by ecurrencyhodler** [comment]
Okay go ahead with it.

**Comment by ecurrencyhodler** [comment]
Closed by #1064
