### ISSUE TITLE
Unable to upload a picture to an organization even with right permissions

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1068]
**Describe the bug**
I'm unable to upload a picture to an organization even with right permissions. In the video below, I am the admin of the org.

https://github.com/stakwork/sphinx-tribes/assets/32662508/3b3cafb7-d0a7-4f86-855f-9d535e6dd640

**Expected behavior**
I should be able to upload the image.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video of this working

**Comment by gouravmpk** [comment]
Hey @ecurrencyhodler  Is this issue still there ?

**Comment by ecurrencyhodler** [comment]
It is but raph should take a look at this one as it's bit complex.

**Comment by gouravmpk** [comment]
Okay
