### ISSUE TITLE
Add a "load more" button to assigned tickets in profile

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1074]
Currently, the assigned tickets only show 10 tickets. We should have the ability to view more using a "load more" button.
<img width="1379" alt="Screenshot 2023-12-11 at 9 20 38 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/2a7d7174-8c29-47e8-892a-a0458c598830">

### Acceptance Criteria

- [ ] Tested on Chrome
- [ ] Posted a video of the load more button working
- [ ] Tests have passed.

**Comment by VividhPandey003** [comment]
I would like to work on it

**Comment by ecurrencyhodler** [comment]
Tested and it works! Paying you out now.
