### ISSUE TITLE
Query first 100 profiles on people page from backend and add "load more" button.

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1076]
Right now front end is querying first 100 people. And there is no "load more" button.

We should enable the ability to query the whole people table from the backend and when we query the backend we should get the results in a paginated requests with the params limit and offset

Also add a "load more" button.

**Comment by kapildadhich075** [comment]
hi, @ecurrencyhodler   I would like to work on this issue, can you please assign me to this?

**Comment by ecurrencyhodler** [comment]
Updated the ticket @kevkevinpal

**Comment by ecurrencyhodler** [comment]
Closed by #1075
