### ISSUE TITLE
Podcast  Index search

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-tribes#108]
We should also move the Podcast Index search to tribes server instead of doing it directly from the app. 

```
GET "\(API.kPodcastIndexURL)/api/1.0/search/byterm"
Param: 
    1. q
```

Response: 
```
{
    id: Int,
    title: String,
    podcastDescription: String,
    author: String,
    imageURLPath: String?,
    feedURLPath: String?,
}
```

And then use existing /podcast endpoint to get the detailed information about one specific podcast if user selects it.

**Comment by Evanfeenstra** [comment]
do you mean "podcasts/byfeedurl" ?

**Comment by tomastiminskas** [comment]
@Evanfeenstra just fixed the endpoint we should use
