### ISSUE TITLE
Show count next to ticket status in filter

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1081]
Now that we have open bounties by default, we should add counts next to ticket status for social validation that work is being assigned and completed. The format should be:

- Open (X)

<img width="1076" alt="Screenshot 2023-12-12 at 9 44 41 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/72e81024-dfde-4edf-b124-c2d10991f236">

Use this api call to gather the information for open, assigned, and paid: gobounties/filter/count

### Acceptance Criteria

- [ ] I've tested on Chrome
- [ ] I've posted a screenshot in my PR
- [ ] Implement following unit tests
  - [ ] Create mock data for the endpoint calling open/assigned/paid status then test for return data
  - [ ] Create a mock endpoint for getting status count of open/assigned/paid.
  - [ ] When it's checked, amount of mock data returned should match the count of each status.
- [ ] All tests have passed

**Comment by VividhPandey003** [comment]
Can I work on it.

**Comment by ecurrencyhodler** [comment]
Let me scope this out first vividh!

**Comment by VividhPandey003** [comment]
Update: In progress.
