### ISSUE TITLE
Paid bounties show org image, not profile image.

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1082]
**Describe the bug**
Where the profile image should be, the org image is being displayed for paid bounties.
<img width="1214" alt="paid" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/b6b34e58-dbcf-46c4-bd23-c4366424c3c0">

**Expected behavior**
Profile image should be displayed.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot of a bounty that is marked as paid
- [ ] Tests in PR have passsed

**Comment by kapildadhich075** [comment]
hi, @ecurrencyhodler I would like to work on this issue, can you please assign me to this?

**Comment by VividhPandey003** [comment]
I would like to work on it. Could you please assign it to me
