### ISSUE TITLE
Width when adding a user to an org is initially incorrect

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1103]
**Describe the bug**
When adding a member to the org, the width is incorrect. It should be the same width that you see after I type in a name in the video below.

https://github.com/stakwork/sphinx-tribes/assets/32662508/8e7c08b3-a2c0-4f7b-aead-bec4c0f88695

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video
- [ ] I created a craco component test that confirms the size of the module is the same throughout the whole flow
- [ ] All tests have passed.

**Comment by VividhPandey003** [comment]
@ecurrencyhodler Could you please assign this issue to me. I've worked with something similar in aboutProfile section.

**Comment by Khaalid-oh** [comment]
On it...

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler 
Please can I work on this?
