### ISSUE TITLE
Assigned filter displays paid bounties on the home page.

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1118]
**Describe the bug**
When the assigned filter is selected, paid bounties also appear. 
<img width="1209" alt="Screenshot 2023-12-16 at 8 30 24 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/be7be1f0-8901-4fa0-9b39-c0f28b022c0f">

**Expected behavior**
Paid bounties should not appear if assigned tickets are selected. Only tickets that are assigned and not paid should appear.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler  
Could you please assign this to me?

**Comment by ecurrencyhodler** [comment]
Okay
