### ISSUE TITLE
Bring back "Assign hunter" button for created bounties when signed in.

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1121]
**Describe the bug**
The "assign hunter" button no longer appears if I am signed in and looking at a bounty that I created. 

https://github.com/stakwork/sphinx-tribes/assets/32662508/eeec938f-9c4e-427b-9bb3-122d0f587624

**Expected behavior**
This is what it should look like, except let's also change "user"->"hunter" and remove the text "Do your skills match?"

![Screenshot 2023-09-15 at 8 51 1](https://github.com/stakwork/sphinx-tribes/assets/32662508/cf9db215-142e-44f4-aa99-d10eaf2831a2)

When I click on that button, the bounty should pop up like this screenshot.
<img width="908" alt="Screenshot 2023-12-16 at 9 38 02 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/e88b9a71-f410-4ff9-a2e0-1bf4f23b6cd8">

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video
- [ ] I have created a unit test that states the "assign hunter" button appears when looking at a bounty I created and when I'm signed in

**Comment by Vayras** [comment]
Hi, I would like to work on this issue ,can you assign me to this , also I would like to know how to get All of this bounty data for testing on my local machine

**Comment by ecurrencyhodler** [comment]
Let's have you join stand up to discuss this issue first. We can also help you with getting the bounty data.

**Comment by Vayras** [comment]
okay , send me the link

**Comment by elraphty** [comment]
Oops! I fixed this already @ecurrencyhodler while working on the GitHub error.

**Comment by ecurrencyhodler** [comment]
Tested and it works.
