### ISSUE TITLE
Re-enable opening a window to the org on the bounty home page 

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1122]
**Describe the bug**
Right now when I click on an org on the home page, the bounty specific page pops up. 

https://github.com/stakwork/sphinx-tribes/assets/32662508/b2aac2b8-3530-4257-8998-75380e284fcb

**Expected behavior**
When I click on an org, the org page with org specific bounties should appear in a separate window. Here is an example of an org page: https://community.sphinx.chat/org/bounties/ck95pe04nncjnaefo08g

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video of org opening in a separate window
- [ ] I have created a component test that tests the org page will appear in a separate window

**Comment by aliraza556** [comment]
@ecurrencyhodler could you assign me this task?

**Comment by ecurrencyhodler** [comment]
Absolutely! I'll assign the bounty as well.

**Comment by ecurrencyhodler** [comment]
Okay @aliraza556 Removing org component from clickable bounty link is the fix after chatting with the team. Hope that helps.

**Comment by aliraza556** [comment]
@ecurrencyhodler Thank you for the guidance and assigning me this task. I apologize for the delay in starting; I was under the weather yesterday. However, I'm feeling much better today and am ready to tackle the task. I understand the fix involves removing the org component from the clickable bounty link. I'll get started right away and ensure to keep you updated on my progress.

**Comment by ecurrencyhodler** [comment]
Hey Ali. Thanks for the update. Sorry to hear you were sick. And no worries. Just wanted to give you more information to help you navigate the issue.

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler 
Thank you for your understanding. I appreciate your support. I've been trying to make progress on the project, but I've encountered some challenges. I believe additional documentation or guidance would be helpful for me to navigate through the issues.

Could you please point me to any relevant documents or resources that might assist me in stepping through the project successfully?

I'm eager to overcome these obstacles and contribute effectively to the project.

Thanks,
Ali

**Comment by wright-eric** [comment]
Hi @ecurrencyhodler  is this bounty still up for grabs ?

**Comment by ecurrencyhodler** [comment]
@wright-eric no it's not. Let's give @aliraza556 a few more days for an update on this issue.

**Comment by aliraza556** [comment]
Hi @wright-eric, I am currently working on it. I accidentally clicked 'unassigned' by mistake.

**Comment by wright-eric** [comment]
@aliraza556  sure.

**Comment by aliraza556** [comment]
@ecurrencyhodler Please check [demo](https://www.loom.com/share/61c66620c06744c2aa9797acd3fce3f5)

**Comment by kevkevinpal** [comment]
looks like this issue was fixed by https://github.com/stakwork/sphinx-tribes/pull/1201 already
