### ISSUE TITLE
Create "paid bounty" modal

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#1126]
When viewing paid bounty modal in mobile flow it doesn't look as if it is paid no banner or such.

<img width="890" alt="Screenshot 2023-12-18 at 10 25 06 AM" src="https://github.com/stakwork/sphinx-tribes/assets/15950706/34a0f2c6-0a43-4965-a902-69d68ddc24d6">
<img width="890" alt="Screenshot 2023-12-18 at 10 25 16 AM" src="https://github.com/stakwork/sphinx-tribes/assets/15950706/be6a2792-fe89-4eef-83ae-002402bfc513">

Let's use the desktop version and resize it for mobile using mediaquery.

_Originally posted by @kevkevinpal in https://github.com/stakwork/sphinx-tribes/issues/1104#issuecomment-1860950526_

### Acceptance Criteria

- [ ] I've tested on mobile chrome
- [ ] I've added a video of clicking into a bounty and seeing it marked as paid 
- [ ] Add unit test to make sure that the "paid banner" is reflected when status of bounty is marked as paid

**Comment by kevkevinpal** [comment]
<img width="890" alt="Screenshot 2023-12-18 at 10 25 06 AM" src="https://github.com/stakwork/sphinx-tribes/assets/15950706/34a0f2c6-0a43-4965-a902-69d68ddc24d6">
<img width="890" alt="Screenshot 2023-12-18 at 10 25 16 AM" src="https://github.com/stakwork/sphinx-tribes/assets/15950706/be6a2792-fe89-4eef-83ae-002402bfc513">

**Comment by okhot** [comment]
@ecurrencyhodler can I work on this?

**Comment by ecurrencyhodler** [comment]
Ooof @okhot sorry but @Loicbtc beat you to it. There are lots of other bounties for you though on our website! https://community.sphinx.chat/bounties

**Comment by okhot** [comment]
okay boss thanks

**Comment by gouravmpk** [comment]
@ecurrencyhodler This feature is being completed in my user story

**Comment by ecurrencyhodler** [comment]
okay thanks @gouravmpk

**Comment by ecurrencyhodler** [comment]
I'll increase your bounty another 50k
