### ISSUE TITLE
[Unit Test][Golang] CreateOrEditBounty

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#1129]
### Task:
1). create a new file in `/handlers/bounty_test.go` you can use `/handlers/auth_test.go` as a template
2). create unit test for golang function `CreateOrEditBounty` https://github.com/stakwork/sphinx-tribes/blob/master/handlers/bounty.go#L121
3). you may need to edit `/db/db_mock.go` to setup mock responses for `CreateOrEditBounty`

### Acceptance Criteria:
golang code coverage is increased and `CreateOrEditBounty` handler now has coverage

**Comment by anish-yadav** [comment]
can i attempt this?
/attempt

**Comment by ecurrencyhodler** [comment]
Yes absolutely. This is yours. 

Also try using this code and sign up as a new user on sphinx chat:

connect::relay.swarm4.sphinx.chat::03dfcf169395df3b06813071c1462a9090433630e054284c9abdebf06e8d75dc11

Then you can send me a DM by adding this pubkey as an existing user: 021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b:02736e7dad83d7205826649fc17db672ce08f8e87a2b47c7785ccbf79f24e91db0:1099755618305

**Comment by ecurrencyhodler** [comment]
Okay this bounty has also been assigned to you: https://community.sphinx.chat/bounty/931

Do you mind me asking how you heard about our project and bounties platform?

**Comment by anish-yadav** [comment]
> Okay this bounty has also been assigned to you: https://community.sphinx.chat/bounty/931
> 
> Do you mind me asking how you heard about our project and bounties platform?

Just heard from a friend so thought to try this out.

**Comment by ecurrencyhodler** [comment]
Awesome! We're glad to have you. :)

**Comment by anish-yadav** [comment]
hi @ecurrencyhodler  can you please assign the bounty to this profile  if possible.
Eric Wright 
031a8f3eb9a601366074c829e94d10f291a91f2ea9d8a414c079c246d3dc351b4d:03a6ea2d9ead2120b12bd66292bb4a302c756983dc45dcb2b364b461c66fd53bcb:1099522637825

I lost my account and needed to create another.

**Comment by ecurrencyhodler** [comment]
Of course: https://people-test.sphinx.chat/bounty/931

**Comment by ecurrencyhodler** [comment]
So @anish-yadav are you also @wright-eric on github?

**Comment by wright-eric** [comment]
yeah @ecurrencyhodler  yeah thought not to use my personal github account :)
