### ISSUE TITLE
when clicking on "I can help" on unassigned bounty it just refreshes to home screen

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#1131]
**Describe the bug**
Clicking on "I can help" button refreshes screen

**To Reproduce**
click  on "I can help" button 

**Expected behavior**
I should see a QR code and a button to help me connect to the owner of the bounty

**Comment by ecurrencyhodler** [comment]
@kevkevinpal do you have a screen recording? I can repro on my laptop.

**Comment by ecurrencyhodler** [comment]
Closing because it's been fixed already.
