### ISSUE TITLE
Display created bounty after successful bounty creation

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1137]
### Context
When I create a bounty, i should be displayed the bounty if it has been successfully created. 

Currently our website does not do this.

https://github.com/stakwork/sphinx-tribes/assets/32662508/33652560-19a8-4489-9fc9-911a6f1a4e2b

### Expected behavior
Let's say I created a bounty titled: Show count next to ticket status in filter

I should see this bounty page immediately after finishing clicking "finish". This is true for both assigned and unassigned created bounties.

<img width="1063" alt="Screenshot 2023-12-18 at 4 11 41 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/31d14b54-d9c8-42ef-9003-1e0fa7b42384">

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've created a component test that the bounty page modal appears after bounty has been created. Here is an example of a component [test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by Vayras** [comment]
@ecurrencyhodler I would like to work on this issue, Can you please assign me to this. Thanks

**Comment by ecurrencyhodler** [comment]
Let me scope this first. Will follow up!

**Comment by ecurrencyhodler** [comment]
assigned bounty and issue to you @Vayras
