### ISSUE TITLE
Remove code from mobile view of setting bounty status as open if github issue is open

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1143]
**Describe the bug**
There is currently code in mobile view where the status of the bounty is set to "open" if the github issue is still open. This was previously used to to track status of issues, not status of bounties. 

This means that bounties marked as paid are viewed as "open" when you click into a bounty in mobile view.
<img width="890" alt="Screenshot 2023-12-18 at 10 25 06 AM" src="https://github.com/stakwork/sphinx-tribes/assets/15950706/34a0f2c6-0a43-4965-a902-69d68ddc24d6">
<img width="890" alt="Screenshot 2023-12-18 at 10 25 16 AM" src="https://github.com/stakwork/sphinx-tribes/assets/15950706/be6a2792-fe89-4eef-83ae-002402bfc513">

Let's remove this code. Instead the status of the bounty should be set by status of the bounty.

**Expected behavior**
Status of the bounty should be set by status of the bounty.

**Smartphone (please complete the following information):**
 - Device: iPhone or Android
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on mobile Chrome
- [ ] I have posted a video clicking on a paid bounty on the home page and it showing the status as "paid" inside viewing the bounty page as well

**Comment by gouravmpk** [comment]
Assign

**Comment by gouravmpk** [comment]
@ecurrencyhodler Just for clarification if bounty is paid it shouldn't show open in mobile view, is that correct !!

**Comment by ecurrencyhodler** [comment]
No. 

There is code that sets the bounty to open if the GitHub issue is open even if the bounty has been completed. 

Remove this code. 

If the bounty is paid, the status should be paid regardless of what the GitHub issue was in mobile.

**Comment by ecurrencyhodler** [comment]
Closed by #1164
