### ISSUE TITLE
Add ability to manually enlarge the height of the description box when creating bounty

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1148]
We should also add a feature to manually enlarge the size of the window when creating a bounty. Currently, only a scroll button appears when text goes beyond the size of the description box. But since the height is so small, it's hard to see the whole text. 

We should add a way to manually increase the height of the description box and have it scale gracefully with the size. The size of the loom box should be preserved.

<img width="990" alt="enlargebox" src="https://user-images.githubusercontent.com/32662508/291725250-9f39189a-00f5-41c7-af63-9fea52c558fb.png">

Something like this:

https://user-images.githubusercontent.com/32662508/291725738-551c8d33-f5fb-4b96-b339-26addbb5075c.mov

Blocks #1147

_Originally posted by @ecurrencyhodler in https://github.com/stakwork/sphinx-tribes/issues/1145#issuecomment-1863523816_

**Comment by okhot** [comment]
@ecurrencyhodler  has someone already been assigned to this I'd love to work on it!

**Comment by ecurrencyhodler** [comment]
Hey this still needs to be scoped. So not yet!

You can verify that in the ticket status: Scope Needed

**Comment by okhot** [comment]
Okay @ecurrencyhodler Thanks can I please get an invite to the community chat so that I can know when tickets are available thanks

**Comment by ecurrencyhodler** [comment]
@okhot this is available now. Are you still interested? https://people-test.sphinx.chat/bounty/1033

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler, could you assign this task to me? My previous bounty is already complete; I just need to create a PR.

**Comment by okhot** [comment]
> @okhot this is available now. Are you still interested? https://community.sphinx.chat/bounty/1033

Yes @ecurrencyhodler I'd love to help

**Comment by ecurrencyhodler** [comment]
@okhot this one is yours.

**Comment by ecurrencyhodler** [comment]
@okhot can you dm on sphinx chat?
021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b:02736e7dad83d7205826649fc17db672ce08f8e87a2b47c7785ccbf79f24e91db0:1099755618305

**Comment by okhot** [comment]
Need an invite please

**Comment by ecurrencyhodler** [comment]
@okhot you can use this code to sign up as a new user:
connect::relay.swarm4.sphinx.chat::02d3a7408fd87ce846d51cb36d72c9ae6effa240648263896f9f8b7aff9995e570

And you can DL Sphinx chat from here: https://buy.sphinx.chat/

After that sign into this page to create and account and I can assign the bounty to you! https://community.sphinx.chat/bounties

**Comment by hritikmunde** [comment]
Hi @ecurrencyhodler , can I take this?

**Comment by ecurrencyhodler** [comment]
Hi welcome! 

This was already assigned. Sorry! You can find more open bounties here: https://community.sphinx.chat/bounties

How did you hear about our platform?

**Comment by hritikmunde** [comment]
Hey @ecurrencyhodler , I heard this from a friend and I've been trying to get into sphinx chat but it says we are out of QR codes. Can you help?

**Comment by ecurrencyhodler** [comment]
@hritikmunde absolutely. Use this one and sign up as a new user using sphinx chat: 
connect::relay.swarm4.sphinx.chat::03cbb9c01cdcf91a3ac3b543a556fbec9c4c3c2a6ed753e19f2706012a26367ae3

You can DL the app here: https://buy.sphinx.chat/

**Comment by hritikmunde** [comment]
@ecurrencyhodler , the above one is not working. I use IOS, I pasted it still it says invalid.

**Comment by ecurrencyhodler** [comment]
@hritikmunde are you signing up as a new user? And are you copy and pasting the whole string from connect all the way down to the 3?

**Comment by ecurrencyhodler** [comment]
@hritikmunde you have to also make sure you're on testflight.

**Comment by aliraza556** [comment]
@hritikmunde please check this requirement
![image](https://github.com/stakwork/sphinx-tribes/assets/87068339/c60c935c-2320-4a34-9138-3ef40acc379c)

**Comment by hritikmunde** [comment]
Okay got it thanks for the help @ecurrencyhodler !

**Comment by ecurrencyhodler** [comment]
@okhot did you sign up? I want to get this assigned to you ASAP.

**Comment by okhot** [comment]
Haven't been able to signup yet! I'm having issues with the connection string

**Comment by ecurrencyhodler** [comment]
Make sure you're on testflight, not the app store. And to sign up as a new user.

Also paste the whole string: "connect...319d3"

Here's an [FAQ](https://docs.google.com/document/d/16NQ4SM4ptP4Lz5JKERAagdNw3GFRVv9eshMZ_oU-MVw/edit?usp=sharing) you can look at too for some help or just reach out to me.

**Comment by okhot** [comment]
@ecurrencyhodler sorry but I'm not really sure on how to use testflight. Do I need an email invite to access?

**Comment by gouravmpk** [comment]
@hritikmunde can help you set it up

**Comment by hritikmunde** [comment]
Sure @okhot , download the IOS application from here: https://buy.sphinx.chat/ not from the AppStore.
Here is a breakdown of steps.
- Install Testflight on your device.
- Go to [Sphinx](https://buy.sphinx.chat/) and click on Appstore download option there.
- It'll redirect you to test flight from which you'll download your app.
- Now scan the QR or paste the connections trying and register as new user.
- Rest follows along.
Let me know if you need any help.

**Comment by okhot** [comment]
Thanks @hritikmunde

**Comment by ecurrencyhodler** [comment]
Thanks for helping out @hritikmunde!

**Comment by ecurrencyhodler** [comment]
@okhot this has been assigned to you: https://community.sphinx.chat/bounty/1033

**Comment by okhot** [comment]
on it
