### ISSUE TITLE
Add Github Ticket button in MobileView of Bounty Description

### ISSUE THREAD

**Issue by VividhPandey003** [stakwork/sphinx-tribes#1161]
**Describe the bug**

The bounty body should have a href button to link to the github issue but in mobile view the button does not exist.

https://github.com/stakwork/sphinx-tribes/assets/91251535/cf0fd09a-2344-4322-bcdd-d7099eff4b5c

**Expected behavior**
A button to be added at the very top which links to the github issue which is referenced in the specific bounty

**Smartphone (please complete the following information):**
 - Device: iPhone 12Mini
 - OS: iOS 17.2
 - Browser -Safari

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video if it is a change in the front end

**Comment by VividhPandey003** [comment]
I would like to work on this issue. Could you please scope it out first

**Comment by kevkevinpal** [comment]
@ecurrencyhodler This is a valid issue we should track and fix

**Comment by ecurrencyhodler** [comment]
@kevkevinpal he might need some help scoping this out. @VividhPandey003 Jeezman did a similar PR with this pay button:  https://github.com/stakwork/sphinx-tribes/pull/1104

Let's follow the design on the desktop here.
<img width="199" alt="Screenshot 2023-12-23 at 7 47 46 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/52b4cd15-0c31-48e5-a473-9bbc4ef30352">

It shouldn't be too hard of a fix I think. Just take the same components in the desktop version of mediaquery and appy it to mobile. What you'd want to test for is that it hyperlinks to the correct github issue.

If that sounds good to you vividh, i'll turn this into a bounty. Let me know what you think.

**Comment by VividhPandey003** [comment]
@ecurrencyhodler I would like to work on this. Looks a doable task to me. If I face any difficulties.. i'll let you know

**Comment by ecurrencyhodler** [comment]
My man! Okay let me create a bounty for you. I think 400k should be a good amount for this one.
