### ISSUE TITLE
Add component test to: frontend/app/src/pages/superadmin/accessDenied

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#1165]
### Task:
- Create a new file in `frontend/app/src/pages/superadmin/accessDenied/AccessDenied.Spec.tsx` you can use `frontend/app/src/pages/superAdmin/headers/SuperAdminHeader.Spec.tsx` as a template
- Create component test for `frontend/app/src/pages/superadmin/accessDenied/index.tsx`

### Acceptance Criteria:
We want to cover these tests
- words "Access Denied" show up in the document. 
- Words "You don't have access to this page" show up in the document
- A clickable button with the words "Go Back" show up in the document

**Comment by KumarNayan** [comment]
Is this bounty open?
Can you assign this to me ? @kevkevinpal

**Comment by KumarNayan** [comment]
Assign

**Comment by ecurrencyhodler** [comment]
hey @KumarNayan I'd be happy to. Do you have a sphinx chat account already? If so, you would qualify to earning Bitcoin by completing this bounty: https://community.sphinx.chat/bounty/972

**Comment by KumarNayan** [comment]
> hey @KumarNayan I'd be happy to. Do you have a sphinx chat account already? If so, you would qualify to earning Bitcoin by completing this bounty: https://community.sphinx.chat/bounty/972

I have the sphinx account. I have raised the PR for this ticket. Can you tell me whom to assign for review

**Comment by ecurrencyhodler** [comment]
@KumarNayan that's awesome! I see the PR. Since it's the weekend and monday is christmas, you should expect a review sometime mid-next week.

**Comment by kevkevinpal** [comment]
closed by https://github.com/stakwork/sphinx-tribes/pull/1181
