### ISSUE TITLE
Add componenet tests to: frontend/app/src/pages/superadmin/statistics

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#1166]
### Task:
- Create a new file in `frontend/app/src/pages/superadmin/statistics/Statistics.Spec.tsx` 
you can use `frontend/app/src/pages/superAdmin/headers/SuperAdminHeader.Spec.tsx` as a template
- Create component test for `frontend/app/src/pages/superadmin/statistics/index.tsx`

### Acceptance Criteria:
We want to cover these tests
- words "Bounties" show up in the document. 
- words "200" show up in the document. 
- Words "Total Bounties Posted" show up in the document
- words "78" show up in the document. 
- words "Bounties Assigned" show up in the document. 
- words "136" show up in the document. 
- words "Bounties Paid" show up in the document. 
- words "100%" show up in the document. 
- words "Bounties Paid" show up in the document. 
- words "22536" show up in the document. 
- words "Total Sats Posted" show up in the document. 
- words "13625" show up in the document. 
- words "Sats Paid" show up in the document. 
- words "3 Days" show up in the document. 
- words "Avg Time to Paid" show up in the document. 
- words "48%" show up in the document. 
- words "Paid" show up in the document. 

NOTE: some of these words are hardcoded and will need to be passed in as props when we make this dynamic

**Comment by ecurrencyhodler** [comment]
Hey @anish-yadav! Thanks for offering to complete this issue. Are you on sphinx chat by any chance? If so, you'd qualify for earning bitcoin by completing this issue. 

https://community.sphinx.chat/bounty/971

If not, I can help you set up a sphinx chat.

**Comment by ManyRios** [comment]
Can apply to this...?

**Comment by ecurrencyhodler** [comment]
Hey many, you can take this one. I'll assign the bounty to you as well!

**Comment by ManyRios** [comment]
Awesome

**Comment by anish-yadav** [comment]
hi @ecurrencyhodler  can you help me set up a sphinx chat account. Scanning the url seems to not work here. 
![image](https://github.com/stakwork/sphinx-tribes/assets/40102074/55fc74cf-5560-4542-97f1-673c82467366)

**Comment by ecurrencyhodler** [comment]
Closed by #1197
