### ISSUE TITLE
Add component tests to: frontend/app/src/pages/superadmin/tableComponent

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#1167]
### Task:
- Create a new file in `frontend/app/src/pages/superadmin/tableComponent/TableComponent.Spec.tsx` you can use `frontend/app/src/pages/superAdmin/headers/SuperAdminHeader.Spec.tsx` as a template
- Create component test for `frontend/app/src/pages/superadmin/tableComponent/index.tsx`

### Acceptance Criteria:
We want to cover these tests
- Pass in `TableProps` and make sure we can see elements from `TableProps` in the document
- words "Sort By:" show up in the document. 
- Words "Date" show up in the document twice
- Words "Assignee" show up in the document twice
- Words "Status" show up in the document twice
- Words "Status:" show up in the document
- Words "All" show up in the document
- Words "Open" show up in the document
- Words "In Progress" show up in the document
- Words "Completed" show up in the document
- Words "Bounty" show up in the document
- Words "#DTGP" show up in the document
- Words "Provider" show up in the document
- Words "Organization" show up in the document
- Make sure we can see each element in the table in the document ex(bounty?.title, bounty?.date, bounty?.dtgp, bounty?.assignee, bounty?.provider, bounty?.organization)

**Comment by KumarNayan** [comment]
Assign

**Comment by ecurrencyhodler** [comment]
issue and bounty is yours. https://community.sphinx.chat/bounty/970
