### ISSUE TITLE
[Bounty][Frontend] When I click on org tag I want to see the bounties with that org

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#1170]
#### Current behavior
Current behavior is when I click on the org on the bounty row item it just opens the bounty
#### Expected behavior
To open up the bounties under that org

#### Screenshot of button
![Screenshot 2023-12-21 at 10 39 30 PM](https://github.com/stakwork/sphinx-tribes/assets/15950706/a5aa1960-964a-436f-828d-323c0deb64cc)

### Acceptance Criteria
- [ ] It now opens to the org bounty page

**Comment by VividhPandey003** [comment]
I would like to work on this issue

**Comment by ecurrencyhodler** [comment]
Ali is currently addressing this issue: https://community.sphinx.chat/bounty/926

Closing because it's a duplicate.
