### ISSUE TITLE
Add status components to mobile view

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1182]
### Context
Right now, bounty status in mobile view is tied to a github link. This is being removed in #1164. 

We need to add mobile components for the bounty status for mobile. It should look like this:
<img width="410" alt="Screenshot 2023-12-23 at 7 58 13 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/9b434657-98a6-4ef8-94c4-cdf937a160cc">

Use mediaquery from desktop and resize it for mobile.

### Acceptance Criteria
- [ ] I've tested on Chrome mobile
- [ ] I've submitted a screenshot of bounty in open/assigned/paid states.
- [ ] I've created a unit test that checks the correct status is displayed when the status is set to open/assigned/paid. Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

**Comment by gouravmpk** [comment]
Hey Assign me this whenever its ready ! I will show you demo soon trying to figure it out half way there

**Comment by ecurrencyhodler** [comment]
@gouravmpk if you feel like you can figure it out without scoping help from us, go ahead and take it. It shouldn't be too difficult I think since you can resize the desktop mediaquery for mobile. 

I'll make this 400k sats.

**Comment by ecurrencyhodler** [comment]
Here you go: https://community.sphinx.chat/bounty/975

**Comment by ecurrencyhodler** [comment]
Closed by #1187
