### ISSUE TITLE
Merge different env vars for ADMINS to one

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#1183]
I noticed that we have two ENV vars ADMINS and ADMIN_PUBKEYS we should only use one of these in our codebase otherwise it might get confusing

ADMIN_PUBKEYS
https://github.com/stakwork/sphinx-tribes/blob/master/handlers/auth.go#L18

ADMINS
https://github.com/stakwork/sphinx-tribes/blob/master/config/config.go#L33

This seems a bit confusing as they should be the exact same values

**Comment by elraphty** [comment]
This PR fixes this https://github.com/stakwork/sphinx-tribes/pull/1192, I removed ADMIN_PUBKEYS env, closing.

**Comment by elraphty** [comment]
This PR fixes this https://github.com/stakwork/sphinx-tribes/pull/1192, I removed ADMIN_PUBKEYS env, closing.
