### ISSUE TITLE
Scale icon on edit and delete button shift off button when zooming out of browser window

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#1193]
**Describe the bug**
Basically when I open a bounty modal and hit cmd+shift+"-" the icon on the button seems to get displaced

**To Reproduce**
Above

**Expected behavior**
for the icon to look right

![Screenshot 2023-12-26 at 9 36 34 AM](https://github.com/stakwork/sphinx-tribes/assets/15950706/1ea1d91d-0eb0-4b14-8f37-73c9c414a56b)

### Acceptance Criteria

- [ ] I've tested on Chrome Desktop
- [ ] I've posted a video of decreasing view size

**Comment by Vayras** [comment]
Hey @kevkevinpal I would like to work on this issue , can you please assign me to this

**Comment by ecurrencyhodler** [comment]
Assigned this to you. 200k. Let me know if you think a diff price is needed.

**Comment by ecurrencyhodler** [comment]
https://people-test.sphinx.chat/bounty/1013

**Comment by Vayras** [comment]
> Assigned this to you. 200k. Let me know if you think a diff price is needed.

@ecurrencyhodler no that would be enough , will fix this
