### ISSUE TITLE
Correct "mark as paid" button and its various states

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1196]
**Describe the bug**
The button "mark as unpaid" is incorrectly displayed on mobile.
![IMG_4167](https://github.com/stakwork/sphinx-tribes/assets/32662508/eafb3208-4088-44a2-ac08-466965e4bfe2)

**Expected behavior**

These are the various states the button should cover:
**No button**
- Logged in user who did not create bounty is looking at bounty
- Logged in user who did not create bounty and is NOT part of org with "manage bounty permissions" is looking at bounty
- Unlogged in user is looking at bounty

**Mark as Paid (Solid Green)**
- Logged-in user who created bounty is looking at the bounty
- Logged-in user who is an organization member has "manage bounty" permissions and is looking at bounty

**Mark as unpaid (white button with green outline)**
- Logged-in user who created bounty is looking at the bounty and bounty is paid
- Logged-in user who is an organization member has "manage bounty" permissions and is looking at bounty and bounty is paid

**Mark as paid flow**
- Logged in user who created bounty or is a user with the "manage bounty" permissions for that org should be taken through the same "paid bounty flow" as in desktop.
https://github.com/stakwork/sphinx-tribes/assets/32662508/64d444a6-ecad-4be4-9cc9-634c51489f7a
- Logged in user who created bounty or is a user with the "manage bounty" permissions for that org should be taken through the same "mark as unpaid bounty flow" as in desktop.

https://github.com/stakwork/sphinx-tribes/assets/32662508/e3599d38-0c41-480a-872b-f974a65416ab

**Smartphone (please complete the following information):**
 - Chrome: Mobile

### Acceptance Criteria
- [ ] I have tested on Chrome mobile
- [ ] I have posted a video displaying all the various states above

**Comment by Khaalid-oh** [comment]
Can you assign this to me?

**Comment by gouravmpk** [comment]
Assign

**Comment by ecurrencyhodler** [comment]
Alright you can take this one Gourav

**Comment by gouravmpk** [comment]
Unit test are pending for this one
