### ISSUE TITLE
[Tests][Component] Create test for summaries/wantedSummaries/CodingBounty.tsx

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#1200]
### Context
CodingBounty.tsx is a fairly important file as we use it to show the modal for our bounties so we should add some test coverage onto it

File to be tested
`src/people/widgetViews/summaries/wantedSummaries/CodingBounty.tsx `

Create a file named
`src/people/widgetViews/summaries/wantedSummaries/CodingBounty.spec.tsx`

We want to test that certain words appear on the screen 
### Acceptance Criteria
- [ ] Test that`titleString` passed into component appears on screen
- [ ] Test that `description` passed into component appears on screen
- [ ] Test that `deliverables` passed into component appears on screen
- [ ] Test that "I can help" button  appears on screen
- [ ] Test that correct price appears on screen in sats
- [ ] Test that "Share to Twitter" button appears on screen

You can use this PR as a example `https://github.com/stakwork/sphinx-tribes/pull/1185`

**Comment by KumarNayan** [comment]
Assign

**Comment by ecurrencyhodler** [comment]
Here you go @KumarNayan https://community.sphinx.chat/bounty/1017
