### ISSUE TITLE
Clicking on user icon more than 1 time makes the back button require multiple clicks

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#1205]
**Describe the bug**
1). Click profile image on top right
2). click on profile picture again
3). click back button on left 
4). notice that now if you click it again then you actually go to the bounties page

**Expected behavior**
The fix here is if you are on your profile and click on profile again, don't add to the route history. 

https://github.com/stakwork/sphinx-tribes/assets/15950706/f4bb82c5-8748-438e-99fc-389cb1241255

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video of this behavior

**Comment by KumarNayan** [comment]
Can you assign this to me ?

**Comment by aliraza556** [comment]
@kevkevinpal could you assign me this task?

**Comment by ecurrencyhodler** [comment]
@KumarNayan this is yours. Please re-read the description as the instructions have changed. 
https://people-test.sphinx.chat/bounty/1037
