### ISSUE TITLE
No Badge next to filter on mobile

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#1206]
**Describe the bug**
On desktop there is a badge next to the filter to let you know a filter is selected on mobile there is not
![Screenshot 2023-12-28 at 11 58 34 AM](https://github.com/stakwork/sphinx-tribes/assets/15950706/ffe703ee-c68e-4499-a1b3-37bb0f1cd8c6)

**To Reproduce**
1). Go to mobile mode
2). select the filter button
3). select filters and observe issue

**Expected behavior**
To have a badge like on desktop
![Screenshot 2023-12-28 at 11 57 52 AM](https://github.com/stakwork/sphinx-tribes/assets/15950706/266287ec-cbb3-4963-a981-834b8339b862)

### Acceptance Criteria
- [ ] I have tested on Chrome mobile
- [ ] I have posted a screenshot 
- [ ] Create component test when you selected a filter that the # displayed is correct in mobile

**Comment by aliraza556** [comment]
@kevkevinpal  could you assign me this task?

**Comment by aliraza556** [comment]
Hi @kevkevinpal, I have completed this task. Please see the attached image as evidence.
- **image#1**: [Link](https://i.imgur.com/j5NOWYv.png)
- **image#2**: [Link](https://i.imgur.com/e1qUGpU.png)
- **image#3**: [Link](https://i.imgur.com/27QmFaj.png)

I have tested all devices, and they are functioning perfectly.

**Comment by ecurrencyhodler** [comment]
@aliraza556 if you'd like for this issue to be a bounty, I strongly recommend you wait for us to assign it to you.

If you'd like to submit your PR without getting paid a bounty, feel free to work on it.

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler 
Thank you for the advice. I understand now that I should wait for the task to be officially assigned to me before starting work, especially for bounties. I appreciate the opportunity to contribute and will make sure to follow the correct process going forward.

Best regards,
Ali Raza

**Comment by KumarNayan** [comment]
Assign

**Comment by ecurrencyhodler** [comment]
Let me scope this out. It will go to Ali once we do sometime next week.

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler 
Thanks for the update. I'm ready to begin as soon as the task is assigned.

**Comment by ecurrencyhodler** [comment]
@aliraza556 this is yours: https://community.sphinx.chat/bounty/1036

**Comment by aliraza556** [comment]
@ecurrencyhodler 
Thanks, Man!

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler,

I've just submitted PR #1238, which addresses the issue of displaying the badge next to the filter in the Mobile View. Could you please take a look and provide your feedback?

Thanks!

**Comment by ecurrencyhodler** [comment]
Paid
