### ISSUE TITLE
Have blank description for profiles instead of "description".

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#1207]
**Describe the bug**
Says description when we can keep it simpler with nothing
![Screenshot 2023-12-28 at 12 00 12 PM](https://github.com/stakwork/sphinx-tribes/assets/15950706/f0c4e2f8-0d5e-45cc-9d80-7dee35f10fa6)

**To Reproduce**
1. Go to people page
2. Select person
3. observe side bar

**Expected behavior**
It should be blank instead of saying description

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video if it is a change in the front end

**Comment by wright-eric** [comment]
Can i take this up?

**Comment by aliraza556** [comment]
@kevkevinpal could you assign me this task?

**Comment by aliraza556** [comment]
Hi @kevkevinpal, I have completed this task. Please see the attached image as evidence.
- Image#1: [Link](https://i.imgur.com/djNQhIy.png)
- Image#2: [Link](https://i.imgur.com/FV6JQow.png)
- Image#3: [Link](https://i.imgur.com/XuKo9cX.png)

I have tested all devices, and they are functioning perfectly.

**Comment by kevkevinpal** [comment]
> Hi @kevkevinpal, I have completed this task. Please see the attached image as evidence.
> 
>     * Image#1: [Link](https://i.imgur.com/djNQhIy.png)
> 
>     * Image#2: [Link](https://i.imgur.com/FV6JQow.png)
> 
>     * Image#3: [Link](https://i.imgur.com/XuKo9cX.png)
> 
> 
> I have tested all devices, and they are functioning perfectly.

I assigned you not sure if we have a bounty up for this yet

**Comment by aliraza556** [comment]
Thank you, @kevkevinpal, for confirming the assignment. I'm glad to have completed it successfully. Regarding the bounty, it's not a concern at the moment. My primary focus was ensuring the quality and functionality of the devices, which I'm happy to report is excellent. Please let me know if there's anything else I can assist with or any further steps required for this task.

**Comment by aliraza556** [comment]
Hi @kevkevinpal 
I have resolved issue #1217 related to the side-panel display description. Could you please review it and provide your feedback?

**Comment by ecurrencyhodler** [comment]
Hey @aliraza556 where is the PR for this? I can create a bounty for you.

**Comment by ecurrencyhodler** [comment]
Ok i see it. here's the pr: https://community.sphinx.chat/bounty/1024

**Comment by aliraza556** [comment]
Thank you for following up! I've just submitted the PR for issue #1217 and it's ready for review. However, I committed to the wrong branch, but I will fix it within 10 minutes. Also, I appreciate the offer for a bounty – that's great motivation!

**Comment by ecurrencyhodler** [comment]
Closed by #1217.
