### ISSUE TITLE
[Test][Backend] test handlers/bounty.go PayLightningInvoice

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#1208]
### Context
We have the function [PayLightningInvoice](https://github.com/stakwork/sphinx-tribes/blob/master/handlers/bounty.go#L587)

We want to create a new test in [./handlers/bounty_test.go](https://github.com/stakwork/sphinx-tribes/blob/master/handlers/bounty_test.go) that will add coverage to PayLightningInvoice

### Acceptance Criteria
- [ ] Test that we create a request to `/invoices`
- [ ] Test the payment request is what we are using in the body of the request
- [ ] test that a malformed payment request will fail 
- [ ] any other additional assertions are glady appreciated

**Comment by wright-eric** [comment]
Assign

**Comment by ecurrencyhodler** [comment]
If @kevkevinpal says you can, I'll assign the bounty to you. https://community.sphinx.chat/bounty/1021

**Comment by wright-eric** [comment]
On a different topic @kevkevinpal  can i do some refactoring of the handlers to make it more testable ? **if i get assigned this bounty** ? 

Mainly would keep all the handler functions behind a struct and inject httpClient to it, making it much more easier to replace it with mockClient at the test. Something like this [handler.go](https://github.com/anish-yadav/lms-api/blob/main/internal/user/handler/http.go#L18).

In the future can create an interface for DB and inject it in the handler thereby making the handler unit much more testable.
Can use [mockery](https://github.com/vektra/mockery)  to auto generate mocks to cover all scenario and inject the mocks in tests thereby reducing our error to create mock functions and all.

Just a thought.

**Comment by kevkevinpal** [comment]
> On a different topic @kevkevinpal can i do some refactoring of the handlers to make it more testable ? **if i get assigned this bounty** .
> 
> Mainly would keep all the handler functions behind a struct and inject httpClient to it, making it much more easier to replace it with mockClient at the test. Something like this [handler.go](https://github.com/anish-yadav/lms-api/blob/main/internal/user/handler/http.go#L18).
> 
> In the future can create an interface for DB and inject it in the handler thereby making the handler unit much more testable. Can use [mockery](https://github.com/vektra/mockery) to auto generate mocks to cover all scenario and inject the mocks in tests thereby reducing our error to create mock functions and all.
> 
> Just a thought.

I think that would be cool if there is a way to auto generate db mocks that would make our lives easier, I can open a new issue based off of your comment

**Comment by wright-eric** [comment]
> > On a different topic @kevkevinpal can i do some refactoring of the handlers to make it more testable ? **if i get assigned this bounty** .
> > Mainly would keep all the handler functions behind a struct and inject httpClient to it, making it much more easier to replace it with mockClient at the test. Something like this [handler.go](https://github.com/anish-yadav/lms-api/blob/main/internal/user/handler/http.go#L18).
> > In the future can create an interface for DB and inject it in the handler thereby making the handler unit much more testable. Can use [mockery](https://github.com/vektra/mockery) to auto generate mocks to cover all scenario and inject the mocks in tests thereby reducing our error to create mock functions and all.
> > Just a thought.
> 
> I think that would be cool if there is a way to auto generate db mocks that would make our lives easier, I can open a new issue based off of your comment

Cool

**Comment by wright-eric** [comment]
@kevkevinpal  I can work on the db one for sure. But do let me know if u want me to work on this one too.

**Comment by ecurrencyhodler** [comment]
I'll assign this issue and bounty to you @wright-eric https://community.sphinx.chat/bounty/1020
