### ISSUE TITLE
Hide tribe button if no tribe is attached to a bounty

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#1209]
**Describe the bug**
Currently if a tribe is tied to a bounty, I can click the button and it takes me nowhere
![Screenshot 2023-12-28 at 12 24 08 PM](https://github.com/stakwork/sphinx-tribes/assets/15950706/992b9fa6-eebb-4b08-831c-8f2bb7475292)
concise description of what the bug is. Include a screenshot or recording if you can.

**To Reproduce**
1. Click on bounty with no tribe attached

**Expected behavior**
If no tribe is associated with a ticket, the tribe should not be displayed for both desktop and mobile

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video if it is a change in the front end
- [ ] Create component test that asserts if no tribe is associated with a bounty, then tribe button will not be displayed

**Comment by gouravmpk** [comment]
Should it be clickable ? If no tribes attached ?

**Comment by kevkevinpal** [comment]
> @kevkevinpal Should it be clickable ? If no tribes attached ?
> 

It should not be clickable and greyed out similar to what we do with the delete button

**Comment by gouravmpk** [comment]
Okay I can take that if possible !!

**Comment by kevkevinpal** [comment]
> Okay I can take that if possible !!

Don't think a bounty is up for it yet but will assign when one is created

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler,

This bounty is available. If it is available, please assign it to me.

**Comment by ecurrencyhodler** [comment]
Ali this is yours.

**Comment by gouravmpk** [comment]
@ecurrencyhodler I asked for this one first

**Comment by ecurrencyhodler** [comment]
Hey @gouravmpk you are right you did. But you already have 2 bounties and ali didn't have any. So I decided to give it to him. Hope you understand.

**Comment by ecurrencyhodler** [comment]
@aliraza556 do you have an update on this issue?

**Comment by aliraza556** [comment]
@ecurrencyhodler I've successfully resolved the issue and submitted a PR for review today after some testing.

**Comment by ecurrencyhodler** [comment]
Can you submit the PR? I don't see it in our repo.

**Comment by aliraza556** [comment]
@ecurrencyhodler, please give me some time. I will submit the PR shortly.

**Comment by aliraza556** [comment]
> > @kevkevinpal Should it be clickable ? If no tribes attached ?
> 
> It should not be clickable and greyed out similar to what we do with the delete button

Hi @kevkevinpal @ecurrencyhodler Please check the [demo](https://www.loom.com/share/9666814103bf4742acf628b28f1b3b36)
If everything is correct, I will create a PR. If there is anything to add or modify, please provide me with your feedback.

**Comment by ecurrencyhodler** [comment]
That LGTM. Repost the video when you submit the PR.

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler 
Please review PR #1327.

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler
Please review PR https://github.com/stakwork/sphinx-tribes/pull/1327.
