### ISSUE TITLE
Auto mock db

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#1214]
On a different topic @kevkevinpal  can i do some refactoring of the handlers to make it more testable ? **if i get assigned this bounty** . 

Mainly would keep all the handler functions behind a struct and inject httpClient to it, making it much more easier to replace it with mockClient at the test. Something like this [handler.go](https://github.com/anish-yadav/lms-api/blob/main/internal/user/handler/http.go#L18).

In the future can create an interface for DB and inject it in the handler thereby making the handler unit much more testable.
Can use [mockery](https://github.com/vektra/mockery)  to auto generate mocks to cover all scenario and inject the mocks in tests thereby reducing our error to create mock functions and all.

Just a thought.

_Originally posted by @wright-eric in https://github.com/stakwork/sphinx-tribes/issues/1208#issuecomment-1872173900_

**Comment by ecurrencyhodler** [comment]
@wright-eric would you be open to addressing this issue? I created a bounty for 400k.
https://community.sphinx.chat/bounty/1031

**Comment by wright-eric** [comment]
Yes absolutely
