### ISSUE TITLE
Remove logout button from superadmin

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1221]
### Context
 I met with the team and it looks like we're going to embed this into the bounties website. Therefore a log out system already exists. See https://github.com/stakwork/sphinx-tribes/issues/1011#issuecomment-1865048710

Instead let's remove the logout button and ux from super admin.

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot

**Comment by ecurrencyhodler** [comment]
@gouravmpk assigned the bounty to you. Comment here and I'll assign the issue to you too: https://people-test.sphinx.chat/bounty/1026

**Comment by gouravmpk** [comment]
Assign

**Comment by ecurrencyhodler** [comment]
Closing as it's no longer needed.

**Comment by gouravmpk** [comment]
No problem
