### ISSUE TITLE
Fix coding languages in staging during bounty creation

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1222]
**Describe the bug**
When creating a bounty, the UI for selecting a coding language is different from staging.

This is staging.
<img width="463" alt="Screenshot 2023-12-30 at 3 17 29 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/50aaa85b-2ca9-4816-bb02-9ac2bd74225e">

This is production.
<img width="523" alt="Screenshot 2023-12-30 at 3 17 17 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/eb4f2cd3-8b5d-4400-9652-e2ff12f5eb36">

Match staging to production.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video if it is a change in the front end

**Comment by VividhPandey003** [comment]
Assign @ecurrencyhodler

**Comment by aliraza556** [comment]
@ecurrencyhodler could you assign me this task?

**Comment by ecurrencyhodler** [comment]
Hey Ali. This has already been assigned.

**Comment by aliraza556** [comment]
Oh!
