### ISSUE TITLE
Filter Popover width does not display all the available tags

### ISSUE THREAD

**Issue by VividhPandey003** [stakwork/sphinx-tribes#1225]
**Describe the bug**
Right now the only visible language tags are 
<img width="450" alt="image" src="https://github.com/stakwork/sphinx-tribes/assets/91251535/b5a8c670-ba9b-4f39-af68-dd02bffe7cff">

However the list of available tags is 
<img width="558" alt="image" src="https://github.com/stakwork/sphinx-tribes/assets/91251535/e04746cf-8b8e-44d3-9d8e-452b551a00df">

Therefore, what needs to be done is fix the width of the filter popover so that the remaining tags also get displayed.

**To Reproduce**
1. Go to bounties
2. Click on filters
3. See error

**Expected behavior**
All tags should be visible

**Desktop (please complete the following information):**
 - Browser [Chrome]

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video if it is a change in the front end

**Comment by VividhPandey003** [comment]
I would like to work on this issue

**Comment by ecurrencyhodler** [comment]
Created and assigned a bounty to you: https://community.sphinx.chat/bounty/1038
