### ISSUE TITLE
[Tests][Component] Create test for people/widgetViews/UserTicketsView.tsx

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1228]
### Context

UserTicketsView.tsx displays the bounties assigned to a bounty hunter and adds some test coverage.

File to be tested
`src/people/widgetViews/__tests__/UserTicketsView.spec.tsx`

Create a file named
`src/people/widgetViews/__tests__/UserTicketsView.spec.tsx`

Make a Mock API request to get user-assigned tickets, check ```getPersonAssignedBounties``` in  frontend/app/src/store/main.ts, and mock the request API request in the function.

Check ```frontend/app/src/bounties/__tests__/bountyTest.spec.ts``` for example

We want to test that the bounties listed match the mock data bounties

### Acceptance Criteria

- [ ] Test that bounties assigned to a bounty hunter are visible
- [ ] Test that`titleString` displayed matches the title from the mock data
- [ ] Test that the `description` displayed matches the title from the mock data
- [ ] Test that the correct price appears on the screen in Sats
- [ ] Test that the `Estimated time` displayed matches the title from the mock data

You can use this PR as an example `https://github.com/stakwork/sphinx-tribes/pull/1185`

**Comment by KumarNayan** [comment]
Can you assign this to me ? @elraphty

**Comment by elraphty** [comment]
> Can you assign this to me ? @elraphty

@ecurrencyhodler has not created a bounty for it yet.

**Comment by ecurrencyhodler** [comment]
All yours @KumarNayan https://community.sphinx.chat/bounty/1028
