### ISSUE TITLE
[Tests][Component] Create test for people/widgetViews/BountyHeader.tsx

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1229]
### Context

BountyHeader.tsx holds the search Input and filters for the bounties list. Add component test coverage.

File to be tested
`src/people/widgetViews/__tests__/BountyHeader..spec.tsx`

Create a file named
`src/people/widgetViews/__tests__/BountyHeader..spec.tsx`

Make a Mock API request to get the total developers count,  check ```getBountyHeaderData``` in  frontend/app/src/store/main.ts, and mock the request API request in the function.

Check ```frontend/app/src/bounties/__tests__/bountyTest.spec.ts``` for example

We want to test that Bounty header components are visible

### Acceptance Criteria

- [ ] Test that the Post Bounty Button is visible
- [ ] Test that the Leaderboard button is visible
- [ ] Test that the search bar is visible
- [ ] Test that the filters are visible
- [ ] Test that the total developer's count is visible and matches the count returned from the mock  API data.

You can use this PR as an example `https://github.com/stakwork/sphinx-tribes/pull/1185`

**Comment by AbdulWahab3181** [comment]
Could you please assign this task to me? @elraphty

**Comment by KumarNayan** [comment]
I can work on this as well, as I have worked on unit tests previously
Will wait for @ecurrencyhodler to create the bounty.

**Comment by ecurrencyhodler** [comment]
Welcome @AbdulWahab3181 ! I can assign this to you. Are you on sphinx chat? We also have a bounty for this issue so you can get paid in bitcoin if you're interested. :)

https://community.sphinx.chat/bounty/1030

**Comment by AbdulWahab3181** [comment]
Hi @ecurrencyhodler,
Thanks for the welcome and assignment! I'm not on Sphinx Chat, and I'm interested in the bounty. I'll check the link and start working on it. Excited to contribute!
I will signup on Sphinx Chat after completing this task.

**Comment by ecurrencyhodler** [comment]
Amazing! Here is a code for you to use to sign up as a new user (Check email):

connect::relay.swarm4.sphinx.chat::030c76b569cd5b04b1bec7013554dba4eb7e418d7911d77f8094985f5745abd6b7

And here are the instructions to download sphinx: https://buy.sphinx.chat/

BTW how did you find this community?

**Comment by AbdulWahab3181** [comment]
I was searching for bounty issues on GitHub and came across this project.

**Comment by ecurrencyhodler** [comment]
@AbdulWahab3181 following up here. Did you sign up for a sphinx chat? Let me know if you did.

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler I just installed the application. It's asking for a connection code, which I haven't received yet. Could you please send it to abdulwahab3181@gmail.com?

**Comment by KumarNayan** [comment]
@ecurrencyhodler can I take this up ?

**Comment by ecurrencyhodler** [comment]
@KumarNayan this has already been assigned. Please check the issues before requesting.

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler Could you please review this [PR#1302](https://github.com/stakwork/sphinx-tribes/pull/1302)

**Comment by ecurrencyhodler** [comment]
@AbdulWahab3181 great job! Are you on sphinx? I'd like to pay you the bitcoin bounty. Also here's an [FAQ](https://docs.google.com/document/d/16NQ4SM4ptP4Lz5JKERAagdNw3GFRVv9eshMZ_oU-MVw/edit?usp=sharing) which includes steps to create an account on our site.

**Comment by AbdulWahab3181** [comment]
I appreciate that! Yes, I am on Sphinx. I'm glad to hear about the bitcoin bounty. Thanks for sharing the FAQ

**Comment by ecurrencyhodler** [comment]
Paid!
