### ISSUE TITLE
Placeholder profile images

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#123]
@plell @Evanfeenstra Please, use these placeholder images.

People placeholder image
![People_placeholder_profile](https://user-images.githubusercontent.com/13258550/144245173-f4bcc04f-436c-4df0-a904-2ea9d6f8ecc5.png)
Bot placeholder image
![Bot_placeholder_image](https://user-images.githubusercontent.com/13258550/144245168-9aaa46c8-80da-408a-a25e-1e4e6c537e4b.png)

**Comment by plell** [comment]
included in next deployment (later today)
