### ISSUE TITLE
[Tests][Unit] Complete Bounties unit test for frontend/app/src/store/main.ts

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1230]
### Context

main.ts houses all the API call functions. Add tests to complete all the bounty API calls,

File to add test

`src/store/__test__/main.spec.ts`

Make Mock APIs to get:
 
- To delete a bounty,  check ```deleteBounty``` in  frontend/app/src/store/main.ts, and mock the request API request in the function.
- To remove a bounty assignee, check ```deleteBountyAssignee``` in  frontend/app/src/store/main.ts, and mock the request API request in the function.
- To update a bounty payment status, check ```updateBountyPaymentStatus``` in  frontend/app/src/store/main.ts, and mock the request API request in the function.
- To get a bounty by its id, check ```getBountyById``` in  frontend/app/src/store/main.ts, and mock the request API request in the function.
- To get a bounty Index in the database by its id, check ```getBountyIndexById``` in  frontend/app/src/store/main.ts, and mock the request API request in the function.

Check ```src/store/__test__/main.spec.ts`` for example

We want to test that Bounty APIs return the right data

### Acceptance Criteria

- [ ] Test that the tests pass with the right data
- [ ] Also test for failures.

**Comment by elraphty** [comment]
@ecurrencyhodler will create a bounty for it.

**Comment by ecurrencyhodler** [comment]
All yours @wright-eric https://community.sphinx.chat/bounty/1029
