### ISSUE TITLE
[Tests][Unit] Add Organization unit test for frontend/app/src/store/main.ts

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1235]
### Context

main.ts houses all the API call functions. Add tests to organization API calls,

File to add test

`src/store/__test__/main.spec.ts`

Make Mock APIs to get:
 
- To add an organization , check ```addOrganization``` in  frontend/app/src/store/main.ts, and mock the request API request in the function.
- To get a user's organization,  check ```getUserOrganizations``` in  frontend/app/src/store/main.ts, and mock the request API request in the function. Note: The Mock should affect the store state, and assert that the calls changed the store state.
- To get a user's organization by UUID, check ```getUserOrganizationByUuid``` in  frontend/app/src/store/main.ts, and mock the request API request in the function, it should return a single organization.
- To update an organization check ```updateOrganization``` in  frontend/app/src/store/main.ts, and mock the request API request in the function.

Check ```src/store/__test__/main.spec.ts`` for example

We want to test that organization APIs return the right data

### Acceptance Criteria

- [ ] Test that the tests pass with the right data
- [ ] Also test for failures.

**Comment by gouravmpk** [comment]
I want to try this

**Comment by ecurrencyhodler** [comment]
@gouravmpk you have 3 pending bounties. Let's got those addressed first.

**Comment by gouravmpk** [comment]
> @gouravmpk you have 3 pending bounties. Let's got those addressed first.

Sure I have raised PR for one of them and the other one is not reproducible pinged kev accordingly, also The mark as paid flow is lengthy trying to get a workaround for the awards page.

**Comment by ecurrencyhodler** [comment]
okay I'll assign this to you.
