### ISSUE TITLE
[Tests][Unit] Add Organization Users unit test for frontend/app/src/store/main.ts

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1236]
### Context

main.ts houses all the API call functions. Add tests to organization users' API calls,

File to add test

`src/store/__test__/main.spec.ts`

Make Mock APIs to get:
 
- To add a user to an organization, check ```addOrganizationUser``` in  frontend/app/src/store/main.ts, and mock the request API request in the function.
- To get users in an organization,  check ```getOrganizationUsers``` in  frontend/app/src/store/main.ts, and mock the request API request in the function.
- To get a specific organization user check ```getOrganizationUser``` in  frontend/app/src/store/main.ts, and mock the request API request in the function, it should return a single organization user.
- To get the total count of a user's organizations, check ```getOrganizationUsersCount``` in  frontend/app/src/store/main.ts, and mock the request API request in the function, it should return a number of the total organizations.
- To delete an organization user ```deleteOrganizationUser``` in  frontend/app/src/store/main.ts, and mock the request API request in the function, this should delete an organization from the organization users list.

Check ```src/store/__test__/main.spec.ts`` for example

We want to test that organization users' APIs return the right data

### Acceptance Criteria

- [ ] Test that the tests pass with the right data
- [ ] Also test for failures.

**Comment by hritikmunde** [comment]
@elraphty , can I work on this?

**Comment by elraphty** [comment]
Okay, @hritikmunde What's ur username on Sphinx?

**Comment by hritikmunde** [comment]
Its Ednum

**Comment by elraphty** [comment]
> Its Ednum

Okay, thanks.

**Comment by elraphty** [comment]
@hritikmunde assigned

**Comment by hritikmunde** [comment]
Hi @elraphty , deleteOrganizationUser deletes the user from an organization right? Please specify as this is also done but I just want to clarify before making any changes.

**Comment by hritikmunde** [comment]
@ecurrencyhodler @elraphty , created a pull request for the changes I made. Please review and let me know if any change is required.

**Comment by ecurrencyhodler** [comment]
@hritikmunde in the future tie the issue you are addressing to the PR. It makes it harder to track if you don't!

Closed by #1247
