### ISSUE TITLE
[Tests][Component] Create test for people/widgetViews/OrganizationView.tsx

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1237]
### Context

OrganizationView.tsx displays a user organization list.

File to be tested
`src/people/widgetViews/__tests__/OrganizationView.spec.tsx`

Create a file named
`src/people/widgetViews/__tests__/OrganizationView.spec.tsx`

The organizations listed on OrganizationView come from ```main. organizations ``

Make a Mock API request to get the user's organization and add data to ```main. organizations```, check ```getUserOrganizations``` in  frontend/app/src/store/main.ts, and mock the request API request in the function.

Check ```frontend/app/src/bounties/__tests__/bountyTest.spec.ts``` for example

We want to test that the organizations listed match the mocked data organizations

### Acceptance Criteria

- [ ] Test that user's organizations are visible
- [ ] Test that the name displayed matches the title from the mock data
- [ ] Test that the view bounties button is visible
- [ ] Test that the manage button is visible if the user is the owner of the organization
- [ ] Test that the manage button is hidden if the user is not the owner of the organization

You can use this PR as an example `https://github.com/stakwork/sphinx-tribes/pull/1185`

**Comment by hritikmunde** [comment]
@elraphty , can I work on this?

**Comment by hritikmunde** [comment]
@kevkevinpal , can you help? I'm getting this TypeScript error
![image](https://github.com/stakwork/sphinx-tribes/assets/46834595/304d24b2-e51c-4285-8f0e-ae389e94ed8e)

**Comment by ecurrencyhodler** [comment]
Kev is going to be out for the next two weeks. @elraphty can you take a look?
