### ISSUE TITLE
Styling fixes - Profile Elements

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#124]
Homepage profile element
![image](https://user-images.githubusercontent.com/13258550/144254454-0feefb23-cf92-45d7-9130-234b326145e3.png)
Sidebar profile element
![image](https://user-images.githubusercontent.com/13258550/144259318-784f70a4-78de-4e9b-a13b-def5eb3e7ff6.png)
Main profile
![image](https://user-images.githubusercontent.com/13258550/144260193-241dfacd-17f9-4252-9b71-24390690c82b.png)
![image](https://user-images.githubusercontent.com/13258550/144262671-cf8be384-8cbf-480c-a9aa-bf72eb0dfb11.png)

**Comment by Antanasijevic** [comment]
![image](https://user-images.githubusercontent.com/13258550/144267360-36f95887-5139-414a-9dfc-d763455498f6.png)

**Comment by plell** [comment]
included in next deployment (later today)
