### ISSUE TITLE
I see the "I can help" on bounty even though I have managed permissions

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1241]
**Describe the bug**
When I go to the homepage and see the bounties platform, Raph created a bounty. But instead of seeing the "Assign Hunter" button, I see the "I can help" button. When I click on the "I can help" button, I'm prompted to connect to Raph instead of the bounty page opening up (which is the expected behavior).

<img width="1117" alt="Screenshot 2024-01-03 at 1 08 40 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/8b4399bd-5918-4d93-96bd-9fbbe3f90d38">

Good news is that when I click on the bounty, I'm able to assign a hunter.
<img width="1099" alt="Screenshot 2024-01-03 at 1 08 47 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/eed31ad7-850b-4a84-b980-a3674c0e7805">

**Expected behavior**
I should see the assign hunter when viewing a bounty from an org I have "manage bounty" permissions on even if someone else created it.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have created common logic saying whether we can manage bounty in the utils folder and use it in both places: the modal page and assign hunter button. 
- [ ] I have posted a video of the "assign hunter" button being correctly displayed and the bounty page being brought up when clicked.
- [ ] I have created a test that checks common logic

**Comment by Mayank77maruti** [comment]
Hey @ecurrencyhodler , please assign this task to me.

**Comment by ecurrencyhodler** [comment]
Hi! Thanks for reaching. This hasn't been posted as a bounty yet. Feel free to check our website for more bounties: https://community.sphinx.chat/bounties

I'll also ping you again once this is ready. 

Are you on sphinx chat already by any chance?

**Comment by Mayank77maruti** [comment]
Hi @ecurrencyhodler , I joined sphinx just currently.

**Comment by Mayank77maruti** [comment]
Hey @ecurrencyhodler Thanks can I please get an invite to the community chat so that I can know when tickets are available thanks

**Comment by ecurrencyhodler** [comment]
Of course. First download sphinx chat from here: https://buy.sphinx.chat/

Then sign up using this code as a new user: 
connect::relay.swarm4.sphinx.chat::02b19e99e1cda219795cc47c292bf2993c2f64a760bda16d24e5b3aad12152546d

Then sign into this website and let me know your username: https://community.sphinx.chat/bounties

BTW how did you hear about our project?

**Comment by Mayank77maruti** [comment]
@ecurrencyhodler , thank you so much for the invitation. I came across sphinx while I was searching for bug bounties :)

**Comment by Mayank77maruti** [comment]
Hi @ecurrencyhodler , my username is Naruto7.

**Comment by ecurrencyhodler** [comment]
Awesome! Okay will probably ping you sometime tomorrow.

**Comment by ecurrencyhodler** [comment]
@Mayank77maruti okay this is good to go! Please review the acceptance criteria before starting your work as it has been updated.

**Comment by ecurrencyhodler** [comment]
Bounty has been assigned to you as well: https://community.sphinx.chat/bounty/1069

**Comment by ecurrencyhodler** [comment]
@Mayank77maruti do you have an update here?

**Comment by ecurrencyhodler** [comment]
I'm going to unassign the issue and bounty from you @Mayank77maruti 

@wright-eric can you take this?

**Comment by wright-eric** [comment]
yes sure @ecurrencyhodler
