### ISSUE TITLE
Remove image from bounty that is being displayed on the home page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1242]
**Describe the bug**
The image inside the bounty and github issue is being displayed on the home page.

https://community.sphinx.chat/bounty/1033

<img width="1117" alt="Screenshot 2024-01-03 at 1 08 40 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/6d57c699-b0bb-49e9-b98c-face10c2f4e8">

**Expected behavior**
The image should not be displayed.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot of the fix

**Comment by VividhPandey003** [comment]
Could you please assign it to me @ecurrencyhodler

**Comment by ecurrencyhodler** [comment]
This is yours vividh. https://community.sphinx.chat/bounty/1066
