### ISSUE TITLE
Enable clicking of bounties inside of super admin

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1244]
### Context
Right now, bounties are unclickable in superadmin. What is expected is that when I right click on the bounty title, I should be able to open it up in a new window.

<img width="954" alt="Screenshot 2024-01-03 at 3 17 40 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/975df7b4-4549-499c-904a-1c5cf6fe8419">

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a video recording of my PR

**Comment by Vayras** [comment]
Hey! @ecurrencyhodler since I have finished all of my other bounties can I work on this issue as well? Let me know thanks

**Comment by ecurrencyhodler** [comment]
Go for it.
