### ISSUE TITLE
Wrong status is displayed in super admin for paid bounties

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1245]
**Describe the bug**
The status that is being displayed in super admin says "completed". It should be "paid."
<img width="939" alt="Screenshot 2024-01-03 at 3 21 42 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/81253912-b6f3-4c0b-b0e7-ff357e49f319">

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot of the correct status being displayed

**Comment by Vayras** [comment]
Hi @ecurrencyhodler I would like to work on this issue, can you please assign me to this

**Comment by ecurrencyhodler** [comment]
Done
