### ISSUE TITLE
Admin is not showing the hunter/provider alias of the sphinx profiles 

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1246]
**Describe the bug**
Admin is not showing the hunter/provider alias of the sphinx profiles. It's just showing the pubkey.

<img width="1166" alt="Screenshot 2024-01-04 at 9 41 23 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/eed421d4-a13a-40ab-b07b-4a1824b0d971">

**Expected behavior**
It should display the alias associated with the pubkey.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot of superadmin displaying the alias
- [ ] Add test you can see alias

**Comment by Mayank77maruti** [comment]
Hey @ecurrencyhodler , please assign this task to me.

**Comment by ecurrencyhodler** [comment]
It's yours!

**Comment by gmkadu** [comment]
@ecurrencyhodler Can I take this ne

**Comment by ecurrencyhodler** [comment]
@gmkadu this is yours if you respond today. Did you download sphinx?

**Comment by gouravmpk** [comment]
Yeah I'm working on it rn

**Comment by ecurrencyhodler** [comment]
@gouravmpk this is yours.

**Comment by gouravmpk** [comment]
Thanks

**Comment by gouravmpk** [comment]
@ecurrencyhodler is this fine ?

https://github.com/stakwork/sphinx-tribes/assets/20900042/0db5a0d5-d6d1-4899-ad46-ee3c996704ef
