### ISSUE TITLE
Viewing bounty from profile pops up twice

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1254]
**Describe the bug**
When I view a bounty in my profile (both under created and assigned), the bounty pops up twice.  This is most likely a routing issue.

https://github.com/stakwork/sphinx-tribes/assets/32662508/8d07122c-c982-4ec4-9a3c-31b73f53e318

**Expected behavior**
The bounty page should only appear once.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video

**Comment by aliraza556** [comment]
@ecurrencyhodler could you assign me this task?

**Comment by ecurrencyhodler** [comment]
This is yours!

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler, there's one more issue. Please check the problem in the [demo](https://www.loom.com/share/72c5911ecd0d48b4a8b96fafaa0bb98d) video

**Comment by ecurrencyhodler** [comment]
Thanks for raising that! It's been addressed already in staging!
