### ISSUE TITLE
Make the Admin Filter Status Functional

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1258]
### Context

The admin filter status currently doesn't work 

### Design

On selecting any of the statuses from the filter dropdown the metrics bounties list should be re-rendered and list only the status selected

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a component test that Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by ecurrencyhodler** [comment]
@elraphty does #1257 close this?
