### ISSUE TITLE
[Tests][Component] Create test for people/widgetViews/OrganizationDetails.tsx

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1261]
### Context

OrganizationDetails.tsx displays the details and users of an organization add test coverage.

File to be tested
`src/people/widgetViews/__tests__/OrganizationDetails.spec.tsx`

Create a file named
`src/people/widgetViews/__tests__/OrganizationDetails.spec.tsx`

Mock a user organization and pass it as a prop to OrganizationDetails, check the `Organization` interface in /app/src/store/main.ts, and make a mock.

Mock the local storage and add a user, the user pubkey should be the same as the Organization `owner_pubkey` so the user can be the org admin.

Check ```frontend/app/src/bounties/__tests__/bountyTest.spec.ts``` for example

We want to test that the right organization details are displayed 

### Acceptance Criteria

- [ ] Test that the organization name Is visible
- [ ] Test that the Deposit, Withdraw, Edit, View Bounties, and History buttons are visible
- [ ] Test that Edit, and Add User buttons are disabled if the user is not the admin
- [ ] Test that View Bounties is disabled if the organization `bounty_count` is 0 
- [ ] Test that the History, and Withdraw Buttons are disabled if the user is not the admin

You can use this PR as an example `https://github.com/stakwork/sphinx-tribes/pull/1185`

**Comment by wright-eric** [comment]
@elraphty  can i work on this ?

**Comment by ecurrencyhodler** [comment]
This is yours eric
