### ISSUE TITLE
Make Admin Metrics Page Responsive On Bounties Section

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1264]
### Context

The current admin metrics page `/admin` is not responsive. 

![Metrics Page Currently](https://i.ibb.co/z5K67yZ/Screenshot-2024-01-05-at-16-34-10.png)

Add responsiveness to the page for various screens using media queries. The admin page should be responsive both when it is zoomed out and zoomed in.

Todo:

- Make the bounty table responsive
- Make the Metrics statistics boxes responsive
- Make the Metrics header and buttons responsive

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a recording in my pr of the responsive design
- [ ] I've tested the metrics page on multiple screens and it looks good

**Comment by mukeshblackhat** [comment]
i am good with frontend i can make it responsive assign this to me

**Comment by ecurrencyhodler** [comment]
Hey welcome @mukeshblackhat ! We actually have a bitcoin bounty for this. Are you on sphinx chat?

Also I'm curious, how did you hear about this project?

**Comment by mukeshblackhat** [comment]
NO i dont have the account , i tried it stated i need referal code and i am actively looking for the opensource contributions so i discovered your repos @ecurrencyhodler

**Comment by ecurrencyhodler** [comment]
Amazing! Okay here's our [FAQ](https://docs.google.com/document/d/16NQ4SM4ptP4Lz5JKERAagdNw3GFRVv9eshMZ_oU-MVw/edit?usp=sharing). Follow the instructions there. 

Also here is a code for you to use:
connect::relay.swarm4.sphinx.chat::0284974132185a09b2e8d201c6bf6a13f630ec2737da8aee9bde85aa18ab40fa18

Let me know when you created a profile on our site and I'll assign the bounty to you.

**Comment by mukeshblackhat** [comment]
i am on the app u can assign me the bounty now @ecurrencyhodler  i am blackhat

**Comment by ecurrencyhodler** [comment]
Assigned!

**Comment by ecurrencyhodler** [comment]
@mukeshblackhat we are going to scope down this issue a little bit.

All you have to do is make the description box dynamically expand and shrink with the view. 

Don't touch the stats (top half of super admin) as that is going to change.

**Comment by bilalshaikh292** [comment]
heyy @ecurrencyhodler is the issue still open ? i would like to solve this ? i have a coount on sphinx too.

**Comment by bilalshaikh292** [comment]
@ecurrencyhodler and also i have peviously worked on sphinx and have also earned a bonty too . assign me please so that i can start Working.

**Comment by ecurrencyhodler** [comment]
Hi @bilalshaikh292 welcome back!

As you can see, this issue has been assigned already.

Check out the bounties homepage for open bounties! https://community.sphinx.chat/bounties

**Comment by bilalshaikh292** [comment]
But its a small issue and its not solved yet.

**Comment by ecurrencyhodler** [comment]
@bilalshaikh292 complaining is not the way for you to get assigned a bounty. This makes me more resistant to assign you one. 

Follow the process and if it opens up, I'll let you know.

Also here's an [FAQ](https://docs.google.com/document/d/16NQ4SM4ptP4Lz5JKERAagdNw3GFRVv9eshMZ_oU-MVw/edit?usp=sharing). In there you can see a hunters tribe to join if you want.

**Comment by bilalshaikh292** [comment]
Sorry i was not complaning i thought the other was not working .any way i will for another issue thanks

**Comment by ecurrencyhodler** [comment]
@mukeshblackhat do you have an update on this issue?

**Comment by mukeshblackhat** [comment]
Yes I am Working on it , it will be completed soon .

**Comment by elraphty** [comment]
@mukeshblackhat pull from the master branch, there has been some new updates on the design after merging this PR https://github.com/stakwork/sphinx-tribes/pull/1352

**Comment by bilalshaikh292** [comment]
heyy @ecurrencyhodler as you have mentoned to resize only the the botttom half i was having a confusion on what things need to be made responsive . do i only  have  to make the bounties i.e bottom half responsive or The table  Which is above it .

**Comment by ecurrencyhodler** [comment]
Let's just do the bounties for now. I'm only going to use it on desktop and not mobile.

**Comment by bilalshaikh292** [comment]
![image](https://github.com/stakwork/sphinx-tribes/assets/110531971/beb0aa25-71e7-4ed3-90db-c247a824fd0e)

**Comment by bilalshaikh292** [comment]
You mean this section

**Comment by bilalshaikh292** [comment]
![image](https://github.com/stakwork/sphinx-tribes/assets/110531971/0d25c25c-c3bd-4375-9425-b702197a88b5)
Or this bounties table

**Comment by bilalshaikh292** [comment]
so do you want me to change the table format or should it have a hoizontal scroll view. And also How to check it without data as I don't have a Admin account.

**Comment by ecurrencyhodler** [comment]
Let's just make the description boxes dynamically expand and shrink with the view in the bounties section (bottom half). 

You don't need an admin account for now. We haven't restricted access.

**Comment by ecurrencyhodler** [comment]
This isn't well defined. We don't need to make it responsive for mobile either as I will only use this on desktop.
