### ISSUE TITLE
Get sphinx for a signed in user displays a "post bounty" modal

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1271]
**Describe the bug**
When a user is signed in, the "get sphinx" button prompts a "create bounty" modal. 
https://www.loom.com/share/e0877101f0034e7da377fcb87d1da5f6?sid=d789f18e-4f12-4a8b-acff-69b0c8239476

**Expected behavior**
It should open this page in a new window instead: https://buy.sphinx.chat/

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video 
- [ ] I've created a test that the button links to the correct link if a user is signed in

**Comment by Vayras** [comment]
Hey! @ecurrencyhodler I would like to work on this issue
