### ISSUE TITLE
Add parameters to prioritize open bounties inside of profile for assigned bounties

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1274]
### Context
Currently, bounties are listed chronologically regardless of status.
<img width="997" alt="Bounties" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/0adc1c53-6217-4ee3-997a-10854d4e4da6">

We've gotten feedback from several hunters who said they would prefer to have open bounties first as it would help the locate bounties they need to work on first.
<img width="689" alt="1" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/9e735457-28f7-4295-8dec-7b94cedfd41b">
<img width="693" alt="2" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/befcf7ae-2adc-4f83-a672-df93477c04e3">

As a bounty provider, it would also help me keep track of open bounties as well. 

The fix is to add a parameter to the api call to prioritize open bounties call first. I'll create another issue to enable pagination in the backend to match the 20 displayed bounties under assigned bounties.

### Design
One simple and quick fix would be to simply show open bounties first like this:
<img width="1192" alt="Screenshot 2024-01-06 at 10 32 25 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/17bb943e-ef1b-4efc-bf19-1fa759b88f13">

### Acceptance Criteria
- [ ] I've tested on Chrome

**Comment by VividhPandey003** [comment]
Assign @ecurrencyhodler

**Comment by ecurrencyhodler** [comment]
Reopening as this isn't working for assigned bounties. It is working for created bounties.

**Comment by VividhPandey003** [comment]
Update: Will have a look at it today.

**Comment by ecurrencyhodler** [comment]
@VividhPandey003 I think what's remaining is a backend issue. raph is going to take a look.

**Comment by VividhPandey003** [comment]
> @VividhPandey003 I think what's remaining is a backend issue. raph is going to take a look. 

Yea actually I have the fix i guess. Should I add it here in comments?

**Comment by ecurrencyhodler** [comment]
You were able to find the backend fix?
