### ISSUE TITLE
Enable scrolling of bounties on the home page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1276]
**Describe the bug**
I'm unable to scroll left and right on the home page.

https://github.com/stakwork/sphinx-tribes/assets/32662508/0f311657-70b2-48b8-8673-09bdb6f293aa

**Expected behavior**
I should be able to scroll left and right based on the order of bounties on the home page. This should work for all statuses.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video of scrolling

**Comment by Gaurav-Gaikwad-1** [comment]
Okay assign me this

**Comment by ecurrencyhodler** [comment]
Okay. We also have a bitcoin bounty. Are you on sphinx chat yet?

**Comment by Gaurav-Gaikwad-1** [comment]
yes I am by name Gstar

**Comment by ecurrencyhodler** [comment]
Great bounty has been assigned to you.

**Comment by ecurrencyhodler** [comment]
Also read through our [FAQ](https://docs.google.com/document/d/16NQ4SM4ptP4Lz5JKERAagdNw3GFRVv9eshMZ_oU-MVw/edit?usp=sharing)!

**Comment by ecurrencyhodler** [comment]
@Gaurav-Gaikwad-1 so @Vayras mistakenly fixed this issue. Would you mind taking #1277 ?

Also @Vayras can you comment on this issue so I can have this assigned to you?

**Comment by Vayras** [comment]
hey @ecurrencyhodler  just completed this issue.

**Comment by Vayras** [comment]
@Gaurav-Gaikwad-1 sorry for the inconvenience , I will try to send you some code information related to the other task which will help you to complete that, thanks

**Comment by Gaurav-Gaikwad-1** [comment]
@ecurrencyhodler Okay then I will work on #1277
@Vayras thanks let me know.

**Comment by ecurrencyhodler** [comment]
@Gaurav-Gaikwad-1 can you also check your sphinx chat? I sent you a message.

**Comment by Gaurav-Gaikwad-1** [comment]
@ecurrencyhodler I didn't recieve any message from you

**Comment by ecurrencyhodler** [comment]
Are you Gaurav_155 on sphinx chat?

**Comment by Gaurav-Gaikwad-1** [comment]
I am by name Gstar
