### ISSUE TITLE
Enable scrolling on the org page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1277]
**Describe the bug**
I'm unable to scroll left or right on the org page: https://people-test.sphinx.chat/org/bounties/ck95pe04nncjnaefo08g

Also it is displaying the incorrect bounty. The 2nd bounty that appears in the video is not part of the org.

https://github.com/stakwork/sphinx-tribes/assets/32662508/3dcc3a41-ba8c-4db9-9b65-603de98f3705

**Expected behavior**
I should be able to scroll left and right based on the order of bounties on the org page.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video
- [ ] Add a test here so that the arrows correctly calls the next bounty on the org page when scrolling. 
- [ ] Add acomponent test that an action happens when an arrow is clicked.

**Comment by Gaurav-Gaikwad-1** [comment]
Can you assign this to me?

**Comment by Vayras** [comment]
@ecurrencyhodler I would like to work on this , can you assign me to this

**Comment by ecurrencyhodler** [comment]
Hey @Gaurav-Gaikwad-1 I'm going to assign this to @Vayras as it's a bit complicated. 

Let me find a different issue for you.

BTW how did you hear about our project?

**Comment by ecurrencyhodler** [comment]
@Gaurav-Gaikwad-1 how about this one? https://github.com/stakwork/sphinx-tribes/issues/1276

**Comment by Gaurav-Gaikwad-1** [comment]
Yes please assign me that
@hritikmunde referred me

**Comment by ecurrencyhodler** [comment]
@Gaurav-Gaikwad-1 do you have an update?

**Comment by ecurrencyhodler** [comment]
Hey Vayras. Raph said he created the endpoints but has to merge another pr first before he can push that one to main. So he will keep you posted.

**Comment by Vayras** [comment]
@ecurrencyhodler Thanks for the update
