### ISSUE TITLE
Update button to "Mark as Unpaid" when bounty is paid

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#1279]
just noticing one issue with desktop

Should say mark unpaid
![Screenshot 2024-01-08 at 9 34 33 AM](https://github.com/stakwork/sphinx-tribes/assets/15950706/fa0bba88-06d0-4b34-9bd5-435bb36809b5)

_Originally posted by @kevkevinpal in https://github.com/stakwork/sphinx-tribes/issues/1218#issuecomment-1881241725_

### Acceptance Criteria

- [ ] I've tested on Chrome
- [ ] I've posted a screenshot of it correctly saying "Mark as Unpaid"
- [ ] Create a component test if status is paid, the button shows "Mark as Unpaid"

**Comment by gouravmpk** [comment]
I fixed this in my pr

**Comment by ecurrencyhodler** [comment]
This hasn't been resolved and is still live on staging.

**Comment by gouravmpk** [comment]
I will look into it

**Comment by ecurrencyhodler** [comment]
Sure I can turn this into a small bounty. It's a small text change.

**Comment by ecurrencyhodler** [comment]
https://people-test.sphinx.chat/bounty/1110
