### ISSUE TITLE
Add "Load more" button to created bounties in the people page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1284]
### Context
Add "Load more" button to created bounties in the people page and restrict visibility to 20 bounties. 

### Design
Match it with the design in the assigned bounties section

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created mock data for the api to load more bounties
- [ ] I've created a component test that tests the "load more" button is displayed when we scroll down. Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by VividhPandey003** [comment]
Assign @ecurrencyhodler

**Comment by hritikmunde** [comment]
Assign

**Comment by ecurrencyhodler** [comment]
It's already been assigned. Make sure to check the issues before commenting!
