### ISSUE TITLE
Enable LNAUTH user ability to manage bounties

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1287]
**Describe the bug**
An LNAUTH user is unable to assign a hunter even when they have the correct permissions in the org. 

https://github.com/stakwork/sphinx-tribes/assets/32662508/cc25c2ad-c791-4104-a7ba-76a934ee8eff

**Expected behavior**
An LNAUTH user should be able to manage a bounty if they have the right permissions. This includes:
- Edit
- Delete
- Assign
- Pay

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video if it is a change in the front end

**Comment by gouravmpk** [comment]
Can I Take this ?

**Comment by ecurrencyhodler** [comment]
@gouravmpk this might be a bit complex. But if you think you can take it, I will turn this into a bounty and assign it to you.

**Comment by ecurrencyhodler** [comment]
Hmmm i just tested as well and it looks like I can now. Sorry raph. Thanks for taking a look.
