### ISSUE TITLE
Update designs for publicly facing org page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1291]
Here is the design in [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=8698%3A6666&mode=design&t=pXBySiUq69mb3yWO-1) where I left some comments.

**Comment by Antanasijevic** [comment]
Organization Homepage

![image](https://github.com/stakwork/sphinx-tribes/assets/13258550/0758ec26-485b-4b54-8169-face3df06c7a)


HEADER VARIATIONS WITH ADMIN ACCESS

Version with large (2 line) description
![image](https://github.com/stakwork/sphinx-tribes/assets/13258550/307a97a1-663b-409c-8a52-c88e75a1685e)

Version with small (2 line) description

![image](https://github.com/stakwork/sphinx-tribes/assets/13258550/2e99d936-54c6-4b19-a6b4-245c74528725)

Version with no description
![image](https://github.com/stakwork/sphinx-tribes/assets/13258550/4fb92a9c-e170-4818-a832-4d88d1a03136)


HEADER VARIATIONS WITHOUT ADMIN ACCESS

**Comment by ecurrencyhodler** [comment]
Amazing. thanks for also considering non-signed in flows.
