### ISSUE TITLE
Add hunter stats to super admin view

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1292]
Here is the design in [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=10218%3A26894&mode=design&t=MoIn3j84bRHVQJ2t-1).

**Comment by Antanasijevic** [comment]
![image](https://github.com/stakwork/sphinx-tribes/assets/13258550/c2e935f7-2369-43ea-b6ae-b9b067756e98)

**Comment by ecurrencyhodler** [comment]
thanks milan!
