### ISSUE TITLE
Add validation check for org name to be 20 characters or less

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1308]
### Context
Now that we are revamping the org home page, we will need to set limits to org names so that it fits nicely within our designs. 

<img width="715" alt="Screenshot 2024-01-09 at 12 30 45 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/c93e4b65-c797-4a0c-add2-ca62ee273db0">

Let's limit the width to the name of an organization to 20 characters.

### Acceptance Criteria
- [ ] I've added a validation check that the length of an org name is 20 characters or less. If it greater than 20 then a response will be returned as "Error: exceeds 20 character limit".
- [ ] Create a unit test that checks if validation fails and passes

**Comment by wright-eric** [comment]
Assign
