### ISSUE TITLE
Enable create/edit org call to send 3 new fields to backend

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1309]
### Context
Update endpoint to accept the three fields mentioned in #1307.

There are two diff. modals but designs are the same: Create organization and Edit organization.

Add organization: frontend/app/src/people/widgetViews/organization/AddOrganization.tsx

Edit organization: frontend/app/src/people/widgetViews/organization/EditOrgModal.tsx

Add website, github, and description field command to the body of the request.

And also populate website, github, and description inputs for edits.

 Also make sure to return error responses if any of the validation checks fail.

### Acceptance Criteria

- [ ] Add test for edit organization so that all values passed for org should be visible such as github, website, description if there is data. But if there is no org name the test should fail.
- [ ] Add test that checks that if save changes is clicked, a call is made.

**Comment by wright-eric** [comment]
Assign

**Comment by wright-eric** [comment]
hi @ecurrencyhodler  i can see that raph has already done those changes in this (MR)[https://github.com/stakwork/sphinx-tribes/pull/1376https://github.com/stakwork/sphinx-tribes/pull/1376]. He has updated add and edit organization endpoint to include these 3 new fields

**Comment by wright-eric** [comment]
if this a UI change if yes than we can remove the `backed` tag to clear some confusions
