### ISSUE TITLE
Enable search endpoint in org homepage

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1311]
### Context
We will enable searching of bounties in org homepage. Let's enable the endpoint for this. 

Use same endpoint we use on the homepage search bar and add query params for org_uuid. 
![Organization Page-Desktop (1)](https://github.com/stakwork/sphinx-tribes/assets/32662508/c22ba349-f834-4c1c-be23-ff7606399bdb)

### Acceptance Criteria
- [ ] Create a unit test so that if you do search with the new query parameters, that only bounties associated with that org show up.

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler  could you assign me this task?

**Comment by ecurrencyhodler** [comment]
@aliraza556 are you familiar with go?

**Comment by aliraza556** [comment]
@ecurrencyhodler Yes, I am.

**Comment by ecurrencyhodler** [comment]
Can you address this issue for? https://github.com/stakwork/sphinx-tribes/issues/1209

**Comment by wright-eric** [comment]
Can i work on this @ecurrencyhodler ?
