### ISSUE TITLE
Create basic home page template without button functionality

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1312]
### Context
Implement the design for the basic homepage design including the buttons. But don't enable the button functionality. We will handle those in separate PR's. 

Add `GET '/organizations/{uuid}'` when you land on the org page. 

**Do not include**
Do NOT include the website and github buttons for the website. That will be handled in a separate PR. Also do not include the org name, logo, or description box for the org either. The endstate should look like the image in the design section of this issue.

For the # of bounties, use dummy data and set a 3 digit number.

For the search bar, make it unclickable.

For the "post a bounty button" you can repurpose the existing button. Just make sure the design matches what is in figma.

### Design
![Organization Page-Desktop (1)](https://github.com/stakwork/sphinx-tribes/assets/32662508/c86fc76f-c12c-4b68-87ce-fcdda0f4c0a7)

Make sure that the PR matches the hi-fidelity design in [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=10347%3A12771&mode=design&t=AgKX6SW5J4gLGz56-1).  Use [dev mode](https://www.figma.com/dev-mode/) in figma to help you with your work.

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot in my pr of the design
- [ ] I've created a component test that validates the status button appears
- [ ] I've created a component test that validates the skills button appears
- [ ] I've created a component test that validates the search bar appears
- [ ] I've created a component test that validates the sort by button appears
- [ ] I've created a component test that validates the post a bounty button appears
- [ ] I've created mockdata and a component test that validates the # of bounties appears

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by aliraza556** [comment]
HI @ecurrencyhodler could you assign me this task?

**Comment by Vayras** [comment]
hey @ecurrencyhodler I would like to work on this issue, can you assign me to this

**Comment by ecurrencyhodler** [comment]
@aliraza556 I'm going to assign this to vayras. He's done similar work for superadmin and since this is a key piece that unlocks future issues I want him to work on it. 

I'll will definitely assign you other bounties once this has been resolved.

**Comment by aliraza556** [comment]
@ecurrencyhodler Ok no issue.
