### ISSUE TITLE
Implement the status filter on the org homepage

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1313]
### Context
Implement the status filter on the org homepage. It should include:

- Open
- Assigned
- Completed
- Paid

Also make sure that when a user clicks on status, it fires the correct API call and parameters.

The default filter should show bounties of all statuses, all skills (which should be 0 skills selected), and newest bounty first.

### Design
Here is the design in [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=8704%3A9459&mode=design&t=AgKX6SW5J4gLGz56-1). Use [dev mode](https://www.figma.com/dev-mode/) if needed. 
![Group 399](https://github.com/stakwork/sphinx-tribes/assets/32662508/5de215b7-8c9e-401e-a1ff-89ead5eeb031)

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a recording in my pr going through each state
- [ ] I've created a component test that makes sure that when the button is clicked, the correct api call gets made with correct query parameters.
Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler could you please assign me this task?

**Comment by ecurrencyhodler** [comment]
Hey abdul! You have 2 pending bounties. Let's focus on those first.

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler 
I can help with this 
Can you assign me

**Comment by gouravmpk** [comment]
I can take this

**Comment by ecurrencyhodler** [comment]
Both of you have several bounties open. 

Ekep let's focus on getting your sort by PR merged and then edit organization one.

**Comment by okhot** [comment]
Can take this. One of my PR's is in review and I'm closing in on the second one

**Comment by MahtabBukhari** [comment]
Could you assign me @ecurrencyhodler?

**Comment by ecurrencyhodler** [comment]
@MahtabBukhari this is yours. @okhot you have another you requested. you can take that one.

**Comment by MahtabBukhari** [comment]
Thank you @ecurrencyhodler

**Comment by MahtabBukhari** [comment]
Hi @ecurrencyhodler, I would like to confirm whether I only need to implement an API call when the user clicks on the [STATUS](https://i.imgur.com/X9H7DHN.png) button with default parameters, or if I also need to implement API calls for the 'Open,' 'Assigned,' 'Completed,' and 'Paid' checkboxes when they are clicked?

**Comment by ecurrencyhodler** [comment]
Just the status button.

**Comment by ecurrencyhodler** [comment]
Hey @MahtabBukhari I tried testing this on staging and for some reason the bounties displays don't function like they do in your video. Did we have a regression? Can you take a look?

https://github.com/stakwork/sphinx-tribes/assets/32662508/c278b8bc-2934-4674-a8ac-cfefffcfd49d

**Comment by MahtabBukhari** [comment]
It's weird I think due to merging others code it's effected let me check it what is happening behind the seen.

**Comment by MahtabBukhari** [comment]
Hi @ecurrencyhodler , It is working perfectly in my side at staging point you can see that video
https://www.loom.com/share/850c81860e13415c8416bbf80b2c7daa

**Comment by MahtabBukhari** [comment]
Also the complete check box would be not work becuase at backend side there is no implimentation for that is present 
![image](https://github.com/stakwork/sphinx-tribes/assets/98140673/274271cc-a63d-4733-bb81-699abc985ddf)

**Comment by ecurrencyhodler** [comment]
Hmmm okay. I'm going to have to create a separate issue then.

**Comment by ecurrencyhodler** [comment]
Looks like staging wasn't updated. Sorry about that. It's working now.

**Comment by MahtabBukhari** [comment]
Not a problem @ecurrencyhodler 😊
