### ISSUE TITLE
Implement skills filter on org homepage

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1315]
### Context
Implement the status filter on the org homepage. It should include all the filters in the home when skills are selected.

Also make sure that when a user clicks on skills, it fires the correct API call and parameters.

The default filter should show bounties of all statuses, all skills (which should be 0 skills selected), and newest bounty first.

### Design
Here is the design in [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=8605%3A12600&mode=design&t=AgKX6SW5J4gLGz56-1). Use [dev mode](https://www.figma.com/dev-mode/) for exact requirements.
![Dropdown type=Skills Dropdown](https://github.com/stakwork/sphinx-tribes/assets/32662508/9bc34008-64fc-4c42-b554-8061d88617a2)

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a recording in my pr selecting 3 skills
- [ ] I've created a component test that makes sure that when the button is clicked, the correct api call gets made with correct query parameters.

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by Vayras** [comment]
@ecurrencyhodler I would like to work on this ,can I take this?, let me know thanks

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler could you please assign me

**Comment by ecurrencyhodler** [comment]
Its' yours @Vayras
