### ISSUE TITLE
Add website and github buttons to org home page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1317]
### Context
When the org page is loaded, a get request is made and website + github sites will be returned if it is available in the database. Buttons are left aligned if visible. So if github link is available but not website, the github button will be left aligned.

This is the call: `GET '/organizations/{uuid}'`

Display the website and/or github link as a button on the page. When a user clicks on it, it should open in a separate window. 

### Design
<img width="334" alt="Screenshot 2024-01-09 at 3 20 59 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/db9eff26-099c-4136-a87e-509bc57a1d66">

You can find the design in [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=10247%3A20688&mode=design&t=AgKX6SW5J4gLGz56-1). Make sure to follow the exact requirements. Use figma's [dev mode](https://www.figma.com/dev-mode/) if needed.

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a recording in my pr of clicking the button.
- [ ] I've created mock data for the website urls
- [ ] I've created a component test that validates the buttons appear when website and github is available
- [ ] I've created a component test that buttons are left aligned if visible

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by gouravmpk** [comment]
Assign

**Comment by aliraza556** [comment]
Hi @gouravmpk Please check this issue #1315. He is free.

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler,
Could you please confirm whether I need to create a design similar to the one in this [image](https://i.imgur.com/u8yIvb3.png) within org/bounties? Also, could you clarify if I should design both the logo and heading along with the two buttons, or do I only need to design the two buttons?

**Comment by ecurrencyhodler** [comment]
@aliraza556 you just need to design the two buttons. You can follow the designs in figma.

**Comment by aliraza556** [comment]
On this page route org/bounties/:id?

**Comment by ecurrencyhodler** [comment]
@aliraza556 This is unblocked. You can use this as a test org. https://people-test.sphinx.chat/org/bounties/cmkln4tm098m49vhlt80

**Comment by aliraza556** [comment]
Ok Thanks
