### ISSUE TITLE
Create description box for org home page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1318]
### Context
When the org page is loaded, a get request is made and the org description will be returned if it is available in the database. 

This is the call: `GET '/organizations/{uuid}'`

Display the org description if it is available.

### Design
Here's the design in [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=8704%3A9459&mode=design&t=AgKX6SW5J4gLGz56-1). Use [dev mode](https://www.figma.com/dev-mode/) for exact requirements.
<img width="1059" alt="Screenshot 2024-01-09 at 3 36 22 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/6c771779-1783-4039-ac61-9705a5347952">

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot in my PR of the description
- [ ] I've created mockdata to display the description
- [ ] I've created a component test that asserts the description for the org will be displayed if available.

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by ecurrencyhodler** [comment]
Reserving this one for @Khaalid-oh for another chance to earn a bounty. 

Can you leave a comment?

**Comment by Khaalid-oh** [comment]
Alright, thanks. I'm waiting for it to be unblocked

**Comment by ecurrencyhodler** [comment]
This is unblocked. You can use this as a test org. https://people-test.sphinx.chat/org/bounties/cmkln4tm098m49vhlt80

**Comment by Khaalid-oh** [comment]
I created a PR:https://github.com/stakwork/sphinx-tribes/pull/1433 for this
