### ISSUE TITLE
Add org name and logo to org home page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1319]
### Context
When the org page is loaded, a call is made and the org name and logo will be returned if it is available in the database and meme server.

Display the logo and org name if it is available. If a logo is not available, the default org image will be displayed.

This is the call: `GET '/organizations/{uuid}'`

### Design
Here is the design in [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=8605%3A12600&mode=design&t=AgKX6SW5J4gLGz56-1). Use [dev mode](https://www.figma.com/dev-mode/) for exact requirements.
![Organization Header](https://github.com/stakwork/sphinx-tribes/assets/32662508/bf6b6e0a-e28a-4282-bff5-8d17d2c1f935)

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot in my pr
- [ ] I've created mockdata for an org name
- [ ] I've created a component test that validates the name is displayed if available
- [ ] I've created a test that validates the default image will displayed if logo image is not present

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler  could you please assign me this when it is unblocked?

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler could you please assign me?

**Comment by ecurrencyhodler** [comment]
@NengakDakup do you want to take this one?

**Comment by NengakDakup** [comment]
@ecurrencyhodler yeah man. Would love to work on this

**Comment by ecurrencyhodler** [comment]
You can use this as a test org. https://people-test.sphinx.chat/org/bounties/cmkln4tm098m49vhlt80

**Comment by ecurrencyhodler** [comment]
@NengakDakup I need an update on this. If I don't hear back by tomorrow I'm going to reassign this issue.

**Comment by NengakDakup** [comment]
@ecurrencyhodler  will submit a PR later in the day on this

**Comment by aliraza556** [comment]
@ecurrencyhodler Please assign me? If you reassign this issue.

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler this issue is available?
