### ISSUE TITLE
Auto-populate org when "create a bounty" modal is initiated from org page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1320]
### Context
When someone creates a bounty from an org page, the org field should be auto-populated when they reach step 2 instead of it being manually set. Here is an example of an org page: https://community.sphinx.chat/org/bounties/ck95pe04nncjnaefo08g

### Design
<img width="925" alt="Screenshot 2024-01-09 at 3 55 12 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/3569d1b2-5b77-4821-bea0-c4222e84b5d8">

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a recording in my pr showing this work
- [ ] I've included appropriate tests that asserts the same org is populated as the org page I'm on

**Comment by Vayras** [comment]
@ecurrencyhodler I would like to contribute towards this issue, can I work on this?

**Comment by ecurrencyhodler** [comment]
Sure. However our team isn't exactly sure how to implement it so you will need to figure out your own solution. If you're okay with that, I can assign it to you.

**Comment by Vayras** [comment]
> Sure. However our team isn't exactly sure how to implement it so you will need to figure out your own solution. If you're okay with that, I can assign it to you.

@ecurrencyhodler yeah I know how to get this done ,  you can assign this to me, thanks
