### ISSUE TITLE
Update "edit organization" UI

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1332]
### Context
Now that we are revamping the org homepage, we need to add fields for description, website, and github repo to the edit organization. We will handle character restrictions in a separate issue. But implement the org name as a required field.

### Design
Here is the design in [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=10360%3A6845&mode=design&t=YE6C1hFPCjMOCAhN-1). Use [dev mode](https://www.figma.com/dev-mode/) for exact requirements. 
![Edit Organization](https://github.com/stakwork/sphinx-tribes/assets/32662508/628be98f-08a0-4573-8bfa-03653b3efb3b)

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've tested on Chrome
- [ ]  I've submitted a screenshot of the dashboard
- [ ]  I've created a component test that the Organization Name text field appears
- [ ]  I've created a component test that the website text field appears
- [ ]  I've created a component test that the Github repo text field appears
- [ ]  I've created a component test that the logo button appears
- [ ]  I've created a component test that the description box appears
- [ ]  I've created a component test that the save changes button appears
- [ ] I've created a component test that when I click on the save change button, an action occurs.
- [ ] I've created a component test that the delete button appears

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by hritikmunde** [comment]
@ecurrencyhodler , does this issue include creating UI and unit tests as well? I can help with both.

**Comment by ecurrencyhodler** [comment]
Can you resolve #1237 first?

**Comment by hritikmunde** [comment]
Working on it

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler is this still available?
I will like to work on this

**Comment by ecurrencyhodler** [comment]
Okay this is yours.

**Comment by NengakDakup** [comment]
Do i need to be assigned to work on this?

**Comment by ecurrencyhodler** [comment]
Hi @NengakDakup yes that's right but it's already been assigned. We have more bitcoin bounties if you're interested: https://community.sphinx.chat/bounties

Are you on sphinx chat by any chance?

Also how did you hear about this project?

**Comment by NengakDakup** [comment]
Okay then @ecurrencyhodler 
Yes i joined Sphinx chat recently. A friend told me i can work on bounties. I saw the project on the bounties page

**Comment by ecurrencyhodler** [comment]
Awesome! Welcome. Let me know if there's a bounty you see that hasn't been assigned and I can help you out. What is your sphinx user name and who referred you?

**Comment by NengakDakup** [comment]
Thanks for having me. i'd let you know if i see any.
My username is NEN and the person that referred me is BRAINSHARK
