### ISSUE TITLE
Add restrictions to the "Edit Organization" UI

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1333]
### Context
We are going to add character limits to org name and org description. Create a frontend check that checks the character limit of both. If a user tries to type 1 character above the limit, prevent them from doing so and turn the ui red. See the design below.

So if the limit is 20 characters and a user types 20 characters, there is no restriction. But if they try to type a 21st character, that triggers this restriction.

### Design
Here is the design in [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=10364%3A10054&mode=design&t=YE6C1hFPCjMOCAhN-1).  Use [dev mode](https://www.figma.com/dev-mode/) for exact requirements. Simply follow the design for the red box and text and numbers. Ignore the title "add new org" and "add org" button.
![Add New organization (1) copy](https://github.com/stakwork/sphinx-tribes/assets/32662508/6546af57-f283-42ba-98ad-c1ec7da46f32)

This is blocked by #1332 

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a recording in my pr
- [ ] I've created mock data of 21 characters for org name and 121 characters for org description
- [ ] I've created a component tests that asserts if an input over the restriction is provided, they are restricted for both org name and org description

Add text below to say that text is too long.

**Comment by NengakDakup** [comment]
Hi, @ecurrencyhodler can I work on this when #1332 is completed?

**Comment by NengakDakup** [comment]
> Hi, @ecurrencyhodler can I work on this when #1332 is completed?

This is also similar to #1331 . Can work on that too

**Comment by ecurrencyhodler** [comment]
Moved to this issue: https://github.com/stakwork/sphinx-tribes-frontend/issues/9
