### ISSUE TITLE
Update "delete org" endpoint and functionality

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1334]
### Context
Currently, our "delete" button for org simply soft deletes the org by removing members and hiding them.

Let's update create an endpoint and the functionality to delete an org. When someone pushes the "delete" button, the following should occur:

1. Website/github/description -> Set to null. 
2. Hide organization
3. Removes users from org
4. Set delete to true

That means the bounties should be preserved. 

### Design
Here is the design where a user will click "delete" for context.
![Delete Organization - Warning](https://github.com/stakwork/sphinx-tribes/assets/32662508/8a8e8952-c07c-4c6e-8156-7f82f12e7c95)

File to add test

`handlers/organization_test.go`

Make Mock delete API test:
 
- Create a test function `TestDeleteOrganization` in  `handlers/organization_test.go``
- Test the Request Handler

Check ```/handlers/bounty_test.go``` for example

We want to test that the delete API works

### Acceptance Criteria

- [ ] Test that the tests pass with the right data
- [ ] Also test for failures.
- [ ] Test that the organization deleted column is set to true
- [ ] Test that the Website/github/description is set to null. 
- [ ] Test that the organization users are deleted.

**Comment by hritikmunde** [comment]
@ecurrencyhodler , can I work on this?

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler Could you please assign this task to me
