### ISSUE TITLE
Update superadmin ui to include hunters 

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1336]
### Context
One other metric I'm tracking is # of unique hunters paid as well as new hunters who got paid their first bounty. 

We have redesigned the stats section to accommodate this new field. 

### Design
Here is the design in [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=9067%3A23134&mode=design&t=0IzheDn10KrPCOp7-1). Use [dev mode](https://www.figma.com/dev-mode/) for precise requirements. Use dummy data for now until the backend is properly set up.
<img width="615" alt="Screenshot 2024-01-11 at 1 43 13 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/86cb4d78-4c8f-45c2-a372-af363884f8ea">

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot in my pr
- [ ] I've created a component test that confirms the following words appear: Hunters
- [ ] I've created a component test that confirms the name of the statistic is displayed: total paid and first bounty paid
- [ ] I've created mock data to display numbers for total paid and first bounty paid in the hunters section
- [ ] I've created a unit test that asserts the number is properly displayed based on the mock data

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by ecurrencyhodler** [comment]
Hi @MahtabBukhari happy to. Are you on sphinx chat? Also I'm curious, how did you hear about our project?

**Comment by MahtabBukhari** [comment]
Hi @ecurrencyhodler,
I am currently not on Sphinx Chat. Kindly add me to this Sphinx chat. I was referred to this platform by @aliraza556.

**Comment by ecurrencyhodler** [comment]
Amazing yes of course.

Follow the instructions in our [FAQ](https://docs.google.com/document/d/16NQ4SM4ptP4Lz5JKERAagdNw3GFRVv9eshMZ_oU-MVw/edit?usp=sharing) to download the app and sign into our site.

Here is your code you can use! 

connect::relay.swarm4.sphinx.chat::03bb3400b6fdfee72a8869c87f4de81210da5a8c9d1d7f7b7f166f22ba497cccfe

**Comment by ecurrencyhodler** [comment]
Also can you reply back with your sphinx name?

**Comment by MahtabBukhari** [comment]
This is my sphinx name Syed Mahtab Ali

**Comment by ecurrencyhodler** [comment]
Awesome. Can you sign up to our website as well? Then I can assign you the bounty: https://community.sphinx.chat/bounties

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler  done!

**Comment by ecurrencyhodler** [comment]
Assigned :) https://community.sphinx.chat/bounty/1154

**Comment by MahtabBukhari** [comment]
Thanks @ecurrencyhodler

**Comment by MahtabBukhari** [comment]
Hi @ecurrencyhodler,
Please verify whether we need to convert the row-based statistics fields from https://i.imgur.com/Y59Geg2.png to column-based fields as shown in https://i.imgur.com/5TIip9q.png. Additionally, confirm the inclusion of a new field for "Hunters".

**Comment by ecurrencyhodler** [comment]
Yes that's correct.

**Comment by MahtabBukhari** [comment]
My UI is complete; only unit tests remain https://i.imgur.com/eVnicu0.png

**Comment by ecurrencyhodler** [comment]
This looks great. I'm really impressed by the quality of the work and attention to detail.

Make sure to include the same shot in your pr.

**Comment by MahtabBukhari** [comment]
Hello @ecurrencyhodler,
Kindly review my pull request.

**Comment by MahtabBukhari** [comment]
Hi @ecurrencyhodler,
Kindly review my new pull request #1352
