### ISSUE TITLE
Update backend and endpoint for new fields for superadmin

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1337]
### Context
I need to track two other sets of metrics:
- Total # of unique hunters paid within a date range
- Total # of hunters who got paid their first bounty

Update the superadmin endpoint `metrics/bounty_stats` and update the backend to support this feature for super admin.

### Design
**# of hunters paid**

- Check # of bounties paid. Then use array manipulation to strip duplicates, then count. 
- For now put in database query. Eventually we will put it in redis. 

**New hunters who got paid first bounty**

- Check all assigned bounties then check how many were paid.
- Check paid bounties within a date range. Grab pub keys. Check pub keys against another set to see if they’ve already been paid another bounty. Display that and cache that value
- After we update this every week and cache.

**Comment by wright-eric** [comment]
@ecurrencyhodler can i work on this?
