### ISSUE TITLE
Unable to export csv from superadmin

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1344]
**Describe the bug**
I'm unable to export CSV from superadmin

https://github.com/stakwork/sphinx-tribes/assets/32662508/b279ec70-4379-4ee6-9fec-bdaf5f1ff350

**Expected behavior**
I should be able to export

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler Could you please assign me this task?

**Comment by ecurrencyhodler** [comment]
We are going to have raph take a look at this issue sorry! It has to do with admin access privileges.

**Comment by AbdulWahab3181** [comment]
No worries at all! Thanks for letting me know.

**Comment by ecurrencyhodler** [comment]
I dm'd you another bounty on sphinx chat if you were interested.
