### ISSUE TITLE
Add comma to metrics in superadmin dashboard

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1356]
### Context
Currently there is no comma for values in the superadmin data dashboard. 
<img width="1079" alt="Screenshot 2024-01-15 at 9 31 07 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/f4dc1e7f-8786-4bef-82ed-07df32ac1452">

Let's add the ability to display a comma when displaying data over 3 digits in the Bounties, Satoshis, and Hunters section.

You can use this function:
convertToLocaleString()
File: frontend/app/src/helpers/helpers-extended.ts

### Design
<img width="1079" alt="Screenshot 2024-01-15 at 9 33 36 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/b8562598-f35b-4239-8549-d7f2137f429d">

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot in my pr
- [ ] I've created a unit test that checks the data is correctly displayed

**Comment by KumarNayan** [comment]
Assign

**Comment by aliraza556** [comment]
@ecurrencyhodler could you assign me this task?
