### ISSUE TITLE
Update date format in superadmin

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1357]
### Context
Currently the date format in superadmin is a bit confusing because it has dashes:
<img width="270" alt="Screenshot 2024-01-15 at 9 46 26 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/a6393323-fe05-410c-a34c-7dd6fd6cdb0b">

### Design
Here's the [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=9067%3A23134&mode=design&t=3o2Aa4RMHsuItjE2-1). Let's update it to the following format:
<img width="409" alt="Screenshot 2024-01-15 at 9 49 13 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/448c6d91-4aa6-4125-b0f0-0ee85518c59c">

Let's update it to the following format if the year is different:
<img width="1079" alt="Screenshot 2024-01-15 at 9 46 21 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/e7be0d3c-eb89-46db-8eca-8dbaf1845666">

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot in my pr
- [ ] I've created a unit test that checks different years are displayed 

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

**Comment by MahtabBukhari** [comment]
could you assigne me this task?

**Comment by hritikmunde** [comment]
@ecurrencyhodler , can I work on this? All other issues are done so far.

**Comment by ecurrencyhodler** [comment]
@hritikmunde you can take this one. 

@MahtabBukhari give me 1-2 hours. There is going to be quite a few bounties I'm going to post today.

**Comment by MahtabBukhari** [comment]
Sure
