### ISSUE TITLE
Default profile picture is appearing when looking at assigned bounties for certain profiles

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1360]
**Describe the bug**
The default is being displayed when looking at assigned bounties for certain profiles.

Here are two profiles that I see this affecting:
https://people-test.sphinx.chat/p/031863256ab7ce989e82453f38602018cd198753d8cb57d342241e7d49ba6c2f47/usertickets
https://people-test.sphinx.chat/p/03bfe6723c06fb2b7546df1e8ca1a17ae5c504615da32c945425ccbe8d3ca6260d/usertickets

https://github.com/stakwork/sphinx-tribes/assets/32662508/e9a3b0dc-badf-40ca-8c2d-a8a35d369775

**Expected behavior**
The profile pic of the user who created the bounty should be displayed

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video
- [ ] I've created a test that the profile picture of the creator of the bounty will be displayed in the assigned bounties section of the user profile

**Comment by VividhPandey003** [comment]
Hey @ecurrencyhodler, Can I work on this issue?

**Comment by ecurrencyhodler** [comment]
Hey you've got 3 pending bounties. Let's get those wrapped up first.

**Comment by Vayras** [comment]
hey @ecurrencyhodler can I work on this issue?
