### ISSUE TITLE
Make bounty page go back to the home page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1362]
**Describe the bug**
If I paste a bounty page (https://community.sphinx.chat/bounty/1181) into a brand new tab and "x" to close it, it takes me back to the google home page. Let's have it return the user to the homepage: https://community.sphinx.chat/bounties

https://github.com/stakwork/sphinx-tribes/assets/32662508/3e4bf33b-7320-4b30-a918-6523b0c9ac74

**Expected behavior**
I should be returned to the bounty home page. This should ONLY affect going directly to a bounty page. All other times, closing the bounty page should return the user back to what they were looking at before. For example if I look at a bounty page from my profile, I should be returned to my profile not the bounty home page.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR
- [ ] I have created a test that asserts I am taking to the home page in the right circumstance

**Comment by aliraza556** [comment]
@ecurrencyhodler could you assign me this task?

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler this [issue](https://github.com/stakwork/sphinx-tribes/issues/1317) is a temporary pause according to you. Please assign me this issue. 
Thanks!

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler are you here?

**Comment by ecurrencyhodler** [comment]
You already have a couple bounties let's leave this open for other hunters.

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler,
Okay, but I am completely free now as I have resolved issue #1209. Other bounties are temporarily on hold because the backend of the Scenod Brain app has not been deployed, so progress on other issues has stopped. According to your information, issue #1317 is also on hold.

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler can you assigned me?

**Comment by KumarNayan** [comment]
Can I take this up @ecurrencyhodler

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler, could I please work on this?

**Comment by vishnu552** [comment]
Hi @ecurrencyhodler ,can i  work on this issue?

**Comment by ecurrencyhodler** [comment]
@MirzaHanan are you on Sphinx chat?  You can take this one as well as the bitcoin bounty with it.

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler,
I am currently not on Sphinx Chat.

**Comment by ecurrencyhodler** [comment]
Here are instructions in our [FAQ](https://docs.google.com/document/d/16NQ4SM4ptP4Lz5JKERAagdNw3GFRVv9eshMZ_oU-MVw/edit?usp=sharing) to sign up with sphinx. 

You can sign up as a new user with this connection code:
connect::relay.swarm4.sphinx.chat::03bb3400b6fdfee72a8869c87f4de81210da5a8c9d1d7f7b7f166f22ba497cccfe

Then sign in to our site and reply back with your sphinx name: https://community.sphinx.chat/bounties

BTW how did you hear about our project?

**Comment by MirzaHanan** [comment]
I was referred to this platform by @aliraza556.

**Comment by ecurrencyhodler** [comment]
Awesome let me know when you've created an account what your user name is.

**Comment by MirzaHanan** [comment]
Hi ecurrency,
code is invild
[image: image.png]

**Comment by ecurrencyhodler** [comment]
Did you download the app from the app store or test flight?

**Comment by MirzaHanan** [comment]
i download play store

**Comment by ecurrencyhodler** [comment]
Oh okay that should be fine. 

Try this one:
connect::relay.swarm4.sphinx.chat::0217a4a1a1c9d027ae5d08074aea546ecd3738bcb187d272b82ce3ad47986a97ef

**Comment by MirzaHanan** [comment]
> Oh okay that should be fine.
> 
> Try this one: connect::relay.swarm4.sphinx.chat::0217a4a1a1c9d027ae5d08074aea546ecd3738bcb187d272b82ce3ad47986a97ef

Hi @ecurrencyhodler,
this code worked and my sphinx name is Mirza Hanan.

**Comment by MirzaHanan** [comment]
Thank Man!

**Comment by ecurrencyhodler** [comment]
okay great!  I've assigned the bounty to you: https://community.sphinx.chat/bounty/1182

You may now start working on this issue. Just as a heads up, I am instituting a new rule that if I don't hear back in 7 days I will unassign the bounty and issue from you.

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler,

Please take a look at my [demo](https://www.loom.com/share/fd257b02d12d45709e37ac1c4270e80f). If everything is in accordance with the task requirements, I will then create a PR.

**Comment by ecurrencyhodler** [comment]
Video looks great. Thanks for testing the edge cases as well. Create a pr and include the video as well!

**Comment by MirzaHanan** [comment]
Ok Thanks Man!

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler,
Do I need to add a unit test to resolve the issue?  OR Just resolve the issue and then create a pull request and include a demo video in the PR description.

**Comment by ecurrencyhodler** [comment]
Hey Mirza! Yes that's correct. We want to implement test-driven development so include a test.

**Comment by MirzaHanan** [comment]
Absolutely, I completely agree with the approach! Implementing test-driven development will undoubtedly enhance our project's quality and reliability. I'll start by writing a comprehensive test for the new feature we're working on. Looking forward to seeing the positive impact this will have on our project!

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler,
Please review this PR #1428.

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler @elraphty,
Please check new PR #/16 in new repo and also check new [demo](https://www.loom.com/share/47cb6672c39044a3b190452316110d9f)

**Comment by ecurrencyhodler** [comment]
Tested and it works! GJ and paid.
