### ISSUE TITLE
Filters not triggering when unselected

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1364]
**Describe the bug**
The filters stop working after I unselected one.
https://github.com/stakwork/sphinx-tribes/assets/32662508/0ff038ca-0631-4d36-a722-bf20de95b8fb

**Expected behavior**
They should trigger every time I select and unselect a filter.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR
- [ ] I have created a test that asserts a call is made everytime a filter is selected or unselected

**Comment by hritikmunde** [comment]
@ecurrencyhodler , can you assign me this?

**Comment by Vayras** [comment]
@ecurrencyhodler  is this issue available to work on , if yes can I work on this?

**Comment by ecurrencyhodler** [comment]
@Vayras this is yours. Ednum you already have 2 bounties assigned to you.

**Comment by hritikmunde** [comment]
@ecurrencyhodler , both are done you can review.

**Comment by ecurrencyhodler** [comment]
Is it in a pr that hasn't been submitted yet? If so, don't submit because it's been assigned to vayras.

**Comment by Vayras** [comment]
> Is it in a pr that hasn't been submitted yet? If so, don't submit because it's been assigned to vayras.

@ecurrencyhodler  I think @hritikmunde is trying to convey his previously assigned tasks have been done and under review

**Comment by hritikmunde** [comment]
> > Is it in a pr that hasn't been submitted yet? If so, don't submit because it's been assigned to vayras.
> 
> @ecurrencyhodler  I think @hritikmunde is trying to convey his previously assigned tasks have been done and under review 

Yes correct

**Comment by ecurrencyhodler** [comment]
Oh sorry. Now I understand. I'm going to be posting more bounties including unit tests. So sit tight!

In the meantime, how about these two typescript bounties?
https://community.sphinx.chat/bounty/1186
https://community.sphinx.chat/bounty/1185

**Comment by hritikmunde** [comment]
Are you referring me? If so then yes assign me those, also let me know any other ones you're gonna post.

**Comment by ecurrencyhodler** [comment]
@hritikmunde reach out to the bounty poster if you want to get assigned those.

**Comment by hritikmunde** [comment]
@ecurrencyhodler , those are assigned to someone else I'll take others
