### ISSUE TITLE
Allow old bounties to be displayed

### ISSUE THREAD

**Issue by VividhPandey003** [stakwork/sphinx-tribes#1365]
**Describe the bug**
Some specific bounties such as the old ones most probably lead to a blank screen
![image](https://github.com/stakwork/sphinx-tribes/assets/91251535/f89d24cd-549c-4c21-b832-4fc7c3e6abba)

https://github.com/stakwork/sphinx-tribes/assets/91251535/3fb51bb2-ec6a-4e2c-b089-1632c812e6ba

**To Reproduce**
1. Go to https://people.sphinx.chat/bounty/75 , https://people.sphinx.chat/bounty/252

**Expected behavior**
The bounty popup should appear

**REASON**
The reason might be that these are the old bounties which are already probably completed.
A quick fix to be to fix the frontend or to fix the database regarding these bounties still having open tag.

**Desktop (please complete the following information):**
 - Browser [Chrome]

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video if it is a change in the front end

**Comment by VividhPandey003** [comment]
I would like to fix this

**Comment by ecurrencyhodler** [comment]
Closing this as evan has addressed the bug as he was tackling a larger issue. But good work. I paid you out partially.
