### ISSUE TITLE
Backend [Integration Test] people.go handlers `GetPersonByPubkey & CreateOrEditPerson`

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1387]
### Context

We are trying to increase the test coverage for our Golang backend. 

### Design

Write tests for the people handlers, the test should:

- Return with a 401 if the pubkeyFromAuth is not decoded from the auth token
- Create a new user if the right data is provided
- Should update a user if the user is already created
- Should throw an error if the pubkeyFromAuth is not equaled to the `person.OwnerPubKey`
- Should get a user by pubkey if the user exists

Create a new file `people_test.go`

### Acceptance Criteria

We are trying to test that all tests pass

- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a unit test that 
- [ ] I've created tests with the appropriate data and they all pass
- [ ] I've tested that tests with the wrong data fails

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/bounty_test.go)

**Comment by wright-eric** [comment]
Hi @elraphty can i work on this?

**Comment by ecurrencyhodler** [comment]
You can take this eric.
