### ISSUE TITLE
Backend [Integration Test] people.go handlers `GetPersonById & DeletePerson`

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1388]
### Context

We are trying to increase the test coverage for our Golang backend. 

### Design

Write tests for the people handlers, the test should:

- Return with a 401 if the pubkeyFromAuth is not decoded from the auth token
- Delete a new user if the right data is provided
- Should throw an error if the pubkeyFromAuth is not equaled to the `existing.OwnerPubKey`
- Should update a user if the user and set `deleted = true`
- Should get a user's by `id` if the user exists

FIle to test `people_test.go`

### Acceptance Criteria

We are trying to test that all tests pass

- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a unit test that 
- [ ] I've created tests with the appropriate data and they all pass
- [ ] I've tested that tests with the wrong data fails

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/bounty_test.go)

**Comment by Vayras** [comment]
Hey @elraphty I would like to work on this issue , can I work on this.

**Comment by gouravmpk** [comment]
I can take this

**Comment by ecurrencyhodler** [comment]
@Vayras this is yours. Gourav you have several bounties assigned to you already. Let's focus on wrapping those up.
