### ISSUE TITLE
[Tests][Component] Add tests to src/people/main/__tests__/MainHeader.spec.tsx

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1393]
### Context

MainHeader.tsx holds the sign-in button and the user image that leads to the user's profile for signed-in users. Add component test coverage.

File to be tested
` src/people/main/__tests__/MainHeader.spec.tsx`

Update file
` src/people/main/__tests__/MainHeader.spec.tsx

Make a Mock user and save it to the mocked localStorage frontend/app/src/__test__/__mockData__/localStorage.ts as `ui`, the `ui.meInfo` should be set to the mocked user.

Check ```frontend/app/src/people/main/__tests__/MainHeader.spec.tsx``` for example

We want to test that the Main header components are visible

### Acceptance Criteria

- [ ] Test that the Get Sphinx button is visible
- [ ] Test that the Sign In button is visible when a user is logged out
- [ ] Test that a Signed in user Image can be viewed
- [ ] Test that a Signed in user does not see the Sign In button

You can use this PR as an example `https://github.com/stakwork/sphinx-tribes/pull/1185`

**Comment by MahtabBukhari** [comment]
Could you assign me @elraphty?

**Comment by ecurrencyhodler** [comment]
@KumarNayan this is yours.
