### ISSUE TITLE
Add estimated completion date to bounty

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1397]
Add estimated completion date to bounty

**Comment by Antanasijevic** [comment]
@ecurrencyhodler Here is layout we discussed. Please let me know if any additional change is needed.

Figma Prototype
https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=10885%3A18546&mode=design&t=FRpZW9eh5dHJRjNy-1

![image](https://github.com/stakwork/sphinx-tribes/assets/13258550/c9d54e2f-9fce-48df-84be-a3d788815e4c)

**Comment by ecurrencyhodler** [comment]
Amazing ty!
