### ISSUE TITLE
Backend FIx: Language / Bounty Status Filter

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1401]
### Context

Language filter should only select the Languages that meet the selected bounty status.

### Design

Currently, the language status filter selects all the selected language bounties regardless of the selected filter status, fix this.

### Acceptance Criteria

- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a unit test that

**Comment by ecurrencyhodler** [comment]
paid for this raph: https://community.sphinx.chat/bounty/1229
