### ISSUE TITLE
Enable opening a new tab by right clicking on the people page.

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1406]
### Context
Currently, we are unable to right click to open a hunter profile in a new tab on the people page. But we can for right clicking on the home page. 

https://github.com/stakwork/sphinx-tribes/assets/32662508/58c3afbf-cf7a-4d9f-b239-ca09c92a252b

Enable opening a new tab by right clicking like you see in the back half of the video.

Here's the PR that enabled right clicking on the home page that you can use for reference: https://github.com/stakwork/sphinx-tribes/pull/991

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a video
- [ ] I've created a test that asserts that when I right click, the correct menu opens

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler please assign me.

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler could you please assign me?

**Comment by hritikmunde** [comment]
@ecurrencyhodler can I take this?

**Comment by ecurrencyhodler** [comment]
Giving it to ednum because his bounties have submitted pr's that just need review for now.

**Comment by hritikmunde** [comment]
@ecurrencyhodler , this is done. Please review.

**Comment by hritikmunde** [comment]
@ecurrencyhodler , this issue now closes in new repo for frontend.
PR link: [#3](https://github.com/stakwork/sphinx-tribes-frontend/pull/3)
