### ISSUE TITLE
Enable opening a new tab by right clicking on the sphinx website header

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1407]
### Context
Currently, we are unable to right click to the buttons in the header in a new tab across the whole website. But we can for right clicking on a bounty on the home page. 

https://github.com/stakwork/sphinx-tribes/assets/32662508/f7c0d2cf-4abe-4d60-a185-4867c95a1c0e

Enable opening a new tab by right clicking like you see in the back half of the video.

Here's the PR that enabled right clicking on the home page that you can use for reference: https://github.com/stakwork/sphinx-tribes/pull/991

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a video recording in my pr

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler Please could you assign this to me?
All my issues have PRs submitted and are awaiting review

**Comment by ecurrencyhodler** [comment]
You can take this one as it's similar to the one you submitted before.

**Comment by Ekep-Obasi** [comment]
@Thank you @ecurrencyhodler

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler, to write tests for the context menu when you right-click will need cypress since that action is a browser interaction

**Comment by ecurrencyhodler** [comment]
Okay we can skip that for this pr.
