### ISSUE TITLE
Enable search functionality when viewing profiles inside a profile

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1408]
**Describe the bug**
We currently are unable to search for hunters when viewing someone else's profile. 

https://github.com/stakwork/sphinx-tribes/assets/32662508/983f55c4-58e9-4375-be4a-c676b7906161

Enable this functionality. You can use the same logic that currently exists in the search bar for the people page.
<img width="1159" alt="Screenshot 2024-01-18 at 2 10 35 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/5409781d-9ddf-4738-99f1-123af9d53bcb">

**Expected behavior**
I should be able to search for other profiles.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my pr
- [ ] I've created a test that the search bar fires an event when a character is typed

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler,
Please assign me this task.

**Comment by ecurrencyhodler** [comment]
Reserving this one for @YLeight. Can you comment?

**Comment by YLeight** [comment]
I can commit on this issue

**Comment by YLeight** [comment]
I've linked PR above

**Comment by YLeight** [comment]
This solution doesn't relate to `SearchTextInput` component.
Should I cover it with test in scope of this PR?

**Comment by ecurrencyhodler** [comment]
No.  But you should include a relevant test in the pr. Thnx.
