### ISSUE TITLE
Clear search when going back to the people page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1409]
**Describe the bug**
When I type in a search term when viewing a profile so that I can look for other hunters then click to the people page, the search term is preserved. This is true for clicking on the bounty homepage as well.

https://github.com/stakwork/sphinx-tribes/assets/32662508/ec630a16-9231-458d-bb32-2f89c9710579

**Expected behavior**
Let's clear the search when someone clicks out of the page. 

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR
- [ ] I have created a unit test that asserts that when I click out of the page, the search term is cleared.

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler,
Please assigne me.

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler,
Please assign me this task.

**Comment by ecurrencyhodler** [comment]
That looks nice. Gj.Lets get a code review.

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler,
Please review my PR #1429
