### ISSUE TITLE
[Tests][Component] Add tests to frontend/app/src/pages/tickets/TicketModalPage.tsx

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1414]
### Context

TicketModalPage.tsx Displays a single bounty in a modal. Add component test coverage.

File to be tested
`src/pages/tickets/__tests__/TicketModalPage.spec.tsx`

Create file
` src/pages/tickets/__tests__/TicketModalPage.spec.tsx`

Make a mock bounty and return the mock bounty when  `TicketModalPage.tsx`  makes a `getBounty()` call, also mock the `main.getBountyIndexById()` call to return your mock bounty index.

Check ```frontend/app/src/people/main/__tests__/MainHeader.spec.tsx``` for example

We want to test that the TicketModalPage displays the right data

### Acceptance Criteria

- [ ] Test that the TicketModalPage is rendered when the URL `{host}/bounty/{bountyId}` is hit.
- [ ] Test that the bounty title, description, estimated hours, sats amount is equal that of the mocked bounty
- [ ] Test that when a bounty is assigned, the profile image and user name of hunter should appear on top right.
- [ ] Test that If a hunter is not assigned, there should be a clickable button **"I can help"**

You can use this PR as an example `https://github.com/stakwork/sphinx-tribes/pull/1185`

**Comment by KumarNayan** [comment]
Assign

**Comment by elraphty** [comment]
> Assign

@ecurrencyhodler

**Comment by KumarNayan** [comment]
@ecurrencyhodler can I work on this ?

**Comment by ecurrencyhodler** [comment]
Sorry missed this. It's yours.

**Comment by ecurrencyhodler** [comment]
@KumarNayan do you have an update on this issue? Also can you submit your pr to the frontend repo but tag this issue in the backend repo?
