### ISSUE TITLE
[Tests][Component] Add tests to frontend/app/src/pages/tickets/Tickets.tsx

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1415]
### Context

Tickets.tsx Displays the bounties list. Add component test coverage.

File to be tested
`src/pages/tickets/__tests__/Tickets.spec.tsx`

Create file
` src/pages/tickets/__tests__/Tickets.spec.tsx`

Mock an array of bounties and return the mock bounty when  `Tickets.tsx`  makes a `getPeopleBounties` call, also mock other calls needed to run this component test.

Check ```frontend/app/src/people/main/__tests__/MainHeader.spec.tsx``` for example

We want to test that Tickets.tsx displays the bounties list.
### Acceptance Criteria

- [ ] Test that the Ticket is rendered when the URL `{host}/bountyies` is hit.
- [ ] Test that the bounty title, estimated hours, sats amount equals that of each mocked bounty
- [ ] Test that when a bounty is assigned,  the profile image, user name of the hunter, and a view profile link are visible.
- [ ] Test that If a hunter is not assigned, there should be a clickable button **"I can help"**
- [ ] Test that if a bounty is created by an organization, the organization name should be visible.

You can use this PR as an example `https://github.com/stakwork/sphinx-tribes/pull/1185`

**Comment by Gaurav-Gaikwad-1** [comment]
Can you assign me this?

**Comment by ecurrencyhodler** [comment]
do you have an update on this issue? Also can you submit your pr to the frontend repo but tag this issue in the backend repo?

**Comment by Gaurav-Gaikwad-1** [comment]
@ecurrencyhodler @elraphty This issue is referenced in PR [#76](https://github.com/stakwork/sphinx-tribes-frontend/pull/76)
