### ISSUE TITLE
[Tests][Component] Add tests to frontend/app/src/pages/tickets/TicketModalPage.tsx

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1416]
### Context

TicketModalPage.tsx Displays a single bounty in a modal. Add component test coverage.

File to be tested
`src/pages/tickets/__tests__/TicketModalPage.spec.tsx`

Create file
` src/pages/tickets/__tests__/TicketModalPage.spec.tsx`

Make a mock bounty and return the mock bounty when  `TicketModalPage.tsx`  makes a `getBounty()` call, also mock the `main.getBountyIndexById()` call to return your mock bounty index.

Check ```frontend/app/src/people/main/__tests__/MainHeader.spec.tsx``` for example

We want to test that the TicketModalPage buttons perform the right actions

### Acceptance Criteria

- [ ] Test that the TicketModalPage is rendered when the URL `{host}/bounty/{bountyId}` is hit.
- [ ] Test that when the X close Icon is clicked the bounty modal gets closed.
- [ ] Test that If a hunter is not assigned, there should be a clickable button **"I can help"**
- [ ] Test that When I can help button is clicked  the bounty provider modal pops up
- [ ] Test that the Copy Link button and Share to Twitter Buttons are visible and clickable
- [ ] Test that the Github button link is visible and clickable if the bounty has a GitHub link

You can use this PR as an example `https://github.com/stakwork/sphinx-tribes/pull/1185`

**Comment by wright-eric** [comment]
@ecurrencyhodler can i work on this ?

**Comment by gouravmpk** [comment]
assign

**Comment by ecurrencyhodler** [comment]
Hey eric. I'm assign gourav because I owe him a bounty. Let's find another one for you.

**Comment by ecurrencyhodler** [comment]
do you have an update on this issue? Also can you submit your pr to the frontend repo but tag this issue in the backend repo?

**Comment by wright-eric** [comment]
Assign
