### ISSUE TITLE
Make go order columns correctly in CSV export

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1421]
### Context
Currently when I export the CSV from superadmin, the columns are ordered like this:
the order isn't correct.
<img width="854" alt="Screenshot 2024-01-15 at 11 33 30 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/6b113df5-50ae-4153-af84-0cc11eb0d41f">

This is the order it should be in:

- Date posted
- Organization
- Bounty amount
- Provider (Sphinx alias)
- Bounty Hunter (Sphinx alias)
- Bounty title
- Bounty link
- Bounty status
- Date assigned
- Date paid

### Acceptance Criteria
- [ ] I've submitted a screenshot of the export
- [ ] I've created a test that checks the order

**Comment by okhot** [comment]
@ecurrencyhodler can I get this?

**Comment by wright-eric** [comment]
@ecurrencyhodler  can i take this ?

**Comment by okhot** [comment]
@ecurrencyhodler I'll pass on this one

**Comment by ecurrencyhodler** [comment]
@okhot i have more questions for you hahaha. check your sphinx chat.
