### ISSUE TITLE
Dig into nginx stuff, traefik, and docker for splitting up sphinx-tribes repo

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1424]
When we split up the database, we will need to safely and correctly deploy these two systems together.

Dig into nginx stuff and docker for splitting up sphinx-tribes repo.

**Comment by ecurrencyhodler** [comment]
One thing we'll need to do is make sure routes will go to the right place in JS. 

It’s easy if they all start with the same call. But if it’s not, it’s difficult.

**Comment by Evanfeenstra** [comment]
> other option is to just use 2 separate domains and not worry about the traefik routing as much. This is easier, but we would need to hardcode into the frontend the domain for the backend (so if someone wanted to run their own bounty server, they would have to add their domain mapping hardcoded as well, which is annoying)

**Comment by Evanfeenstra** [comment]
Run the first test locally

- run sphinx-stack (proxy.yml file)
- wait for the setup scripts to be done
- make a /tests folder in sphinx-tribes-frontend
- install cypress there
- copy the NODES.json file into the tests folder
- write a login test!

login test
- serve the frontend on a specific port, that can map to the stack port (this might be there already in `getHostIncludingDockerHosts`). Does cypress hit the frontend after its built into a docker image? or are we hosting the frontend directly in the test (yarn run start) or (yarn run build && npx serve). Whichever is easier.
- look for "login" button
- click it
- get the challenge somehow (might need to add it as a data-attribute)
- sign the challenge with alice relay
- send the signature to the tribe backend
- verify that the frontend is logged in!

**Comment by ecurrencyhodler** [comment]
This has been implemented.
