### ISSUE TITLE
Clear github link after bounty creation

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1434]
**Describe the bug**
After a bounty gets created with a github link, the github link gets saved and populated when I create another bounty.
![sphinx mon 22 jan 08 55 44](https://github.com/stakwork/sphinx-tribes/assets/32662508/47afbcda-dd8c-47a2-8cf7-76588e8864db)

**To Reproduce**
1. Create a bounty using a github issue
2. Create another bounty and see that the github issue is saved

**Expected behavior**
The github link should not be saved and repopulated when creating another bounty.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my pr
- [ ] I've created a test that checks that the github link is empty at beginning of bounty creation

**Comment by hritikmunde** [comment]
@ecurrencyhodler , can you assign me this?

**Comment by VividhPandey003** [comment]
@ecurrencyhodler Could you please assign this issue to me

**Comment by ecurrencyhodler** [comment]
This is yours vividh. abdul and ednum i'll try and find you other ones.

**Comment by ecurrencyhodler** [comment]
Tested and it works! Gj! Paid.
