### ISSUE TITLE
Increase tribes displayed on the tribe page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1435]
**Describe the bug**
Right now only 10 tribes are getting displayed.
<img width="1216" alt="Screenshot 2024-01-22 at 9 35 43 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/7cd5ca94-ad9b-4aab-bf80-ef6a78c6d11e">

**Expected behavior**
It should be an infinite list that keeps loading as your scroll down. But for now, let's just load the first 100.

Currently the default query limit is 10. Create a new variable for tribes and set it to 100.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot 
- [ ] Test to see if variable is 100.

**Comment by ecurrencyhodler** [comment]
@hritikmunde want to take this? It's a small bounty though.

**Comment by hritikmunde** [comment]
Sure assign me

**Comment by hritikmunde** [comment]
@ecurrencyhodler , do you want to keep the loadmore function which loads more tribes as you scroll down?

**Comment by ecurrencyhodler** [comment]
@hritikmunde Yeah. Let's actually do 20 then and use the load more button.

**Comment by ecurrencyhodler** [comment]
Sorry let's keep the 100.

**Comment by hritikmunde** [comment]
@ecurrencyhodler , I have modified the code to show 100 tribes and load more as we scroll. I'm not sure how we can test the query limit. I mean it's hardcoded for variable value.

**Comment by hritikmunde** [comment]
@ecurrencyhodler , its a hardcoded variable that I don't think should be tested. Testing the tribes page whereas is a different story as I need to mock data of 100 tribes and the rendering takes more than jest threshold. For now I'm pushing changes of new varible I set, you can test that it shows 100 tribes first andas you scroll you'll get 100 more. Let me know any changes required.

**Comment by hritikmunde** [comment]
@ecurrencyhodler , this issue is referenced in PR [#178](https://github.com/stakwork/sphinx-tribes-frontend/pull/178)

**Comment by ecurrencyhodler** [comment]
Okay understood. Thanks for explaining it.

**Comment by hritikmunde** [comment]
I'll try to get the tribes page to be mocked in a short time. But due to 100 tribes it might not succeed. Let me know what you think
