### ISSUE TITLE
Unabstract edit organization from bounty creation modals

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1438]
### Context
The inputs for edit bounty and bounty creation modals are abstracted together. This means touching one modal may unintentionally affect another. 

Let's unabstract these two modals so that this doesn't happen. 

### Acceptance Criteria
- [ ] I've tested on Chrome

**Comment by vishnu552** [comment]
Hi, @ecurrencyhodler I am interested in this work. Could you please provide more details about it?

**Comment by ecurrencyhodler** [comment]
Closing this issue. We are actually going to direct people to use components directly instead of using our abstraction.
