### ISSUE TITLE
Add est. time and due date to bounty page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1439]
### Context
Currently our bounty page doesn't include a due date or the estimated time. 
<img width="644" alt="Screenshot 2024-01-22 at 1 44 04 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/92127f7e-07c0-4c67-bf0f-e1aff828dc21">

Let's include that in the bounty page modal. Here is the design in [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=10885%3A18546&mode=dev&t=AtObCUQ87Pq1Xq4m-1).
![Bounty Opened](https://github.com/stakwork/sphinx-tribes/assets/32662508/75a5dfa1-e19e-4fa2-ac73-ee128c8dc899)

All this info should be surfaced by `getBountyById()`.

### Acceptance Criteria
- [ ] I've tested on Chrome desktop
- [ ] I've tested on Chrome mobile
- [ ] I've submitted a screenshot in my pr
- [ ] I've created a component test that the fields "Estimate" and "Due date:" appear when viewing the page
- [ ] I've created mock data and a unit test that asserts the data is correctly displayed below the fields.

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler Could you please assign this to me?

**Comment by ecurrencyhodler** [comment]
Hey @Ekep-Obasi i see that you have 4 pending bounties. Let's focus on those first and leave this open to another hunter.

**Comment by wright-eric** [comment]
Assign

**Comment by aliraza556** [comment]
@ecurrencyhodler,
Please assign me

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler,
Could you please assign me?

**Comment by ecurrencyhodler** [comment]
Mirza and Ali you both have multiple bounties open. I'm going to assign this to another hunter.

**Comment by MirzaHanan** [comment]
@ecurrencyhodler,
I complete the all bounties. I make a all bounty PR.

**Comment by MahtabBukhari** [comment]
Could you assign me this one @ecurrencyhodler ?

**Comment by ecurrencyhodler** [comment]
@wright-eric this is yours
