### ISSUE TITLE
Filter and search on People page isn't synced

### ISSUE THREAD

**Issue by YLeight** [stakwork/sphinx-tribes#1448]
**Describe the bug**
Searching and filtration work independently

https://jam.dev/c/b87e499e-7330-4e8f-9460-f7016c0b6ef9

**To Reproduce**

1. Steps to reproduce the behavior:
2. Open People page - https://community.sphinx.chat/p
3. Select filter (e.g. typescript)
4. There are no `ecurrencyholder` person
5. Type  `ecurr` in search field
6. The search result contains `ecurrencyholder` what conflict with set filter

**Expected behavior**
With selected filter, search should execute on filtered list.
With search text, filtration should execute with search result list.

**Desktop (please complete the following information):**
 - Browser - Chromium Based Brave

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video if it is a change in the front end

**Comment by YLeight** [comment]
@ecurrencyhodler ✅ Done

**Comment by YLeight** [comment]
With this issue relates several side effects during initial render with preset search string

**Comment by ecurrencyhodler** [comment]
Covered in https://github.com/stakwork/sphinx-tribes-frontend/issues/1
