### ISSUE TITLE
Linkedin and Twitter Background cover for PMs

### ISSUE THREAD

**Issue by Analysislearning** [stakwork/sphinx-tribes#1450]
Brief
This initiative aims to enhance our brand awareness and make a positive impact on our online presence.

Problem
Brand recognition

Task
Create some cover drafts utilizing our existing branding image (stak, 2B and sphinx) for the PM's LinkedIn cover background and Twitter.

Ideas

Doing a background and cover for each branding
Doing a background and cover that includes 3 branding in 1

**Comment by Antanasijevic** [comment]
![sample-1](https://github.com/stakwork/sphinx-tribes/assets/13258550/5ddbd9ff-f4a7-481e-9402-f0c9a29743cb)
![Untitled-19](https://github.com/stakwork/sphinx-tribes/assets/13258550/dfe7a586-2857-4157-8914-e0f6235c0987)
![Untitled-17](https://github.com/stakwork/sphinx-tribes/assets/13258550/a058d344-5e57-4aa5-ab3d-75e1c9df92bc)
![Untitled-18](https://github.com/stakwork/sphinx-tribes/assets/13258550/f3cb9c8d-d33c-43a4-ae1f-739cc2d46fc1)

![Untitled-15](https://github.com/stakwork/sphinx-tribes/assets/13258550/6edcb7d8-10a8-4fcc-9daa-75cdae034839)

![Untitled-16](https://github.com/stakwork/sphinx-tribes/assets/13258550/a362c81a-7f66-4e08-9265-81584e1699ac)
![Untitled-12](https://github.com/stakwork/sphinx-tribes/assets/13258550/912f01ba-b14a-40f2-94a8-ec2f04ae7ead)
![Untitled-11a](https://github.com/stakwork/sphinx-tribes/assets/13258550/c3082053-b1d1-4807-85bb-d1f130aba07b)
![Untitled-4](https://github.com/stakwork/sphinx-tribes/assets/13258550/5bc290e5-0118-4254-8939-1e190d195bc6)
![Untitled-5](https://github.com/stakwork/sphinx-tribes/assets/13258550/4b0d22fb-1130-4cab-bbb6-c0069525df41)

**Comment by Antanasijevic** [comment]
@Analysislearning Here is an alternative option containing all 3 project

![sample-3](https://github.com/stakwork/sphinx-tribes/assets/13258550/43f8c37e-75ff-43a4-bf5d-b58507de8843)

**Comment by Antanasijevic** [comment]
![semifinal-1](https://github.com/stakwork/sphinx-tribes/assets/13258550/1e80cfef-95b5-4fc9-b5a0-8cc83dde1a85)

**Comment by Analysislearning** [comment]
woooowww!!! the last one looks AMAZING

**Comment by Analysislearning** [comment]
Can we add the word 'chat & pay' next to sphinx ?

**Comment by Antanasijevic** [comment]
![PM_COVER_LinkedIn](https://github.com/stakwork/sphinx-tribes/assets/13258550/c1a8dbf5-3904-4d46-9b8f-a06ca7d7607d)
![PM_COVER_Twitter](https://github.com/stakwork/sphinx-tribes/assets/13258550/db474a10-05a2-4eea-82bc-66cdc1d52177)

**Comment by Antanasijevic** [comment]
@Analysislearning Here are versions in larger sizes.

LinkedIn
![PM_COVER_LinkedIn_HI_RES](https://github.com/stakwork/sphinx-tribes/assets/13258550/5954ed05-8cb7-4e31-9759-b7224662df2f)

Twitter
![PM_COVER_Twitter_HI_RES](https://github.com/stakwork/sphinx-tribes/assets/13258550/c97d9180-9e12-4b03-be91-5b7fc487232a)
