### ISSUE TITLE
Enabled created and assigned bounties to display all bounties

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1451]
**Describe the bug**
Only paid bounties are appearing for created and assigned bounties inside the profile.
<img width="1222" alt="Screenshot 2024-01-24 at 11 44 58 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/87db6cf6-1a33-4da8-b8e1-e0f27083c4a6">

**Expected behavior**
Display all bounties and have open bounties displayed first.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot in my PR

**Comment by gouravmpk** [comment]
Assign

**Comment by ecurrencyhodler** [comment]
Sorry this is a duplicate.

**Comment by ecurrencyhodler** [comment]
This is Raphael's.
