### ISSUE TITLE
Delete packer.go from githistory

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1453]
### Context
Increases the time for contributors to download the repo.

It’s large and we don’t use it anymore since we are separating the front and backend.

**Comment by Fog3211** [comment]
@ecurrencyhodler Could you please assign this to me?

**Comment by ecurrencyhodler** [comment]
Hi! Let me touch base with the team.

Are you on sphinx chat? This is a how we ditribute the bitcoin bounties. 

Also how did you hear about our project?

**Comment by Fog3211** [comment]
> Hi! Let me touch base with the team.
> 
> Are you on sphinx chat? This is a how we ditribute the bitcoin bounties.
> 
> Also how did you hear about our project?

yes, this is my account [Fog3211](https://community.sphinx.chat/p/0368c4fce96ddb3e3cefe477c9e1b418e467a97441afe4a98c8420815ef0203060/usertickets)

I came to know about it by searching for bounty issues on GitHub.

**Comment by ecurrencyhodler** [comment]
Looks like we were able to handle this today. Sorry about that. There are more open bounties here: https://community.sphinx.chat/bounties.

Let me know if you find one that you like.
