### ISSUE TITLE
Update backend to handle multiple true statements for super admin

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1458]
"I am currently working on this task and have identified an issue with the backend API response. When I set multiple statuses as true, such as Open=true&Assigned=true, the backend returns null, as demonstrated in the attached video. I am utilizing the staging environment "people-test.sphinx.chat." Should I address the backend issue within the scope of this ticket, or do we need to initiate a separate bounty for this fix?"

**Note:** The issue is related to the backend.

https://github.com/stakwork/sphinx-tribes/assets/41957704/984d903a-4725-4d24-8dd2-1583f0708b91

_Originally posted by @AbdulWahab3181 in https://github.com/stakwork/sphinx-tribes/issues/1013#issuecomment-1906802420_

**Comment by ecurrencyhodler** [comment]
I created this bounty and paid you. Thanks abdul: https://community.sphinx.chat/bounty/1295

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler Could you please assign me?
