### ISSUE TITLE
Make Backend Functionality People Skill Search 

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1473]
### Context

At the moment the people skill search is done using an array filter on the tribes-frontend, which will only search the paginated array.

### Design

The Skill search should be done in the backend, so a global search can be carried out for people based on the skill value.

https://github.com/stakwork/sphinx-tribes/blob/4e2c767260915dff9573ee5f1832778e8b421ac5/db/db.go `GetAllBounties()` has an example implementation for searching bounties skill

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a unit test that tests that people are displayed based on skill values submitted.

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by wright-eric** [comment]
assign
