### ISSUE TITLE
Remove description restriction to create and edit org 

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1490]
**Describe the bug**
Right now, we are unable to create or edit an organization if the description is empty. 

**Expected behavior**
The only restriction an org should have to create or edit is if the name of the org is empty.

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR testing the backend change on the frontend

**Comment by Vayras** [comment]
@ecurrencyhodler I would really like to work on this, can you assign this one to me

**Comment by ManyRios** [comment]
> @ecurrencyhodler I would really like to work on this, can you assign this one to me

You're fast dude hehe
