### ISSUE TITLE
Filters on homepage aren't working properly

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1498]
**Describe the bug**
Filters for skills aren't working properly on the home page. The status is working correctly however.

https://github.com/stakwork/sphinx-tribes/assets/32662508/0b3ac0d3-7584-441d-ae90-813d69b3e8d3

**Expected behavior**
Bounties with only the selected language and status should appear.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video in my PR
- [ ] I've included a test

Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)

Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

**Comment by wright-eric** [comment]
Assign
