### ISSUE TITLE
badges ui: Counter and duplicate badge design

### ISSUE THREAD

**Issue by plell** [stakwork/sphinx-tribes#150]
**Badge counter**
Some badges will have a counter to indicate its "birth order" (for the lack of a better term). For example, if I have the Early Adopter badge with a counter of "13", that means I am the 13th person to have received that badge.  

**Duplicate badge ui**
There will be badge types that you may hold multiples of that have distinguishing differences. For example, if a badge is rewarded for completing a github issue, there will be users with many github badges. There should be a way to indicate that the badge displayed on the main screen is really a "deck" of badges (like a deck of cards), and clicking it should allow you to see each badge with their distinguishing details - (in the case of a github badge, there will probably be a repository name, and issue number)  

**Badge status**
Badges will have a "pending" status until they are "on-chain" on liquid, which happens when the user clicks a button to put the badge on the liquid chain (this costs some sats)

**Comment by plell** [comment]
maybe similar to this? https://github.com/stakwork/sphinx/issues/185

**Comment by Antanasijevic** [comment]
![image](https://user-images.githubusercontent.com/13258550/150362052-d77d27cb-e1b9-4447-998e-b565c2a81d6d.png)

**Comment by plell** [comment]
here is the prompt for adding a a badge to liquid (changing status from off-chain to on-chain) 
![image](https://user-images.githubusercontent.com/30448242/151097796-3429204a-ab79-4cd7-ba20-a736fc36e64f.png)

**Comment by Antanasijevic** [comment]
Another note after meeting
- Badges should be grouped by tribe (not badge type), since tribe owners can make custom badge.

**Comment by Antanasijevic** [comment]
Layout of a badges grouped by tribe
Figma project
https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/People.Sphinx?node-id=2006%3A9342

![image](https://user-images.githubusercontent.com/13258550/152790673-31991290-d2ff-42be-a05f-db08e88a066c.png)
