### ISSUE TITLE
Website strategy: Content Creators landing page

### ISSUE THREAD

**Issue by Analysislearning** [stakwork/sphinx-tribes#1502]
Issue: 
Improve content strategy on current website focused at content creators

Goal:
Increase lead generation of content creators to come and get on a internview with Analys

Tasks:
- @Analysislearning Write strategy script/text in a Google Doc format
- @Analysislearning Search, and identify the main key points that need to be addressed to communicate the need and problem the product is solving.
- @Antanasijevic  design a landing page for content creators in which includes the corresponding text, layout, and visual designs
- @Antanasijevic to search for webflow costs and implement new changes to the new web platform 

Resources:
1. https://docs.google.com/document/d/1mXnskfEN_JXgEgQirEm7LU9-PoLXb6TVVgJISXhEvzY/edit
2. https://www.figma.com/file/9cCBX8GdYlUiDIugyVYy1Y/Sphinx-Website-2024?type=design&node-id=16-290&mode=design&t=3ta1m5lPRfZy1lsE-0

**Comment by ecurrencyhodler** [comment]
Hey @Analysislearning these tickets are better at this repo https://github.com/stakwork/sphinx-tribes-frontend

**Comment by ecurrencyhodler** [comment]
Also for referral bot issues, add the "referral bot" milestones
