### ISSUE TITLE
Referral program for bounty platfrom: sign up page

### ISSUE THREAD

**Issue by Analysislearning** [stakwork/sphinx-tribes#1505]
Issue:
Improve user sign up to the bounty platform for new hunters that joins via the referral program

Goal:
Build a customer centric sign up landing page for new hunters that were referred by existing hunters 

Tasks:

@Analysislearning with the help of Andrew, write the steps required to sign up to the bounty platform nd create a first draft on figma 
@Analysislearning Search, and identify the main key points that need to be addressed on the FAQ of the sign up page (top 10 questions)
@Antanasijevic design sign up page for new hunters mock ups
@Analysislearning with help of Andrew, create tickets and post to the bounty platfrom to outsource implementation

Resources:

1. https://www.figma.com/file/jM4BZzPfN8K5tAUbl7gGoO/People.Sphinx-%5BDRAFTS%5D?type=design&node-id=7226-8245&mode=design&t=lVYIS8BHPxPCEnpS-0
2. https://docs.google.com/document/d/1SV6PTQ-xTtHkiBNMsxb3LwoX9lxPiPFw6SSnejx_NRI/edit
3. https://docs.google.com/document/d/1WwbQq5A-UDazYwZ6lzuFcIe_TYSeBKL1JRAv4wgwDb0/edit

**Comment by Antanasijevic** [comment]
@ecurrencyhodler @Analysislearning  Here is the current version of the wireframe. I have posted few minor suggestions in Figma.
Please, let me know if you want more changes. 
If you think overall layout is good to go, do you think i can start making final design and image assets?

https://www.figma.com/proto/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=11192-19683&t=OgNc9gPF0boOR017-1&scaling=scale-down&page-id=11191%3A665&starting-point-node-id=11193%3A143&show-proto-sidebar=1&mode=design

**Comment by Antanasijevic** [comment]
@ecurrencyhodler I have posted Responsive versions of current landing page on following links:

Desktop Version
https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=11320%3A1462&mode=design&t=qjzUGA97W0rIrfPX-1

Tablet version
https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=11479%3A17969&mode=design&t=qjzUGA97W0rIrfPX-1

Mobile Version
https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=11467%3A7144&mode=design&t=qjzUGA97W0rIrfPX-1

**Comment by Antanasijevic** [comment]
@ecurrencyhodler Here is updated version

Desktop
https://www.figma.com/proto/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=11320-1462&t=qkMLPDA0oznPxGlV-1&scaling=scale-down&page-id=11191%3A665&mode=design

Tablet
https://www.figma.com/proto/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=11479-17969&t=AnJbCUIgO2cvoD1s-1&scaling=scale-down&page-id=11191%3A665&mode=design

Mobile
https://www.figma.com/proto/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=11467-7144&t=RgJ5aGtYiuak7Z2v-1&scaling=scale-down&page-id=11191%3A665&mode=design
