### ISSUE TITLE
Referral Program for bounty platform: superadmin dashboard

### ISSUE THREAD

**Issue by Analysislearning** [stakwork/sphinx-tribes#1506]
Issue:
Super admin need to keep track of the referral program earnings and referred by

Goal:
Build landing a page that will exists inside of super admin. This landing page is a dashboard with metrics from the referral program. 

Tasks:

@Analysislearning with help of Andrew, defined that the super admin dashboard will keep track of the following metrics:
Total # of referred hunters that signed up
Total # of referred hunters with 1 bounty completed
Total # with paid referrals
Total # of sats paid for referrals
Average day to completed referral since joining
List of pending and completed referrals including 
hunter, 
referred hunter, 
Completion date
days to completion (since joining)
referral status
Pending / complete 
assigned bounty, 
sign up date of referred hunter
Ability to toggle date and time
Default is 1 week period
Options: 7/30/90/custom
Scroll dates
CSV Export
Status
Ability to track status of referral. If failed, try  again button appears. Click to make payment again
Button to manage organizations
View organizations, delete from list, add to list

@ecurrencyhodler design an ideal layout for this landing page
@Antanasijevic design final layout and mock up for this landing page 
@Analysislearning to create a bounty and post it so can get implemented 

Resources:
1. https://www.figma.com/file/jM4BZzPfN8K5tAUbl7gGoO/People.Sphinx-%5BDRAFTS%5D?type=design&node-id=7226-8245&mode=design&t=lVYIS8BHPxPCEnpS-0

**Comment by Antanasijevic** [comment]
@ecurrencyhodler @Analysislearning Here is the current version of super admin dashboard for referral program.
https://www.figma.com/proto/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=11256-10985&t=etXDS0XadyYQO184-1&scaling=scale-down&page-id=11191%3A665&starting-point-node-id=11193%3A143&show-proto-sidebar=1&mode=design

**Comment by Antanasijevic** [comment]
@ecurrencyhodler Version with latest updates

https://www.figma.com/proto/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=11256-10985&t=7TgqmRd4fG7DxoY1-1&scaling=scale-down&page-id=11191%3A665&starting-point-node-id=11193%3A143&show-proto-sidebar=1&mode=design

**Comment by ecurrencyhodler** [comment]
TY This looks good so far!
