### ISSUE TITLE
Referral Program for bounty platform: Hunter Dashboard

### ISSUE THREAD

**Issue by Analysislearning** [stakwork/sphinx-tribes#1507]
Issue:
Hunter need to keep track of the referral program earnings 

Goal:
Build landing a page that will exists inside of hunter profile. This landing page is a dashboard that keeps tracks of referral program earnings. 

Tasks:

@Analysislearning with help of Andrew, defined that the hunter profile dashboard will keep track of the following metrics:
Dashboard hunter earnings
4 columns with
Referral name
Date Joined
Date Paid
Sats Earned
A static total row in the bottom with 
Total Referred count 
Total sats earned

@Analysislearning  design an ideal layout for this landing page
@Antanasijevic design final layout and mock up for this landing page
@Analysislearning to create a bounty and post it so can get implemented

Resources:

https://www.figma.com/file/jM4BZzPfN8K5tAUbl7gGoO/People.Sphinx-%5BDRAFTS%5D?type=design&node-id=7226-8245&mode=design&t=lVYIS8BHPxPCEnpS-0

**Comment by Antanasijevic** [comment]
@ecurrencyhodler @Analysislearning Here is current version of Hunter dashboard

https://www.figma.com/proto/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=11256-6366&t=e8FEaul8PGXLw3t9-1&scaling=scale-down&page-id=11191%3A665&starting-point-node-id=11193%3A143&show-proto-sidebar=1&mode=design

**Comment by Antanasijevic** [comment]
@ecurrencyhodler Here is updated version

Desktop
https://www.figma.com/proto/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=11320-1462&t=qkMLPDA0oznPxGlV-1&scaling=scale-down&page-id=11191%3A665&mode=design

Tablet
https://www.figma.com/proto/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=11479-17969&t=AnJbCUIgO2cvoD1s-1&scaling=scale-down&page-id=11191%3A665&mode=design

Mobile
https://www.figma.com/proto/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=11467-7144&t=RgJ5aGtYiuak7Z2v-1&scaling=scale-down&page-id=11191%3A665&mode=design

**Comment by ecurrencyhodler** [comment]
@Antanasijevic this LGTM. I think we need to standardized how we refer to sphinx. I think we call it:
- Sphinx app
- Sphinx Chat
- sphinx chat
- Sphinx

We should stick with one naming convention.

I vote for just Sphinx Chat.

Everything else looks great.

**Comment by Antanasijevic** [comment]
@ecurrencyhodler Sure, Sphinx Chat is mostly mentioned on Sign up page. I made this change, using "Sphinx Chat" everywhere.
