### ISSUE TITLE
Backend [Integration Test] bounty.go handlers GetPersonCreatedBounties, GetPersonAssignedBounties, & GetBountyByCreated

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1509]
### Context

We are trying to increase the test coverage for our Golang backend. Please take this bounty if you are able to work on it within 24 hours and submit a PR within 1-2 days.

### Design

Write tests for the bounty handlers, the test should:

- Should test that bounties assigned to a user are returned successfully 
- Should test that a bounties created by a user is returned successfully
- Should test that bounties created by other users are not returned
- Should test that bounties assigned to other users are not returned
- Should test that the right bounty gets returned when the created value is passed.

Bounty Handlers To Test

```
GetPersonCreatedBounties
GetPersonAssignedBounties
GetBountyByCreated
```

Add tests to `bounty_test.go`

### Acceptance Criteria

We are trying to test that all tests pass

- [ ] I've tested on Chrome
- [ ] I've created tests with the appropriate data and they all pass
- [ ] I've tested that tests with the wrong data fails

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/bounty_test.go)

**Comment by PeteClubSeven** [comment]
The third acceptance criteria is incomplete

**Comment by ecurrencyhodler** [comment]
I've updated it pete. Are you on sphinx chat and are you interested in taking this bounty?

**Comment by PeteClubSeven** [comment]
> I've updated it pete. Are you on sphinx chat and are you interested in taking this bounty?

I’m not on Sphinx and unfortunately I can’t right now but I saw the bounty on Twitter and wanted to let you know 👍

**Comment by ecurrencyhodler** [comment]
Thanks! We also offer 100k sat referral if you know of someone who'd be a good fit and they complete a bounty.

**Comment by gouravmpk** [comment]
Assign

**Comment by gouravmpk** [comment]
@elraphty can I get where are we using this GetBountyByCreated just want to check something

**Comment by ecurrencyhodler** [comment]
Sorry gourav had to unassign you.

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler assign me?

**Comment by gouravmpk** [comment]
> Sorry gourav had to unassign you.

@ecurrencyhodler I can raise PR right now Done the test

**Comment by gouravmpk** [comment]
> Sorry @gouravmpk your PR had failing tests. @AbdulWahab3181 you can take this one.

Tests are running locally
