### ISSUE TITLE
Backend [Integration Test] organizations.go handlers GetOrganizationBounties, GetOrganizationBudget, & GetOrganizationBudgetHistory

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1510]
### Context

We are trying to increase the test coverage for our Golang backend. 

### Design

Write tests for the  organization handlers, the test should:

- Should test that an organization's bounties can be listed without authentication
- Should test that an empty array is returned when the wrong organization uuid is passed
- Should test that a 401 is returned when trying to view an organization's budget without a token
- Should test that a 401 is returned when trying to view an organization's budget history without a token
- Should test that the right organization budget is returned,  if the user is the organization admin or has the ViewReport role
- Should test that the right budget history is returned, if the user is the organization admin or has the ViewReport role

Organizations Handlers To Test

```
GetOrganizationBounties
GetOrganizationBudget
GetOrganizationBudgetHistory
```

Add tests to `organization_test.go`

### Acceptance Criteria

We are trying to test that all tests pass

- [ ] I've tested on Chrome
- [ ] I've submitted a screenshot or recording in my pr
- [ ] I've created a unit test that 
- [ ] I've created tests with the appropriate data and they all pass
- [ ] I've tested that tests with the wrong data fails

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler I would like to give this a try. Could you please assign it to me?

**Comment by ecurrencyhodler** [comment]
okay let's get a PR up in 1-2 days!
