### ISSUE TITLE
Enable correct filtering when status is selected in superadmin

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1511]
**Describe the bug**
When selecting a status in superadmin, the bounties are incorrectly called. The video below shows that bounties outside the date range are being displayed.

https://www.loom.com/share/0412a5a5c47b40e78347ca1e307d95ba

**Expected behavior**
Only the correct bounties within the date range should be called. 

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video in my PR

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler could you please assign me?
