### ISSUE TITLE
Backend [Integration Test] people.go handlers GetListedPeople, GetPeopleBySearch

### ISSUE THREAD

**Issue by Vayras** [stakwork/sphinx-tribes#1516]
### Context
We are trying to increase the test coverage for our Golang backend. Please take this bounty if you are able to work on it within 24 hours and submit a PR within 1-2 days.

### Design
Write tests for the people handlers, the test should:

- [ ] Test that `GetListedPeople` returns all the people publicly available on the bounties platform
- [ ] Test that `GetPeopleBySearch` returns the correct person searched
- [ ] Test that if no person found for given params show a no results found message

### Bounty Handlers To Test
`GetListedPeople
 GetPeopleBySearch
`

Add tests to `people_test.go`

### Acceptance Criteria
Tests related to backend should pass
All workflows should pass

**Comment by Vayras** [comment]
@elraphty this would be my first draft backend test issue, let me know your feedback on this

cc: @ecurrencyhodler

**Comment by AbdulWahab3181** [comment]
@Vayras @ecurrencyhodler It seems like there is an updated version of this issue https://github.com/stakwork/sphinx-tribes/issues/1518. If that's the case, then we need to close this one.

**Comment by Vayras** [comment]
@AbdulWahab3181 this is a draft issue I created for @elraphty to approve, Please ignore this one at the moment
