### ISSUE TITLE
Backend [Integration Test] bounty.go handlers GetBountyByCreated, GetNextBountyByCreated, GetPreviousBountyByCreated, GetOrganizationNextBountyByCreated, & GetOrganizationPreviousBountyByCreated

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1517]
### Context

We are trying to increase the test coverage for our Golang backend. 

### FIle to write test

Write tests for the  bounty handlers, the test should:

- Should test that a bounty can be gotten by its created value
- Should test that the next bounty on the bounties homepage can be gotten by its created value and the selected filters
- Should test that the previous bounty on the bounties homepage can be gotten by its created value and the selected filters
- Should test that the next bounty on the organization bounties homepage can be gotten by its created value and the selected 
filters
- Should test that the previous bounty on the organization bounties homepage can be gotten by its created value and the selected 
filters

Bounty Handlers To Test

```
GetBountyByCreated
GetNextBountyByCreated
GetPreviousBountyByCreated
GetOrganizationNextBountyByCreated
GetOrganizationPreviousBountyByCreated
```

Add tests to `bounty_test.go`

### Acceptance Criteria
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler could you please assign me?

**Comment by AbdulWahab3181** [comment]
I have also written the unit tests for this issue locally. I'm just waiting for you to assign me so that I can create a pull request and share it with you.

**Comment by ecurrencyhodler** [comment]
Here you go: https://community.sphinx.chat/bounty/1500

**Comment by ecurrencyhodler** [comment]
Paid 200k sats! https://community.sphinx.chat/bounty/1500
