### ISSUE TITLE
Backend [Integration Test] people.go handlers GetPeopleBySearch, GetListedPeople, & GetPersonByUuid

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1518]
### Context

We are trying to increase the test coverage for our Golang backend. 

### File to to test

handlers/people.go

### Design

Write tests for the people handlers, the test should:

- Should test that a user can be fetched with the right uuid
- Should test that a wrong uuid returns no user
- Should test that users that match a search text are returned
- Should test that an empty search is returned when no user matches the search text
- Should test that all users can be listed ` GetListedPeople`
- Should test that ` GetListedPeople` returns only users that match a search text when a search is added to the URL query
- Should test that ` GetListedPeople` returns only users that match a skill set, when `languages` are passed to the URL query.

People Handlers To Test

```
GetPeopleBySearch
GetListedPeople
GetPersonByUuid
```

Add tests to `people_test.go`

### Acceptance Criteria
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by Fog3211** [comment]
@ecurrencyhodler 
I'm not very familiar with Golang, but I would like to give this task a try.

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler could you please assign me?

**Comment by M-tidings** [comment]
@ecurrencyhodler   is this still open?

**Comment by Marvel-Ib** [comment]
@ecurrencyhodler  is this still open? Would love to take it.

**Comment by ecurrencyhodler** [comment]
Welcome back marvel! We will be posting more test bounties soon. I'll save one for you. Are you looking at go? Or are you open to typescript as well?

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler I saw you have assigned me the task and then unassigned me . Should I start working on it?

**Comment by ecurrencyhodler** [comment]
No let's get clarity from @Vayras first.

**Comment by ecurrencyhodler** [comment]
Paid 300k sats!
