### ISSUE TITLE
Update create date of bounty only once.

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1520]
**Describe the bug**
Superadmin is displaying incorrect bounties. The query of the date range should account for bounty creation date. But instead it's showing something different. Possible latest activity. 

Here is an example. I set a custom date range from 9/9-9/15 and saw this bounty:
https://community.sphinx.chat/bounty/1302
<img width="1108" alt="Screenshot 2024-02-15 at 4 16 02 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/7c1977f0-08f9-498c-a905-c224d562f4fb">
 When I click the bounty it also shows the creation date as "a day".
<img width="658" alt="Screenshot 2024-02-15 at 4 15 55 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/bce9c57e-06aa-43a3-b71d-3be336e9ac81">
But I posted this bounty 1/29
<img width="1064" alt="Screenshot 2024-02-15 at 4 16 16 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/493a2c12-b7c3-4803-a35b-5758c97943fe">

Upon further investigation, the problem is that the field "created" gets updated whenever a bounty gets saved. 

**Expected behavior**
Creation date of bounties should reflect the date it was created only. The "created" field should only get updated once, which is when a bounty gets created.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by ecurrencyhodler** [comment]
@elraphty can you take a look at this issue when you get a chance?

**Comment by ColdMice** [comment]
@ecurrencyhodler would this be available to work on? or this is reserved?

**Comment by wright-eric** [comment]
Assign

**Comment by ecurrencyhodler** [comment]
Sorry just missed your comment cold mice.
