### ISSUE TITLE
Create endpoint to send count of bounties displayed in org homepage

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1524]
### Context
Right now, org homepage has a static # for bounties displayed and doesn't change when you click a filter.
<img width="996" alt="Screenshot 2024-02-16 at 7 58 12 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/857cdeb0-44c7-4bc6-8fc8-bd6a577d12fd">

Create an endpoint that returns the total # of bounties displayed on the org homepage regardless of pagination. This blocks https://github.com/stakwork/sphinx-tribes-frontend/issues/248

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've created a test that asserts the number returned matches bounties called
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler could you please assign me?

**Comment by ecurrencyhodler** [comment]
It's yours abdul: https://community.sphinx.chat/bounty/1534
