### ISSUE TITLE
Backend [Integration Test] bounty.go handlers  GetAllBounties, GetBountyById, & GetBountyIndexById

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1526]
### Context

We are trying to increase the test coverage for our Golang backend. 

### File to to test

handlers/bounty.go

### Design

Write tests for the bounty handlers, the test should:

- Should test that all bounties are listed 
- Should test that bounties are listed when the right query params are passed *(languages, search, Open, Paid, Assigned)*
- Should test that a bounty can be fetched with the right ID
- Should test that a nonexistent bounty ID returns no bounty
- Should test a bounty Index is returned when an existent bounty ID is passed

Bounty Handlers To Test

```
GetAllBounties
GetBountyById
GetBountyIndexById
```

Add tests to `bounty_test.go`

### Acceptance Criteria
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by gouravmpk** [comment]
@elraphty I wrote test for these two
GetBountyById
GetBountyIndexById

**Comment by elraphty** [comment]
> @elraphty I wrote test for these two GetBountyById GetBountyIndexById

posted yet?

**Comment by gouravmpk** [comment]
> > @elraphty I wrote test for these two GetBountyById GetBountyIndexById
> 
> posted yet?

Not yet but I can get pr by tomorrow

**Comment by elraphty** [comment]
Okay, ask @ecurrencyhodler to assign this to you then

**Comment by gouravmpk** [comment]
@ecurrencyhodler Assign

**Comment by ecurrencyhodler** [comment]
It's yours gourav.

**Comment by ecurrencyhodler** [comment]
Paid 200k!

**Comment by gouravmpk** [comment]
> Paid 200k!

didn't received yet

**Comment by ecurrencyhodler** [comment]
Okay it's marked as paid here: https://community.sphinx.chat/bounty/1529

But it's not showing up in our org txn history. Let me check on this for your.

**Comment by ecurrencyhodler** [comment]
Sorry for the delay @gouravmpk it's now paid: https://community.sphinx.chat/bounty/1529

**Comment by gouravmpk** [comment]
> Sorry for the delay @gouravmpk it's now paid: https://community.sphinx.chat/bounty/1529

No problem ,Thanks
