### ISSUE TITLE
Backend [Integration Test] tribes.go handlers GetTribesByOwner, GetTribesByAppUrl, & GetTribe

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1528]
### Context

We are trying to increase the test coverage for our Golang backend. 

### File to to test

handlers/tribes.go

### Design

Write tests for the tribes handlers, the test should:

- Should test that all tribes that an owner did not delete are returned if `all=true` is added to the request query.
- Should test that all tribes that are not unlisted by an owner are returned.
- Should test that a tribe can be returned when the right uuid is passed to the request param for `GetTribe`
- Should test that no tribe is returned when a nonexistent uuid is passed.
- Should test that a tribe is returned when the right app URL is passed to `GetTribesByAppUrl`

Tribes Handlers To Test

```
GetTribesByOwner
GetTribesByAppUrl
GetTribe
```

Add tests to `tribes_test.go`

### Acceptance Criteria
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by AbdulWahab3181** [comment]
assign?
