### ISSUE TITLE
Backend [Integration Test] auth.go handlers GetAdminPubkeys, GetIsAdmin, & RefreshToken

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1529]
### Context

We are trying to increase the test coverage for our Golang backend. 

### File to to test

handlers/auth.go

### Design

Write tests for the auth handlers, the test should:

- Should test that all admin pubkeys is returned by `GetAdminPubkeys` handlers.
- Should test that ` GetIsAdmin` returns a 401 error if the user is not an admin 
- Should test that a 200 status code is returned if the user is an admin.
- Should test that a user token can be refreshed.

Auth Handlers To Test

```
GetAdminPubkeys
GetIsAdmin
RefreshToken
```

Add tests to `auth_test.go`

### Acceptance Criteria
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler Could you please assign me this task?

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler
Assign me

**Comment by MahtabBukhari** [comment]
Hey @ecurrencyhodler , Could you assign to me?

**Comment by MahtabBukhari** [comment]
Hey @ecurrencyhodler Could you assign to me?

**Comment by ecurrencyhodler** [comment]
Sorry @aliraza556 let me get this to another hunter. I have another bounty for you.

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler I have already written the unit tests for this issue locally. I'm just waiting for you to assign me so that I can create a pull request and share it with you.

**Comment by aliraza556** [comment]
Hi @AbdulWahab3181,
Please ensure that the next time @ecurrencyhodler assigns you a bounty, you either start working on it promptly or kindly leave the issue available for others to tackle.

**Comment by gouravmpk** [comment]
@ecurrencyhodler Assign

**Comment by ecurrencyhodler** [comment]
I'm trying to reserve this for another hunter. I'll check again tomorrow.

**Comment by FaisalIqbal211** [comment]
@ecurrencyhodler assign me?
