### ISSUE TITLE
Change all deprecated `ioutil.ReadAll` to `io.ReadAll` in the handlers function

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1530]
### Context

The `io/ioutil` module is deprecated, and we are being warned to move away from it Golang built-in `io` library now performs the same function of ioutil.

### Design

Change all `ioutil.ReadAll` to `io.ReadAll`

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty
- [ ] Submit a screenshot that proves that ioutil.ReadAll is no longer being used in all files

**Comment by Ekep-Obasi** [comment]
@elraphty @ecurrencyhodler, will love to work on this. Could you please assign?

**Comment by FaisalIqbal211** [comment]
@ecurrencyhodler I want to work on this. Please assign me.

**Comment by Khaalid-oh** [comment]
I can take this

**Comment by ecurrencyhodler** [comment]
Closed by #1556
