### ISSUE TITLE
Backend [Integration Test] tribes.go handlers GetTribe, CreateOrEditTribe, & GetTribeByUniqueName

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1533]
### Context

We are trying to increase the test coverage for our Golang backend. 

### File to to test

handlers/tribes.go

### Design

Write tests for the tribe's handlers, the test should:

- Should test that a tribe can be fetched by its uuid
- Should test that a non-existent uuid returns no tribe
- Should test that a tribe can be created when the right data is passed
- Should test that a tribe can be fetched by its unique name

Tribes Handlers To Test

```
GetTribe
CreateOrEditTribe
GetTribeByUniqueName
```

Add tests to `tribes_test.go`

### Acceptance Criteria
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by Fog3211** [comment]
@ecurrencyhodler can you assign this to me？

**Comment by FaisalIqbal211** [comment]
@ecurrencyhodler assign me the issue?

**Comment by Vayras** [comment]
@ecurrencyhodler I can take this one

**Comment by ecurrencyhodler** [comment]
@FaisalIqbal211 this is yours. Let's get a PR up in 2 days.
