### ISSUE TITLE
Backend [Integration Test] tribes.go handlers DeleteTribe, GetFirstTribeByFeed, & SetTribePreview

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1534]
### Context

We are trying to increase the test coverage for our Golang backend. 

### File to to test

handlers/tribes.go

### Design

Write tests for the tribe's handlers, the test should:

- Should test that the owner of a tribe can delete a tribe
- Should test that a 401 error is returned when a tribe is attempted to be deleted by someone other than the owner
- Should test that a tribe can be gotten by passing the feed url
- Should test that a tribe preview can be set by the owner of the tribe
- Should test that setting a tribe preview action returns a 401 for non-owners.

Tribes Handlers To Test

```
DeleteTribe
GetFirstTribeByFeed
SetTribePreview
```

Add tests to `tribes_test.go`

### Acceptance Criteria
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by AbdulWahab3181** [comment]
assign?
