### ISSUE TITLE
Backend [Integration Test] channel.go handlers CreateChannel, & DeleteChannel

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1535]
### Context

We are trying to increase the test coverage for our Golang backend. 

### File to to test

handlers/channel.go

### Design

Write tests for the channel handlers, the test should:

- Should test that a user that is not authenticated cannot create a channel, a 401 error should be returned
- Should test that an authenticated user can create a channel
- Should test that a user cannot create a channel with a name that already exists, it should return 406
- Should test that the owner of a channel can delete the channel
- Should test that non-channel owners cannot delete the channel, it should return a 401 error.

Channel Handlers To Test

```
CreateChannel
DeleteChannel
```

Add tests to `channel_test.go`

### Acceptance Criteria
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by AbdulWahab3181** [comment]
assign?

**Comment by Vayras** [comment]
@ecurrencyhodler I can take this issue

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler assign me?
