### ISSUE TITLE
[SuperAdmin] Add optional word clause to query for providers

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1547]
### Context
I'd like to be able to filter for providers when looking at bounties inside of superadmin.

We are currently grabbing bounties using this call: `metrics/bounties`. 

Add an optional word clause to search for providers and their bounties only. In other words, don’t search for anything other than the selected providers and their bounties within a given date range.

Also enable "or" statements so that multiple providers and the bounties they posted are returned.

### Design
This is what the frontend will look like for reference (without the search bar).
<img width="546" alt="Screenshot 2024-02-21 at 1 54 51 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/2a35e42b-7ed7-414b-8495-c76d8ccb659f">

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've created mock db with 3 different providers each with 2 bounties. 
- [ ] I've created a test asserting the response we get from the call only returns bounties from selected providers.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by FaisalIqbal211** [comment]
@ecurrencyhodler assign me?

**Comment by ecurrencyhodler** [comment]
It's yours @FaisalIqbal211 let's get a PR up within 2 days.

**Comment by FaisalIqbal211** [comment]
@ecurrencyhodler Just want to confirm, provider means the owner of bounty. Am I correct?

**Comment by ecurrencyhodler** [comment]
Yup that's correct. The person who created the bounty.
