### ISSUE TITLE
Trim whitespaces from org names when an org is created or saved

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1548]
**Describe the bug**
Currently an org can be created and saved with just spaces. 

**Expected behavior**
When an org name is created or saved, trim spaces in the front and end of the text that is received. Spaces inbetween should be preserved. This is related to https://github.com/stakwork/sphinx-tribes-frontend/issues/267

Also return a failure if an org is being created or saved with just spaces.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have created a test that an org name with just spaces fails
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler could you please assign me?

**Comment by ecurrencyhodler** [comment]
This is yours
