### ISSUE TITLE
Return `second_brain_url` if available

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-tribes#1561]
### Task

Return `second_brain_url` for the GET request - TRIBES_SERVER_URL/tribes/\(uuid) if available.

**Acceptance Criteria**

- [ ] Return `second_brain_url` is availavle

**Comment by aliraza556** [comment]
Hi @tomsmith8,
assign me?

**Comment by gouravmpk** [comment]
Assign

**Comment by aliraza556** [comment]
This issue is already fixed
