### ISSUE TITLE
Backend [Unit Test] db/config.go  UserHasManageBountyRoles,  UserHasAccess,  CheckUser, & RolesCheck

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1562]
### Context

We are trying to increase the test coverage for our Golang backend. 

### File to to test

db/config.go

### Design

Write tests for the database config functions, the test should:

- RolesCheck:  Should test that  it returns true when a user has a role (Mock user roles)
- RolesCHeck: Should test that it returns false when a use does not have a role (Mock user roles)
- CheckUser: This should test that a user cannot add himself to a role, if in the user roles, one of the owner_pubkey belongs to the user return false else return true
- UserHasAccess:  Should test that if the user is the admin of an organization returns true
- UserHasAccess: Should test that if the user is not the organization admin, and the user has the required role it should return true, else it should return false
- UserHasManageBountyRoles: Should test that if the user is the organization admin return true
- UserHasManageBountyRoles: Should test that if the user has all bounty roles return true, else return false.

Bounty Roles

```sh
var ManageBountiesGroup = []string{AddBounty, UpdateBounty, DeleteBounty, PayBounty}
```

```
RolesCheck
CheckUser
UserHasAccess
UserHasManageBountyRoles
```

Add tests to `db/config_test.go`

### Acceptance Criteria
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by AbdulWahab3181** [comment]
assign me?

**Comment by arimusdev** [comment]
@ecurrencyhodler  assign me please

**Comment by ecurrencyhodler** [comment]
Can you submit a PR in 2 days?

**Comment by hkarani** [comment]
Hey @ecurrencyhodler  I can take this on.

**Comment by Jagmohan2k** [comment]
@ecurrencyhodler  assign  can get PR in 2 daYS

**Comment by ecurrencyhodler** [comment]
@arimusdev will you submit a PR soon?

**Comment by gouravmpk** [comment]
@ecurrencyhodler Assign

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler Could you please assign me?

**Comment by hkarani** [comment]
I can work on this @ecurrencyhodler , I have no other pending assigned bounties.

**Comment by ecurrencyhodler** [comment]
@gouravmpk this is yours.

**Comment by AbdulWahab3181** [comment]
?

**Comment by Fog3211** [comment]
assign
