### ISSUE TITLE
Backend [Integration Test] bounty.go handlers MakeBountyPayment

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1563]
### Context

We are trying to increase the test coverage for our Golang backend. 

### File to to test

handlers/bounty.go

### Design

Write tests for the bounty handlers, the test should:

- Should test that the handler gets locked by go mutex when it is called i.e. the handler has to be fully executed before it processes another request.
- Should test that a 401 unauthorized error is returned when an unauthorized user hits the endpoint `gobounties/pay/{id}`
- Should test that a 405 is returned when a user tries to pay an already-paid bounty
- Should test that a 401 error is returned if the user is not the organization admin or does not have a *PAY BOUNTY* role
- Should test that a 403 error is returned when the amount to be paid exceeds the organization's budget balance.

Bounty Handlers To Test

```
MakeBountyPayment
```

Add tests to `bounty_test.go`

### Acceptance Criteria
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler could you please assign me?

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler,
Please assign me?

**Comment by ecurrencyhodler** [comment]
Paid 200k sats! https://community.sphinx.chat/bounty/1587
