### ISSUE TITLE
Backend [Integration Test] bounty.go handlers MakeBountyPayment

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1564]
### Context

We are trying to increase the test coverage for our Golang backend. 

### File to to test

handlers/bounty.go

### Design

Write tests for the bounty handlers, the test should:

- Mock a call to `/payment` to make the bounty payment 
- Should test that If the payment is successful the payment gets added to the payment history, the bounty paid is updated to true, the bounty paid date is updated, and the bounty completion date is updated
- Should test that if `/payment` is successful, the organization budget gets reduced by the bounty amount.
- Should test that a successful WebSocket message is sent if the payment is successful
- Should test that an error WebSocket message is sent if the payment fails

Bounty Handlers To Test

```
MakeBountyPayment
```

Add tests to `bounty_test.go`

### Acceptance Criteria
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by FaisalIqbal211** [comment]
@ecurrencyhodler assign me?

**Comment by arimusdev** [comment]
@ecurrencyhodler  assign me please

**Comment by gouravmpk** [comment]
Assign

**Comment by ecurrencyhodler** [comment]
Let's get a PR up in 2 days.

**Comment by gouravmpk** [comment]
@ecurrencyhodler this is done all the tests are passing but one I will resolve it and get pr by tonight

**Comment by AbdulWahab3181** [comment]
?

**Comment by ecurrencyhodler** [comment]
paid
