### ISSUE TITLE
Bounty paid but bounty wasn't successful

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1569]
**Describe the bug**
I paid a 200k sat invoice to Gourav: https://community.sphinx.chat/bounty/1529

The bounty has been marked as paid but Gourav said he didn't receive payment. https://github.com/stakwork/sphinx-tribes/issues/1526#issuecomment-1968415577

I also check txn history and I don't see the payment to him.

<img width="631" alt="Screenshot 2024-02-28 at 12 35 14 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/4341a366-d61c-4fb7-a9ad-324f3d240a58">

**Expected behavior**
Gourav should've been paid 200k on 2/26/24 and it should display in the org txn history. A bounty should also not be marked as paid if it has been unsuccessfully paid.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by okhot** [comment]
@ecurrencyhodler i can check it out

**Comment by ecurrencyhodler** [comment]
I marked this as unpaid and paid it out again. Payment is displayed in txn history now: https://community.sphinx.chat/bounty/1529
<img width="639" alt="Screenshot 2024-02-29 at 10 47 25 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/dcadd905-0fd7-4203-93c2-58af19411814">
