### ISSUE TITLE
Add optional word clause to query to call bounty statuses for assigned bounties when viewing profile

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1570]
### Context
We want to enable the ability for users to filter bounties when viewing the assigned bounties on their profile.
<img width="1124" alt="Screenshot 2024-02-28 at 1 22 15 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/7288e7ac-d61f-4921-8e83-b00a889a9cfe">

Add an optional word clause to query to call a person's specific bounty and filter the bounties based on status:
- Assigned
- Paid

Here is the call: `r.Get("/wanteds/header", handlers.GetWantedsHeader)`
https://github.com/stakwork/sphinx-tribes/blob/master/routes/people.go

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've created a test that asserts that the endpoint accepts search query, limits query, and bounty status
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by Jagmohan2k** [comment]
Assign me @ecurrencyhodler

**Comment by ecurrencyhodler** [comment]
Hey @Jagmohan2k I took a look at your profile and it looks brand new with 0 contributions. Do you have any work you can share? I'd like to see 3 projects of some sort before assigning you a bounty.

**Comment by okhot** [comment]
@ecurrencyhodler i can help with this

**Comment by gouravmpk** [comment]
> Hey @Jagmohan2k I took a look at your profile and it looks brand new with 0 contributions. Do you have any work you can share? I'd like to see 3 projects of some sort before assigning you a bounty.

Okay

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler could you please assign me?

**Comment by ecurrencyhodler** [comment]
This is yours @okhot https://community.sphinx.chat/bounty/1599

**Comment by okhot** [comment]
@ecurrencyhodler Is there any design available for the filters? Or should I just add generic filters to the top of the page

**Comment by ecurrencyhodler** [comment]
This is purely a backend change.

**Comment by okhot** [comment]
ooppss... didn't get the memo right then. I'm not fluent with Go 🙏🏽 you can reassign thanks

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler Could you please assign me, I will create a PR in few hours.

**Comment by aliraza556** [comment]
Hi @ecurrencyhodler,
Assign me
