### ISSUE TITLE
Backend [Integration Test] tribes.go handlers GenerateBudgetInvoice

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1584]
### Context

We are trying to increase the test coverage for our Golang backend. 

### File to to test

handlers/tribes.go

### Design

Write tests for the tribe handlers, the test should:

- Should test that a wrong Post body returns a 406 error 
- Mock a call to  relay `/invoices`  that receives a body of ```sh {"amount": 0, "memo": "Budget Invoice"}```
- Should test that the amount passed by the user is equal to the amount sent for invoice generation
- If the mock relay  invoice call is successful, the payments get added to the payment history, the invoice gets added to the invoice list, and a success message is returned with a 200 Status

Tribes Handlers To Test

```
GenerateBudgetInvoice
```

Add tests to `tribes_test.go`

### Acceptance Criteria
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler Could you please assign me?

**Comment by AbdulWahab3181** [comment]
@ecurrencyhodler Could you please assign me?

**Comment by MirzaHanan** [comment]
Hi @ecurrencyhodler,
assign me?

**Comment by ecurrencyhodler** [comment]
This is yours Mirza. Next one is yours @MuhammadUmer44 but make sure to complete the other 2 bounties you're working on in the next couple of days.

**Comment by ecurrencyhodler** [comment]
Paid!
