### ISSUE TITLE
Backend [Integration Test] bounty.go handlers PollInvoice For Organization Budget

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1585]
### Context

We are trying to increase the test coverage for our Golang backend. 

### File to to test

handlers/bounty.go

### Design

Write tests for the bounty handlers, the test should:

- Should test that a 401 error is returned if a user is unauthorized
- Mock a call to  relay GET `/invoice?payment_request=${paymentRequest}`   to get the status of the invoice
- If there is an invoice error a 403 status error should be returned
- If the invoice is settled and the `invoice.Type` is equal to `BUDGET` the invoice amount should be added to the organization budget and the payment status of the related invoice should be sent to true on the payment history table.

Bounty Handlers To Test

```
PollInvoice
```

Add tests to `bounty_test.go`

### Acceptance Criteria
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by AbdulWahab3181** [comment]
assign

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler Could you assign me?

**Comment by MuhammadUmer44** [comment]
Hi @ecurrencyhodler,
Please assign me?

**Comment by MuhammadUmer44** [comment]
@ecurrencyhodler,
I have completed all bounties.

**Comment by ecurrencyhodler** [comment]
@MuhammadUmer44 I'll assign you this one. But you have 2 other open bounties.
