### ISSUE TITLE
Backend [Integration Test] bounty.go handlers BountyBudgetWithdraw For Organization Budget Withdrawal

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1587]
### Context

We are trying to increase the test coverage for our Golang backend. 

### File to to test

handlers/bounty.go

### Design

Write tests for the bounty handlers, the test should:

- Should test that a 401 error is returned if a user is unauthorized
- Should test that a 406 error is returned if wrong data is passed
- Should test that a 401 error is returned if a user is not the organization admin, or does not have a `WithdrawBudget` role with an error message `'You don't have appropriate permissions to withdraw bounty budget'`
- If the amount to be withdrawn is greater than the organization's budget a 403 error is returned with the message `'Organization budget is not enough to withdraw the amount'`
- If the amount is lesser than the organization's budget the budget invoices get paid, and deducted from the organization's budget
- If there is an error with invoice payment a 400 BadRequest error is returned

Bounty Handlers To Test

```
BountyBudgetWithdraw
```

Add tests to `bounty_test.go`

### Acceptance Criteria
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

### References
- Watch this [Jest Youtube playlist](https://www.youtube.com/watch?v=T2sv8jXoP4s&list=PLC3y8-rFHvwirqe1KHFCHJ0RqNuN61SJd) if you are new to testing
- Here is an [example unit test](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/__test__/helpers.spec.ts)
- Here is an [example component test](https://github.com/stakwork/sphinx-tribes/blob/9310f49b3b17a51992dada932f4298eb9eba15ff/frontend/app/src/people/widgetViews/__tests__/AboutView.spec.tsx)

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by AbdulWahab3181** [comment]
?

**Comment by MahtabBukhari** [comment]
@ecurrencyhodler Could you assign me?

**Comment by ecurrencyhodler** [comment]
Paid!
