### ISSUE TITLE
Claiming badges on tor

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#159]
When I tried claiming my sphinx baged to my liquid wallet I came across this error, I'm assuming it's failing because of the tor relay address

![Screen Shot 2022-02-08 at 11 12 17 AM](https://user-images.githubusercontent.com/15950706/153039877-4115b6c6-621e-41f9-a73e-8000bf186f4d.png)

this is the file calling the endpoint `./frontend/app/src/store/main.ts`

Should we do something similar to how we do in `sphinx-tribes/frontend/app/src/people/main/focusView.tsx` where we popup a qr code and then have the user scan it with `torSave` and `submitFormViaApp`

**Comment by Evanfeenstra** [comment]
exactly, if the node endpoint is tor, then we need to do a QR popup. But instead of the path being `profile`, it should be `claim_on_liquid`. With`data` of stringified {asset, to, amount, memo}

@plell 

note: in the desktop app its in tribesSaveModal.tsx

**Comment by kevkevinpal** [comment]
I'm 100% sure but I think we might need to add another deeplink to the kotlin app for this to work with a new QR code

**Comment by plell** [comment]
i'll add the ui for tor badge claiming today

**Comment by kevkevinpal** [comment]
I can add the changes for the deeplink on kotlin since it should be similar with the save profile deeplink code

**Comment by plell** [comment]
the ui for tor badge claiming should work on prod now

**Comment by kevkevinpal** [comment]
Closing as this should be solved now
