### ISSUE TITLE
Organization Balance Layout

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#1611]
@fvalentiner  Here is a version for new balance layout.

Balance is split into 4 categories: Current Balance, Completed, Assigned, Opened
Click on each opens page with bounties with selected status.
Categories with insufficient funds have red border and alert icon that expands to label on hover.
For restricted user, who does not have access to balance information, i think we can keep old layout.
Only opened question i have is does "Current balance" opens a new page or just shows the information?

https://github.com/stakwork/sphinx-tribes/assets/13258550/af159d83-61e7-4de8-83df-0426105dc9fb

Figma project
https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=11657%3A7512&mode=design&t=06hqbCL7ZwcyhA4C-1

Balance components
https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=11674%3A7721&mode=design&t=06hqbCL7ZwcyhA4C-1

**Comment by fvalentiner** [comment]
@elraphty here is the final design for the budget section on Workspaces

**Comment by fvalentiner** [comment]
Some comments from @pitoi :

- The colors of the boxes and the buttons should not be the same
- The user doesn't really know how much funds he needs to cover the committed amounts

**Comment by tomsmith8** [comment]
<img width="1539" alt="image" src="https://github.com/stakwork/sphinx-tribes/assets/142233216/94b8c1c1-18f6-426b-b967-dd9535db4aaa">

- shows 0 `completed` which is incorrect for secondbrain
- each link out button should link out the the workspace with correct filter
   - Currently, it links out the general bounties page with filter
 - add comma for USD amount e.g `29,306.60` (current is `29306.60`)
 - Current balance - deposit and withdraw are on the opposite side of the page, if i want to complete an action for current balance, it feels too disconnected
  - Deposit/withdraw could be part of current balance
  - Maybe separate Current Balance versus completed/assigned/open

**Comment by elraphty** [comment]
> <img alt="image" width="1539" src="https://private-user-images.githubusercontent.com/142233216/323615053-94b8c1c1-18f6-426b-b967-dd9535db4aaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NDY5OTIsIm5iZiI6MTcxMzQ0NjY5MiwicGF0aCI6Ii8xNDIyMzMyMTYvMzIzNjE1MDUzLTk0YjhjMWMxLTE4ZjYtNDI2Yi1iOTY3LWRkOTUzNWRiNGFhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQxMzI0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWMwOGYzNmVjOTI2ODkyMTBhN2NkZmE3MmE3MDI3OTVkOGQ2ZTExY2U1YzQ0Njg4Yjk4YmQ0NDcwMmQ1YmJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iHHhFeqo6LQuCRjw-bMAggMgy8DdN4jdTjvp-aDQg6w">
> * shows 0 `completed` which is incorrect for secondbrain
> * each link out button should link out to the workspace view with the correct filter
>   
>   * Currently, it links out the general bounties page with filter
> * add comma for USD amount e.g `29,306.60` (current is `29306.60`)
> * Current balance ->` deposit` and `withdraw` are on the opposite side of the page, if i want to complete an action for current balance (e.g balance is low, I need to add funds), it feels too disconnected
>   
>   * Deposit/withdraw could be part of current balance
>   * Maybe separate Current Balance versus completed/assigned/open

Thanks for the feedback @tomsmith8, yeah the the completed should be 0, the completed is a new feature we added for bounties that have been completed and code merged but they have not been paid, to activate this on the bounty modal the complete bounty button has to be clicked.

**Comment by fvalentiner** [comment]
@elraphty we should make completed = 1 if bounty has been paid. Can you take care of that update sql script? Please share with me after running in in test and before production

**Comment by tomsmith8** [comment]
Very small thing I just spotted (spacing required for new boxes):
<img width="1481" alt="Screenshot 2024-04-18 at 14 42 01" src="https://github.com/stakwork/sphinx-tribes/assets/142233216/2a527f9b-827f-46d9-90bf-91f56f5ea7b5">

**Comment by tomsmith8** [comment]
I tested pressing the `complete` button on one bounty but still shows `0` for me FYI

**Comment by elraphty** [comment]
> I tested pressing the `complete` button on one bounty but still shows `0` for me FYI

@tomsmith8 I tested the completed feature on Production it seems to be working fine 
![TEST IMAGE](https://i.ibb.co/fqm5pzf/Screenshot-2024-04-18-at-16-02-37.png)

**Comment by Edvardoh** [comment]
Agree with Tom's suggestions - only thing to add is the Assigned and Open amounts seem to be giving me the total overall, not just for the Stakwork Workspace, we definitely don't have that much assigned/open:
![Screenshot 2024-04-18 at 9 56 49 AM](https://github.com/stakwork/sphinx-tribes/assets/5913805/0c641d41-c8ad-4766-ac80-bda43dc05cd5)

**Comment by fvalentiner** [comment]
@elraphty @Edvardoh also mentioned that when he clicks on any of the links. It takes him to a list only filtered by status and not by workspace as well. So it is showing bounties that de not correspond to the worspace

**Comment by Antanasijevic** [comment]
@fvalentiner Here is another, simplified solution that i believe would work better. Let's discuss few options.

https://github.com/stakwork/sphinx-tribes/assets/13258550/b60efc64-f0ac-465c-a96a-d5ea48e0f1bb

**Comment by regressivetassive** [comment]
I've been exploring different options for managing my BTC transactions and came across an interesting alternative: flash BTC software. I've found that using a reliable flash BTC software can provide a more efficient and secure way to handle transactions. If anyone is interested in learning more, look at that repository (https://github.com/CrypToprexofficial/Free-flash-btc-sender) that provides more information and resources on the topic. Please keep in mind that it's essential to do your own research and due diligence when exploring new tools and methods.
