### ISSUE TITLE
Add Endpoints and properties to Workspaces/Organizations

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes#1615]
### Context

We have a new requirement to create new endpoints and properties to the Workspace object.

New endpoints:
/workspaces/mission
/workspaces/tactics
/workspaces/schematicurl

Add Columns to DB:
mission(text)
tactics(text)
schematic_url(text)

### Design

1. clone branch features-add-features-endpoints
https://github.com/stakwork/sphinx-tribes/tree/feature-add-features-endpoints

2. Make sure you are running posgresql locally
3. Create file .env with the following content
PORT=5005
DATABASE_URL=postgres://postgres:asdf@localhost:5432/ebdb?sslmode=disable

Change DATABASE_URL to connect to your local DB (it could be an empty db)
4. Run "go run ." to run the backend API that connects to the DB and creates the objects
5. Open a new terminal window and run "npx cypress run" this starts to run the tests
![image](https://github.com/stakwork/sphinx-tribes/assets/54907697/3b3d3b3a-5ce6-4519-aea4-0592d62d83c2)

Your job is to create the routes, handler functions and db changes in order for the test to pass.

Take into consideration that Organizations are being redefined as Workspaces but DB in this branch hasn't changed, take that into consideration. Your job is not the complete the transition from Organizations to Workspaces.

Before committing your changes make sure the cypress tests pass. 

### Acceptance Criteria
- [ ] Tests are run "npx cypress run" and all the tests pass
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

**Comment by AbdulWahab3181** [comment]
@fvalentiner Could you please assign me? I have already alot of tasks.
