### ISSUE TITLE
Bounties exported from Admin module not showing all bounties

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes#1620]
**Describe the bug**

When you go to the admin module and export the bounties only one bounty is being shown and not all the bounties that are supposed to be shown.

**To Reproduce**

1. Go to admin module
2. Click on export
3. Open the .csv file
4. see that only one bounty is shown

**Expected behavior**
All corresponding bounties to the filter should be displayed in the .csv file

**Desktop (please complete the following information):**
Browser

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 2 days of taking the bounty

Here is a video example of the bug
https://www.loom.com/share/c3e344b98f1f42bb8996eff5460ef4ca?sid=1f393a27-cf4d-4d7d-b976-26ca30e3a899

**Comment by aliraza556** [comment]
@fvalentiner assign me?

**Comment by AbdulWahab3181** [comment]
G
