### ISSUE TITLE
Add multiple select filter for workspaces in admin

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes#1622]
### Context
The admin module has a list of bounties for the system filtered by a date range

The feature is to add a new multi select dropdown to filter by Workspaces. There should be the hability to filter by multiple workspaces at the same time.

### Design
![image](https://github.com/stakwork/sphinx-tribes/assets/54907697/5f7f55c0-b7ac-40e1-8fd9-af028f9ec009)

### Acceptance Criteria
- [ ] I've tested on Chrome
- [ ] I've created a cypress test that successfully tests the new feature
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

**Comment by Vayras** [comment]
@fvalentiner is this issue open to work on? I see this is already assigned to @elraphty

**Comment by fvalentiner** [comment]
@Vayras is already assigned. More front end tickets are coming. Stay tuned
