### ISSUE TITLE
Add Endpoints for Workspace Repositories

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes#1624]
### Context

We have a new requirement for endpoints to manage repositories in workspaces

New endpoints:
/workspaces/repositories
/workspaces/repositories/{uuid} workspace uuid

Add Table to DB:
workspace_repositories

uuid (text)
workspace_uuid (text)
name (text)
url (text)
created (datetime)
updated (datetime)
created_by (text)
updated_by (text)

### Design

1. clone branch features-add-repos-to-workspaces
https://github.com/stakwork/sphinx-tribes/tree/feature-add-repos-to-workspaces

2. Make sure you are running posgresql locally
3. Create file .env with the following content
PORT=5005
DATABASE_URL=postgres://postgres:asdf@localhost:5432/ebdb?sslmode=disable

Change DATABASE_URL to connect to your local DB (it could be an empty db)
4. Run "go run ." to run the backend API that connects to the DB and creates the objects
5. Open a new terminal window and run "npx cypress run" this starts to run the tests
![image](https://github.com/stakwork/sphinx-tribes/assets/54907697/2e2cd04d-b815-4ec9-99b3-a7aa512261b6)

Your job is to create the routes, handler functions and db changes in order for the test to pass.

Before committing your changes make sure the cypress tests pass. 

### Acceptance Criteria
- [ ] Tests are run "npx cypress run" and all the tests pass
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

**Comment by MirzaHanan** [comment]
Hi @fvalentiner,
Please assign me?
