### ISSUE TITLE
Add User Stories to Features

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes#1637]
### Context

We have a new requirement for endpoints to manage user stories inside features

New endpoints:
POST /features/story
GET /features/{feature_uuid}/story
GET /features/{feature_uuid}/story/{story_uuid}
DELETE  /features/{feature_uuid}/story/{story_uuid}

Add Table to DB:
feature_story

uuid (text)
feature_uuid (text)
description (text)
priority (integer)
created (datetime)
updated (datetime)
created_by (text)
updated_by (text)

Remember to fill the last 4 columns with the corresponding data.

### Design

1. clone branch
https://github.com/stakwork/sphinx-tribes/tree/feature-add-user-stories

2. Make sure you are running posgresql locally
3. Create file .env with the following content
PORT=5005
DATABASE_URL=postgres://postgres:asdf@localhost:5432/ebdb?sslmode=disable

Change DATABASE_URL to connect to your local DB (it could be an empty db)
4. Run "go run ." to run the backend API that connects to the DB and creates the objects
5. Open a new terminal window and run "npx cypress run" this starts to run the tests
![image](https://github.com/stakwork/sphinx-tribes/assets/54907697/caa83c15-8a40-413a-a2e3-0c5c12ac2d2e)

Your job is to create the routes, handler functions and db changes in order for the test to pass. If you find any issues or typos in the cypress tests please let the creator of the issue know.

Before committing your changes make sure the cypress tests pass. 

### Acceptance Criteria
- [ ] Tests are passing using "npx cypress run"
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

**Comment by MirzaHanan** [comment]
hi @fvalentiner assign me?
