### ISSUE TITLE
Modify Features endpoint and add delete feature

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes#1639]
### Context

Step 1
Modify the endpoint url from 

`/features/forworkspace/{workspace_uuid}`

to

`workspaces/{workspace_uuid}/features`

Step 2
Add endpoint for `DELETE /features`

### Design

1. clone branch
https://github.com/stakwork/sphinx-tribes/tree/feature-add-features-to-workspaces-modify-delete

2. Make sure you are running posgresql locally
3. Create file .env with the following content
PORT=5005
DATABASE_URL=postgres://postgres:asdf@localhost:5432/ebdb?sslmode=disable

Change DATABASE_URL to connect to your local DB (it could be an empty db)
4. Run "go run ." to run the backend API that connects to the DB and creates the objects
5. Open a new terminal window and run "npx cypress run" this starts to run the tests
![image](https://github.com/stakwork/sphinx-tribes/assets/54907697/9197a59f-7248-4758-89bc-f4cdafd90df3)

Your job is to create the routes, handler functions and db changes in order for the test to pass. If you find any issues or typos in the cypress tests please let the creator of the issue know.

Before committing your changes make sure the cypress tests pass. 

### Acceptance Criteria
- [ ] Tests are passing using "npx cypress run"
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

The bounty for this is: https://community.sphinx.chat/bounty/1926

**Comment by jordan-ae** [comment]
I can help

**Comment by fvalentiner** [comment]
> I can help

Great! What's you user here? https://community.sphinx.chat/p

**Comment by fvalentiner** [comment]
@jordan-ae

**Comment by jordan-ae** [comment]
@fvalentiner its Mandela on Sphinx

**Comment by MirzaHanan** [comment]
Hi @fvalentiner,
may I handle this task if @jordan-ae doesn't wish to work on it?

**Comment by MahtabBukhari** [comment]
Hi @jordan-ae are you working on this task?
@fvalentiner if @jordan-ae working on it then its great otherwise I am awailable for this task as i have no any other task.

**Comment by MahtabBukhari** [comment]
@fvalentiner Could i take this one if @jordan-ae not want to continue with that?

**Comment by MahtabBukhari** [comment]
Hi @fvalentiner @elraphty Could you please confirm is this enpoint is in used at frontend side 
![image](https://github.com/stakwork/sphinx-tribes/assets/98140673/dbecd5f4-dadb-4b3c-933e-10d260b64c4e)

Becuase Cypress tests are going to be pass only this endpoint as I change the url cypress tests are going to be failed.

**Comment by MahtabBukhari** [comment]
@fvalentiner @elraphty Could you please update from frontend side becuase this endpoint is used at frontend side due to which when i change this url then cypress are going to be failed   "/features/forworkspace/{workspace_uuid}"

**Comment by fvalentiner** [comment]
@MahtabBukhari leave the old endpoint for now

**Comment by MahtabBukhari** [comment]
@fvalentiner I have implemented the new endpoint and old one is also present.
The benefit is that when we update the url from front-end then no cypress issue Will accor and we can delete the old endpoint when needed.

**Comment by MahtabBukhari** [comment]
@elraphty suggest this solution that is better otherwise someone else will face the same cypress failing issue like me 😔
