### ISSUE TITLE
Add Endpoint to get repo and delete repo [feature-add-repos-to-workspaces-modify-delete]

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes#1651]
### Context

We have a new requirement for endpoints to manage repositories in workspaces

### Design

1. clone branch features-add-repos-to-workspaces
https://github.com/stakwork/sphinx-tribes/blob/feature-add-repos-to-workspaces-modify-delete

2. Make sure you are running posgresql locally
3. Create file .env with the following content
PORT=5005
DATABASE_URL=postgres://postgres:asdf@localhost:5432/ebdb?sslmode=disable

Change DATABASE_URL to connect to your local DB (it could be an empty db)
4. Run "go run ." to run the backend API that connects to the DB and creates the objects
5. Open a new terminal window and run "npx cypress run --spec 'cypress/e2e/02_repositories.cy.ts'" this starts to run the tests
![image](https://github.com/stakwork/sphinx-tribes/assets/54907697/c448673c-9933-4063-b361-be0e0f58e4fd)

Your job is to create the routes, handler functions and db changes in order for the test to pass.

- Make sure you handle cases where repository_uuid is empty, create a new uuid before saving.
- Make sure you handle the logic for created, updated, created_by, updated_by fields for repositories

Before committing your changes make sure the cypress tests pass. 

### Acceptance Criteria
- [ ] Tests are run "npx cypress run" and all the tests pass
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

**Comment by AbdulWahab3181** [comment]
aa
