### ISSUE TITLE
Add Bounties to Phase [feature-add-bounty-to-phase]

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes#1662]
### Context

Bounty: https://community.sphinx.chat/bounty/1980

We have a new requirement to add a property `phase_uuid` and `phase_priority` to bounties in order to relate them to phases within features.

Here is an schematic on the object relations:
![image](https://github.com/stakwork/sphinx-tribes/assets/54907697/16588d25-25c7-4948-a7eb-4cfa67cc8eba)

Modify Endpoints:
POST /gobounties/
GET /gobounties/all

New endpoints:
GET /features/{feature_uuid}/phase/{phase_uuid}/bounty

Add columns to bounty Table in DB:

phase_uuid (text) null
phase_priority (int) null

### Design

1. clone branch
https://github.com/stakwork/sphinx-tribes/tree/feature-add-bounty-to-phase

2. Make sure you are running posgresql locally
3. Create file .env with the following content
PORT=5005
DATABASE_URL=postgres://postgres:asdf@localhost:5432/ebdb?sslmode=disable

Change DATABASE_URL to connect to your local DB (it could be an empty db)
4. Run "go run ." to run the backend API that connects to the DB and creates the objects
5. Open a new terminal window and run "npx cypress run --spec 'cypress/e2e/07_add_bounty_to_phase.cy.ts' " this starts to run the tests
![image](https://github.com/stakwork/sphinx-tribes/assets/54907697/be131178-3ee5-40aa-93ac-6ac3344b615d)

Your job is to create the routes, handler functions and db changes in order for the test to pass. If you find any issues or typos in the cypress tests please let the creator of the issue know.

Before committing your changes make sure the cypress tests pass. 

### Acceptance Criteria
- [ ] Tests are passing using "npx cypress run --spec 'cypress/e2e/07_add_bounty_to_phase.cy.ts'"
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a pr within 2 days of taking the bounty

**Comment by Vayras** [comment]
Assign

**Comment by saithsab877** [comment]
@fvalentiner assign me

**Comment by MahtabBukhari** [comment]
assign

**Comment by AbdulWahab3181** [comment]
a

**Comment by aliraza556** [comment]
Hi @fvalentiner, Please assign me?
