### ISSUE TITLE
Add Pagination, Sorting and 3 summary fields to endpoint Get Features for Workspace

### ISSUE THREAD

**Issue by fvalentiner** [stakwork/sphinx-tribes#1670]
### Context

Bounty: https://community.sphinx.chat/bounty/2009

Add Pagination, Filtering, Sorting and 3 more fields to the Get Features for Workspace endpoint 

/workspaces/{workspace_uuid}/features

### Design

We need to add:
- Pagination
- Sorting

Use the Database pagination and sorting function

```sh
offset, limit, sortBy, direction, search := utils.GetPaginationParams(r)
```

- And Three fields:
-- Total Completed Bounties [bounties_count_completed] (int )
-- Total Assigned Bounties [bounties_count_assigned] (int)
-- Total Open Bounties [bounties_count_open] (int)

To the get features for workspace endpoint.
GET /workspaces/{workspace_uuid}/features

Pagination Query Parameters
limit=10
&page=1
&resetPage=true

Sorting Query Parameter
&sortBy=priority, created

You can copy functionality for pagination and sorting from /gobounties/all endpoint where all this query parameters are implemented.

This changes in the endpoints are necessary to make this UI changes.

Current Design

<img width="595" alt="image" src="https://github.com/stakwork/sphinx-tribes/assets/54907697/3388cea5-1f5c-4c4b-9362-9b88a32a7fda">

New Design

![image](https://github.com/stakwork/sphinx-tribes/assets/54907697/1e03aba8-cc56-447a-a78d-0bbf7e7e435c)

- Make sure you are running posgresql locally
- Create file .env with the following content
PORT=5005
DATABASE_URL=postgres://postgres:asdf@localhost:5432/ebdb?sslmode=disable

Change DATABASE_URL to connect to your local DB (it could be an empty db)
- Run "go run ." to run the backend API that connects to the DB and creates the objects

### Acceptance Criteria
- [ ] I have created at least 5 features for a single workspace 
- [ ] I have created at least 5 bounties for each feature total (25) and put at least 1 in each of the bounty states [Open], [Assigned], [Completed], [Paid]
- [ ] I have checked that the summary fields are returning the right values
- [ ] I have tested each of the query parameters [limit], [sortBy], [page], [resetPage]
- [ ] I have tested several values for each filter parameter
- [ ] I can submit a pr within 6 hours of taking the bounty

**Comment by AbdulWahab3181** [comment]
@fvalentiner Could you please assign me?

**Comment by MahtabBukhari** [comment]
@fvalentiner Could you please assign me?

**Comment by MirzaHanan** [comment]
Hi @fvalentiner, please assign me?
