### ISSUE TITLE
Paid label and layout fixes

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#170]
We need a prominent way to tell the user that it is no longer available to work on and it was paid.We want it to be readable if they are interested, but also know right away that it’s no longer available so they don’t waste time and getting their hopes up.

**Comment by Antanasijevic** [comment]
![image](https://user-images.githubusercontent.com/13258550/156584737-8e86b78a-2962-42c3-949a-690d73f55ba0.png)

**Comment by Antanasijevic** [comment]
![image](https://user-images.githubusercontent.com/13258550/157042273-7cd6999d-9947-4f02-b05b-5dc892c86d17.png)

**Comment by pitoi** [comment]
If there's a way to show who did the ticket, that'd be a nice touch (with link to their people profile)

**Comment by Antanasijevic** [comment]
@pitoi Here are labels combination we could use. Completed tickets can have additional label "Completed by..." with users name being link to their profile. Same logic can be used for "Assigned to..." .
![image](https://user-images.githubusercontent.com/13258550/157256710-8d6985b7-459d-431e-b95e-5c05712a9301.png)
