### ISSUE TITLE
Refactor TestGetPersonById To Use A Real Postgres DB For The Test

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1710]
### Context

Currently, we test the TestGetPersonById with a mock database.

### Design

We want to refactor the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestGetPersonById ` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)
```
The test will throw a dereference error if not connected to a DB.
- Remove all mock database functions in the `TestGetPersonById ` test cases e.g. `mockDb.On("GetPersonByPubkey", "test-key").Return(db.Person{}).Once()`.
- Change the database parameter in `pHandler := NewPeopleHandler(mockDb)` to `pHandler := NewPeopleHandler(db.TestDB)`
- Create a new person by passing person data to the create person db function `db.TestDb.CreateOrEditPerson()` e.g 
```sh
person := db.Person{
     ID: 100,
     Uuid:        "perosn_1_uuid",
     OwnerAlias:  "person",
     UniqueName:  "person",
     OwnerPubKey: "person_1_pubkey",
     PriceToMeet: 0,
     Description: "this is test user 1",
}
db.TestDb.CreateOrEditPerson(person)
```
- Update the id URL param `rctx.URLParams.Add("id", strconv.Itoa(int(person.ID)))` to the created person id `rctx.URLParams.Add("id", strconv.Itoa(int(person.ID)))`

### Assertions

- [ ] Assert that all the test passes
- [ ] Asert that the new user created is available in the DB by getting the user from the DB with `db.TestDB.GetPerson(person.ID)`
- [ ] Assert that the user created is equal to the data sent from the test request 

### Acceptance Criteria

- [ ] Do not delete any of the existing test cases on the `TestGetPersonById`
- [ ] All test cases after the `TestGetPersonById` refactor passes 
- [ ] The Refactoring of `TestGetPersonById` should not break existing test flows.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by AbdulWahab3181** [comment]
A

**Comment by MahtabBukhari** [comment]
@elraphty @fvalentiner Could you please assign me?

**Comment by elraphty** [comment]
> @elraphty @fvalentiner Could you please assign me?

@AbdulWahab3181 You can have this, please it is 1 day time bound.
