### ISSUE TITLE
Refactor TestGetPeopleBySearch To Use A Real Postgres DB For The Test

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1712]
### Context

Currently, we test the TestGetPeopleBySearch with a mock database.

### Design

We want to refactor the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestGetPeopleBySearch` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)
```
The test will throw a dereference error if not connected to a DB.
- Remove all mock database functions in the `TestGetPeopleBySearch` test cases e.g. `mockDb.On("GetPersonByPubkey", "test-key").Return(db.Person{}).Once()`.
- Change the database parameter in `pHandler := NewPeopleHandler(mockDb)` to `pHandler := NewPeopleHandler(db.TestDB)`
- Create 2 persons by passing person data to the create person db function `db.TestDb.CreateOrEditPerson()` e.g 
```sh
person := db.Person{
     ID: 102,
     Uuid:        "perosn_102_uuid",
     OwnerAlias:  "person102",
     UniqueName:  "person102",
     OwnerPubKey: "person_102_pubkey",
     PriceToMeet: 0,
     Description: "This is test user 102",
}
person2 := db.Person{
     ID: 102,
     Uuid:        "perosn_103_uuid",
     OwnerAlias:  "person103",
     UniqueName:  "person103",
     OwnerPubKey: "person_103_pubkey",
     PriceToMeet: 0,
     Description: "This is test user 103",
}
db.TestDb.CreateOrEditPerson(person)
db.TestDb.CreateOrEditPerson(person2)
```
- Get the persons created by using `person  :=  db.TestDb.GetPerson(person.ID)`
- Assert that the persons created are returned
- Update the id URL search query to one of the person's `OwnerAlias `req, err := http.NewRequestWithContext(context.WithValue(context.Background(), chi.RouteCtxKey, rctx), http.MethodGet, "/search?search=John", nil)`
- Assert that a user is returned

### Assertions

- [ ] Assert that a user is returned when we pass a user alias  to the URL query search value
- [ ] Assert that no user is returned when an unknown user_alias or unique name is passed to the search query value
- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] Do not delete any of the existing test cases on the `TestGetPeopleBySearch`
- [ ] All test cases after the `TestGetPeopleBySearch` refactor passes 
- [ ] The Refactoring of `TestGetPeopleBySearch` should not break existing test flows.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by MahtabBukhari** [comment]
d

**Comment by elraphty** [comment]
> 

> @elraphty Could you please assign me?

Okay

**Comment by elraphty** [comment]
@MahtabBukhari will you finish this in a day?

**Comment by MahtabBukhari** [comment]
> @MahtabBukhari will you finish this in a day?

Yeah
