### ISSUE TITLE
Refactor TestGetPersonByPuKey To Use A Real Postgres DB For The Test

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1713]
### Context

Currently, we test the TestGetPersonByPuKey with a mock database.

### Design

We want to refactor the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestGetPersonByPuKey` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)
```
The test will throw a dereference error if not connected to a DB.
- Remove all mock database functions in the `TestGetPersonByPuKey` test cases e.g. `mockDb.On("GetPersonByPubkey", "test-key").Return(db.Person{}).Once()`.
- Change the database parameter in `pHandler := NewPeopleHandler(mockDb)` to `pHandler := NewPeopleHandler(db.TestDB)`
- Create a persons by passing person data to the create person db function `db.TestDb.CreateOrEditPerson()` e.g 
```sh
person := db.Person{
     ID: 104,
     Uuid:        "perosn_104_uuid",
     OwnerAlias:  "person104",
     UniqueName:  "person104",
     OwnerPubKey: "person_104_pubkey",
     PriceToMeet: 0,
     Description: "This is test user 104",
}
db.TestDb.CreateOrEditPerson(person)
```
- Get the persons created by using `person  :=  db.TestDb.GetPerson(person.ID)`
- Assert that the persons created are returned
- Update the id URL params. value to the person's `OwnerPubKey `req, err := http.NewRequestWithContext(context.WithValue(context.Background(), chi.RouteCtxKey, rctx), http.MethodGet, "/person/person-pub-key", nil)`, also update the params to the person's pubkey `rctx.URLParams.Add("pubkey", "person-pub-key")`
- Assert that a user is returned

### Assertions

- [ ] Assert that a user is returned when we pass the person's public key
- [ ] Asert that the user returned equals the user created
- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] Do not delete any of the existing test cases on the `TestGetPersonByPuKey`
- [ ] All test cases after the `TestGetPersonByPuKey` refactor passes 
- [ ] The Refactoring of `TestGetPersonByPuKey` should not break existing test flows.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by MuhammadUmer44** [comment]
s

**Comment by AbdulWahab3181** [comment]
a

**Comment by saithsab877** [comment]
s

**Comment by elraphty** [comment]
> @elraphty Please assign me?

@MuhammadUmer44 you have to finish this in a day.
