### ISSUE TITLE
Refactor TestGetBountyIndexById To Use A Real Postgres DB For The Test

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1722]
### Context

Currently, we test the  TestGetBountyIndexById with a mock database.

### Design

We want to refactor the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestGetBountyIndexById` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)
```
The test will throw a dereference error if not connected to a DB.
- Remove all mock database functions in the `TestGetBountyIndexById` test cases e.g. `mockDb.On("GetPersonByPubkey", "test-key").Return(db.Person{}).Once()`.
- Change the database parameter in `pHandler := NewPeopleHandler(mockDb)` to `pHandler := NewPeopleHandler(db.TestDB)`
- Create a bounty using this db function `db.TestDb.CreateOrEditBounty()` e.g 
```sh

now := time.Now()
bounty  :=  db.NewBounty{
	Type:          "coding",
	Title:         "Bounty With ID",
	Description:   "Bounty ID description",
	WorkspaceUuid: "",
	Assignee:      "",
	OwnerID:       bountyOwner.OwnerPubKey,
	Show:          true,
        Created: &now
}
db.TestDb.CreateOrEditBounty(bounty)
```
- Get the bounty created by using `bountyInDb  :=  db.TestDb.GetBountyByCreated(bounty.Created)`
- Assert that the bounty is returned
- Update the URL id param to the bounty's ID `bountyInDb.Id` `req, err := http.NewRequestWithContext(context.WithValue(context.Background(), chi.RouteCtxKey, rctx), http.MethodGet, "/index/1", nil)
assert.NoError(t, err)`
- Update the string bountyId value  `rctx.URLParams.Add("bountyId", strconv.Itoa(int(bounty.ID)))` to   `rctx.URLParams.Add("bountyId", strconv.Itoa(int(bountyInDb.ID)))` 

### Assertions

- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] Do not delete any of the existing test cases on the `TestGetBountyIndexById`
- [ ] All test cases after the `TestGetBountyIndexById` refactor passes 
- [ ] The Refactoring of `TestGetBountyIndexById` should not break existing test flows.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by Shoaibdev7** [comment]
H

**Comment by AbdulWahab3181** [comment]
@elraphty Could you please assign me?

**Comment by Shoaibdev7** [comment]
@elraphty Please next task assign me

**Comment by elraphty** [comment]
Have you worked on any of the Go backend tests before now? I'm not so sure

**Comment by Shoaibdev7** [comment]
@elraphty, please assign it to me, and then I'll take care of it and ensure it's completed.

**Comment by Shoaibdev7** [comment]
> @elraphty, please assign it to me, and then I'll take care of it and ensure it's completed.

Next issue
