### ISSUE TITLE
Refactor TestCreateConnectionCode To Use A Real Postgres DB For The Test

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1730]
### Context

Currently, we test the TestCreateConnectionCode with a mock database.

### Design

We want to refactor the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestCreateConnectionCode` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)
```
The test will throw a dereference error if not connected to a DB.
- Remove all mock database functions in the `TestCreateConnectionCode` test cases e.g. `mockDb.On("CreateConnectionCode", codeArr).Return(codeArr, nil).Once()`.
- Change the database parameter in `aHandler := NewAuthHandler(mockDb)` to `aHandler := NewAuthHandler(db.TestDb)`
- Create connection codes using this db function `db.TestDB.CreateConnectionCode()` e.g 
```sh
codeArr := []db.ConnectionCodes{}
db.TestDB.CreateConnectionCode(codeArr)
```
- Get connection codes by using `codes  :=  db.TestDb.GetConnectionCode()`
- Assert that the connection is returned and the length is equals 1

### Assertions

- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] Do not delete any of the existing test cases on the `TestCreateConnectionCode`
- [ ] All test cases after the `TestCreateConnectionCode` refactor passes 
- [ ] The Refactoring of `TestCreateConnectionCode` should not break existing test flows.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by aliraza556** [comment]
a

**Comment by Shoaibdev7** [comment]
a

**Comment by aliraza556** [comment]
Hi @elraphty Please next assign me?

**Comment by MahtabBukhari** [comment]
@elraphty Could you assign me?

**Comment by elraphty** [comment]
@Shoaibdev7 what's your name on the Sphinx chat?

**Comment by MahtabBukhari** [comment]
> Hi @elraphty Please next assign me?

@elraphty it should be first comment

**Comment by Shoaibdev7** [comment]
> @Shoaibdev7 what's your name on the Sphinx chat?

Shoaibdev7

**Comment by Shoaibdev7** [comment]
> @Shoaibdev7 what's your name on the Sphinx chat?

@elraphty Same name `Shoaibdev7`

**Comment by AbdulWahab3181** [comment]
A

**Comment by AbdulWahab3181** [comment]
@elraphty Can I take this one if @Shoaibdev7 is unable to complete it?

**Comment by elraphty** [comment]
@Shoaibdev7 I will have to reassign to someone else if you don't make a PR today, you are supposed to finish this in a day.

**Comment by elraphty** [comment]
@Shoaibdev7 You have 3 hours to complete this

**Comment by aliraza556** [comment]
> @Shoaibdev7 You have 3 hours to complete this, its 2 days now

@elraphty I just made a PR because I faced a memory error.

**Comment by Shoaibdev7** [comment]
@elraphty I just made a PR because I faced a small invalid memory error that took some time to resolve.

**Comment by elraphty** [comment]
> @elraphty I just make a PR because I faced a small invalid memory error that took some time to resolve.

What was causing it?

**Comment by elraphty** [comment]
> @elraphty I just make a PR because I faced a small invalid memory error that took some time to resolve.

And I can't see your PR yet

**Comment by Shoaibdev7** [comment]
> > @elraphty I just make a PR because I faced a small invalid memory error that took some time to resolve.
> 
> And I can't see your PR yet

Just 2 mint
