### ISSUE TITLE
Refactor TestGetConnectionCode To Use A Real Postgres DB For The Test

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1731]
### Context

Currently, we test the TestGetConnectionCode with a mock database.

### Design

We want to refactor the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestGetConnectionCode` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)
```
The test will throw a dereference error if not connected to a DB.
- Remove all mock database functions in the `TestGetConnectionCode` test cases e.g. `mockDb.On("CreateConnectionCode", codeArr).Return(codeArr, nil).Once()`.
- Change the database parameter in `aHandler := NewAuthHandler(mockDb)` to `aHandler := NewAuthHandler(db.TestDb)`
- Create connection codes using this db function `db.TestDB.CreateConnectionCode()`
- Add one connection code to the connection codes array
```sh
codeArr := []db.ConnectionCodes{}
db.TestDB.CreateConnectionCode(codeArr)
```
- Get connection codes by using `codes:=  db.TestDb.GetConnectionCode()`
- Assert that the connection is returned and the length is equal to 1
- Assert that the connection codes return equals the one created 

### Assertions

- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] Do not delete any of the existing test cases on the `TestGetConnectionCode`
- [ ] All test cases after the `TestGetConnectionCode` refactor passes 
- [ ] The Refactoring of `TestGetConnectionCode` should not break existing test flows.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by aliraza556** [comment]
g

**Comment by AbdulWahab3181** [comment]
a
