### ISSUE TITLE
Refactor TestRefreshToken To Use A Real Postgres DB For The Test

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1732]
### Context

Currently, we test the TestRefreshToken with a mock database.

### Design

We want to refactor the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestRefreshToken` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)
```
The test will throw a dereference error if not connected to a DB.
- Remove all mock database functions in the `TestRefreshToken` test cases e.g. `mockDb.On("GetPersonByPubkey", mockUserPubkey).Return(mockPerson).Once()`.
- Change the database parameter in `aHandler := NewAuthHandler(mockDb)` to `aHandler := NewAuthHandler(db.TestDb)`
- Create a new person using this db function `db.TestDB.CreateOrEditPerson(person)` e.g
```sh
person := db.Person{
    Uuid:         "your_uuid",
    OwnerPubKey:  "your_pubkey",
    OwnerAlias:   "your_owner",
    UniqueName:   "your_user",
    Description:  "your user",
    Tags:         pq.StringArray{},
    Extras:       db.PropertyMap{},
    GithubIssues: db.PropertyMap{},
}
db.TestDB.CreateOrEditPerson(person)
```
- Get the person created by using `fetchedPerson := db.TestDB.GetPersonByUuid(person.Uuid)`
- Assert that the person returned is equal to the one created
- Change the public key in `mockClaims` to the created person's public key 
```sh 
// Mock JWT decoding
mockClaims := jwt.MapClaims{
    "pubkey":  person.OwnerPubKey,
}
```

### Assertions

- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] Do not delete any of the existing test cases on the `TestRefreshToken`
- [ ] All test cases after the `TestRefreshToken` refactor passes 
- [ ] The Refactoring of `TestRefreshToken` should not break existing test flows.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by AhsanFarooqDev** [comment]
g

**Comment by MuhammadUmer44** [comment]
N

**Comment by AbdulWahab3181** [comment]
s

**Comment by aliraza556** [comment]
@elraphty please assign me?

**Comment by elraphty** [comment]
> AhsanFarooqDev

@AhsanFarooqDev have you worked on Golang before now?

**Comment by AhsanFarooqDev** [comment]
yes

**Comment by AhsanFarooqDev** [comment]
@elraphty I have done issue on friday

**Comment by elraphty** [comment]
@aliraza556, and @AbdulWahab3181 will get the next 2 issues in no particular order.

**Comment by AhsanFarooqDev** [comment]
@elraphty please check this one https://github.com/stakwork/sphinx-tribes/issues/1709

**Comment by elraphty** [comment]
> @elraphty please check this one #1709

I have assigned the issue to you @AhsanFarooqDev
