### ISSUE TITLE
Refactor TestGetBotsByOwner To Use A Real Postgres DB For The Test

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1737]
### Context

Currently, we test the TestGetBotsByOwner with a mock database.

### Design

We want to refactor the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add `db.AutoMigrate(&Bot{})` to the test_config.go after `db.AutoMigrate(&WorkspaceUserRoles{})`
- Add this line of code on the first line and second of the test function `TestGetBotsByOwner` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)
```
The test will throw a dereference error if not connected to a DB.
- Remove all mock database functions in the `TestGetBotsByOwner` test cases e.g. `mockDb.On("GetBotsByOwner", bot.OwnerPubKey).Return([]db.Bot{}, nil).Once()`.
- Change the database parameter in `bHandler := NewBotHandler(mockDb)` to `bHandler := NewBotHandler(db.TestDb)`
- Create a new person using this db function `db.TestDB.CreateOrEditPerson(person)` e.g
```sh
person := db.Person{
    Uuid:         "your_uuid",
    OwnerPubKey:  "your_pubkey",
    OwnerAlias:   "your_owner",
    UniqueName:   "your_user",
    Description:  "Your user",
    Tags:         pq.StringArray{},
    Extras:       db.PropertyMap{},
    GithubIssues: db.PropertyMap{},
}
db.TestDB.CreateOrEditPerson(person)
```
- Create  two new using this db function `db.TestDB.CreateOrEditBot(bot)` e.g
```sh
bot := db.Bot{
    Uuid:         "bot1_uuid",
    OwnerPubKey:  person.OwnerPubkey,
    OwnerAlias: person.OwnerAlias,
    Name:   "test_bot_owner",
    Unique_Name:   "test_bot_owner",
    Description:  "bot description",
    Tags:         pq.StringArray{}
}
bot2 := db.Bot{
    Uuid:         "bot2_uuid",
    OwnerPubKey:  person.OwnerPubkey,
    OwnerAlias: person.OwnerAlias,
    Name:   "test_bot_owner2",
    Unique_Name:   "test_bot_owner2",
    Description:  "bot description",
    Tags:         pq.StringArray{}
}
db.TestDB.CreateOrEditBot(bot)
db.TestDB.CreateOrEditBot(bot2)
```
- Assert that it returns all the person-created bots

### Assertions

- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] Do not delete any of the existing test cases on the `TestGetBotsByOwner`
- [ ] All test cases after the `TestGetBotsByOwner` refactor passes 
- [ ] The Refactoring of `TestGetBotsByOwner` should not break existing test flows.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by AhsanFarooqDev** [comment]
S

**Comment by MirzaHanan** [comment]
s
