### ISSUE TITLE
Refactor TestGetBot To Use A Real Postgres DB For The Test

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1739]
### Context

Currently, we test the TestGetBot with a mock database.

### Design

We want to refactor the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add `db.AutoMigrate(&Bot{})` to the test_config.go after `db.AutoMigrate(&WorkspaceUserRoles{})`
- Add this line of code on the first line and second of the test function `TestGetBot` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)
```
The test will throw a dereference error if not connected to a DB.
- Remove all mock database functions in the `TestGetBot` test cases e.g. `mockDb.On("GetBot", mock.Anything).Return(mockBot).Once()`.
- Change the database parameter in `bHandler := NewBotHandler(mockDb)` to `bHandler := NewBotHandler(db.TestDb)`
- Create a new bot using this db function `db.TestDB.CreateOrEditBot(bot)` e.g
```sh
bot := db.Bot{
    Uuid:         "bot_uuid",
    OwnerPubKey:  "your_pubkey",
    OwnerAlias:   "your_owner",
    Name:   "test_bot",
    Unique_Name:   "test_bot",
    Description:  "bot description",
    Tags:         pq.StringArray{},}
db.TestDB.CreateOrEditBot(bot)
```
- Update the `mockUUID` value `mockUUID := "valid_uuid"` to   `mockUUID :=  bot.Uuid` 
- Use the `db.TestDb.GetBot(uuid)` function to get the bot created
- Assert that the bot is not returned from the Db function equals the bot returned from the API request.

### Assertions

- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] Do not delete any of the existing test cases on the `TestGetBot`
- [ ] All test cases after the `TestGetBot` refactor passes 
- [ ] The Refactoring of `TestGetBot` should not break existing test flows.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by AhsanFarooqDev** [comment]
s
