### ISSUE TITLE
Refactor TestDeleteChannel To Use A Real Postgres DB For The Test

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1749]
### Context

Currently, we test the TestDeleteChannel with a mock database.

### Design

We want to refactor the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestDeleteChannel` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)
```
The test will throw a dereference error if not connected to a DB.
- Remove all mock database functions in the `TestDeleteChannel` test cases e.g. `mockDb.On("GetChannel", mockChannelID).Return(db.Channel{ID: mockChannelID, TribeUUID: "mock_tribe_uuid"})`.
- Change the database parameter in `cHandler := NewChannelHandler(mockDb)` to `cHandler := NewChannelHandler(db.TestDb)`
- Create a new channel by creating a new person, then a tribe, and finally create the channel  e.g 
```sh
person := db.Person{
   Uuid:         "person_chan1_uuid",
   OwnerAlias:   "person_chan1",
   UniqueName:   "person_chan1",
   OwnerPubKey:  "person_chan1_pubkey",
   PriceToMeet:  0,
   Description:  "This is test user chan1",
   Unlisted:     false,
   Tags:         pq.StringArray{},
   GithubIssues: db.PropertyMap{},
   Extras:       db.PropertyMap{"coding_languages": "Lightning"},
}
db.TestDB.CreateOrEditPerson(person)

tribe := db.Tribe{
    UUID: "tribe_uuid1", 
    OwnerPubKey:  person.OwnerPubkey,
    OwnerAlias: person.OwnerAlias,
    Name:  "New Tribe 1",
    Unlisted: false,
    UniqueName: "NewTribe1",
}
db.TestDb.CreateOrEditTribe(tribe)

channel := db.Channel{
    TribeUUID: tribe.UUID,
    Name: "Test Channe 1l"
    Deleted: false,
}
db.TestDb.CreateChannel(channel)
```
- Get the channel created by using `channels :=  db.TestDb.GetChannelsByTribe(tribe.UUID)`
- Change the mockChannelID  `mockChannelID := uint(1)`  to `mockChannelID :=  channels[0].ID`
- Assert that the channel is returned and the length is equal to 1
- Assert that the channel returned is equal to the one created
- Get the channel by using the DB function `db.TestDb.GetChannel(channelID)`
- After deletion assert that the channel created does not exist 

### Assertions

- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] Do not delete any of the existing test cases on the `TestDeleteChannel`
- [ ] All test cases after the `TestDeleteChannel` refactor passes 
- [ ] The Refactoring of `TestDeleteChannel` should not break existing test flows.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by AbdulWahab3181** [comment]
a

**Comment by MirzaHanan** [comment]
s

**Comment by aliraza556** [comment]
@elraphty assign me?
