### ISSUE TITLE
Refactor TestCreateOrEditTribe To Use A Real Postgres DB For The Test

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1764]
### Context

Currently, we test the TestCreateOrEditTribe with a mock database.

### Design

We want to refactor the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestCreateOrEditTribe` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)
```
The test will throw a dereference error if not connected to a DB.
- Remove all mock database functions in the `TestCreateOrEditTribe` test cases e.g. `mockDb.On("GetTribe", mock.Anything).Return(db.Tribe{
   UUID:        mockUUID,
   OwnerPubKey: mockPubKey,
}).Once()`.
- Change the database parameter in `tHandler := NewTribeHandler(mockDb)` to `tHandler := NewTribeHandler(db.TestDb)`
- Delete mock data variables 
```sh
// Mock data
mockPubKey := "valid_pubkey"
mockUUID := "valid_uuid"
mockName := "Test Tribe"
mockDescription := "This is a test tribe."
mockTags := []string{"tag1", "tag2"}
```
- Create a tribe using the request body passed to the route  e.g 
```sh
tribe := db.Tribe{
    UUID: ${tribe_uuid}, 
    OwnerPubKey:  ${pubkey},
    Name:  ${name},
    Description: ${description}
    Tags: []string{"tag1", "tag2"}
}
```
- Update the `requestBody` values to use data from the `tribe` variable
```sh
requestBody := map[string]interface{}{
    "UUID":        tribe.UUID,
    "Name":       tribe.Name,
    "Description": tribe.Descriprion,
    "Tags":        tribe.Tags,
    "OwnerPubkey": tribe.OwnerPubkey
}
```
- Assert that the response data is equal to the tribe POST data sent to the request

### Assertions

- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] Do not delete any of the existing test cases on the `TestCreateOrEditTribe`
- [ ] All test cases after the `TestCreateOrEditTribe` refactor passes 
- [ ] The Refactoring of `TestCreateOrEditTribe` should not break existing test flows.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by MuhammadUmer44** [comment]
B

**Comment by AhsanFarooqDev** [comment]
d

**Comment by AbdulWahab3181** [comment]
s

**Comment by aliraza556** [comment]
Hi @elraphty, please assign?

**Comment by AbdulWahab3181** [comment]
c
