### ISSUE TITLE
Refactor TestDeleteTribe To Use A Real Postgres DB For The Test

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1767]
### Context

Currently, we test the TestDeleteTribe with a mock database.

### Design

We want to refactor the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestDeleteTribe` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)
```
The test will throw a dereference error if not connected to a DB.
- Remove all mock database functions in the `TestDeleteTribe` test cases e.g. `mockDb.On("UpdateTribe", mock.Anything, map[string]interface{}{"deleted": true}).Return(true)`.
- Change the database parameter in `tHandler := NewTribeHandler(mockDb)` to `tHandler := NewTribeHandler(db.TestDb)`
- Create a user using the `db.TestDb.CreateOrEditPerson()` function e.g.
```sh
person := db.Person{
     Uuid:        ${person_uuid},
     OwnerAlias:  ${person_alias},
     UniqueName:  ${person_unique_name},
     OwnerPubKey: ${person_pubkey},
     PriceToMeet: 0,
     Description: "this is test user 1",
}
db.TestDb.CreateOrEditPerson(person)
```
- Create a tribe using the db.TestDb.CreateOrEditTribe() function   e.g 
```sh
tribe := db.Tribe{
    UUID: ${tribe_uuid}, 
    OwnerPubKey:  ${pubkey},
    Name:  ${name},
    Description: ${description}
    Tags: []string{"tag3", "tag4"}
    AppUrl: ${AppURl}
}
db.TestDb.CreateOrEditTribe(tribe)
```
- Get the created tribe using the `db.TestDB.Get(tribe.UUID)` function
- Assert that the tribe created is equals to the one returned
- Update the `mockUUID` values  from `mockUUID:= "valid_uuid"` to `mockUUID :=  tribe.AppURL` 
- Update the `mockOwnerPubKey` values  from `mockOwnerPubKey= "valid_uuid"` to `mockOwnerPubKey:=  person.OwnerPubkey` 
- Assert that Deletion, get the created tribe using the `db.TestDB.GetTribe(tribe.UUID)` function
- Assert that an empty object is returned
- Assert that the response response is equal to true

### Assertions

- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] Do not delete any of the existing test cases on the `TestDeleteTribe`
- [ ] All test cases after the `TestDeleteTribe` refactor passes 
- [ ] The Refactoring of `TestDeleteTribe` should not break existing test flows.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by elraphty** [comment]
@aliraza556

**Comment by aliraza556** [comment]
@elraphty Please assign me?

**Comment by AbdulWahab3181** [comment]
A

**Comment by saithsab877** [comment]
HI @elraphty assign me next one?

**Comment by MirzaHanan** [comment]
Hi @elraphty Next assign me?
