### ISSUE TITLE
Refactor TestGetTribesByOwner To Use A Real Postgres DB For The Test

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1771]
### Context

Currently, we test the TestGetTribesByOwner with a mock database.

### Design

We want to refactor the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestGetTribesByOwner` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)
```
The test will throw a dereference error if not connected to a DB.
- Remove all mock database functions in the `TestGetTribesByOwner` test cases e.g. `mockDb.On("GetAllTribesByOwner", mock.Anything).Return(mockTribes).Once()`.
- Change the database parameter in `tHandler := NewTribeHandler(mockDb)` to `tHandler := NewTribeHandler(db.TestDb)`
- Create a user using the `db.TestDb.CreateOrEditPerson()` function e.g.
```sh
person := db.Person{
     Uuid:        ${person_uuid},
     OwnerAlias:  ${person_alias},
     UniqueName:  ${person_unique_name},
     OwnerPubKey: ${person_pubkey},
     PriceToMeet: 0,
     Description: "This is test user 1",
}
db.TestDb.CreateOrEditPerson(person)
```
- Create a tribe using the db.TestDb.CreateOrEditTribe() function   e.g 
```sh
tribe := db.Tribe{
    UUID: ${tribe_uuid}, 
    OwnerPubKey:  person.OwnerPubkey,
    Name:  ${name},
    Description: ${description}
    Tags: []string{"tag3", "tag4"}
    AppUrl: ${AppURl}
}
db.TestDb.CreateOrEditTribe(tribe)
```
- Update the `mockPubkey` values  from `mockPubkey:= "valid_uuid"` to `mockPubkey :=  person.OwnerPubkey` 
- Assert that all the tribes created by the user are returned

### Assertions

- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] Do not delete any of the existing test cases on the `TestGetTribesByOwner`
- [ ] All test cases after the `TestGetTribesByOwner` refactor passes 
- [ ] The Refactoring of `TestGetTribesByOwner` should not break existing test flows.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by saithsab877** [comment]
n

**Comment by MirzaHanan** [comment]
@elraphty assign me next?
