### ISSUE TITLE
Refactor TestGetTribeByUniqueName To Use A Real Postgres DB For The Test

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1772]
### Context

Currently, we test the TestGetTribeByUniqueName with a mock database.

### Design

We want to refactor the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestGetTribeByUniqueName` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)
```
The test will throw a dereference error if not connected to a DB.
- Remove all mock database functions in the `TestGetTribeByUniqueName` test cases e.g. `mockDb.On("GetTribe", mock.Anything).Return(db.Tribe{
   UUID:        mockUUID,
   OwnerPubKey: mockPubKey,
}).Once()`.
- Change the database parameter in `tHandler := NewTribeHandler(mockDb)` to `tHandler := NewTribeHandler(db.TestDb)`
- Create a tribe using the db.TestDb.CreateOrEditTribe() function   e.g 
```sh
tribe := db.Tribe{
    UUID: ${tribe_uuid}, 
    OwnerPubKey:  ${pubkey},
    Name:  ${name},
    UniqueName: ${uniqueName},
    Description: ${description}
    Tags: []string{"tag3", "tag4"}
    AppUrl: ${AppURl}
}
db.TestDb.CreateOrEditTribe(tribe)
```
- Update the `mockUniqueName` values  from `mockUniqueName:= "valid_uuid"` to `mockUniqueName :=  tribe.UniqueName` 
- Assert that the tribe created is equal to the one returned from the response
- Assert that the response length is equal to 1

### Assertions

- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] Do not delete any of the existing test cases on the `TestGetTribeByUniqueName`
- [ ] All test cases after the `TestGetTribeByUniqueName` refactor passes 
- [ ] The Refactoring of `TestGetTribeByUniqueName` should not break existing test flows.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by AbdulWahab3181** [comment]
a

**Comment by MirzaHanan** [comment]
@elraphty assign me?

**Comment by AbdulWahab3181** [comment]
My previous task are completed
