### ISSUE TITLE
Refactor `TestSetTribePreview` To Use A Real Postgres DB For The Test

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1782]
### Context

Currently, we test the `TestSetTribePreview` with a mock database.

### Design

We want to refactor the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestSetTribePreview` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)
```
The test will throw a dereference error if not connected to a DB.
- Remove all mock database functions in the `TestSetTribePreview` test cases e.g. `mockDb.On("UpdateTribe", mock.Anything, map[string]interface{}{"preview": "preview"}).Return(true)`.
- Change the database parameter in `tHandler := NewTribeHandler(mockDb)` to `tHandler := NewTribeHandler(db.TestDb)`
- Create a using the db.TestDb.CreateOrEditTribe() function   e.g 
```sh
tribe := db.Tribe{
    UUID: ${tribe_uuid}, 
    OwnerPubKey:  person.OwnerPubkey,
    Name:  ${name},
    Description: ${description}
    Tags: []string{"tag3", "tag4"}
    AppUrl: ${AppURl}
}
db.TestDb.CreateOrEditTribe(tribe)
```
- Change the `mockUuid` value from `mockUUID := "valid_uuid"` to `mockUUID := tribe.UUID`
- Change the `mockOwnerPubKey` value from `mockOwnerPubKey := "owner_pubkey"` to `mockOwnerPubKey := tribe.OwnerPubkey`
- Create a new variable named `preview`, see the value of `preview` to a string 
- Pass the preview variable to the route `req, err := http.NewRequestWithContext(ctx, "PUT", "/tribepreview/"+mockUUID+"?preview=preview", nil)`
- Assert that the response of the  API request is true
- After the API request assert that when you get the tribe using the DB function `db.TestDb.GetTribe(tribe.UUID)`, the value of the tribe created preview is equal to the value of the preview variable.

### Assertions

- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] Do not delete any of the existing test cases on the `TestSetTribePreview`
- [ ] All test cases after the `TestSetTribePreview` refactor passes 
- [ ] The Refactoring of `TestSetTribePreview` should not break existing test flows.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by AbdulWahab3181** [comment]
@elraphty Could you please assign me?

**Comment by MuhammadUmer44** [comment]
H

**Comment by elraphty** [comment]
> @elraphty Could you please assign me?

@AbdulWahab3181 I will give this to @MuhammadUmer44, I want you to work on the next Issue.

**Comment by AbdulWahab3181** [comment]
> > @elraphty Could you please assign me?
> 
> @AbdulWahab3181 I will give this to @MuhammadUmer44, I want you to work on the next Issue.

Ok
