### ISSUE TITLE
 Refactor `TestGenerateBudgetInvoice` To Use A Real Postgres DB For The Test

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1785]
### Context

Currently, we test the `TestGenerateBudgetInvoice` with a mock database.

### Design

We want to refactor the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestGenerateBudgetInvoice` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)
```
The test will throw a dereference error if not connected to a DB.
- Remove all mock database functions in the `TestGenerateBudgetInvoice` test cases e.g. `mockDb.On("ProcessBudgetInvoice", mock.AnythingOfType("db.NewPaymentHistory"), mock.AnythingOfType("db.NewInvoiceList")).Return(nil)`.
- Change the database parameter in `tHandler := NewTribeHandler(mockDb)` to `tHandler := NewTribeHandler(db.TestDb)`
- Create a person using the db.TestDb.CreateOrEditPerson() function   e.g 
```sh
person := db.Person{
     ID: 104,
     Uuid:        "perosn_104_uuid",
     OwnerAlias:  "person104",
     UniqueName:  "person104",
     OwnerPubKey: "person_104_pubkey",
     PriceToMeet: 0,
     Description: "This is test user 104",
}
db.TestDb.CreateOrEditPerson(person)
```
- Change the `authorizedCtx` value from `authorizedCtx := context.WithValue(ctx, auth.ContextKey, "valid-key")` to `authorizedCtx := context.WithValue(ctx, auth.ContextKey, tribe.OwnerPubkey)`
- Update the `reqBody` value from `reqBody := map[string]interface{}{"amount": userAmount}` to 
```sh
reqBody := map[string]interface{}{
    "amount": userAmount, 
    "sender_pubkey": person.OwnerPubkey,  
    "payment_type": "deposit",
    "workspace_uuid: ${workspaceuuid}
 }
```
- Assert that the new payment is added to the Payment History using the `db.TestDb.GetPaymentHistory(workspace_uuid, request)` function

### Assertions

- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] Do not delete any of the existing test cases on the `TestGenerateBudgetInvoice`
- [ ] All test cases after the `TestGenerateBudgetInvoice` refactor passes 
- [ ] The Refactoring of `TestGenerateBudgetInvoice` should not break existing test flows.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by MirzaHanan** [comment]
@elraphty Please assign me next one?

**Comment by AbdulWahab3181** [comment]
@elraphty Could you please assign me?

**Comment by elraphty** [comment]
> @elraphty Please assign me next one?

Okay

**Comment by MirzaHanan** [comment]
> > @elraphty Please assign me next one?
> 
> Okay

Thanks Man
