### ISSUE TITLE
Refactor TestMetricsBounties To Use A Real Postgres DB For The Test

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1793]
### Context

Currently, we test the TestMetricsBounties with a mock database.

### Design

We want to refactor the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestMetricsBounties` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)
```
The test will throw a dereference error if not connected to a DB.
- Remove all mock database functions in the `TestMetricsBounties` test cases e.g. `mockDb.On("GetBountiesByDateRange", dateRange, req).Return(bounties).Once()`.
- Change the database parameter in `mh := NewMetricHandler(mockDb)` to `mh := NewMetricHandler(db.TestDb)`
- Delete all bounties in the TestDB
- Create 4 bounties using this db function `db.TestDb.CreateOrEditBounty()` e.g 
```sh
now := time.Now()
bounty  :=  db.NewBounty{
	Type:          "coding",
	Title:         "Bounty With ID",
	Description:   "Bounty ID Description",
	WorkspaceUuid: "",
	Assignee:      "",
	OwnerID:       bountyOwner.OwnerPubKey,
	Show:          true,
        Created: &now,
        Paid: true
}
db.TestDb.CreateOrEditBounty(bounty)
bounty2  :=  db.NewBounty{
	Type:          "coding",
	Title:         "Bounty With ID",
	Description:   "Bounty ID Description",
	WorkspaceUuid: "",
	Assignee:      "",
	OwnerID:       bountyOwner.OwnerPubKey,
	Show:          true,
        Created: &now,
}
db.TestDb.CreateOrEditBounty(bounty2)
```
2 Bounties, should be set to `Paid: true`, while the Other 2 should be set as `Paid: false`, and the `Created` time value of the 4 bounties should be within 30 days i.e, the first bounty and the last bounties should be 30 days apart, use Golang date manipulation to achieve this.
- Change the `dateRange` StartDate and EndDate values to be the `Created` date of the first bounty and the `Created` date of the last bounty e.g. 
```sh
dateRange := db.PaymentDateRange{
   StartDate:  bounty.Created,
   EndDate:   bounty4.Created,
}
```
- Get all the bounties created by using the `db.TestDb.GetBountiesByDateRange(request, r)` function
- Assert that the 4 bounties created are in the bounties DB response

### Assertions

- [ ] Assert that the API call returned value matches the bounties fetched from the DB.

### Acceptance Criteria

- [ ] Do not delete any of the existing test cases on the `TestMetricsBounties`
- [ ] All test cases after the `TestMetricsBounties` refactor passes 
- [ ] The Refactoring of `TestMetricsBounties` should not break existing test flows.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by AbdulWahab3181** [comment]
@elraphty Could you please assign me?

**Comment by MirzaHanan** [comment]
@elraphty assign me?

**Comment by saithsab877** [comment]
@elraphty Please assign me?

**Comment by elraphty** [comment]
> @elraphty Could you please assign me?

@AbdulWahab3181 I will assign this @MirzaHanan, I will create a PollInvoice issue for you later in the day, since you already worked on something similar yesterday.

**Comment by AbdulWahab3181** [comment]
> > @elraphty Could you please assign me?
> 
> @AbdulWahab3181 I will assign this @MirzaHanan, I will create a PollInvoice issue for you later in the day, since you already worked on something similar yesterday.

Ok I am waiting

**Comment by MuhammadUmer44** [comment]
@elraphty Please assign me next one?
