### ISSUE TITLE
Refactor TestMetricsBountiesCount To Use A Real Postgres DB For The Test

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1794]
### Context

Currently, we test the TestMetricsBountiesCount with a mock database.

### Design

We want to refactor the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestMetricsBountiesCount` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)
```
The test will throw a dereference error if not connected to a DB.
- Remove all mock database functions in the `TestMetricsBountiesCount` test cases e.g. `mockDb.On("GetBountiesByDateRangeCount", dateRange, req).Return(int64(100)).Once()`.
- Change the database parameter in `mh := NewMetricHandler(mockDb)` to `mh := NewMetricHandler(db.TestDb)`
- Create 4 bounties using this db function `db.TestDb.CreateOrEditBounty()` e.g 
```sh
now := time.Now()
bounty  :=  db.NewBounty{
	Type:          "coding",
	Title:         "Bounty With ID",
	Description:   "Bounty ID Description",
	WorkspaceUuid: "",
	Assignee:      "",
	OwnerID:       bountyOwner.OwnerPubKey,
	Show:          true,
        Created: &now,
        Paid: true
}
db.TestDb.CreateOrEditBounty(bounty)
bounty2  :=  db.NewBounty{
	Type:          "coding",
	Title:         "Bounty With ID",
	Description:   "Bounty ID Description",
	WorkspaceUuid: "",
	Assignee:      "",
	OwnerID:       bountyOwner.OwnerPubKey,
	Show:          true,
        Created: &now,
}
db.TestDb.CreateOrEditBounty(bounty2)
```
2 Bounties, should be set to `Paid: true`, while the Other 2 should be set as `Paid: false`, and the `Created` time value of the 4 bounties should be within 30 days i.e, the first bounty and the last bounties should be 30 days apart, use Golang Date manipulation to achieve this.
- Change the `dateRange` StartDate and EndDate values to be the `Created` date of the first bounty and the `Created` date of the last bounty e.g. 
```sh
dateRange := db.PaymentDateRange{
   StartDate:  bounty.Created,
   EndDate:   bounty4.Created,
}
```
- Get all the total count of the bounties created using the `GetBountiesByDateRangeCount` function
- Assert that the API call response matches the value returned from the DB.

### Assertions

- [ ] Assert that the API call returned value matches the bounties fetched from the DB.

### Acceptance Criteria

- [ ] Do not delete any of the existing test cases on the `TestMetricsBountiesCount`
- [ ] All test cases after the `TestMetricsBountiesCount` refactor passes 
- [ ] The Refactoring of `TestMetricsBountiesCount` should not break existing test flows.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by MahtabBukhari** [comment]
j

**Comment by saithsab877** [comment]
m

**Comment by MahtabBukhari** [comment]
> @elraphty could you please assign me?

@elraphty please assign please next one

**Comment by MuhammadUmer44** [comment]
@elraphty Please assign me Next?
