### ISSUE TITLE
 Refactor `TestPollInvoice` To Use A Real Postgres DB For The Test

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1798]
### Context

Currently, we test the `TestPollInvoice` with a mock database.

### Design

We want to refactor the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestPollInvoice` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)
```
The test will throw a dereference error if not connected to a DB.
- Remove all mock database functions in the `TTestPollInvoice` test cases e.g. `mockDb.On("AddAndUpdateBudget", mock.Anything).Return(db.NewPaymentHistory{})`.
- Change the database parameter in `tHandler := NewTribeHandler(mockDb)` to `tHandler := NewTribeHandler(db.TestDb)`
- Create a new invoice using the db.TestDb.AddInvoice() function   e.g 
```sh
now := time.Now()
bountyAmount := 5000;
Invoice := db.NewInvoiceLis{
	PaymentRequest: ${DummyPayReq}
	Status: false,
	Type: "KEYSEND"
	OwnerPubkey: ${owner_pubkey}
	WorkspaceUuid: ${workspace_uuid},
        Created: &now,
}
db.TestDb.AddInvoice(invoice)
```
- Create a new invoice data using the db.TestDb.AddUserInvoiceData() function   e.g 
```sh
InvoiceData := db.UserInvoiceData{
	PaymentRequest: invoice.PaymentRequest,
        Amount: bountyAmount,
        UserPubkey: invoice.OwnerPubkey,
        Created: &now,
}
db.TestDb.AddUserInvoiceData(invoiceData)
```
- Create a new bounty using the db.TestDb.CreateOrEditBounty() function   e.g 
```sh
bounty := db.Bounty{
        OwnerId: ${owner_pubkey}
        Price:  bountyAmount,
        Created: &now,
        Type:          "coding",
	Title:         ${bountyTitle},
	Description:   ${bountyDescription},
	Assignee:    ${assigneePubkey},
	Show:          true,
        Paid: false,
}
db.TestDb.CreateOrEditBounty(bounty)
```
- Change the `authorizedCtx` value from `authorizedCtx := context.WithValue(ctx, auth.ContextKey, "valid-key")` to `authorizedCtx := context.WithValue(ctx, auth.ContextKey, invoice.OwnerPubkey)`
- Change the route payment request param to the invoice `PaymentRequest` e.g. `ro.Post("/poll/invoice/"+invoice.PaymentRequest, bHandler.PollInvoice)`
- After the request is successful, get the bounty by using the `db.TestDb.GetBountyByCreated(bounty.Created)` function, and get the invoice by using the invoice by using the `db.TestDB.GetInvoice(invoice.PaymentRequest)` function
- Assert that the bounty is Paid value is set to true 
- Assert that the Invoice Status value is set to true

### Assertions

- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] Do not delete any of the existing test cases on the `TestPollInvoice`
- [ ] All test cases after the `TestPollInvoice` refactor passes 
- [ ] The Refactoring of `TestPollInvoice` should not break existing test flows.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by elraphty** [comment]
@AbdulWahab3181

**Comment by MuhammadUmer44** [comment]
@elraphty assign me the next one?

**Comment by Shoaibdev7** [comment]
@elraphty Please assign me next issue??

**Comment by AbdulWahab3181** [comment]
@elraphty Could you please assign me?
