### ISSUE TITLE
Write Test For CreateWorkspaceUser

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1803]
### Context

Currently, we do not have a test for CreateWorkspaceUser
### Design

We want to write the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestCreateWorkspaceUser` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)

    oHandler := NewWorkspaceHandler(mockDb)` to `oHandler := NewWorkspaceHandler(db.TestDb)
```
The test will throw a dereference error if not connected to a DB.
- Create 2 persons using the  `db.TestDb.CreateOrPerson()` function e.g 
```sh
person := db.Person{
     Uuid:        ${uuid},
     OwnerAlias:  ${alias},
     UniqueName:  ${unique_name},
     OwnerPubKey:  ${pubkey},
     PriceToMeet: 0,
     Description:  ${description},
}

person2 := db.Person{
     Uuid:        ${uuid},
     OwnerAlias:  ${alias},
     UniqueName:  ${unique_name},
     OwnerPubKey:  ${pubkey},
     PriceToMeet: 0,
     Description:  ${description},
}
db.TestDb.CreateOrEditPerson(person)
db.TestDb.CreateOrEditPerson(person2)
```
- Create a  workspace by using the `db.TestDb.CreateOrEditWorkspace()` function e.g 
```sh
workspace := db.Workspace{
   Uuid:   ${workspace_uuid},
   Name:   ${workspace_name},
   OwnerPubKey:  ${person.OwnerPubkey},
   Github: ${gtihub},
   Website: ${website},
   Description: ${description},
}
db.TestDB.CreateOrEditWorkspace(workspace)
```
- Get the workspace created by using `workspace:=  db.TestDb.GetWorkspaceByUuid(workspace.Uuid)`
- Create a test route using `r.Post("/users/{uuid}", handlers.CreateWorkspaceUser)` as a reference, the test route should pass  `workspace.Uuid` as a parameter
- Create a test case to assert that when an unauthorized user hits the endpoint it returns a `401` error
- Create a test case to assert that when a wrong body data is sent to the endpoint it returns a `406` error
- Create a test case to assert that if a user is not the creator of the workspace or does not have an `ADD USER ROLE` it returns a `401` error 
- Create a test case to assert that when a user pubkey from the URL param does not match the pubkey from the JWT AUTH claims it returns a `401` error
- Create a test case to assert that a user cannot add themselves it should return  a `401` error
- Create a test case to assert that an existing user cannot be added to the workspace it returns a `401` error 
- Create a test to assert that when the right conditions are met a user can be added to a workspace.

### Assertions

- [ ] Assert that users are added to the workspace by using the `db.TestDB.GetWorkspaceUsers()` the length of the array returned should be the length of users added to the workspace.
- [ ] Assert that `person2` is added to the workspace using the  `db.TestDB.GetWorkspaceUser(person2.OwnerPubkey, workspace.UUID)`
- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by AbdulWahab3181** [comment]
@elraphty Could you please assign me?

**Comment by MahtabBukhari** [comment]
k

**Comment by MuhammadUmer44** [comment]
@elraphty assign me?
