### ISSUE TITLE
Write Test For GetUserDropdownWorkspaces

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1805]
### Context

Currently, we do not have a test for GetUserDropdownWorkspaces

### Design

We want to write the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestGetUserDropdownWorkspaces` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)

    oHandler := NewWorkspaceHandler(mockDb)` to `oHandler := NewWorkspaceHandler(db.TestDb)
```
The test will throw a dereference error if not connected to a DB.
- Create 2 persons using the  `db.TestDb.CreateOrPerson()` function e.g 
```sh
person := db.Person{
     Uuid:        ${uuid},
     OwnerAlias:  ${alias},
     UniqueName:  ${unique_name},
     OwnerPubKey:  ${pubkey},
     PriceToMeet: 0,
     Description:  ${description},
}

person2 := db.Person{
     Uuid:        ${uuid},
     OwnerAlias:  ${alias},
     UniqueName:  ${unique_name},
     OwnerPubKey:  ${pubkey},
     PriceToMeet: 0,
     Description:  ${description},
}
db.TestDb.CreateOrEditPerson(person)
db.TestDb.CreateOrEditPerson(person2)
```
- Create a  workspace by using the `db.TestDb.CreateOrEditWorkspace()` function e.g 
```sh
workspace := db.Workspace{
   Uuid:   ${workspace_uuid},
   Name:   ${workspace_name},
   OwnerPubKey:  ${person.OwnerPubkey},
   Github: ${gtihub},
   Website: ${website},
   Description: ${description},
}
db.TestDB.CreateOrEditWorkspace(workspace)
```
- Get the workspace created by using `workspace:=  db.TestDb.GetWorkspaceByUuid(workspace.Uuid)`
- Create a variable `roles` e.g
```sh
roles := []db.WorkspaceUserRoles{
	db.WorkspaceUserRoles{
		WorkspaceUuid: ${uuid},
		OwnerPubKey:  ${pubkey},
		Role:          "ADD BOUNTY",
	},
	db.WorkspaceUserRoles{
		WorkspaceUuid: ${uuid},
		OwnerPubKey:  ${pubkey},
		Role:          "UPDATE BOUNTY",
	},
	db.WorkspaceUserRoles{
		WorkspaceUuid: ${uuid},
		OwnerPubKey:  ${pubkey},
		Role:          "DELETE BOUNTY",
	},
	db.WorkspaceUserRoles{
		WorkspaceUuid: ${uuid},
		OwnerPubKey:  ${pubkey},
		Role:          "PAY BOUNTY",
	},
}
``` 
- Add the roles to `person2` using the `db.TestDb.CreateUserRoles(roles, workspace.Uuid, person2.OwnerPubkey)` function
- Get `person2` details by using the db function `dbPerson := db.TestDb.GetPersonByUuid(person2.Uuid)`
- Create a test route using `	r.Get("/user/dropdown/{userId}", workspaceHandlers.GetUserDropdownWorkspaces)` as a reference, the test route
- The `{userId}` parameter in the route should be `dbPerson.ID`

### Assertions

- [ ] Assert that the workspace created is returned from the GetUserDropdownWorkspaces API request
- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by AbdulWahab3181** [comment]
@elraphty Could you please assign me?

**Comment by elraphty** [comment]
@MuhammadUmer44

**Comment by MahtabBukhari** [comment]
n

**Comment by MuhammadUmer44** [comment]
n

**Comment by elraphty** [comment]
> @elraphty Could you please assign me?

@AbdulWahab3181 you have one already

**Comment by saithsab877** [comment]
@elraphty Please assign me next one?
