### ISSUE TITLE
Write Test For GetWorkspaceRepoByWorkspaceUuidAndRepoUuid

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1809]
### Context

Currently, we do not have a test for GetWorkspaceRepoByWorkspaceUuidAndRepoUuid

### Design

We want to write the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestGetWorkspaceRepoByWorkspaceUuidAndRepoUuid` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)

    oHandler := NewWorkspaceHandler(mockDb)` to `oHandler := NewWorkspaceHandler(db.TestDb)
```
The test will throw a dereference error if not connected to a DB.
- Create a person using the  `db.TestDb.CreateOrPerson()` function e.g 
```sh
person := db.Person{
     Uuid:        ${uuid},
     OwnerAlias:  ${alias},
     UniqueName:  ${unique_name},
     OwnerPubKey:  ${pubkey},
     PriceToMeet: 0,
     Description:  ${description},
}

db.TestDb.CreateOrEditPerson(person)
```
- Create a  workspace by using the `db.TestDb.CreateOrEditWorkspace()` function e.g 
```sh
workspace := db.Workspace{
   Uuid:   ${workspace_uuid},
   Name:   ${workspace_name},
   OwnerPubKey:  ${person.OwnerPubkey},
   Github: ${gtihub},
   Website: ${website},
   Description: ${description},
}
db.TestDB.CreateOrEditWorkspace(workspace)
```
- Get the workspace created by using `workspace:=  db.TestDb.GetWorkspaceByUuid(workspace.Uuid)`
- Create a workspace repository using the `db.TestDb.CreateOrEditWorkspaceRepository(workspaceRepositoru)`  e.g
```sh
repository := db.WorkspaceRepositories{
	Uuid: ${uuid}
	WorkspaceUuid: workspace.UUid,
	Name: ${name},          
	Url: ${url},         
}
db.TestDb.CreateOrEditWorkspaceRepository(repository)
``` 
- Create a test route using `r.Get("/{workspace_uuid}/repository/{uuid}", workspaceHandlers.GetWorkspaceRepoByWorkspaceUuidAndRepoUuid)` as a reference, the test route
- Pass the created workspace uuid and the created repository uuid as the URL  parameters
- Assert that it throws a `401` error if a user is not authorized
- Assert that the repository returned from the API matches the one created.

### Assertions

- [ ] Assert that the workspace repository returned from the API responses matches the one created
- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by AbdulWahab3181** [comment]
@elraphty Can I take this one as I have completed my previous task?

**Comment by saithsab877** [comment]
@elraphty assign me>

**Comment by elraphty** [comment]
@AbdulWahab3181 let me give this to @saithsab877, I have not reviewed yours. I will assign the first one to you tomorrow.
