### ISSUE TITLE
Write Test For CreateOrEditFeatures

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1819]
### Context

Currently, we do not have a test for CreateOrEditFeatures

### Design

We want to write the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestCreateOrEditFeatures` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)

    fHandler := NewFeatureHandler(db.TestDb)
```
The test will throw a dereference error if not connected to a DB.
- Create a person using the  `db.TestDb.CreateOrPerson()` function e.g 
```sh
person := db.Person{
     Uuid:        ${uuid},
     OwnerAlias:  ${alias},
     UniqueName:  ${unique_name},
     OwnerPubKey:  ${pubkey},
     PriceToMeet: 0,
     Description:  ${description},
}

db.TestDb.CreateOrEditPerson(person)
```
- Create a  workspace by using the `db.TestDb.CreateOrEditWorkspace()` function e.g 
```sh
workspace := db.Workspace{
   Uuid:   ${workspace_uuid},
   Name:   ${workspace_name},
   OwnerPubKey:  ${person.OwnerPubkey},
   Github: ${gtihub},
   Website: ${website},
   Description: ${description},
}
db.TestDB.CreateOrEditWorkspace(workspace)
```
- Get the workspace created by using `workspace:=  db.TestDb.GetWorkspaceByUuid(workspace.Uuid)`
- Create a variable `feature` e.g
```sh
feature := db.WorkspaceFeatures {
	Uuid: ${uuid}
	WorkspaceUuid: workspace.UUid,
	Name: ${name},          
	Url: ${url},
        Priority: 0,         
}
``` 
- Create a test route using `r.Post("/features", featureHandlers.CreateOrEditFeatures)` as a reference, the test route
- JSON marshal `features` and pass it as a body to the Endpoint
- Assert that it throws a `401` error if a user is not authenticated
- Assert that a `406` error is returned if the wrong body data is sent to the APi endpoint
- Assert that a `401` is returned if a Workspace UUID that does not exist Is passed to the API body
- Assert that the user can add a workspace feature when the right conditions are met.

### Assertions

- [ ] Assert that the workspace feature is created by using the `db.TestDb.GetFeatureByUuid(feature.uuid)` function
- [ ] Assert that the feature `Name, Prioty, and Url `  returned matches what was sent in the API body.
- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by AbdulWahab3181** [comment]
@elraphty Can I take this one or the next one as I have completed my previous task?

**Comment by elraphty** [comment]
@MirzaHanan

**Comment by MirzaHanan** [comment]
@elraphty Please assign me?

**Comment by aliraza556** [comment]
@elraphty Please assign me next one?

**Comment by AbdulWahab3181** [comment]
@

**Comment by elraphty** [comment]
> @elraphty Please assign me next one?

@aliraza556 You get the next one

**Comment by MahtabBukhari** [comment]
> > @elraphty Please assign me next one?
> 
> @aliraza556 You get the next one

@elraphty Could you please assign next one?
