### ISSUE TITLE
Write Test For DeleteFeature

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1820]
### Context

Currently, we do not have a test for DeleteFeature

### Design

We want to write the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestDeleteFeature` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)

    oHandler := NewWorkspaceHandler(mockDb)` to `oHandler := NewWorkspaceHandler(db.TestDb)
```
The test will throw a dereference error if not connected to a DB.
- Create a person using the  `db.TestDb.CreateOrPerson()` function e.g 
```sh
person := db.Person{
     Uuid:        ${uuid},
     OwnerAlias:  ${alias},
     UniqueName:  ${unique_name},
     OwnerPubKey:  ${pubkey},
     PriceToMeet: 0,
     Description:  ${description},
}

db.TestDb.CreateOrEditPerson(person)
```
- Create a  workspace by using the `db.TestDb.CreateOrEditWorkspace()` function e.g 
```sh
workspace := db.Workspace{
   Uuid:   ${workspace_uuid},
   Name:   ${workspace_name},
   OwnerPubKey:  ${person.OwnerPubkey},
   Github: ${gtihub},
   Website: ${website},
   Description: ${description},
}
db.TestDB.CreateOrEditWorkspace(workspace)
```
- Get the workspace created by using `workspace:=  db.TestDb.GetWorkspaceByUuid(workspace.Uuid)`
- Create a workspace feature using the `db.TestDb.CreateOrEditFeature(feature)` function e.g
```sh
feature := db.WorkspaceFeatures {
	Uuid: ${uuid}
	WorkspaceUuid: workspace.UUid,
	Name: ${name},          
	Url: ${url},
        Priority: 0,         
}
db.TestDb.CreateOrEditFeature(feature)
``` 
- Get the created feature using `db.TestDb.GetFeatureByUuid(feature_uuid)` function
- Assert that the feature was created
- Create a test route using `	r.Delete("features/{uuid}", featureHandlers.DeleteFeature)` as a reference, the test route
- `feature.Uuid` should be used as URL parameters for the route

### Assertions

- [ ] Assert that it throws a `401` error if a user is not authorized
- [ ] Assert that the feature is deleted after the Delete API request is successful using the `db.TestDb.GetFeatureByUuid(feature_uuid)`, the function should return an empty object.
- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by MahtabBukhari** [comment]
h

**Comment by elraphty** [comment]
@aliraza556

**Comment by aliraza556** [comment]
@elraphty assign ?

**Comment by saithsab877** [comment]
@elraphty Could you assign me!
