### ISSUE TITLE
Order Admin Workspaces List By Name

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1834]
### Context

Currently, the admin workspaces list is ordered by the workspace ID

### Design

We want to order the workspaces by name in alphabetical order.

### Acceptance Criteria

- [ ] I've tested on Chrome
- [ ] I've created a test that...
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example backend test](https://github.com/stakwork/sphinx-tribes/blob/f50a099d19f22cc533b947ce04eef6c6f459fa58/handlers/organization_test.go)

**Comment by MahtabBukhari** [comment]
g
