### ISSUE TITLE
Write Test For CreateOrEditStory

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1838]
### Context

Currently, we do not have a test for CreateOrEditStory
### Design

We want to write the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestCreateOrEditStory` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)

    fHandler := NewFeatureHandler(db.TestDb)
```
The test will throw a dereference error if not connected to a DB.
- Create a person using the  `db.TestDb.CreateOrPerson()` function e.g 
```sh
person := db.Person{
     Uuid:        ${uuid},
     OwnerAlias:  ${alias},
     UniqueName:  ${unique_name},
     OwnerPubKey:  ${pubkey},
     PriceToMeet: 0,
     Description:  ${description},
}

db.TestDb.CreateOrEditPerson(person)
```
- Create a  workspace by using the `db.TestDb.CreateOrEditWorkspace()` function e.g 
```sh
workspace := db.Workspace{
   Uuid:   ${workspace_uuid},
   Name:   ${workspace_name},
   OwnerPubKey:  ${person.OwnerPubkey},
   Github: ${gtihub},
   Website: ${website},
   Description: ${description},
}
db.TestDB.CreateOrEditWorkspace(workspace)
```
- Get the workspace created by using `workspace:=  db.TestDb.GetWorkspaceByUuid(workspace.Uuid)`
- Create a new feature using the `db.TestDB.CreateOrEditFeature()` function  e.g
```sh
feature := db.WorkspaceFeatures {
	Uuid: ${uuid}
	WorkspaceUuid: workspace.UUid,
	Name: ${name},          
	Url: ${url},
        Priority: 0,         
}
db.TestDB.CreateOrEditFeature(feature)
``` 
- Create a variable `featureStory` e.g
```sh
featureStory := db.FeatureStory {
	Uuid: ${uuid}
        FeatureUuid: feature.Uuid,
	Description: ${description},          
        Priority: 0,         
}
``` 
- Create a test route using `r.Post("features/story", featureHandlers.CreateOrEditStory)` as a reference, the test route
- JSON marshal `featureStory` and pass it as a body to the Endpoint
- Assert that it throws a `401` error if a user is not authenticated
- Assert that a `406` error is returned if the wrong body data is sent to the APi endpoint
- Assert that the user can add a feature phase when the right conditions are met.

### Assertions

- [ ] Assert that the feature story is created by using the `db.TestDb.GetFeatureStoryByUuid(featureStory.uuid)` function
- [ ] Assert that the feature story `Description, Priority, and FeatureUuid `  returned matches what was sent in the API body.
- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by AbdulWahab3181** [comment]
@elraphty Can I take this one as I have completed my previous task?

**Comment by saithsab877** [comment]
H

**Comment by MirzaHanan** [comment]
@elraphty Please assign me next one?

**Comment by elraphty** [comment]
> @elraphty Can I take this one as I have completed my previous task?

I have not reviewed it  yet, and @saithsab877 was to have this one.
