### ISSUE TITLE
Refactor Test For TestMakeBountyPayment To Use A Real Postgres DB For The Test

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#1855]
### Context

Currently, we test the `TestMakeBountyPayment` with a mock database.

### Design

We want to refactor the tests to use a real Postgres DB spun up on docker, follow the instructions in the `Unit Testing` section of [README.md](https://github.com/stakwork/sphinx-tribes/blob/d942e6ce53719b429ee64d2ddb72599278e05eba/README.md?plain=1#L106C4-L123C4) to run spin up a database in docker, and change the `test_config.go` configuration.

After spinning up the Postgres DB container:

- Add this line of code on the first line and second of the test function `TestMakeBountyPayment` to connect to the Test DB 
```sh
    teardownSuite := SetupSuite(t)
    defer teardownSuite(t)
```
The test will throw a dereference error if not connected to a DB.
- Remove all mock database functions in the `TTestPollInvoice` test cases e.g. `	mockDb.On("ProcessBountyPayment", mock.AnythingOfType("db.NewPaymentHistory"), mock.AnythingOfType("db.NewBounty")).Return(nil)`.
- Change the database parameter in `bHandler := NewBountyHandler(mockHttpClient, mockDb)` to `bHandler := NewBountyHandler(mockHttpClient, db.TestDb)`
- Create a person using the  `db.TestDb.CreateOrPerson()` function e.g 
```sh
person := db.Person{
     Uuid:        ${uuid},
     OwnerAlias:  ${alias},
     UniqueName:  ${unique_name},
     OwnerPubKey:  ${pubkey},
     PriceToMeet: 0,
     Description:  ${description},
}

db.TestDb.CreateOrEditPerson(person)
```
- Create a  workspace by using the `db.TestDb.CreateOrEditWorkspace()` function e.g 
```sh
workspace := db.Workspace{
   Uuid:   ${workspace_uuid},
   Name:   ${workspace_name},
   OwnerPubKey:  ${person.OwnerPubkey},
   Github: ${gtihub},
   Website: ${website},
   Description: ${description},
}
db.TestDB.CreateOrEditWorkspace(workspace)
```
- Get the workspace created by using `workspace:=  db.TestDb.GetWorkspaceByUuid(workspace.Uuid)`
- Add Workspace budget linked to the workspace with the `db.TestDB.CreateWorkspaceBudget()` function e.g
```sh
budgetAmount := 5000;
bounty := db.NewBountyBudget{
    WorkspaceUuid: workspace.Uuid,
    TotalBudget: budgetAmount
}
db.TestDB.CreateWorkspaceBudget((bounty)
```
- Create a new bounty using the db.TestDb.CreateOrEditBounty() function   e.g 
```sh
bountyAmount := 3000
bounty := db.Bounty{
        OwnerId: ${owner_pubkey}
        Price:  bountyAmount,
        Created: &now,
        Type:          "coding",
	Title:         ${bountyTitle},
	Description:   ${bountyDescription},
	Assignee:    ${assigneePubkey},
	Show:          true,
        WorkspaceUuid: workspace.Uuid,
        Paid: false,
        Created: &now,
}
db.TestDb.CreateOrEditBounty(bounty)
```
- Get the bounty created by using the `dbBounty := db.TestDb.GetBountyDataByCreated(bounty.Created)` function
- Change the `authorizedCtx` value from `authorizedCtx := context.WithValue(ctx, auth.ContextKey, "valid-key")` to `authorizedCtx := context.WithValue(ctx, auth.ContextKey, person.OwnerPubkey)`
- Change the route payment request param to the bounty  `Id` e.g. `r.Post("gobounties/pay/{dbBounty.ID}", bountyHandler.MakeBountyPayment)`
- After the request is successful, get the bounty by using the `db.TestDb.GetBountyByCreated(bounty.Created)` function
- Get the workspace budget by using the `db.TestDb.GetWorkspaceBudget(workspace.Uuid)` function
- Assert that the bounty is Paid value is set to true 
- Assert that the bounty amount is deducted from the Workspace budget

### Assertions

- [ ] Assert that all the test passes

### Acceptance Criteria

- [ ] Do not delete any of the existing test cases on the `TestMakeBountyPayment`
- [ ] All test cases after the `TestMakeBountyPayment` refactor passes 
- [ ] The Refactoring of `TestMakeBountyPayment` should not break existing test flows.
- [ ] I have rebased and tested locally before submitting my PR
- [ ] I can submit a PR within 1 day of taking the bounty

Here is an [example Real DB Test](https://github.com/stakwork/sphinx-tribes/blob/e7419f99eff616a5a2ee4daefa12c2a5e5dde930/handlers/bounty_test.go#L455C1-L488C1)

**Comment by elraphty** [comment]
@AbdulWahab3181

**Comment by aliraza556** [comment]
m

**Comment by saithsab877** [comment]
@elraphty Could you assign me next one?

**Comment by MirzaHanan** [comment]
@elraphty Assign me?

**Comment by aliraza556** [comment]
@elraphty Please assign me

**Comment by AbdulWahab3181** [comment]
@elraphty Could you please assign me?

**Comment by aliraza556** [comment]
> @elraphty Please assign me next one?

Thanks

**Comment by AhsanFarooqDev** [comment]
@elraphty Please assign next to next one please?

**Comment by saithsab877** [comment]
@elraphty Could you please assign me?
