### ISSUE TITLE
More visibility states for the Payment History

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-tribes#1904]
**Task**

<img width="1240" alt="image" src="https://github.com/user-attachments/assets/37ab80b4-5fab-4c9c-868c-2c6525381ecf">

**Comment by Evanfeenstra** [comment]
@elraphty in this https://github.com/stakwork/sphinx-tribes/issues/1901 you say that the payment is traked and if SUCCESS is reached then it updates. But we also need to check for FAILED

First in the bounty modal itself

then in the payment list (image above)
