### ISSUE TITLE
Implement `Pending` filter

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-tribes#1907]
**Task**

Now we have async payments, it would be great to filter by pending at the workspace level:

<img width="376" alt="image" src="https://github.com/user-attachments/assets/3cfa3db0-c8dc-494d-9d89-5c6d82c4ad44">

**Comment by MuhammadUmer44** [comment]
N

**Comment by MahtabBukhari** [comment]
@tomsmith8 Is it available for work?

**Comment by tomsmith8** [comment]
@MahtabBukhari i'm submitting a feature request. This will need to be spec'd out :)
