### ISSUE TITLE
Unable to login to staging with v2 pubkey

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-tribes#1909]
**Issue**

I am trying to sign in to `https://people-test.sphinx.chat/bounties` with my v2 pubkey.

After successful login, it immediately logs me straight back out.

Steps to recreate:
- Open `https://people-test.sphinx.chat/bounties`
- Login with v2
- Successfully login
- 3s later it logs me out

**Acceptance Criteria**

 - [ ] Ability to login with Sphinx v2 Pubkey

**Comment by humansinstitute** [comment]
Ali Raza reported an issue here and recorded the following: https://www.loom.com/share/f4559fc022b7429591e5d1867f46ebca

**Comment by aliraza556** [comment]
Hi @elraphty, @tomsmith8 , @humansinstitute 

The login issue is still not fixed on the staging side. Please review the details here:

https://www.loom.com/share/784e68bc689f4659abab9c4607d44dd9

**Comment by tomsmith8** [comment]
@elraphty Can you take a look please

**Comment by tomsmith8** [comment]
This is

**Comment by tomsmith8** [comment]
Reopening closed ticket due to not being fixed across all clients

**Comment by tomastiminskas** [comment]
@tomsmith8 just released an internal testing version with auth fixed to work with testing server. Will move to production as soon as it's approved

**Comment by humansinstitute** [comment]
Did this get deployed?

**Comment by elraphty** [comment]
> Did this get deployed?

Yeah, it's working now
