### ISSUE TITLE
Ticket box borders and shadow 

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#191]
Normal ticket should have no border, 
just box-shadow, with values same as on the image below.

Paid ticket should have no box shadow, 
just 1 px border, with border color #DDE1E5 

![image](https://user-images.githubusercontent.com/13258550/160643221-b7087c4f-0e97-4914-b384-a8b6825e9063.png)

**Comment by plell** [comment]
fixed this in the next deploy
