### ISSUE TITLE
Job tickets - Mobile view

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#192]
Here are 2 small layout fixes for mobile view.
1- Move price below "Open" label.
2- Tickets should be divided with one 2 px border, color #EBEDEF (right now we have a margin and drop shadow that is not needed on mobile)

Figma prototype
https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/People.Sphinx?node-id=2006%3A9342

![image](https://user-images.githubusercontent.com/13258550/160668336-f9e983af-b8db-41da-bf0e-ce2f081cda8f.png)

**Comment by plell** [comment]
fixed this in the next deploy
