### ISSUE TITLE
New database table and schema for wf_requests

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#1925]
## Context
As part of implementing the common Stakwork workflow infrastructure, we need a database table to track all workflow requests and their statuses. This table will serve as the central record for monitoring workflow progress and maintaining request history.

- **Problem**: Currently, there is no dedicated storage for tracking workflow requests and their statuses, which makes it difficult to monitor and manage workflow processes effectively.
- **Need**: A new database table, `wf_requests`, is required to log all submitted and received requests, including their statuses, to facilitate better tracking and management.
- **Fit**: This table will serve as the foundational data structure for the workflow management system, supporting subsequent features like request handling and response processing.
- **Background**: This is the first step in implementing the Stakwork Common Workflow Plumbing feature, which aims to streamline workflow request and response handling.

This is related to a broader project defined here:
For context see: https://github.com/stakwork/sphinx-tribes/issues/1922

System Schematic:
![image](https://github.com/user-attachments/assets/403436a7-9383-43a3-aacf-292d6c31de66)

## Design
- **Table Name**: `wf_requests`
- **Columns**:
  - `id` (Primary Key, Integer, Auto-increment): Unique identifier for each request.
  - `request_id` (String, Unique): Identifier for the request, provided by the client.
  - `status` (String): Current status of the request (e.g., 'pending', 'completed', 'failed').
  - `created_at` (Timestamp): Timestamp of when the request was created.
  - `updated_at` (Timestamp): Timestamp of the last update to the request.
  - `request_data` (JSON): Raw data of the request.
  - `response_data` (JSON, Nullable): Raw data of the response, if available.

- **Indexes**:
  - Index on `request_id` for quick lookup.
  - Index on `status` to facilitate status-based queries.

- **Constraints**:
  - Ensure `request_id` is unique to prevent duplicate entries.

## Assignment Criteria
- **Required Knowledge/Skills**:
  - Proficiency in SQL and database design.
  - Familiarity with the existing database schema and conventions.
- **Communication**:
  - Use Sphinx V2 for all communications.
  - Ensure you are live on Sphinx V2 for real-time updates and discussions.

## Acceptance Criteria
- [ ] A new table `wf_requests` is created in the database with the specified columns and data types.
- [ ] The table includes indexes on `request_id` and `status`.
- [ ] The `request_id` column is unique.
- [ ] The table supports CRUD operations for workflow requests.
- [ ] Documentation is updated to reflect the new table structure.
- [ ] Unit tests are written to verify the integrity and functionality of the table.
- [ ] Performance tests ensure that the table can handle expected load without significant latency.

**Comment by aliraza556** [comment]
@humansinstitute Please assign me
