### ISSUE TITLE
new endpoint /workflows/action

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#1928]
## Context
Develop a new endpoint '/workflows/action' to process the action object, which is a union of request and response objects, and trigger the next steps in the workflow.

The `/workflows/action` endpoint is a critical component of the Stakwork Common Workflow Plumbing feature. It is designed to process an "action" object, which is a union of request and response objects. This endpoint will trigger the subsequent steps in the workflow, ensuring that the system can handle complex interactions between requests and responses efficiently. 

This is related to a broader project defined here:
For context see: https://github.com/stakwork/sphinx-tribes/issues/1922

## System Schematic:
![image](https://github.com/user-attachments/assets/403436a7-9383-43a3-aacf-292d6c31de66)

## Design
- **Endpoint URL**: `/workflows/action`
- **HTTP Method**: POST
- **Request Body**: The request will contain an "action" object, which includes both request and response data.
- Example:

```json
{
    "source": "string",
    "requestUUID": "string",
    "action": "string"
    "workflowID": interger,
    "requestData": { object },
    "responseData": { object }
}
```

- **Response**: The endpoint will return a status indicating the success or failure of processing the action.
  - Example:
    ```json
    {
      "status": "success",
      "message": "Action processed successfully."
    }
    ```

**Logic**:
1. Validate the incoming action object to ensure it contains required data
2. Log the action object for auditing and tracking purposes.
3. Process the action by:
    i. updating the workflow request state in wf_requests
    ii. trigger the next action based on the action "string".
    iii. If there is no defined action then log "no action taken" and exit
4. Return a response indicating the outcome of the processing.

Note the action string will need to map to a next function to take.

## Assignment Criteria
- Familiarity with RESTful API design and implementation.
- Experience with JSON data structures and validation.
- Communication via Sphinx V2 is required; ensure you are live on Sphinx V2.

## Acceptance Criteria
- [ ] The endpoint must accept a POST request at `/workflows/action`.
- [ ] The request body must include a valid action object with both request and response data.
- [ ] The endpoint must validate the action object and log it appropriately.
- [ ] The workflow state must be updated based on the action data.
- [ ] Any subsequent workflow steps must be triggered as necessary.
- [ ] The endpoint must return a JSON response indicating success or failure.
- [ ] The implementation must include unit tests covering both positive and negative cases.
- [ ] The endpoint must handle errors gracefully and log them for further analysis.

**Comment by saithsab877** [comment]
@humansinstitute Please assign?

**Comment by MuhammadUmer44** [comment]
@humansinstitute I can help?

**Comment by humansinstitute** [comment]
Given definition expansion of https://github.com/stakwork/sphinx-tribes/issues/1926 & https://github.com/stakwork/sphinx-tribes/issues/1927

This is no longer requied as it will already be implemented in the handlers and util functions.
