### ISSUE TITLE
Mapping of "action" string to next function

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#1931]
## Context
After receiving responses from Stakwork workflows, the system needs to execute different actions based on the workflow type and response. We need a flexible, maintainable system to map workflow responses to their corresponding handler functions.

## Design

@tobi-bams can you map out a design for this. 

e.g:

Action Registry - defines all actions strings that map to default to "log and exit"
Action Context - typed objects for 
Action Handlers - e.g. update user stories, output ticket plan, log and exit

e.g. context 
```
type ActionContext struct {
    RequestUUID  string    // A unique ID for this request
    WorkflowID   string    // Which workflow it came from
    Source       string    // Where it came from
    ActionString string    // What needs to be done
    ResponseData []byte    // The actual data to process
}
```

## Assignment Criteria
- Strong understanding of Go interfaces and dependency injection
- Experience with concurrent operations in Go
- Connected on Sphinx V2

## Acceptance Criteria
- [ ] Implement ActionHandler interface
- [ ] Create ActionRegistry with thread-safe operations
- [ ] Implement example handlers for:
  - [ ] User story generation
  - [ ] Ticket planning
  - [ ] (Other workflow types as needed)
- [ ] Add comprehensive unit tests for registry and handlers
- [ ] Add integration tests for the complete workflow
- [ ] Implement error handling and logging
- [ ] Document handler registration process
- [ ] Create examples for adding new handlers

## Usage Example
To add a new workflow action:

1. Define a new handler:
```go
type NewFeatureHandler struct {
    db     *sqlx.DB
    logger *zap.Logger
}

func (h *NewFeatureHandler) Handle(ctx context.Context, actionCtx ActionContext) error {
    // Implementation
    return nil
}

func (h *NewFeatureHandler) ValidateInput(actionCtx ActionContext) error {
    // Validation
    return nil
}
```

2. Register the handler:
```go
registry.Register("new_feature_workflow", &NewFeatureHandler{db: db, logger: logger})
```

3. Use in workflow:
```go
// In your workflow response
{
    "action_string": "new_feature_workflow",
    "request_uuid": "...",
    "response_data": {...}
}
```

**Comment by Shoaibdev7** [comment]
.

**Comment by MahtabBukhari** [comment]
@humansinstitute Could you please assign me?

**Comment by humansinstitute** [comment]
Now defunct with https://github.com/stakwork/sphinx-tribes/issues/1926 & https://github.com/stakwork/sphinx-tribes/issues/1927
