### ISSUE TITLE
Add Workflow Response Route

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#1941]
## Context
Implement endpoint to handle incoming workflow responses from Stakwork.

### Technical Implementation

```go
// routes/workflow_routes.go
func SetupWorkflowRoutes(r *gin.Engine) {
    // Add to existing workflow routes
    workflows.POST("/response", handlers.HandleWorkflowResponse)
}

// Test route registration and basic connectivity
func TestWorkflowResponseRoute(t *testing.T) {
    // Test cases for route availability
}
```

### Acceptance Criteria

- [ ] Route correctly maps POST requests to /workflows/response
- [ ] Returns appropriate status codes for various scenarios
- [ ] Documentation updated to include new endpoint
- [ ] Tests verify endpoint availability

### Dependencies

None (extends existing routes)

**Comment by humansinstitute** [comment]
This ticket is a breakdown of work for @MuhammadUmer44

**Comment by MuhammadUmer44** [comment]
@humansinstitute Please assign me?

**Comment by humansinstitute** [comment]
@MuhammadUmer44 - any progress?

**Comment by MuhammadUmer44** [comment]
Hi @humansinstitute, I'm on it. I am wait until this PR https://github.com/stakwork/sphinx-tribes/pull/1949 is merged. Once it's done, I'll create my own PR, as the necessary files are already being created in this one, which I will utilize.

**Comment by humansinstitute** [comment]
Just merged

**Comment by MuhammadUmer44** [comment]
@humansinstitute, please release the payment for the task: 
https://community.sphinx.chat/p/csfohrqtu2rulqj5lfe0/assigned/2764/24
