### ISSUE TITLE
Create Response Processing Utils

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#1943]
### Context
Implement utility functions for response processing, including action object creation and processing lookup.

See context video: https://www.loom.com/share/06e63a7777ef4e76ae05b156586e731e?sid=722510a4-765f-465e-96e2-260dccb20f10

### Technical Implementation

Example

```go
// utils/workflow_response.go
func ProcessWorkflowResponse(response *models.WorkflowResponse) (*models.Action, error) {
    // Load original request
    request, err := db.GetWorkflowRequest(response.RequestUUID)
    if err != nil {
        return nil, fmt.Errorf("failed to load request: %w", err)
    }

    // Create action object
    action := &models.Action{
        Source:       request.Source,
        RequestUUID:  response.RequestUUID,
        Action:      response.Action,
        WorkflowID:  request.WorkflowID,
        RequestData: request.Payload,
        ResponseData: response.Payload,
    }

    // Look up processing requirements
    proc, err := db.LookupProcessor("action", action.Action)
    if err != nil {
        return nil, err
    }

    // Process if required
    if proc != nil && proc.RequiresProcessing {
        if err := processActionWithHandler(action, proc); err != nil {
            return nil, err
        }
    }

    return action, nil
}
```

## Acceptance Criteria

- [ ] Successfully creates action objects
- [ ] Handles processing lookup
- [ ] Proper error handling
- [ ] Test coverage for processing scenarios

**Comment by humansinstitute** [comment]
This ticket is a further breakdown of work for @MuhammadUmer44

**Comment by MuhammadUmer44** [comment]
@humansinstitute Please assign me?

**Comment by MuhammadUmer44** [comment]
@humansinstitute, please release the payment for the task:

https://community.sphinx.chat/p/csfohrqtu2rulqj5lfe0/assigned/2766/22
