### ISSUE TITLE
Endpoint to receive formData and post to Stakwork at /features/brief/send

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#1959]
Generate an endpoint on Sphinx Tribes Server that at  /features/brief/send

1. This endpoint will receive data from the front end app as specified on: https://github.com/stakwork/sphinx-tribes-frontend/issues/651
2. Make a post to Stakwork.

The end point will receive the formData from Feature Brief Modal in the following format:

```
{ "postData" :
    {
        "audioLink": "FROM FORM",
        "featureUUID": "FROM PREVIOUS PAGE",
        "source": "featureBrief",
        "examples":["Array of example feature briefs"]
    }
}
```

The following CURL statement provides details. 

Please note that the API key is not valid. 

```
curl --location 'https://api.stakwork.com/api/v1/projects' \
--header 'Authorization: Token token="aaaaaaahhhhhnoooooo"' \
--header 'Content-Type: application/json' \
--data '{"name":"string","workflow_id":36928,"workflow_params":{"set_var":{"attributes":{"vars": $postData }}}}'
```

NOTE the authorization token is defined in the env variables as `SWWFKEY` as per: https://github.com/stakwork/sphinx-tribes-frontend/issues/608

Where postData example is: 

{
    "audioLink": "https://stakwork-uploads-dev.s3.us-east-1.amazonaws.com/admin_customers/admin/HiveAutomationProcess-AudioDataWorkflow.m4a",
    "featureUUID":"1111-2222-3333-4444",
    "examples": ["Hive Process integrates Stakwork Workflows and LLM based automation into the Hive Development Process. This will reduce workload on Product Managers by streamlining creative tasks and automating the drafting of product artefacts and audit tasks. \nIn this feature we will automate the production of User Stories and Requirements from a Product Brief and Feature Brief. \nThis will leverage a Stakwork workflow which will take the following steps:\n1. Load the product context and specific feature context. \n2. Generate a series of user stories in the workflow as a JSON object. \n3. Iterate through the user stories and score them for relevance against the product and feature context. \n4. Filter out low relevance scores\n5. Return the information to a form in the Hive Process for human review and acceptance."]
}

Note the webhook URL should be domain specific for the deployment, needs to include https:// and need to be set by the tribes server, it won't be passed in postdata.

- STAGING: "webhook_url": "https://people-test.sphinx.chat/features/brief",
- PROD: "webhook_url": "https://community.sphinx.chat/features/brief",

**Comment by aliraza556** [comment]
H

**Comment by Shoaibdev7** [comment]
@humansinstitute, I can help?
