### ISSUE TITLE
Build endpoint /features/brief and write feature brief to DB

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#1961]
## Context

For context this is the flow for the Feature Brief Generation:
![image](https://github.com/user-attachments/assets/87c71433-3dfa-4e01-9b3e-0d011f17dc98)

## Design

1. Create a new webhook at /features/brief
2. Add middleware logic to unpack the data object.
3. Retrieve current feature brief
4. Merge and Update Feature Brief
5. Update on page load

### 1. Create a new webhook

Create a webhook in `sphinx-tribes/routes/features.go` that will receive data from the Stakwork API at proposed route  `features/brief")`

This would be:
```
https://community.sphinx.chat/features/brief
or
https://people-test.sphinx.chat/features/brief
```

### 2. Add logic to unpack the data object.
Output from Stakwork workflow will be in the following format. 
We should verify that the featureUUID is correct and present in the database. 

```
{
  "output": {
    "featureBrief":"Long string to be added into the Feature Brief.",
    "audioLink": "URL can be discarded",
    "featureUUID": "1111-2222-3333-4444"
}
```

We will need to consolidate the Feature Brief update with the existing Data in Feature Brief. 

### 3. Retrieve current feature brief
- Pull the current feature brief using https://github.com/stakwork/sphinx-tribes/blob/master/routes/features.go#L23 and 
- route `r.Get("/{uuid}", featureHandlers.GetFeatureByUuid)`
- e.g. store as ${prevFeatureBrief}

### 4. Update Feature brief
- If the feature brief has an existing Feature Brief this should be merged with the new feature brief provided as follows: 
- `${prevFeatureBrief}\n\n* Generated Feature Brief *\n\n${featureBrief}`
- The feature brief should be updated with `r.Post("/", featureHandlers.CreateOrEditFeatures)` in https://github.com/stakwork/sphinx-tribes/blob/master/routes/features.go#L23

Note only the Feature Brief is being updated here is an example: 

![image](https://github.com/user-attachments/assets/efb25d07-0218-4809-b82a-8700e5d1d6e8)

### 5. Test by refreshing the feature page.
On reload of the feature site page the new brief should be visible

## Assignment Criteria
Before requesting assignment:
- Experience with webhook implementation required
- Familiarity with Stakwork Workflow integration
- Access to sphinx-tribes repository
- Migrated to Sphinx V2 application
- Connect with Pete on Sphinx Community (https://community.sphinx.chat/p/cs7n8c2tu2rivj8gup0g)

## Acceptance Criteria
Webhook Implementation:
- [ ] Create webhook endpoint at `/features/brief`
- [ ] Manual triggering of webhook via postman with test data
- [ ] Implement JSON payload parsing and validation
- [ ] Add error handling for malformed requests
- [ ] Add logging for webhook receipt and processing
- [ ] Store received data in database as new user stories

Testing:
- [ ] Create web hook test with payload validation and data processing
- [ ] Record video demonstration of:
    - [ ] Web hook receiving data
    - [ ] Refresh of feature page updates user stories on this feature

**Comment by MahtabBukhari** [comment]
f

**Comment by MuhammadUmer44** [comment]
@humansinstitute Please assign me
