### ISSUE TITLE
[Bug] Ticket creation on 'ticket editor' component load failing

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2005]
- Load new phase planner page. 
- Add ticket component
- Ticket component should load a new ticketUUID and upsert to DB via endpoint
   - fails.

<img width="1444" alt="image" src="https://github.com/user-attachments/assets/837d711a-929d-44a2-91cb-e97f93e7dd50">

```
main.ts:3668 
        
        
       POST https://people-test.sphinx.chat/bounty/ticket/27457134-4d10-469f-baab-49f492c4009a 405 (Method Not Allowed)
createUpdateTicket @ main.ts:3668
qe @ action.ts:70
createUpdateTicket @ action.ts:50
```

**Comment by saithsab877** [comment]
H

**Comment by MuhammadUmer44** [comment]
@humansinstitute Please assign me

**Comment by MahtabBukhari** [comment]
c

**Comment by aliraza556** [comment]
@humansinstitute Please assign me
