### ISSUE TITLE
[Bug] Ticket update failing on submission

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2006]
Post to /bounty/ticket/UUID not allow 

```
main.ts:3668 
        
        
       POST https://people-test.sphinx.chat/bounty/ticket/105a144a-cf9e-48bb-9e8c-28411aff322c 405 (Method Not Allowed)
createUpdateTicket @ main.ts:3668
qe @ action.ts:70
createUpdateTicket @ action.ts:50
onClick @ TicketEditor.tsx:40
```

<img width="702" alt="image" src="https://github.com/user-attachments/assets/c5aa9572-76a9-477c-85ab-138639ec6436">

<img width="1460" alt="image" src="https://github.com/user-attachments/assets/a30f5481-20cf-4e68-a425-cf54a9f0e00b">

**Comment by saithsab877** [comment]
E

**Comment by MahtabBukhari** [comment]
s

**Comment by MuhammadUmer44** [comment]
@humansinstitute Please assign me

**Comment by aliraza556** [comment]
@humansinstitute Please assign me

**Comment by humansinstitute** [comment]
Still open on testing - can't confirm on staging.
