### ISSUE TITLE
Replace PAT for github projects

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#2012]
**Describe the bug**
Hi!

My PAT is currently used to auto-add items from this repo and/or the front-end repo. It is set to expire 1/25/25. I recommend replacing it to prevent a disruption in service.

**Comment by tomsmith8** [comment]
@ecurrencyhodler hey 👋 thanks man. I'll get this looked into :)

**Comment by ecurrencyhodler** [comment]
Awesome! Np.
