### ISSUE TITLE
[BUG] Can't post to `bounty/ticket/review/send`

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2014]
<img width="897" alt="Screenshot 2024-12-01 at 6 44 49 pm" src="https://github.com/user-attachments/assets/7649ac50-5401-427f-93ca-2a771a39f16a">

We are having similar issues with 405 errors on the submission of data to `bounty/ticket/review/send` so that a ticket can be submitted for workflow.

**Comment by MahtabBukhari** [comment]
@humansinstitute assign me?
