### ISSUE TITLE
[BUG] Stakwork Webhook Updates to resolve conflict

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2017]
To resolve the routing conflicts experiend here: https://github.com/stakwork/sphinx-tribes-frontend/issues/677

We will also need to update the webhook and message posted to Stakwork Workflow. from Tickets: 

- [ ] The endpoint -> https://github.com/stakwork/sphinx-tribes/issues/1985
- [ ] The handler function -> https://github.com/stakwork/sphinx-tribes/issues/1986

### Endpoint
- Update the ticket send endpoint from /bounty/ticket/review/send
- To:  /bounties/ticket/review/send

### Handler Function
Update the webhook_url in the POST message to stakwork from 

In current code update the current code:
```
host := os.Getenv("HOST")
	if host == "" {
		http.Error(w, "HOST environment variable not set", http.StatusInternalServerError)
		return
	}

	webhookURL := fmt.Sprintf("%s/bounty/ticket/review/", host)

	stakworkPayload := map[string]interface{}{
		"name":        "Hive Ticket Builder",
		"workflow_id": 37324,
		"workflow_params": map[string]interface{}{
			"set_var": map[string]interface{}{
				"attributes": map[string]interface{}{
					"vars": map[string]interface{}{
						"featureUUID":       ticket.FeatureUUID,
						"phaseUUID":         ticket.PhaseUUID,
						"ticketUUID":        ticket.UUID.String(),
						"ticketName":        ticket.Name,
						"ticketDescription": ticket.Description,
						"productBrief":      productBrief,
						"featureBrief":      featureBrief,
						"examples":          "",
						"webhook_url":       webhookURL,
					},
				},
			},
		},
	}
```

- To change `webhookURL := fmt.Sprintf("%s/bounty/ticket/review/", host)`
- To: `webhookURL := fmt.Sprintf("%s/bounties/ticket/review/", host)`

Change Two:

**Comment by aliraza556** [comment]
@humansinstitute please assign me?

**Comment by MahtabBukhari** [comment]
@humansinstitute assign?

**Comment by humansinstitute** [comment]
Including the change to the payload of the request to Stakwork to update the return webhook url?

**Comment by humansinstitute** [comment]
Confirmed with Tobi

**Comment by MahtabBukhari** [comment]
> Confirmed with Tobi

@humansinstitute means it fine now?

**Comment by humansinstitute** [comment]
@MahtabBukhari - we need to remove the trailing slash on the 

1. File" https://github.com/stakwork/sphinx-tribes/blob/master/handlers/ticket.go#L260
2. Line 260 - remove trailing slash on webhook URL `webhookURL := fmt.Sprintf("%s/bounties/ticket/review/", host)`
3. Should be: `webhookURL := fmt.Sprintf("%s/bounties/ticket/review", host)`
