### ISSUE TITLE
Donate widget improvement

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#202]
Current donate widget on peoples page is missing clear "One time payment" option that was originally planned.
Right now, it is not clear how user can make one time payment, 
except setting "Make 1 payments", which i don;t think is clear enough.

![image](https://user-images.githubusercontent.com/13258550/162433493-3ebbe4e3-90d9-4402-b6dc-38ba62c2a930.png)

I suggest we bring back "One time payment" option, and polish the layout a bit.

![image](https://user-images.githubusercontent.com/13258550/162433672-7381df69-f928-4d74-bbde-364e2a1494bd.png)

**Comment by ecurrencyhodler** [comment]
I'm going to close this issue for now. Let me know if you want to re-open. We can validate whether or not this is necessary with some user interviews.
