### ISSUE TITLE
[BUG] Remove newUUID line on updating tickets in the DB

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2022]
Line 35 in db/tickets.go is incorrect. 

This function will be provided with a ticketUUID already. This line causes an override and mismatch of the Ticket ID.

![image](https://github.com/user-attachments/assets/5d365844-1ecf-4c2c-ba77-a0643878ae23)

This will need to be update to the logic:

Only create a new ticket.UUID where ticket.uuid is false. 

Otherwise the function should carry on. Note this function should not be reachable without providing a ticketUUID to the route / handler.

## Outcome
The ticket update function will correctly handle UUIDs, preventing unnecessary overrides and ensuring that ticket IDs remain consistent and accurate.

## Design
- **Logic Update:**
  - Check if `ticket.uuid` is present before generating a new UUID.
  - Ensure the function logic flows correctly with the presence of a `ticketUUID`.
- **State Changes:**
  - Maintain the original `ticket.UUID` if provided.
- **Testing:**
  - Verify that the function behaves correctly with and without a `ticketUUID`.

## Example Code
```go
// Example modification in db/tickets.go
func UpdateTicket(ticket Ticket) error {
    if ticket.UUID == "" {
        ticket.UUID = generateNewUUID() // Only generate if UUID is not provided
    }
    // Continue with update logic
    // ...
    return nil
}
```

## Acceptance Criteria
- [ ] The function does not generate a new UUID if `ticket.uuid` is provided.
- [ ] The function correctly updates tickets with the provided `ticketUUID`.
- [ ] No data integrity issues arise from the update process.
- [ ] Code review and testing confirm the fix is correctly implemented.

**Comment by saithsab877** [comment]
H

**Comment by MuhammadUmer44** [comment]
G

**Comment by MahtabBukhari** [comment]
@humansinstitute assign?

**Comment by aliraza556** [comment]
@humansinstitute Please assign me?
