### ISSUE TITLE
[BUG] Webhook Auth Check

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2024]
In `handlers/ticket.go` the function `ProcessTicketReview` performs na auth check on the response from Stakwork at `/boutnies/ticket/review`

I believe this will cause a failure, and is off spec. 

Please check and remove if required. 

```
pubKeyFromAuth, _ := ctx.Value(auth.ContextKey).(string)

	if pubKeyFromAuth == "" {
		fmt.Println("[ticket] no pubkey from auth")
		w.WriteHeader(http.StatusUnauthorized)
		json.NewEncoder(w).Encode(map[string]string{"error": "Unauthorized"})
		return
	}
```

**Comment by saithsab877** [comment]
H

**Comment by MahtabBukhari** [comment]
@humansinstitute assign?
