### ISSUE TITLE
[BUG] Route Conflict on Get Tickets for Phase

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2026]
Related to: https://github.com/stakwork/sphinx-tribes/issues/1982

- On page load a GET request is sent to: `/features/uuid/phase/uuid/tickets` to retrieve tickets for this phase.
- /features/ is a reserved route for front end rendering so we get a generic website back in the response!
- We need to update to route to : GET `/bounties/tickets/feature/uuid/phase/uuid/`

![image](https://github.com/user-attachments/assets/65ed5ab1-5c43-4147-82d5-200ff95c4a86)

## Changes required

- [x] Remove line 42 in routes/feature.go
   remove this from feature.go:
   `r.Get("/{feature_uuid}/phase/{phase_uuid}/tickets", featureHandlers.GetTicketsByPhaseUUID)`

- [x] Create a new route in ticket_routes.go: i.e. This will be for /bounties/ticket/feature/{feature_uuid}/phase/{phase_uuid}
   Add -> `r.Get("/feature/{feature_uuid}/phase/{phase_uuid}", featureHandlers.GetTicketsByPhaseUUID)`

- [ ] Update the Handler GetTicketsByPhaseUUID to ensure it is in the correct file 
   1. Move from handlers/features.go - LINE 702-748
   2. to handlers/ticket.go

- [ ] Ensure hanlder still correctly interperets phase and dfeature UUID from URL 
   1. Ensure that the handler correctly retrieves feature and phase UUID from the url?
   2. Ensure correct calling of db/tickets.go#GetTicketsByPhase
   
- [ ] Front End change - update page to call new endpoint
   - Planner Page loads at: <domain>/feature/featureUUID/phase/phaseUUID
   - Update to Call endpoint GET `/bounties/tickets/feature/uuid/phase/uuid/`

**Comment by MahtabBukhari** [comment]
@humansinstitute assign
