### ISSUE TITLE
Fix filter dropdown

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#203]
Replit link:
https://replit.com/join/zydvsevjmd-sphinx1

@pitoi Current mobile menu for Explore People / Portfolios / Tickets looks broken. Here is an improvement i suggest. I think it would be usefull adding a line of text below each of the options. I saw Similar approach on Upwork search.

![image](https://user-images.githubusercontent.com/13258550/163197558-e5cd76a6-7d98-46c6-9a29-04630b13f143.png)

https://user-images.githubusercontent.com/13258550/163196468-33b8b83a-10b0-4be1-aedc-139f16a9007d.mp4

Current mobile version
![image](https://user-images.githubusercontent.com/13258550/162444141-7039e028-5d12-4792-827d-88a3cc045934.png)

**Comment by kevkevinpal** [comment]
fixed in this PR 🚀 
https://github.com/stakwork/sphinx-tribes/pull/288
