### ISSUE TITLE
[BUG] Need to correctly unpack the Feature ID and Phase ID (not UUID) from URL

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2030]
On receipt of GET request to /bounties/ticket/feature/UUID/phase/UUID
The URLs are not actually formatted as UUID but IDs e.g. random strings. 
As such we should ensure that we are not trying to validate on a UUID format.

**Comment by aliraza556** [comment]
N

**Comment by humansinstitute** [comment]
https://github.com/stakwork/sphinx-tribes/pull/2031
