### ISSUE TITLE
[BUG] Route for `bounties/ticket/review` should not be under pubkey authentication

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2035]
Route for bounties/ticket/review should not be under pubkey authentication. 
It should be moved to the group above as Stakwork cannot provide auth at this time. 

![image](https://github.com/user-attachments/assets/3435a90d-bc1c-42fa-87e9-d33ba02d437e)

**Comment by MuhammadUmer44** [comment]
@humansinstitute Please assign me?

**Comment by MahtabBukhari** [comment]
@humansinstitute assign?
