### ISSUE TITLE
Fix scrollbars

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#204]
We need to change scrollbars next to people list on left side, and on info section.
It should be just a simple scroll indicator, 
a rounded 6px line, colour - #bob7bc with 25% transparency.
We can even try making it visible only while user is scrolling. 

![image](https://user-images.githubusercontent.com/13258550/162478461-5a3c5058-6aef-4504-9578-0d7178484292.png)

![image](https://user-images.githubusercontent.com/13258550/162478311-46ce5b62-1ea3-41c0-b321-c8a46408ad12.png)

**Comment by plell** [comment]
done in next deploy
