### ISSUE TITLE
People list layout fix - Mobile version

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#205]
These notes are just for the homepage on mobile version

- Since time of last appearance is removed, "Connect" button should be aligned left.
- In case there is no description, remove margin between name and "Connect" button, and vertically center name and "Connect" button.
- Layout of "Connect" button need fix too. Please, use same icon on all connect button (icon color #B0B7BC), and check font size/color on the button label.

Icon for "Connect" button
https://drive.google.com/file/d/1kxpsiGWAxlTqIgdfDrlS_xRMBXiXHOwC/view?usp=sharing

![image](https://user-images.githubusercontent.com/13258550/162998423-0a2e0ad3-5d9c-4d28-bb15-f02c3c427dfe.png)

**Comment by plell** [comment]
done in next deploy
