### ISSUE TITLE
Create feature flag in env `FF-WEBSOCKET = false`

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2054]
Create a new entry on Sphinx Tribes to set a feature flag for websocket functionality.
Name of variable = `FF-WEBSOCKET`

- Status on Staging Server = `FF-WEBSOCKET = true`
- Status on Prod Server = `FF-WEBSOCKET = false`

**Comment by aliraza556** [comment]
@humansinstitute. Please assign me?

**Comment by humansinstitute** [comment]
@elraphty can you set this up?

**Comment by elraphty** [comment]
> up

Yeah sure, I'm boarding at the moment, will set it up immediately I get a stable internet connection.

**Comment by elraphty** [comment]
hello @humansinstitute I have to change  FF-WEBSOCKET to ` FF_WEBSOCKET` to follow the normal convention, the dash will not make the env work in production.
