### ISSUE TITLE
Update the webhook for /bounties/ticket/review to post a websocket message on successful update of tickets

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2102]
## Context
This update addresses the need for real-time synchronization between the backend and frontend of the ticket management system. When a ticket is successfully updated in the database, the frontend should automatically refresh to display the latest ticket information. This enhancement ensures that users have the most current data without needing to manually refresh the page.

## Task
1. Locate the `ProcessTicketReview` function in the file at [this link](https://github.com/stakwork/sphinx-tribes/blob/master/handlers/ticket.go#L442C1-L490C2).
2. After the `th.db.UpdateTicket(ticket)` call, implement logic to send a WebSocket message.
3. Test in Front edn that the message is received.

## Outcome
The frontend receives a websocket mesaget o trigger a refresh of the `TicketStore`.

## Design

The message that should be posted is: 

```
{
    broadcastType: "direct",
    sourceSessionID: reviewReq.sourceWebsocket,   // This should be the correct path from the Stakwork object. 
    message: "Successful update of ${ticketDetails.ticketUUID}"  ,
    action: "process",
    ticketDetails: { 
        featureUUID: "chjkdhu893u0qu82908394j",                 // Actual details from reviewReq.value.xyz
        phaseUUID: "chjkdhu893u0qu09890832",                   // Actual details from reviewReq.value.xyz
        ticketUUID: "11111-22222-33333-44444-555555",    // Actual details from reviewReq.value.xyz
        ticketDescription: "I'm a new ticket description"          // Actual details from reviewReq.value.xyz
    }
    
}
```

Note the sourceSessionID is set from the response object from Stakwork in field `sourceWebsocket`

Example Object from Stakwork

```
{
      "value": {
        "featureUUID": "ct3ctn2tu2rkjfln59sg",
        "phaseUUID": "ct7828npaij247dg8bug",
        "ticketUUID": "d1be1f35-6f85-47fe-b124-47132fab0a58",
        "ticketDescription": "# Ticket Name: Update Frontend Ticket Store to Refresh from Database\n\n## Context\nThe current ticket store on the frontend does... a big long description."
      },
      "requestUUID": "1111-2222-3333-4444",
      "sourceWebsocket": "1111-2222-3333-4444"
    },
```

Utilise the send message function in: https://github.com/stakwork/sphinx-tribes/blob/master/websocket/pool.go#L62

## Acceptance Criteria
- [ ] WebSocket message is sent after a successful ticket update.
- [ ] Frontend recieves message with action: Process.

**Comment by saithsab877** [comment]
,

**Comment by MuhammadUmer44** [comment]
k

**Comment by MahtabBukhari** [comment]
a
