### ISSUE TITLE
Update the ticket_message struct for Update the ticket interface to allow: action: 'run-link'

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2118]
Originally implemented here: https://github.com/stakwork/sphinx-tribes/issues/2057

Update the ticket message struct to allow:

action: 'process' | 'message' | run-link;       // Action to be performed

**Comment by saithsab877** [comment]
,

**Comment by MahtabBukhari** [comment]
@humansinstitute assign

**Comment by AhsanFarooqDev** [comment]
@humansinstitute can i help?
