### ISSUE TITLE
[BUG] Auto refresh Ticket Details

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2125]
![image](https://github.com/user-attachments/assets/e4208fbb-187d-4c19-a614-3692f0b2f60d)

https://www.loom.com/share/bc78121b7bed4d43829e8e45f15c7162

**Comment by humansinstitute** [comment]
@aliraza556 @MahtabBukhari - adding this to track resolution.

**Comment by MahtabBukhari** [comment]
@humansinstitute assign

**Comment by aliraza556** [comment]
@humansinstitute Please assign me?

**Comment by aliraza556** [comment]
Hi @humansinstitute, Please move this frontend side

**Comment by MahtabBukhari** [comment]
@humansinstitute Could you please Also assign on sphinx too for both of us 😊

**Comment by humansinstitute** [comment]
Done yesterday.
