### ISSUE TITLE
Update go structs for Chat to Hive Feature

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2144]
To facilitate a chat interface in Hive. 

We will add additional DB tables, migrations and structs to the tribes backend. This will allow us to chat with specific context data, easily from within the Hive Interface.

![image](https://github.com/user-attachments/assets/8f41313f-c704-45e6-82ac-ac6281eaf47c)

Task: 

1. Create the migrations for new database tables (as defined by structs)
2. Update structs.go with new chat structs. 
3. Create stub DB handler functions inside db/chat.go for
   a. addChat, getChatByChatID
   b. addChatMessage, getChatMessagesForChatID

```
type ContextTag struct {
    Type string `json:"type"` // "productBrief" | "featureBrief" | "schematic"
    ID   string `json:"id"`
}

type ChatMessage struct {
    ID               string       `json:"id" gorm:"primaryKey"`
    ChatID          string       `json:"chatId" gorm:"index"`
    Message         string       `json:"message"`
    Role            string       `json:"role"` // "user" | "assistant"
    Timestamp       time.Time    `json:"timestamp"`
    ContextTags     []ContextTag `json:"contextTags" gorm:"type:jsonb"`
    Status          string       `json:"status"` // "sending" | "sent" | "error"
    Source          string       `json:"source"` // "user" | "agent"
}

type Chat struct {
    ID          string    `json:"id" gorm:"primaryKey"`
    WorkspaceID string    `json:"workspaceId" gorm:"index"`
    Title       string    `json:"title"`
    CreatedAt   time.Time `json:"createdAt"`
    UpdatedAt   time.Time `json:"updatedAt"`
}
```

**Comment by AhsanFarooqDev** [comment]
x

**Comment by MuhammadUmer44** [comment]
.

**Comment by aliraza556** [comment]
@humansinstitute Please assign me?

**Comment by MahtabBukhari** [comment]
@humansinstitute Could you please assign me?

**Comment by MahtabBukhari** [comment]
@humansinstitute you can assign me I will do it today or tonight ASAP

**Comment by Shoaibdev7** [comment]
@humansinstitute Please assign me?
