### ISSUE TITLE
Script to update defaults on new DB columns

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2147]
Given changes to the DB Structs for tickets in https://github.com/stakwork/sphinx-tribes/issues/2144

We have added three columns:

1. ticketGroup
2. author
3. authorID

This task is to create a DB script that can be run on staging and prod to update current tickets to include default values for these changes. 

The defaults should be: 

- ticketGroup = set to ticketUUID of ticket.
- author = HUMAN
- authorID = "123456"

Pseudo logic for the script
```
If ticketGroup exists and ticketGroup = NULL | ""
then 
- set ticketGroup == ticketUUID
- set author = "HUMAN"
- set authorID = "123456"
```

## Acceptance 

- [ ] Confirm correct names in DB table
- [ ] Implement and Test Script on local Db
- [ ] Deploy and run on Staging and Prod (once structs are deployed)

**Comment by saithsab877** [comment]
G

**Comment by MahtabBukhari** [comment]
@humansinstitute assign
