### ISSUE TITLE
Sign out button

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#216]
Sign out button needs to be changed on mobile version, to match same button used in desktop.
Here is screenshot of original design
Figma
https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/People.Sphinx?node-id=2441%3A18604

![image](https://user-images.githubusercontent.com/13258550/165491317-7075e226-2b0e-4843-a9be-b691891e4b37.png)

**Comment by plell** [comment]
done
