### ISSUE TITLE
Update /hivechat/chat/send to include product brief

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2173]
In future phases we will use the `contextTags?: ContextTag[];` passed from the front end to retrieve and build context to be included in our chat request. 

In this first phase we will include just the product brief which can be access via: https://github.com/stakwork/sphinx-tribes/blob/master/db/features.go#L331C1-L344C2

This change will add a function to the handler to take in the context tags from the front end (rigth now these will be empty) 

Then it will run the getProductBrief function and output this product brief as the variable `context` 

This will then be Included in the stakwork post: `"contextTags":    context`

**Comment by humansinstitute** [comment]
Assigned - @MahtabBukhari can you approach this detail will be available in 10.

**Comment by MahtabBukhari** [comment]
@humansinstitute assign
