### ISSUE TITLE
[BUG] On Update for Invite Codes

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2180]
PRs 
- FE https://github.com/stakwork/sphinx-tribes-frontend/pull/754
- BE https://github.com/stakwork/sphinx-tribes/pull/2167

Bug shown in video. Fails to correctly interact with endpoint and generate invites. 

https://github.com/user-attachments/assets/fca7897e-b12e-4974-adec-5d96a3ddfae1

Note there is a second UI bug where I cannot type a number as it retains the 0 see screenshot. 

![Image](https://github.com/user-attachments/assets/dcf54c8c-a49c-4c2c-b5ea-d7404f630c9a)

**Comment by aliraza556** [comment]
Hi @humansinstitute, Please review this PR https://github.com/stakwork/sphinx-tribes/pull/2179 i think fixed this issue

**Comment by tobi-bams** [comment]
@humansinstitute, we are having this bug because we don't have the v2botUrl on the test server.

This will only work on production

**Comment by tobi-bams** [comment]
Also, I will fix the frontend issue
