### ISSUE TITLE
Create a logger util

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#2185]
### Goal
We want to create a logger util that we can use throughout the codebase to give us the ability to format the logs uniformly throughout the sphinx-tribes application

### Description
In `./utils/logger.go` create a new file which we can import throughout the app which we can use the following way

`logger.info("Sample log text %s", example_variable`
`logger.error("Sample log text %s", example_variable`
`logger.debug("Sample log text %s", example_variable`

### Note
It is also worth checking to see if there are any modules that we can use that already do this and that we can extend if we need to

**Comment by aliraza556** [comment]
@kevkevinpal Please assign me?

**Comment by MahtabBukhari** [comment]
@kevkevinpal please assign
