### ISSUE TITLE
Get stacktrace in 500 error

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#2186]
### Goal
on a 500 internal server error we want to get the stack trace from the middleware
in the [middleware](https://github.com/stakwork/sphinx-tribes/blob/master/routes/index.go#L150) get the stack trace and print out the stack trace to the logs

We will use the stack trace in the future

**Comment by aliraza556** [comment]
@kevkevinpal Please assign me?

**Comment by MahtabBukhari** [comment]
@kevkevinpal please assign
