### ISSUE TITLE
Process Chat Response

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2196]
Update the endpoint at https://github.com/stakwork/sphinx-tribes/blob/master/handlers/chat.go#L300C1-L306C2

Task: 

1. Review response message
2. Create a chat message for the correct chat ID (this will updates the history) 
3. Trigger a web socket update to the front page in order to refresh the chat history component from the chat history store. 

Secondary Task: 

- The endpoint name is incorrect in the post to stakworkwork. 
- File: https://github.com/stakwork/sphinx-tribes/blob/master/handlers/chat.go#L182C2-L200C3
- Please update to `"webhook_url":       fmt.Sprintf("%s/hivechat/response", os.Getenv("HOST")),
`

**Comment by aliraza556** [comment]
U

**Comment by saithsab877** [comment]
@humansinstitute assign?

**Comment by humansinstitute** [comment]
@aliraza556 - The new webhook setting is correct, but Im having trouble reviewing this as the front end doesn't seem to be integrated correctly. 

Do you have a view on why it wouldn't trigger the update on the front end?

**Comment by aliraza556** [comment]
@humansinstitute Sure
