### ISSUE TITLE
Web socket failure on InternalServerMiddleware

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#2199]
### Context
The `internalServerMiddleware` was causing any websocket request to fail so we need to identify the reason why and resolve that in the middleware so we can reenable it

This is the commented out middleware that is broken https://github.com/stakwork/sphinx-tribes/blob/master/routes/index.go#L144-L166

**Comment by kevkevinpal** [comment]
the response on this post is similar to what we have implemented but the comment below the answer also says that it breaks hijacker which is what is used for websockets

https://stackoverflow.com/questions/53272536/how-do-i-get-response-statuscode-in-golang-middleware

**Comment by aliraza556** [comment]
@kevkevinpal I  am working on this issue and will provide updates shortly.

**Comment by kevkevinpal** [comment]
> @kevkevinpal I am working on this issue and will provide updates shortly, meaning I will create a PR within two hours.

I should have a fix I'm using the `urfave/negroni` library instead of the way its being done currently
