### ISSUE TITLE
Add endpoint GetChat to access from Workspace component

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2205]
We are missing an endpoint here for r.Get("/", chatHandler.GetChat)

This looks like my fault got missed off the initial spec here: https://github.com/stakwork/sphinx-tribes/issues/2154

Task:

1. new route r.Get("/", chatHandler.GetChat)
2. new db function to getChats for a given workspace UUID to be added to https://github.com/stakwork/sphinx-tribes/blob/master/db/chat.go
3. Get the workspace ID and call db.getChats (return all chat details, name updated etc)
4. Display List of links to chat ids by last updated
5. On load of workspace page, display all Chats Associated with this workspace showing title and time last updated
6. On click load correct chat view.

**Comment by humansinstitute** [comment]
@Shoaibdev7 - as discussed in https://github.com/stakwork/sphinx-tribes-frontend/pull/768#issuecomment-2545737756

**Comment by Shoaibdev7** [comment]
@humansinstitute Please assign me?

**Comment by Shoaibdev7** [comment]
@humansinstitute, the bounty has not been created. Please create it when you get a chance.

**Comment by humansinstitute** [comment]
Created - but we still don't have full functionality here. 
https://community.sphinx.chat/bounty/3015

We still have not resolved the front end correctly calling this endpoint to update?

**Comment by Shoaibdev7** [comment]
@humansinstitute https://community.sphinx.chat/p/csfokk2tu2rulqj5lff0/assigned/3015/0
