### ISSUE TITLE
[Bug] Fix 500 error in /hivechat/response endpoint - Primary key conflict in message creation

### ISSUE THREAD

**Issue by humansinstitute** [stakwork/sphinx-tribes#2210]
## Context

The `/hivechat/response` endpoint is currently returning 500 errors when processing responses from Stakwork. Investigation shows this is due to incorrect message ID handling in the response processing logic.

**Current Behavior**
- The endpoint reuses the original message ID (the message being responded to) as the ID for the new assistant message
- This causes a primary key conflict in the database since the ID already exists
- Results in 500 Internal Server Error responses

**Required Changes**
1. Modify the `ProcessChatResponse` handler in `handlers/chat.go`:
- Generate a new unique ID for each assistant message using `xid.New().String()`
- Keep the original `messageId` in the request structure for reference only
- Ensure new messages are created with proper assistant/agent attributes

```go
message := &db.ChatMessage{
    ID:        xid.New().String(),  // Generate new ID here
    ChatID:    request.ChatID,
    Message:   request.Response,
    Role:      "assistant",
    Timestamp: time.Now(),
    Status:    "sent",
    Source:    "agent",
}
```

**Testing**
1. Verify successful message creation with unique IDs
2. Confirm chat history maintains proper conversation flow
3. Check WebSocket notifications still work correctly
4. Test with multiple rapid responses to ensure no race conditions

**Related Code**
- Primary handler: `handlers/chat.go`
- Affected endpoint: `/hivechat/response`
- Database model: `ChatMessage` struct

**Additional Context**
The messageId from Stakwork's response should be treated as a reference to the original message being responded to, not as the ID for the new message.

- [ ] When receiving a response from Stakwork, the system generates a new unique message ID instead of reusing the original messageId
- [ ] New assistant messages are correctly stored in the database with role="assistant" and source="agent"
- [ ] The chat history shows a clear conversation flow between user messages and assistant responses
- [ ] WebSocket notifications are successfully sent to the client with the newly created message details
- [ ] The system handles concurrent responses without creating duplicate messages or database conflicts

**Comment by humansinstitute** [comment]
@MahtabBukhari as discussed

**Comment by MahtabBukhari** [comment]
@humansinstitute assign

**Comment by saithsab877** [comment]
@humansinstitute ASSIGN ME?

**Comment by humansinstitute** [comment]
Testing this morning, this isn't correctly processing the Chat ID as far as I can tell from Stakwork. 

If we consider this screenshot of the look test, we can see that the chatId is returned as part of the 200 response.  

<img width="1464" alt="Screenshot 2024-12-18 at 8 50 32 am" src="https://github.com/user-attachments/assets/5e68ed96-b956-450e-85c6-e0c904d2c8c0" />

The messages aren't shown in the interface or returned from a Get Messages by Chat ID call (see network tab) 

<img width="1464" alt="Screenshot 2024-12-18 at 8 55 04 am" src="https://github.com/user-attachments/assets/eae9461e-1dcd-4d54-b249-da85bf058095" />

Then when we check the stakwork output we see that we got a 200 message resposne, but that it doesn't include the chatId in the response.

<img width="1464" alt="Screenshot 2024-12-18 at 9 06 57 am" src="https://github.com/user-attachments/assets/0c06cf6b-815a-42cb-be46-ae81cbc520f6" />


```
{
  "input": {
    "url": "https://people-test.sphinx.chat/hivechat/response",
    "method": "post",
    "headers": {
      "Content-Type": "application/json",
      "Accept": "application/json"
    },
    "request_params": {
      "value": {
        "chatId": "cth1kh4opisgms0ej8m0",
        "messageId": "cth1lm4opisgms0ej8ng",
        "response": "I apologize for the oversight. Given the context that this is a project with a TypeScript frontend and a Go backend, it seems like you might be asking about implementing or handling messaging features or improving message handling in this setup. Here's a more tailored response:\n\nIf you're looking to implement a messaging feature or handle messages between your TypeScript frontend and Go backend, here are some suggestions:\n\n1. **WebSockets**: For real-time messaging, consider using WebSockets. You can set up a WebSocket server in Go and communicate with it using a WebSocket client in TypeScript.\n\n2. **REST API**: If real-time isn't necessary, you can use a REST API for sending and receiving messages. Define endpoints in your Go backend to handle message operations and use HTTP requests from your TypeScript frontend.\n\n3. **gRPC**: For more efficient communication, especially if you're dealing with a lot of message exchanges, consider using gRPC with Protocol Buffers for defining service contracts and message structures.\n\n4. **Message Queues**: If you need to handle asynchronous messaging or decouple parts of your system, consider using a message queue system like RabbitMQ or Kafka.\n\n5. **Error Handling**: Ensure you have robust error handling on both the frontend and backend to deal with any issues that might arise in message transmission or processing.\n\nPlease let me know if you need more specific guidance on any of these options!",
        "sourceWebsocketId": null
      },
   },
}
```

Response:

```
      "response": {
        "success": true,
        "message": "Response processed successfully",
        "data": {
          "id": "cth1lo4opisgms0ej8o0",
          "chatId": "",
          "message": "",
          "role": "assistant",
          "timestamp": "2024-12-18T00:44:16.360524182Z",
          "contextTags": null,
          "status": "sent",
          "source": "agent"
        }
      },
```

**Comment by MahtabBukhari** [comment]
> @MahtabBukhari  -> Testing this morning, this isn't correctly processing the Chat ID as far as I can tell from Stakwork. 
> 
> If we consider this screenshot of the look test, we can see that the chatId is returned as part of the 200 response.  
> 
> <img width="1464" alt="Screenshot 2024-12-18 at 8 50 32 am" src="https://github.com/user-attachments/assets/5e68ed96-b956-450e-85c6-e0c904d2c8c0" />
> 
> The messages aren't shown in the interface or returned from a Get Messages by Chat ID call (see network tab) 
> 
> <img width="1464" alt="Screenshot 2024-12-18 at 8 55 04 am" src="https://github.com/user-attachments/assets/eae9461e-1dcd-4d54-b249-da85bf058095" />
> 
> Then when we check the stakwork output we see that we got a 200 message resposne, but that it doesn't include the chatId in the response.
> 
> <img width="1464" alt="Screenshot 2024-12-18 at 9 06 57 am" src="https://github.com/user-attachments/assets/0c06cf6b-815a-42cb-be46-ae81cbc520f6" />
> 
> 
> ```
> {
>   "input": {
>     "url": "https://people-test.sphinx.chat/hivechat/response",
>     "method": "post",
>     "headers": {
>       "Content-Type": "application/json",
>       "Accept": "application/json"
>     },
>     "request_params": {
>       "value": {
>         "chatId": "cth1kh4opisgms0ej8m0",
>         "messageId": "cth1lm4opisgms0ej8ng",
>         "response": "I apologize for the oversight. Given the context that this is a project with a TypeScript frontend and a Go backend, it seems like you might be asking about implementing or handling messaging features or improving message handling in this setup. Here's a more tailored response:\n\nIf you're looking to implement a messaging feature or handle messages between your TypeScript frontend and Go backend, here are some suggestions:\n\n1. **WebSockets**: For real-time messaging, consider using WebSockets. You can set up a WebSocket server in Go and communicate with it using a WebSocket client in TypeScript.\n\n2. **REST API**: If real-time isn't necessary, you can use a REST API for sending and receiving messages. Define endpoints in your Go backend to handle message operations and use HTTP requests from your TypeScript frontend.\n\n3. **gRPC**: For more efficient communication, especially if you're dealing with a lot of message exchanges, consider using gRPC with Protocol Buffers for defining service contracts and message structures.\n\n4. **Message Queues**: If you need to handle asynchronous messaging or decouple parts of your system, consider using a message queue system like RabbitMQ or Kafka.\n\n5. **Error Handling**: Ensure you have robust error handling on both the frontend and backend to deal with any issues that might arise in message transmission or processing.\n\nPlease let me know if you need more specific guidance on any of these options!",
>         "sourceWebsocketId": null
>       },
>    },
> }
> ```
> 
> Response:
> 
> ```
>       "response": {
>         "success": true,
>         "message": "Response processed successfully",
>         "data": {
>           "id": "cth1lo4opisgms0ej8o0",
>           "chatId": "",
>           "message": "",
>           "role": "assistant",
>           "timestamp": "2024-12-18T00:44:16.360524182Z",
>           "contextTags": null,
>           "status": "sent",
>           "source": "agent"
>         }
>       },
> ```

@humansinstitute let me check that one too 
yes above screenshot is tested

**Comment by humansinstitute** [comment]
Perhaps 
`ChatID:    request.ChatID,`

should be:
`ChatID:    request.ChatId,` 

Given the return object?

**Comment by MahtabBukhari** [comment]
> Perhaps 
> `ChatID:    request.ChatID,`
> 
> should be:
> `ChatID:    request.chatId,` 
> 
> Given the return object?

issue is something else

**Comment by MahtabBukhari** [comment]
@humansinstitute Could you please pay this bounty https://community.sphinx.chat/p/cs6elnatu2rsh7eq5hk0/assigned/3014/12
its marked as completed but not received payment
