### ISSUE TITLE
Create Post request to jarvis node/edge/bulk

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#2214]
This is dependent on https://github.com/stakwork/sphinx-tribes/issues/2187

### Description
We want to take what we have gotten from the `InternalServerErrorMiddleware` and send it to a jarvis
So what we should do is first
- Check that `JARVIS_URL` is not an empty string
- Check that `JARVIS_TOKEN` is not an empty string
- Then if they do exist then we will attempt a POST request to `/node/edge/bulk`
- `edge_list` will be the body of the request
- If it fails give an error
- If it succeeds give a success message
- use `JARVIS_TOKEN` as the value for the `x-api-token` header

**Comment by aliraza556** [comment]
@kevkevinpal assign me

**Comment by MahtabBukhari** [comment]
@kevkevinpal please assign
