### ISSUE TITLE
Set of VHS/Glitch style Avatars

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#222]
Create a set of square sized avatars for the following roles:
- Admin
- Moderator
- Developer
- VIP member
- Top Contributor

Illustrations should be collage based, goofy and surrealistic, following VHS / 8-bit style NFT Aesthetics.
Once approved, avatars will be animated into GIF loop animation.

Resolution: Min 2000x2000px

Example:
![image](https://user-images.githubusercontent.com/13258550/171474932-3aed743c-5845-4d83-afc3-5396e70fc350.png)

**Comment by NickGSzabo** [comment]
Alright! Is there any of these you'd llike to see first?

**Comment by NickGSzabo** [comment]
I took the liberty to make the admin first, as I could not wait to get my hands dirty. I have a lot of ideas and sketches for the other characters as well, they have great personalities! However I thought it would be good to first see if the style works for you. Let me explain some of the choices I made. 

I took your example of collage based NFT art with glitch but improved on it. 

It's an all unique, custom-build engine for this purpose alone, meaning changing characters but keeping the effects shouldn't be too difficult. The whole image is processed by a VHS simulator, meaning you couldn't get closer to the real deal besides working analog. I've shifted the RG spectrum and added a Matrix style masking for the body. The clipart is hand drawn by me so it can be animated. In fact the whole thing is meant to run in sequence so this is just a still.

![AdminSphinx01](https://user-images.githubusercontent.com/96319599/173079513-52b805db-711c-4136-83eb-5e7e1be55791.png)

Looking forward to your feedback!

**Comment by Antanasijevic** [comment]
@NickGSzabo Hi Nick, sorry for late response. This all looks great. If you are available, lets get in touch on Monday, we can use google meet to share a screen, and discuss everything. I would really like to see the process behind it.

**Comment by NickGSzabo** [comment]
Excellent, I'm in UTC-3 and have a call scheduled from 14:00 to 15:00 with Sam. Before or after would be good, we can discuss the other work at the same time. Let me know what time would be good for you.

**Comment by NickGSzabo** [comment]
You might have an easier time reaching me on Sphinx:
03d9d4e058a5cbef14ba74fc4fc55f2bc965e9f7a6e3884711a38a1d0a9a1602f7

**Comment by Antanasijevic** [comment]
@NickGSzabo Seems like i have some issues reaching you on Sphinx. Can we connect on google meet during next hour, or tomorrow?
https://meet.google.com/ffr-bybs-jjz

**Comment by NickGSzabo** [comment]
I'm trying to join the call, now or tomorrow both are good.

**Comment by NickGSzabo** [comment]
Could you share your Sphinx account? This way I can try to contact you. That would make it easier for me to ask you questions regarding the tickets I'm working on.

**Comment by Antanasijevic** [comment]
@NickGSzabo Sure, here it is 
022b0eb6eac43c0b7e56dc8b6e8205f735a80966521f553db56deff197b0035a7f

**Comment by NickGSzabo** [comment]
Hi Milan, my node crashed, trying to reach you. I'm in the google call we used last time.
