### ISSUE TITLE
100 profile images for Bots page $@270,000

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#223]
We need a set of 100 placeholder profile images, to be used on bots page.
Each one should be a very subtle gradient, so entire screen covered with these images does not feel busy.
Minimal resolution of single image is 1024x1024px.

Example:
![image](https://user-images.githubusercontent.com/13258550/171476442-8b9e98bd-72aa-4b7a-aa39-44f0843bfb92.png)

**Comment by Antanasijevic** [comment]
@NickGSzabo Yes, something like that may work, just we need more variety in color.

**Comment by NickGSzabo** [comment]
[I've increased the color diversity and intensity to make them more unique.](https://we.tl/t-FvlgGkq0rG)

**Comment by Antanasijevic** [comment]
@NickGSzabo Cool, are images generated by script? If so, what are the parameters you are using?

**Comment by NickGSzabo** [comment]
They are indeed procedurally generated. So if you'll ever need more let me know, we are very far off from getting duplicates.

It's a 2x2 canvas filled with perlin noise. With an exponent of 1.5, harmonics of 10 and harmonic spread of 20.

Stretch it to the right resolution, some blur for finesse and some level adjusting for vibrancy.

**Comment by NickGSzabo** [comment]
[BotAvatar.230.zip](https://github.com/stakwork/sphinx-tribes/files/9085036/BotAvatar.230.zip)
