### ISSUE TITLE
Create Feature Flag Database Schema

### ISSUE THREAD

**Issue by tobi-bams** [stakwork/sphinx-tribes#2242]
Breakdown of feature flag system in: https://github.com/stakwork/sphinx-tribes/issues/2235

#### **Create Feature Flag Database Schema**
- **Description:** 
  - Create the necessary database tables: `feature_flags` and `endpoints`.
- **Deliverables:** 
  - Migration scripts for:
    - `feature_flags` table:
      - `uuid` (UUID, Primary Key)
      - `name` (String, Unique, Not Null)
      - `description` (Text)
      - `enabled` (Boolean, Default: false)
    - `endpoints` table:
      - `uuid` (UUID, Primary Key)
      - `path` (String, Not Null)
      - `feature_flag_uuid` (Foreign Key, References `feature_flags.uuid`)
  - Write test for this Migration

**Comment by saithsab877** [comment]
@tobi-bams I can help?

**Comment by MahtabBukhari** [comment]
@tobi-bams @humansinstitute assign me
