### ISSUE TITLE
Create ENV var for `LOG_LEVEL`

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#2246]
### Context

We want to add a new env var `LOG_LEVEL`

Add a new env var in [config.go](https://github.com/stakwork/sphinx-tribes/blob/master/config/config.go) default the value to an empty string "DEBUG"

**Comment by saithsab877** [comment]
@kevkevinpal assign me?

**Comment by MahtabBukhari** [comment]
@kevkevinpal assign

**Comment by AhsanFarooqDev** [comment]
@kevkevinpal can I help
