### ISSUE TITLE
unique uuid for each request in log

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#2255]
### Description
We want to prefix the log with a unique uuid, but for each request it should have the same uuid for each request

modify this file to do so
https://github.com/stakwork/sphinx-tribes/blob/master/utils/logger.go

**Comment by aliraza556** [comment]
J

**Comment by saithsab877** [comment]
@kevkevinpal I can help?

**Comment by MahtabBukhari** [comment]
@kevkevinpal please assign

**Comment by AhsanFarooqDev** [comment]
@kevkevinpal can I help?
