### ISSUE TITLE
Add session_id to frontend, stored in cache

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#2297]
### Description
We want to create a session id on the frontend that is cleared after a user exits the browser window and then pass that session id into every single request on sphinx-tribes

We want the session id to be a unique value but the same value per session, so we can differ them on the backend
`X-SESSION-ID`

example
user opens bounty.sphinx.chat
`X-SESSION-ID = 123456`
user logs on 
still `X-SESSION-ID = 123456`
user creates bounty
still `X-SESSION-ID = 123456`
user closes the browser window
user opens bounty.sphinx.chat
changes to `X-SESSION-ID = <new uuid>`

**Comment by saithsab877** [comment]
,

**Comment by aliraza556** [comment]
H
