### ISSUE TITLE
In Need of a Short Video: How Staking Works on Sphinx

### ISSUE THREAD

**Issue by chrisstak** [stakwork/sphinx-tribes#241]
Looking for someone proficient in Photoshop and video editing to create a short video explaining how staking works on Sphinx.

REQUIREMENTS:
-Should be between 10-12 seconds
-Use simple text and graphics during video
-Easy to understand and must flow well
-Use the script as your text in the video
-Anything in parenthases is a suggested graphic, but be creative!
-"Sphinx blue" should be the dominant color during video

SCRIPT:
Scene 1: “Staking sats to fight spam"
(Graphic of Sphinx logo)

Scene 2: “Most messaging apps don’t require skin in the game”

Scene 3: “Malicious actors can spam a network with few consequences”
(Graphic of a meme troll face)

Scene 4: “Staking a small amount of sats fixes this”

Scene 5: “Skin in the game creates a consequence for bad behavior”

Scene 6:“A moderator can use the staked sats as collateral”
(Graphic showing a user giving sats to a tribe)

Scene 7: “If a user behaves poorly -> the sats are taken and the post is deleted from the tribe"

Scene 8: “And just like that -> Spamming becomes a costly and inefficient”
(Meme troll face with a frowny face instead of smile)

Scene 9: “The only people left are the ones who should be there”

**Comment by NickGSzabo** [comment]
I'll take a look at this together with my wife. Would you be able to reserve the ticket?

**Comment by pitoi** [comment]
I'll ask Chris to assign it to you in the tickets page

**Comment by Antanasijevic** [comment]
@pitoi @chrisstak Here is a rough mock up of a video. It will be one continuous animation, with elements blurring, and zooming in and out.


![Staking_sats_V1](https://user-images.githubusercontent.com/13258550/179609357-b4eb243e-c263-466a-906d-77a5c4044840.gif)

**Comment by chrisstak** [comment]
**Feedback on Story Board** 
- Transitions too quick
- We would like to get rid of stock photos and replace with avatars
- Have the conversation take place in one fluid location
- One of the scenes says “And just like that, staking becomes a costly and inefficient” which is grammatically incorrect.
- A couple people told me they were fans of the troll face
- Does not match color scheme of previous videos

**Comment by chrisstak** [comment]
Staking sats to fight spam

Spam makes the internet not fun

With freedom of speech comes spam

We need to be conversational and understand where they are coming from

Find something that is interesting to them

Hook-Can bitcoin solve spam?

Need to start from the beginning

Don’t assume they know what we are talking about

Freedom is great but it results in other problems

Freedom of speech is awesome, but with it comes spam

Sphinx users stake sats with each post

Depositing a few sats fights bad actors

The deposit is returned, unless the post is marked as spam

No big deal for users

But too costly for spammers

**Comment by Antanasijevic** [comment]
bitcoin solve spam (Can Bitcoin solve spam?)

Freedom of speech is awesome, but with it comes spam

Sphinx users deposit a few sats with each post

The deposit is returned, unless the post is marked as spam

A moderator can use the staked sats as collateral...

...and delete post from the tribe


Zero cost to users->costly for spammers

Staking sats fights spam

Finish with Sphinx logo

**Comment by chrisstak** [comment]
Scene 1: "Can Bitcoin Solve Spam?"
(Only text)

Scene 2: "Freedom of speech means freedom to spam"

Scene 3: "Sphinx users deposit a few sats with each post"
(Graphic of coins leaving a post toward the tribe and then looping back down)
Tribe Name: "Bitcoiners"
Text of post: "Bitcoin is freedom money"

Scene 4: "The deposit is returned, unless the post is marked spam"
(Graphic of coins leaving message and disappearing into tribe name. Post disappears as well)
Tribe Name: "Bitcoiners"
Text of post: "Nigerian princess Bitcoin for sale!"

Scene 5: "Zero cost for users. Costly for spammers."

Scene 6: "Staking sats fights spam"

Scene 7: (Graphic of the Sphinx logo)

**Comment by Antanasijevic** [comment]
![Staking_sats_V3](https://user-images.githubusercontent.com/13258550/180623310-f1bc95bf-4390-4a8a-baab-0ec24301fddc.jpg)

**Comment by pitoi** [comment]
I think this looks really good
I don't think we need the slides "collateral" and "delete post". since that's implied by the previous one where the 'post is marked as spam" and we could show the sats going away.

**Comment by Antanasijevic** [comment]
@pitoi @chrisstak Here is first completed version
https://user-images.githubusercontent.com/13258550/181380190-0983e522-4a53-4f25-9f66-7d5a4958c1b4.mp4

**Comment by pitoi** [comment]
This is pretty much there. Fantastic work!
i am a bit confused by the part where the ‘moderator uses sats as collateral’.
I think we can cut that part out and not lose any meaning.

**Comment by chrisstak** [comment]
I agree! It looks great.

The only thing I noticed was the stock photo of the avatar of "Bob." Do we want to change that to a animated character since the other avatar is a troll face?

**Comment by Antanasijevic** [comment]
@pitoi @chrisstak Here is shorter version

https://user-images.githubusercontent.com/13258550/181572709-0d881b7d-c057-4a9e-af83-6c0ea0a58dc3.mp4
