### ISSUE TITLE
Unique url route for ticket

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#246]
When I'm trying to share the ticket from the people page `people.sphinx.chat` I can't send a link to the ticket itself maybe we could use reactRouter, Not sure what the primary key is for the ticket but maybe we can use that for the route

right now I either send the link to the github page or tell them the title of the ticket which is not ideal

**Comment by pitoi** [comment]
would be a great improvement

**Comment by kevkevinpal** [comment]
thanks to @divyank-rs we can do this now!
