### ISSUE TITLE
Tribe Ticketing

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#251]
Design GitHub messages in tribe in a way that will tell a story about each ticket, showing all actions in a clear and meaningful manner. Design elements should be flexible in order to cover different types of GitHub tickets.

Consider stacking multiple consecutive actions on same ticket. Make Threads on particular issue/ topic (show all actions and comments for it in one view). Check out threads in Slack or Twitter.

Hierarchy of ticket elements:
1 - Repository
2 - Type of item (Issue, Commit, Pull request, Merge, …)
3 - Action (Open, Close, Merge, Comment…)
4 - Who did latest action, who received
5 - Thread 
6 - Add prominent button to view original github page.

Additional way to add clarity to tribe tickets is to enable user to see only tickets mentioning him,
while moderator can see all tickets.

**Comment by Antanasijevic** [comment]
Seems like best solution would be allowing user to customize notification for himself.
As default, this seems to be best solution:

**Show me notification if:**
- Issue is assigned to me
- Comments that mentions me
- Someone closed my issue
- Pull request created, 
- my pull request is merged

**Do not show me notifications:**
- On my own actions
- If comment is edited

**Comment by Antanasijevic** [comment]
Version 1
![image](https://user-images.githubusercontent.com/13258550/190653705-22c64f24-d354-40c3-b461-8c3f457be2ac.png)

**Comment by Antanasijevic** [comment]
Version 2

![image](https://user-images.githubusercontent.com/13258550/190654242-297496b0-e4dc-48e2-8ca6-6d4cc49b7727.png)

**Comment by Antanasijevic** [comment]
![image](https://user-images.githubusercontent.com/13258550/193863338-6d28beeb-eeee-4cb0-a150-da14abaf2318.png)

**Comment by Evanfeenstra** [comment]
beautiful!

**Comment by rkirkendall** [comment]
Really nice work!
