### ISSUE TITLE
Profile pictures missing

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-tribes#253]
looks like an invalid URL parameter:
"https://memes.sphinx.chat/public/nlO8OQslzQTy0oaxnPK79gV6obH7XAm3nRPKqNuk8GE=?medium=true "
This downloads the image:
https://memes.sphinx.chat/public/nlO8OQslzQTy0oaxnPK79gV6obH7XAm3nRPKqNuk8GE=

<img width="681" alt="Screen Shot 2022-09-12 at 10 45 29 AM" src="https://user-images.githubusercontent.com/814886/189721439-5c32dc6f-79ff-4756-bd89-857549c1cd71.png">

**Comment by kevkevinpal** [comment]
should be fixed now
