### ISSUE TITLE
Add create ticket button into my profile/ticket  section

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#298]
When user opens his profile and ticket tab, there is no "Create ticket" button.
We should add one.

**Comment by ecurrencyhodler** [comment]
This has been implemented.
<img width="1120" alt="tix-profile" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/91128231-ba00-43f0-91cd-ffd169cb3989">
