### ISSUE TITLE
Sphinx Bounties [Part 3] - Onboarding [Desktop]

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#300]
- Create one popup layout 
- Each button passes a variable that determines the content in the popup

Figma project 
https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/People.Sphinx?node-id=4404%3A25851

Content 1 - Developer
If developer is not logged in or does not have profile created, click on "I can help" button on opened bounties opens this dialog. Dialog contains:
- GIF animation (loop) 
- Blue "Get Sphinx" button (opens [download ](https://buy.sphinx.chat/)page)
- "I have Sphinx" button  (opens a pop up with QR code and "Login with Sphinx" button.)

Screenshot:
![image](https://user-images.githubusercontent.com/13258550/196550944-f8630bf9-6c1c-4bed-9f4f-87e6c2fa0aa7.png)

Gif animation:
![Onboard_Worker_V1](https://user-images.githubusercontent.com/13258550/195805074-89850b7d-82ae-4edb-a971-0bad4e476387.gif)

Content 2 - Job provider
If job provider is not logged in or does not have profile created, click on "Post a bounty" button opens this dialog. Dialog contains:
- GIF animation (loop) 
- Green "Get Sphinx" button (opens [download ](https://buy.sphinx.chat/)page)
- "I have Sphinx" button  (opens a pop up with QR code and "Login with Sphinx" button.)

Screenshot:
![image](https://user-images.githubusercontent.com/13258550/196550892-c0328d5b-1fc0-46ec-9f45-fff26104468d.png)

Gif animation:
![Onboard_Job_Provider_v1](https://user-images.githubusercontent.com/13258550/195805061-3f60860c-5f69-4346-bf57-210c0b00088d.gif)

Click on "I have Sphinx" opens a pop up with QR code and "Login with Sphinx" button. 
This pop up is same as pop up that opens on "Sign in", but it does not have "Get Sphinx" part on the bottom. 

![image](https://user-images.githubusercontent.com/13258550/195949129-96fed930-1b0a-4039-87e8-5d07a182b748.png)

**Comment by ecurrencyhodler** [comment]
This is now in prod!
