### ISSUE TITLE
Sphinx Bounties [Part 2] - Bounty List [Desktop]

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#310]
This page lists all bounties.

There are 3 states of bounties - Opened (not assigned), Assigned and Paid. 
Each state has slightly different layout. All bounties have 3 parts - First part is job description, second part is price and estimate, while third part shows who is assigned.

Bounty title should be limited to two rows. 
If bounty contains video, its thumbnail should play a preview instantly, so page looks more dynamic.
If bounty contains multiple attachments (images and videos), first one should be featured as thumbnail.
Tap on description part should open a dialog with job details (this is subject of separate ticket #311 )
Tap on "I can help" button also opens a dialog (this is subject of two separate tickets. If user has a profile and is signed in, see ticket #313. If user is not signed in, see ticket #300 ).
On assigned and Paid bounties, there is a link "View profile" below name of assigned developer, and it opens his profile page.

Opened and assigned state contain colored skill labels. Skills can be randomly colored according to provided samples.
Keep in mind that each skill should always have same color, except on paid state where all elements are grayed out.

Figma project
https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/People.Sphinx-FINAL-DESIGNS?node-id=5002%3A70689

![image](https://user-images.githubusercontent.com/13258550/196553726-aee8e62f-9ad7-4ba8-af51-31a32138c867.png)

![image](https://user-images.githubusercontent.com/13258550/196553971-c90ab5c7-1fd5-4927-8606-b8304ceef564.png)

![image](https://user-images.githubusercontent.com/13258550/196553888-e78f6397-ac46-400a-ba95-2e713b476881.png)

**Comment by divyank-rs** [comment]
Hi @Antanasijevic ,

@AmitPaliwal-rs has started working on this. Please assign it to him on sphinx tickets.

**Comment by Antanasijevic** [comment]
@divyank-rs ok, assigned

**Comment by kevkevinpal** [comment]
I see this working on the latest changes, currently available on https://people-test.sphinx.chat

**Comment by kevkevinpal** [comment]
should be able to close this now, it is done for the most part any other minor issues/changes we should make a new ticket for
