### ISSUE TITLE
Sphinx Bounties [Part 5] - Details page [Desktop]

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#311]
Create bounty job detail overlay page according to provided design.
Since each bounty has 3 states - Open, Assigned and Paid - each state is indicated in top right corner.
On Paid state, vertical divider is colored light green on purpose.

Using previous / next arrows, user should be able to go through all bounties.

Figma project
https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/People.Sphinx-FINAL-DESIGNS?node-id=5078%3A42160

Screenshots:
![image](https://user-images.githubusercontent.com/13258550/196556180-c9c60186-f051-4233-bc8c-856c1d4fa7b2.png)

Job creator will have additional buttons:
- Edit
- Delete
- Mark Paid / Unpaid
- Award Badge

![image](https://user-images.githubusercontent.com/13258550/196972602-e51e30cc-c0d7-4e0a-8377-45910b049ccf.png)
![image](https://user-images.githubusercontent.com/13258550/196972690-ca99849d-b6e2-40e0-910e-6afc7d98c0b9.png)

**Comment by Antanasijevic** [comment]
https://user-images.githubusercontent.com/13258550/205624771-397001b8-31fd-4dbd-b6c1-404cb2cb0aeb.mp4

**Comment by Antanasijevic** [comment]
@AmitPaliwal-rs @divyank-rs Here are few notes based on based on version seen on
https://people-test.sphinx.chat/p
![image](https://user-images.githubusercontent.com/13258550/205915997-5693353f-3b4a-4860-80ef-45af2f9fd033.png)

**Comment by Antanasijevic** [comment]
![image](https://user-images.githubusercontent.com/13258550/208081700-63f1fc58-e841-4aad-9e2c-9c417e0aea29.png)

**Comment by AmitPaliwal-rs** [comment]
@Antanasijevic, the height of the bounty detail modal is  768px, for the same screen the height is looking the same as in the design, and for the small screen, there is a scroll bar. And for the large screen, the height is fixed to 768px because otherwise, it will leave empty spaces inside the modal, which will not look good. But if you want, i can make the modal height dynamic according to screen size.

**Comment by Antanasijevic** [comment]
Additional Notes
![image](https://user-images.githubusercontent.com/13258550/208112532-88647e9a-5af8-4734-a10b-8ad28a24b5c6.png)

**Comment by Antanasijevic** [comment]
@AmitPaliwal-rs As mentioned before, bounty ticket should have full height. Here is an preview how it will look an large monitor.
Entire content is aligned on top, except "Mark Paid" button that is aligned on bottom.
![image](https://user-images.githubusercontent.com/13258550/208113236-de7c90ae-920a-4841-895f-e39ab766f99a.png)
