### ISSUE TITLE
Sphinx Bounties [Part 1]- Top elements on Main page [Desktop]

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#312]
On Bounty page, below header and above bounty list there should be a row with following elements: 
- "Post a bounty" Button - If user is signed in, it Opens a Bounty creation dialog. If User is not signed in or does not have a profile, this button wil open onboarding dialog #300 
- Number of opened bounties
- Filter (it should be left off in this version, we will add this later)
- Number of available developers 

Styling can be found in this figma project
https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/People.Sphinx-FINAL-DESIGNS?node-id=5002%3A57046

![image](https://user-images.githubusercontent.com/13258550/196553334-62c963b0-6ec4-4396-999c-929504e06a0c.png)

**Comment by divyank-rs** [comment]
@AmitPaliwal-rs is currently working on this.

**Comment by Antanasijevic** [comment]
@divyank-rs Done, assigned to Amit.

**Comment by ecurrencyhodler** [comment]
This is missing the # of opened bounties but otherwise has been implemented. We can revisit this in the future if needed.
