### ISSUE TITLE
Sphinx Bounties [Part 4] - Discuss this Bounty dialog [Desktop]

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#313]
After user is signed up, tap on "I can help" button opens a contact dialog that allows user to get in touch with job provider on Sphinx. This is a modified Connect dialog that we already have.

Updates needed:
1 - Change text below profile picture to "Discuss this bounty with  [Job provider name] "
2 - Change font from Roboto to Barlow, according to figma design provided.
3 - Apply new styling of a blue button
4 - Add a note "Scan or paste in Sphinx" below dialog

Figma project
https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/People.Sphinx-FINAL-DESIGNS?node-id=5114%3A8406

![image](https://user-images.githubusercontent.com/13258550/200180585-b3d5240c-3d30-4d74-a63a-21f0c9f74e67.png)

**Comment by ecurrencyhodler** [comment]
This has been implemented.
