### ISSUE TITLE
Profiles: add additional profile fields to profile data model

### ISSUE THREAD

**Issue by soup20** [stakwork/sphinx-tribes#330]
**Service involved:**
Tribes server

**Goal:**
Add missing fields to the profile data model so we can store more types of profile info.

**Method:**
- The cells marked with a 'y' are what we already have. Everything else is what we need to add:

|| People Page | App | Tribe Specific |
| -------------- | ----- | ----- | ----- |
| profile picture |y|y|y|
| username |y|y|y|
| pubkey |y|y||
| bio |y|||
| price to connect |y|||
| twitter handle |y|||
| github handle |y|||
| linkedin handle ||||
| keyword (programming languages) |y|||
| github repositories |y|||
| tribes owned |y|||
| total sats contributed (integer) ||||
| total sats earned (integer)||||
| badges |y|||
|admin (boolean)||||
|reputation score (number)||||
|date joined (date)||||
|referral link||||

**Comment by Evanfeenstra** [comment]
@omoniyi24 The `profile_filter` is a column on the Tribe. So when `person/uuid/{uuid}` is called, there should also be an optional `tribe` url parameter, that contains a tribe uuid.

- if `tribe` url param exists, then get the tribe from the DB
- The Tribe's `profile_filters` is a string that can be split on the comma "," character
- the the Tribe's `profile_filters` exists, then only include the fields in the `personResponse` that are included in the filters. You need to look inside the `extras` object ... like one of the filters may be `twitter`
