### ISSUE TITLE
Leaderboard: store sats in/sats out on tribes server

### ISSUE THREAD

**Issue by soup20** [stakwork/sphinx-tribes#337]
Service involved:
tribes server

Goal:
Store the "sats in" (sats earned) and "sats out" (sats given) for each user in a tribe. This data will come from relay and will need to be passed back to relay and then client.

Method:
- create an endpoint that takes a put request from relay containing the leaderboard data
- store that data in data table
- create an endpoint that takes a tribe uuid from the app and returns the leaderboard data for that tribe

**Comment by Evanfeenstra** [comment]
@omoniyi24 an endpoint already exists called `putTribeStats`.

Add a new TEXT column on Tribes, that will take a JSON stringified array of the leaderboard from relay.

The leaderboard will be returned with all GET tribes queries, so we dont need a separate endpoint for retrieving it

**Comment by Evanfeenstra** [comment]
Ok, we decided on a new table instead

```
// route to publish ALL leaderboard for a tribe (delete old rows)
// route to update ONE member
// route to GET tribe leaderboard
type Leaderboard struct {
	TribeUuid string `json:"tribe"`
	Alias     string `json:"alias"`
	Spent     uint   `json:"spent"`
	Earned    uint   `json:"earned"`
}
```

**Comment by Evanfeenstra** [comment]
POST /leaderboard/{tribe_uuid}:
 - [{alias:'evan', earned:200, spent:100}, {alias:'kevin', earned:100, spent: 200}]
