### ISSUE TITLE
Bounty - Filter

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#357]
Create filter in top section

**Comment by Antanasijevic** [comment]
![image](https://user-images.githubusercontent.com/13258550/202269904-0d3d223b-8efa-49da-bf49-68786591fe86.png)

**Comment by Antanasijevic** [comment]
@pitoi With filter like this, we can clearly separate few different filtering options, and if needed, add more later in new column.
What do you think?

**Comment by pitoi** [comment]
This works great, but the "selected" status on Assigned wasn't noticeable to me at first glance. For the options on the right, having the selected status very clear will be important, it'd be good to see what that would look like.

**Comment by Antanasijevic** [comment]
![image](https://user-images.githubusercontent.com/13258550/203195884-48d175e4-e239-43fa-9069-5f09103bd976.png)

**Comment by pitoi** [comment]
That works!

**Comment by Antanasijevic** [comment]
Thank you, i will close this ticket and create new for bounty #369
