### ISSUE TITLE
Award badges - Option inside bounty ticket

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#361]
https://user-images.githubusercontent.com/13258550/202245806-f0fa28ce-0568-429a-9744-df9ff9c9f18e.mp4

**Comment by Antanasijevic** [comment]
@pitoi Here is a rough version of "Mark Paid" wizard, with option to adjust amount and award badge. Please, let me know if this is close to what you had in mind.

https://user-images.githubusercontent.com/13258550/202868856-279e802e-b42f-4796-9a44-71e01d5e9ced.mp4

**Comment by pitoi** [comment]
looking great. I thought about having a quantity for each badge (50 javascript points), but I think maybe a badge specific to the difficulty would be better. "Javascript Expert" badge, "Javascript Intermediate" etc.

**Comment by Antanasijevic** [comment]
Sorry, I missed to update this ticket last week. We can make a list of all skills with difficulty level for each one. With that in mind, I have modified design so more badges can be listed in a single view.

I have posted latest version in ticket #385 and will post it as bounty to Amit.
