### ISSUE TITLE
Bounty creation wizard - assigning Developer

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#364]
@pitoi This is a detail in the Bounty creation process.
Third step of wizard is about assigning developer.
User can skip this step clicking a button "Decide later" offered on the bottom.

Selection of developer can be done in two ways:

1 - (Most commonly used) User can type the developers name, filter him out, and click "Invite" button. "Decide later" button on the bottom will change into "Finish" button. Later, we can show few frequently assigned developers on top, and after that we can show full list of developers.

2 - User can also scroll through the list of developer in order to find one. Initially we can show 10-20 names (as much as we can so it does not load slowly), and after that, a small loader will show up, loading next 20 developer names. Once user is invited. rest of the names can fade out, and "Decide later" button on the bottom will change into "Finish" button.

Please, let me know if this makes sense.

Video Preview

https://user-images.githubusercontent.com/13258550/202871725-ea762732-f29c-4153-94c2-f65dcd2bffb5.mp4

**Comment by pitoi** [comment]
Only one change, the invite dev needs a filter option for skills.

**Comment by Antanasijevic** [comment]
@pitoi That is great idea, here is updated version, with skill filter included. Is this what you had in mind?

https://user-images.githubusercontent.com/13258550/203190937-b303f24e-28c1-4c19-a2cb-c6cc9e8f6aa3.mp4

**Comment by pitoi** [comment]
this looks good to go
