### ISSUE TITLE
Replit link display

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#380]
@kevkevinpal Please, for bounty ticket, use this replit logo, i believe one with the white background will look better.
![replit_logo](https://user-images.githubusercontent.com/13258550/205081885-d431abe2-527b-4eff-95ee-d516b4768fcd.png)

As we discussed, ideally, if replit link is posted in description, a "Replit" button should appear in the right side below "Github ticket" button.
![image](https://user-images.githubusercontent.com/13258550/205082759-f9ac1d41-c215-426f-b15c-34403148636e.png)

**Comment by Antanasijevic** [comment]
@kevkevinpal @pitoi Do you think it is better to generate Replit button on the right side automatically if a replit link appears in content, or should we provide them option to add that link manually (in case more than one replit links appear in content)?

**Comment by kevkevinpal** [comment]
Finished and on people page now
