### ISSUE TITLE
Assign bounty when listing my own bounty

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#384]
instead of having the words "I can help" on the main bounties page I think we should just say assign user

Here is an example, it should say assign rather than I can help on my own bounty

<img width="1443" alt="Screen Shot 2023-02-16 at 2 29 46 PM" src="https://user-images.githubusercontent.com/15950706/219479888-b07b430c-b3c3-4b4e-8961-35132b0ea20f.png">

**Comment by kevkevinpal** [comment]
Here is an example, it should say assign rather than I can help on my own bounty

<img width="1443" alt="Screen Shot 2023-02-16 at 2 29 46 PM" src="https://user-images.githubusercontent.com/15950706/219479888-b07b430c-b3c3-4b4e-8961-35132b0ea20f.png">

**Comment by Marvel-Ib** [comment]
@kevkevinpal can I try this? I see the ticket is still open on sphinx as well.

**Comment by kevkevinpal** [comment]
> @kevkevinpal can I try this? I see the ticket is still open on sphinx as well.

yes please, I can assign you on the page aswell if you're on the bounties page too

**Comment by Marvel-Ib** [comment]
yes. I am on sphinx and I sent you a dm.
