### ISSUE TITLE
Sphinx Bounties - Mark Paid wizard for Details page [Desktop]

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#385]
Click on "Mark Paid" opens a wizard.
Step 1 is "Adjust the Amount" where user has option to change the Amount to be paid.
Step 2 is "Award Badge". If no badge is selected, user clicks "Skip and mark paid" button on the bottom.
If badge is selected, button label changes into "Mark paid".
Both buttons lead back to details page, which is now marked "Paid".
A tooltip "Bounty paid" will appear below developer name, and if badge is awarded, tooltip will also indicate that.

Figma project
https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/People.Sphinx-FINAL-DESIGNS?node-id=5078%3A42160&t=HEf5KPXGcVTgH5Q6-1

Video Preview

https://user-images.githubusercontent.com/13258550/205630433-49fbac08-3766-4eae-8d43-d2d14017e1c2.mp4

**Comment by Antanasijevic** [comment]
@AmitPaliwal-rs Notes regarding Tooltip at the end of mark paid process, on Bounty detail page,
based on [this preview video](https://www.loom.com/share/eb86b41c52a94e35ab05bc79215dc2ab).

- Tooltips should not be clickable.
- Tooltip should show up after delay of 300-500 millisecond
- "Bounty paid" tooltip should appear first , and after that, "Badge awarded" if there is one.
- Both will disappear after 3-4 seconds, in same time.
- They can disappear earlier if user clicks anywhere on the screen.
- Please use fade in / out effect when revealing and closing tooltips.

**Comment by ecurrencyhodler** [comment]
Closing as this has been implemented.
