### ISSUE TITLE
Create Bounty update - Additional step

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#387]

**Comment by Antanasijevic** [comment]
@pitoi Here is version of  "Post a bounty" wizard with additional step on the beginning, where users can choose type of bounty.
Until "Live help" becomes available, we can disable this button and leave "Coming soon" label. This preview contains a version of live help wizard too.
Images used for first step are placeholders until i come up with better option, probably animated.

![image](https://user-images.githubusercontent.com/13258550/205655012-a314135b-8a29-4333-80cc-c0fe657aaf2c.png)

There is also a variation for first step, with larger boxes, which may work well if i come up with nice illustration.
![image](https://user-images.githubusercontent.com/13258550/205655086-64269ada-ba4a-4bec-b8b7-0079436c2ed8.png)

Rest of the "Freelance job request" wizard is pretty much the same, with the addition of bounty type label in the header.
Step 2 of "Live help" is slightly different than one in "Freelance job request" and contains option to upload media.

Please, check it out and let me know if you have any suggestions.

https://user-images.githubusercontent.com/13258550/205652327-66132b08-feb4-415c-875c-f70e661fa3e4.mp4

**Comment by Antanasijevic** [comment]
Updates regarding "Freelance job request" is assigned as bounty. Here is the ticket #391

**Comment by pitoi** [comment]
The layouts look great, I think we need to come up with some catchy names for the "Live" vs "Anytime" bounties.
I think the side by side layout reinforces the "or" nature of the choice.

**Comment by Antanasijevic** [comment]
In this preview, you can see process of creating new bounty, and editing existing one,
Amit will start working on last updates on monday, so i took opportunity to review entire wizard. I noticed that i missed entirely "Record loom video" in previous version, so i have included that in new one. I have created additional step called "Description" including bounty description and loom video.
When it comes to editing bounty, i think we should not repeat wizard, but maybe it would be more practical to list all fields on same page.
Please check it out, and let me know what you think.

https://user-images.githubusercontent.com/13258550/206722613-9a9b2c29-d860-489b-8696-bd6a469a6db6.mp4

**Comment by Antanasijevic** [comment]
@pitoi @kevkevinpal Here is updated version, with new icons on the start, and slightly rearranged fields.
I tried new, simplified illustration for initial step, and with addition of "Start" button, i think it may work fine.
We talked about removing "One sentence summary" field, but since this is actually a title of a bounty, I suggest we leave it but rename it into "Bounty title" so it is clear.
One thing i tried here is to move "Coding Language" to the first step, just below "Tell us about what you need help with".
Please, let me know what you  think.

https://user-images.githubusercontent.com/13258550/207317506-9d4fd137-ecbc-4817-811b-0a3f21aa5bb8.mp4

**Comment by pitoi** [comment]
this looks great, just need to make it clear the Loom is optional.

**Comment by Antanasijevic** [comment]
Great, thank you. I think a small label "Optional" below button may be prominent enough. What do you think?
![image](https://user-images.githubusercontent.com/13258550/207605773-636c3e34-7ef5-4da7-a7ae-4cac30dc6898.png)

**Comment by ecurrencyhodler** [comment]
Closing this as it's been implemented.
