### ISSUE TITLE
Sphinx Bounties - Normal, Hover and Press states

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#388]
Each ticket listed should have a Normal, Hover and Press state.
Normal state has a subtle drop shadow,
Hover has a drop shadow and a subtle green transparent outside border,
While press state has same border, without drop shadow.
All CSS values are included in this sample.

![image](https://user-images.githubusercontent.com/13258550/205665507-49f7ac62-502d-46a8-a01e-58ae098dbec5.png)

@AmitPaliwal-rs Normal, Hover and Press states should be applied on all types of bounties.
For unassigned bounty, states should be applied on white shape on the left side. I have marked shapes that should have normal, hover and press state with red color for each bounty type in this example.

![image](https://user-images.githubusercontent.com/13258550/207860293-921307d9-e3ae-437d-9c66-255619528a41.png)

**Comment by Antanasijevic** [comment]
Few notes based on current version posted on test page.

- Drop shadow is still not applied on normal state

- Hover state need some polishing. Here are some notes.


![image](https://user-images.githubusercontent.com/13258550/209685623-2d717fa7-d418-4bed-b533-c8ac3417911d.png)
![image](https://user-images.githubusercontent.com/13258550/209685656-5a3c9b21-b00d-40ac-9b2e-b9d5629ecf40.png)
![image](https://user-images.githubusercontent.com/13258550/209685673-d6c919fe-0f18-488a-90f9-9bb30cf689e7.png)

**Comment by ecurrencyhodler** [comment]
Closing this as it looks like it's been implemented. We can open a new issue if it needs refinement.
<img width="1128" alt="Screenshot 2023-09-20 at 10 52 01 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/84d95639-ee6e-4550-a548-8b7ffc93b77c">
