### ISSUE TITLE
Sphinx Bounties - Updated Bounty Creation Wizard 

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#393]
We have split bounty creation process into 5 steps.
Wizard is activated by registered user, by clicking on "Post a Bounty" button.

Please, make sure to get all of the elements styling from a "Elements" page created in same figma file.
I have defined all states for each button.

Elements
![image](https://user-images.githubusercontent.com/13258550/207617803-4ac952f7-9bb0-4ca0-b9e3-72c7e774f388.png)

Figma Project
https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/People.Sphinx-FINAL-DESIGNS?node-id=5673%3A9696

Figma Prototype
https://www.figma.com/proto/1aL3lgG5Rpkti4b0j42fwf/People.Sphinx-FINAL-DESIGNS?node-id=6497%3A11265&scaling=scale-down&page-id=5673%3A9696&starting-point-node-id=6497%3A11265&show-proto-sidebar=1

Video Preview

https://user-images.githubusercontent.com/13258550/207621402-0cbadea7-06ff-464e-af90-57a619706c73.mp4

SCREENSHOTS

Step 1

![image](https://user-images.githubusercontent.com/13258550/207624395-0c028762-6ab5-4dc9-9b4b-9ed1050cb4c0.png)

Step 2

![image](https://user-images.githubusercontent.com/13258550/207624108-491acd1e-322c-442e-9375-3e800b0016bf.png)

Step 3

![image](https://user-images.githubusercontent.com/13258550/207624160-e92f592e-5130-4541-a5eb-258433891a9b.png)

Step 4

![image](https://user-images.githubusercontent.com/13258550/207624225-c6351810-e734-40af-a672-1c7d1c702899.png)

Step 5

![image](https://user-images.githubusercontent.com/13258550/207625547-35935adc-af1a-4c68-9355-90babd13ff15.png)

Since majority of elements is already done, some of the previous comments still apply

![image](https://user-images.githubusercontent.com/13258550/207622265-c487fbe9-45ba-4eba-8eaf-e7e9eff1dd0c.png)

Seems like entire dialog breaks apart once browser size is changed. This is a screenshot of a standard browser size on laptop.

![image](https://user-images.githubusercontent.com/13258550/207622345-ff6de9b2-e687-43f6-8e30-4e03af6d7e48.png)

Few general styling corrections

![image](https://user-images.githubusercontent.com/13258550/207622447-30a886a0-1935-408c-b3d1-7d503a6080d0.png)

Notes regarding layout of modified "Invite Developer" modal that shows up on Bounty detail page,
based on [this preview video](https://www.loom.com/share/eb86b41c52a94e35ab05bc79215dc2ab).
You can check out mentioned layout details on this Figma page
https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/People.Sphinx-FINAL-DESIGNS?node-id=5673%3A9696&t=LIhJSk9Z4vgXs2pr-1

![image](https://user-images.githubusercontent.com/13258550/207622957-c94a6af1-a1f0-4f75-b427-28c71dfabc18.png)

**Comment by Antanasijevic** [comment]
@AmitPaliwal-rs @divyank-aggarwal Here are some notes based on current version published on test page.

**Step 1**
- There is a flickr on hover. Please remove it.
- Icons are smaller than ones in original design
- Change text "Find right developer for your task" into "Choose the right developer"


**Step 2**
- Small label of input fields should have font size 12px (this goes for all input fields)
- Rename "One sentence Summary" to "Bounty title"
- Rename "Tell us about what you need help with" to "Category"
- Coding language dropdown - Add option "Other" along with other coding languages. Also, alignment between two columns seems to be off, please fix that.
- Before any coding language is selected, top margin of the window is too large. Once a coding language is selected, and label shows up, whole window resizes and top margin seems to be right then. Please make all margins consistent.
- Back and Next buttons - both button sizes should be 120x42 px. In both buttons, font size should be 14px. Back button should be aligned left while Next button should be aligned right to the input field above it.


**Step 3**
- Description (and all other text fields) should not have option to resize window. A scroll bar should show up if text is too large.
- When loom video is uploaded, layout of it is not matching original design.

**Step 5**
- When skill is selected, the margin above and below labels are still off. Please check my instruction posted in previous note.

**Comment by ecurrencyhodler** [comment]
Closing this as it is in prod.
