### ISSUE TITLE
Delete Bounty

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#395]
@pitoi In the process of deleting Bounty, currently there is no clear indication about what happened.
When Bounty is deleted, next bounty immediately shows up, so it is not clear if action is performed.
I suggest we first present a modal asking "Are you sure you want to delete this Bounty?"
After that we should Show empty page with clear information that Bounty is deleted.
Something like this may work. Please, let me know what you think.

https://user-images.githubusercontent.com/13258550/207885417-feec3edd-6ad0-4893-8a0f-f8ea4dd582d1.mp4

Screenshots

![image](https://user-images.githubusercontent.com/13258550/207885982-bb7ad7e9-8d11-4b17-b596-2206f06161f4.png)

![image](https://user-images.githubusercontent.com/13258550/207886055-d5313049-3154-4abf-9ffc-2303edf6caf1.png)

**Comment by pitoi** [comment]
This looks good. For future releases, we should notify the developer if it's been assigned already. For completed bounties, the option should be to hide the bounty vs delete.

**Comment by ecurrencyhodler** [comment]
Closing this in favor of #636
