### ISSUE TITLE
Add number of active filters

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#398]
If filters are selected, we need to add a number of selected filters next to "Filter" button.
You can get styling from this Figma prototipe
https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/People.Sphinx-FINAL-DESIGNS?node-id=5002%3A50897&t=PJBXUS2ORgP2FWfA-1

![image](https://user-images.githubusercontent.com/13258550/208127062-b840ea05-68e2-4ddc-9b75-51c01a34929d.png)

**Comment by ecurrencyhodler** [comment]
Closing this as it's been implemented.
