### ISSUE TITLE
Invite or Assign Developer

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#400]

**Comment by Antanasijevic** [comment]
![image](https://user-images.githubusercontent.com/13258550/208444371-2d33f3ed-fa2e-49f1-a534-3ae74be08989.png)

![image](https://user-images.githubusercontent.com/13258550/208444664-13d76f73-bf8f-4285-976f-7c772374719c.png)

**Comment by pitoi** [comment]
This works, let's make sure the "Skip this step" option is prominent since these early tickets probably won't use this option.

**Comment by Antanasijevic** [comment]
Here is video preview of entire Bounty creation wizard, with updated step 5.
I have included option "Invite all" at the top of the list, including the number of matching developers.

https://user-images.githubusercontent.com/13258550/208681791-8ae84b78-013d-46d7-9e74-81f9c6448609.mp4

Since version of same modal will be used for assigning/inviting from Bounty page, modal will look like this

![image](https://user-images.githubusercontent.com/13258550/208682281-8f28bdb6-5543-4c51-b8e9-6d4e67ba1a15.png)
