### ISSUE TITLE
Update Edit Bounty

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#403]
@pitoi When editing a bounty, unlike wizard, all field will be listed in one page.
Header with title, "Cancel" and "Save" button will be sticky on top, so it will be always available.
In this version, we are only offering option to assign developer, but that would be expanded with invite option as soon as that option is available.

Video preview

https://user-images.githubusercontent.com/13258550/209681033-191a2456-4686-46aa-b2e4-a7b69159d46a.mp4

Full page 

![edit-bounty](https://user-images.githubusercontent.com/13258550/209680997-a785702f-beb7-4a8d-a365-9695bc53da47.jpg)

**Comment by ecurrencyhodler** [comment]
Hi @Antanasijevic ! Okay after talking with the team, it sounds like there isn't a difference between assign or invite. WDYT about removing "invite" and just keeping the "assign" button here?

**Comment by Antanasijevic** [comment]
@ecurrencyhodler In that case we should definitely remove "Invite". 
If i remember correctly, "Invite" suppose to give you option to inform selected developers that you have a bounty that may be fit for them, so they can review it and accept.

**Comment by ecurrencyhodler** [comment]
@maradondt would you mind commenting so I can assign this to you?

**Comment by maradondt** [comment]
yep sure

**Comment by ecurrencyhodler** [comment]
@maradondt adding to this one more feature. When editing a bounty and a github issue link is known, we should prevent the ability to edit description. So we can grey out that box.

**Comment by maradondt** [comment]
got it

**Comment by ecurrencyhodler** [comment]
This is available to get picked up for now. Vlad won't have time to pick this up until later. There is a bounty for [this ticket too](https://community.sphinx.chat/tickets?owner_id=021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b&created=1695703023).

**Comment by cosmicpotato137** [comment]
Happy to pick this up!

**Comment by ecurrencyhodler** [comment]
"Taking way longer than expected. Part of it is me getting used to things, but there's also some conflicts with the left and right arrow buttons when opening the edit window. I'll push what I have so far, but it still needs some tweaking and formatting." - @cosmicpotato137 
- https://github.com/stakwork/sphinx-tribes/issues/809#issuecomment-1762302841

So right now there are two views to look at a bounty. One is when viewing the profile. Another when looking at a bounty on the home page. I wonder if that's what you're referencing with the left and right arrows. We need to replace the old UI when looking at a ticket when viewing the profile with the newer when people see when viewing the bounty on the home page. This is being addressed by #715 which is being addressed by #819.

We should focus on updating the edit bounty page on the home page.

**Comment by cosmicpotato137** [comment]
I am working on the edit bounty window we see when opening a bounty from the bounties tab. The problem I'm running into is that fixing the overflow seen below causes the left/right buttons to disappear for the view bounty window as well.

![Screenshot 2023-10-13 224443](https://github.com/stakwork/sphinx-tribes/assets/54864515/d32b7a75-6f4d-4a7d-99e1-b08f08650b22)


![Screenshot 2023-10-13 224725](https://github.com/stakwork/sphinx-tribes/assets/54864515/9adf0f1a-70ad-43a4-8bf1-e4e26c2d7fe9)

**Comment by ecurrencyhodler** [comment]
If the arrows disappear when editing, that's actually something we want to happen. 

But are you saying that the arrows still don't appear after after you save it?

**Comment by cosmicpotato137** [comment]
The fix Ive found only changing the css also removes the from all screens.

**Comment by ecurrencyhodler** [comment]
Hmm okay. Well we still want to see the arrows when viewing the bounty, not when you're editing it. Maybe you can join us on our standup and show us what's going on.

**Comment by cosmicpotato137** [comment]
@ecurrencyhodler when is that happening?

**Comment by ecurrencyhodler** [comment]
Check your sphinx chat!
