### ISSUE TITLE
Community page: Authenticate in same tab

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-tribes#405]
When you sign in using Sphinx, the bounty or developer page loads in a new browser tab instead of refreshing the existing tab.
Once the user authenticates, the same browser tab should reload the page the user was on and show the signed in status. Or even better, refresh just the logged in status of the page.

**Comment by ecurrencyhodler** [comment]
Might be related to #736 too.

**Comment by ecurrencyhodler** [comment]
This is being addressed in https://github.com/stakwork/sphinx-mac/pull/130

**Comment by ecurrencyhodler** [comment]
Closed!
