### ISSUE TITLE
Claim Bounty

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#408]
User must claim ticket in order to work on it
- Set amount
- Set a date for deadline
Once you paste a deadline, amount start do decrease

That way developer does not keep ticket forever.

**Comment by Antanasijevic** [comment]
https://user-images.githubusercontent.com/13258550/211328437-89ec95a2-4a83-46b9-a655-f755dc0e294c.mp4

**Comment by ecurrencyhodler** [comment]
Closing for now
