### ISSUE TITLE
Placeholder images for People page

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#410]
@pitoi We need option to replace existing repetitive profile placeholder image, with randomly assigned image from provided collection.
Currently we have two options, one done in hand drawn style, and the other in cartoon / emoji style.

Here are previews of both versions

![test-set-1](https://user-images.githubusercontent.com/13258550/211606079-def78c38-c9e5-4106-97ef-37d24b863ce6.jpg)
![test-set-2](https://user-images.githubusercontent.com/13258550/211606087-5538df71-7504-4622-8b21-285fbaaf5191.jpg)

**Comment by devpanther** [comment]
How does the bounty work @Antanasijevic?

**Comment by maradondt** [comment]
I'll take it

**Comment by ecurrencyhodler** [comment]
Closed by #682
