### ISSUE TITLE
App to Consume Badge API

### ISSUE THREAD

**Issue by omoniyi24** [stakwork/sphinx-tribes#416]
### Task
Document all endpoints on the tribe server needed to get and list all badges for a particular user.

### Observations

The first step will be to get profile info using the publicKey

```
curl --location --request GET 'http://127.0.0.1:13000/person/{{publicKey}}' \
--data-raw ''
```
*response*
```
{
    "id": 1,
    "uuid": "cf8qhi7m1tumu3dpmnvg",
    "owner_pubkey": "03a394d0ebf0d003124ab130c6b12b8b990a50a30a464354800a51981ba745bb07",
    "owner_alias": "alice",
    "unique_name": "alice",
    "description": "this description",
    "tags": [],
    "img": "",
    "created": "2023-01-25T22:06:36.03661Z",
    "updated": "2023-01-25T22:06:36.03661Z",
    "unlisted": false,
    "deleted": false,
    "last_login": 0,
    "owner_route_hint": "",
    "owner_contact_key": "MIIBCgKCAQEA23fAE1A149o2wj+cCQzw1xDS3oUb3J1bPQuaquOdQLKM0/ZSVai0wVe5DT1JReqm5NdmLCs/akFIrxIfG9ZH+CMadnyjrfU21Xp4IMs5h0k2GjALxW8KvzTXffRLV4DcujKNTKL918iDsSHlgcdQRAXpiIE51sbpvsV+XAEhx/F3PpqDp2mSL7gTYgs85enrtAGsf/C1obP2F1QbAlSkbmw2pJ2mzKSzlIkWFKyIRqlp2G878jUkRb80aRpEAOjAp5MlKXxdVQvAXcJwbYJx4LT6GcUGCWDqlzCxQn1oo8lc8ukqKyQ+uTao8Nqs6UQ1cZTc3Pu7wvK9FqObhLNJ1wIDAQAB",
    "price_to_meet": 13,
    "extras": {
        "twitter": "mytwitter"
    },
    "twitter_confirmed": false,
    "github_issues": {},
    "new_ticket_time": 0
}
```
Then, the uuid is returned as part of the response, which can be used to get the badges.
```
curl --location --request GET 'http://127.0.0.1:13000/person/uuid/{{uuid}}' \
--data-raw ''
```
*response*
```
{
    "badges": [
        19,
        18
    ],
    "description": "this description",
    "extras": {
        "twitter": "mytwitter"
    },
    "github_issues": {},
    "id": 1,
    "img": "",
    "owner_alias": "alice",
    "owner_contact_key": "MIIBCgKCAQEA23fAE1A149o2wj+cCQzw1xDS3oUb3J1bPQuaquOdQLKM0/ZSVai0wVe5DT1JReqm5NdmLCs/akFIrxIfG9ZH+CMadnyjrfU21Xp4IMs5h0k2GjALxW8KvzTXffRLV4DcujKNTKL918iDsSHlgcdQRAXpiIE51sbpvsV+XAEhx/F3PpqDp2mSL7gTYgs85enrtAGsf/C1obP2F1QbAlSkbmw2pJ2mzKSzlIkWFKyIRqlp2G878jUkRb80aRpEAOjAp5MlKXxdVQvAXcJwbYJx4LT6GcUGCWDqlzCxQn1oo8lc8ukqKyQ+uTao8Nqs6UQ1cZTc3Pu7wvK9FqObhLNJ1wIDAQAB",
    "owner_route_hint": "",
    "price_to_meet": 13,
    "tags": [],
    "twitter_confirmed": false,
    "unique_name": "alice",
    "uuid": "cf8qhi7m1tumu3dpmnvg"
}
```
*Note*
It seems the tribe server does not expose an endpoint to get badge information for a particular user, instead, it returns just the badge IDs.

*Suggestion*
We need to expose an endpoint on tribe that takes in a {{publicKey/uuid}} and returns badges (a list) with each badge's information like the badge name, badge icon, and so on. This new endpoint can be called directly from the app to get all user badge related information.

**Comment by pitoi** [comment]
different use cases, so I'd vote to keep them separate

**Comment by omoniyi24** [comment]
Here's a draft/structure of the new API to get a profile assets

*request*
```
curl --location --request GET 'http://127.0.0.1:13000/person/uuid/{{owner_uuid}}/assets' \
--data-raw ''
```

*response*

```
{
    "owner_pubkey": "03c23e4e846662475846155c5d7152513a6d09e506b87407cd508940f9409fc4ba",
    "assets": [
        {
        "id": 24,
        "icon": "asset-icon",
        "name": "Test_Asset_1",
        "asset": "ea01e03599c66b81e005d70464c55facfce7b81eb4581623bf9adbb0248851tt",
        "token": "228f77091ffb3641af1466f2690cd9460f5390653b725eea072b6eb67a2b613e",
        "amount": 10,
        "creator": "03a394d0ebf0d003124ab130c6b12b8b990a50a30a464354800a51981ba745bb07",
        "balance": 1
    },
    {
        "id": 25,
        "icon": "asset-icon",
        "name": "Test_Asset_2",
        "asset": "as0d89f3b779185fb9feb9ec7e25ae9f783ffc1a415fc1ea02576f0562781e12",
        "token": "22a410eb98ada67119d485a40e569887efde732f46c01d45d249d7d23f83d90f",
        "amount": 10,
        "creator": "03a394d0ebf0d003124ab130c6b12b8b990a50a30a464354800a51981ba745bb07",
        "balance": 1
    }
    ]
}
```

**Comment by kevkevinpal** [comment]
> Here's a draft/structure of the new API to get a profile assets
> 
> _request_
> 
> ```
> curl --location --request GET 'http://127.0.0.1:13000/person/uuid/{{owner_uuid}}/assets' \
> --data-raw ''
> ```
> 
> _response_
> 
> ```
> {
>     "owner_pubkey": "03c23e4e846662475846155c5d7152513a6d09e506b87407cd508940f9409fc4ba",
>     "assets": [
>         {
>         "id": 24,
>         "icon": "asset-icon",
>         "name": "Test_Asset_1",
>         "asset": "ea01e03599c66b81e005d70464c55facfce7b81eb4581623bf9adbb0248851tt",
>         "token": "228f77091ffb3641af1466f2690cd9460f5390653b725eea072b6eb67a2b613e",
>         "amount": 10,
>         "creator": "03a394d0ebf0d003124ab130c6b12b8b990a50a30a464354800a51981ba745bb07",
>         "balance": 1
>     },
>     {
>         "id": 25,
>         "icon": "asset-icon",
>         "name": "Test_Asset_2",
>         "asset": "as0d89f3b779185fb9feb9ec7e25ae9f783ffc1a415fc1ea02576f0562781e12",
>         "token": "22a410eb98ada67119d485a40e569887efde732f46c01d45d249d7d23f83d90f",
>         "amount": 10,
>         "creator": "03a394d0ebf0d003124ab130c6b12b8b990a50a30a464354800a51981ba745bb07",
>         "balance": 1
>     }
>     ]
> }
> ```

lets not include the `owner_pubkey` as we are using the uuid so we don't expose the pubkey to the users of the tribe, maybe including the `unique_name` instead would work

**Comment by omoniyi24** [comment]
You're right @kevkevinpal, response updated

**Comment by omoniyi24** [comment]
In a bid to fulfill tasks with fewer API calls, I exposed an endpoint on the element server as stated on (https://github.com/stakwork/sphinx-elements/issues/3). The purpose of exposing this. The purpose of API is to keep asset logics on the element server and to prevent clients from making multiple API calls to aggregate data on the fly.

**Comment by kevkevinpal** [comment]
> In a bid to fulfill tasks with fewer API calls, I exposed an endpoint on the element server as stated on ([stakwork/sphinx-elements#3](https://github.com/stakwork/sphinx-elements/issues/3)). The purpose of exposing this. The purpose of API is to keep asset logics on the element server and to prevent clients from making multiple API calls to aggregate data on the fly.

I think this makes sense, otherwise, the solution would be getting all the badges and looping through till you get the correct badge id

**Comment by kevkevinpal** [comment]
@omoniyi24 if you do the following in the PR description it'll auto close issues when the PR merges fyi

closes Issue_Link

example:
closes  https://github.com/stakwork/sphinx-tribes/issues/416

**Comment by omoniyi24** [comment]
noted @kevkevinpal. Thank you
