### ISSUE TITLE
Bounties (idea/improvment brainstorming)

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#423]
### Payments
- Pay directly from the bounties page when paying out the bounty
- Holding a spot for a bounty by paying x sats every n minutes
- Budgeting within a tribe to allocate funds for tribe members to post bounties

### Code Cleanup
- Cleanup of the frontend codebase
- Restructuring of people tables for more efficient querying

### Other
- Better integration with replit, right now we're just linking to a repel not sure if we can embed the repel into the page
- Sign up for developers to get them on sphinx-proxy with a  free invite code

going to edit it to add more ideas

**Comment by ecurrencyhodler** [comment]
We are well on our way to completing everything in this issue except for replit (AFAIK). closing this for now
