### ISSUE TITLE
Stakwork Customer Profile Page - Create Html/CSS version

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#428]
We need Html/CSS version of three elements, marked with red square, that will later be used on Customer profile page.
Please, use Inspect feature in provided Figma design, use provided CSS info and create a  pixel perfect Html/CSS version of provided design. Beside design, Figma project contains All states of buttons and drop down menu.

-------------------------

**Figma Project**
https://www.figma.com/file/OdZC2BfeSPzFT0hREhuWig/FINAL-ADMIN-LAYOUTS?node-id=2979%3A6015&t=aNCKlzsLq3aEgeK5-1

---------------------------

If you need help finding right page inside Figma project, or need help with prototype, please check out our ["General Instructions"](https://github.com/stakwork/sphinx/issues/234) page.

For more detailed instructions, please check out ["Figma for developers" ](https://www.figma.com/best-practices/tips-on-developer-handoff/an-overview-of-figma-for-developers/)page.

---------------------

![image](https://user-images.githubusercontent.com/13258550/219727345-176ef6aa-05c4-49c7-b6f1-632ba7dd7cf8.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/13258550/219726370-a02984ca-e26c-432c-80d0-28fc2f4443f4.png)
![image](https://user-images.githubusercontent.com/13258550/219726439-09b37d19-1129-48d0-928c-4209edd40594.png)

**Comment by kevkevinpal** [comment]
@Antanasijevic are we able to close this issue?

**Comment by Antanasijevic** [comment]
@kevkevinpal Not yet, it is on hold since we had some updates
