### ISSUE TITLE
Bounty worker sphinx account

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#439]
If a user looking to take a bounty does not have a sphinx account we should make it easy to on board them.

From this screen we should create a UI where it says

Get Sphinx -> downloads based on OS -> connection code (stored on tribes DB)

In the structs.go file we can create a new table for connection codes
| Connection string | is_used | date_created

We can have two endpoints

One to obtain the latest connection code in the table where `is_used = false` and then set `is_used = true` 
GET `/v1/connection_code`
And another endpoint which we can manually use postman to add to where we can add a new connection code to the table
POST `/v1/connection_code`

<img width="566" alt="Screen Shot 2023-02-27 at 8 00 24 PM" src="https://user-images.githubusercontent.com/15950706/221733768-c296530e-aa81-416b-8b54-7145aa604df2.png">

**Comment by kevkevinpal** [comment]
@elraphty do you think you can start to take a look at this issue? We might want to first test this out in sphinx-stack or swarm for functionality

**Comment by elraphty** [comment]
> @elraphty do you think you can start to take a look at this issue? We might want to first test this out in sphinx-stack or swarm for functionality

Okay @kevkevinpal, I was working on restructuring and the allow users to post bounties without github links issues, but I have been able to access people.tribes.sphinx
