### ISSUE TITLE
[Regression] Paid bounty missing some of the bottom tile

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#477]
As you can see when we look at the paid bounty it seems the white is not covering the bottom

![Screen Shot 2023-03-21 at 9 16 55 AM](https://user-images.githubusercontent.com/15950706/226634681-fe3e1d9f-7c32-4e19-b88a-1753e97aef8c.png)
---
![Screen Shot 2023-03-21 at 9 18 05 AM](https://user-images.githubusercontent.com/15950706/226634746-348311f3-61a8-41e7-bc75-121316cd6fee.png)

**Comment by Marvel-Ib** [comment]
@kevkevinpal  just made a pr for this
