### ISSUE TITLE
[Regression] Copy bounty link from user profile page

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#478]
From a users profile page if we copy the link for the bounty we should get a link that looks like this

https://people-test.sphinx.chat/tickets?owner_id=03bfe6723c06fb2b7546df1e8ca1a17ae5c504615da32c945425ccbe8d3ca6260d&created=1679408715

instead we get one that looks like the below which doesn't open the ticket correctly when put into the browser
https://people-test.sphinx.chat/p/03bfe6723c06fb2b7546df1e8ca1a17ae5c504615da32c945425ccbe8d3ca6260d/wanted/0

**Comment by Marvel-Ib** [comment]
oops. noted
