### ISSUE TITLE
required fields in post bounty flow not clear

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#499]
It should be showing a * but not seeing any
we also want to review the whole flow in this issue

![Image](https://user-images.githubusercontent.com/15950706/228869082-d8c50e11-4309-42e0-8124-f6d7e990736d.png)

**Comment by btkcodedev** [comment]
Hi I am a new contributor, Can i work on this issue?

**Comment by ecurrencyhodler** [comment]
Hi @btkcodedev ! We would love to have you contribute. This actually has been addressed already. Apologies. But you can look on our website for open bounties so you can earn some bitcoin. Let me know if you see one you like and if you need a code to download our sphinx chat app.
https://community.sphinx.chat/bounties
