### ISSUE TITLE
Stakwork Devel Tribe Deployment Bot

### ISSUE THREAD

**Issue by Edvardoh** [stakwork/sphinx-tribes#534]
Can we create a bot that posts in the Stakwork Devel Tribe when CI has:
- started a deployment (including summary of PRs that were merged)
- finished the deployment (including status success/fail)

**Comment by kevkevinpal** [comment]
This is where the gitbot is in relay
https://github.com/stakwork/sphinx-relay/blob/master/src/builtin/git.ts

looking in the repo settings I do see webhooks for gitactions so it should be possible
![Screen Shot 2023-04-26 at 3 46 47 AM](https://user-images.githubusercontent.com/15950706/234521851-a2df504c-0c1c-475a-bcf5-7e922ba8cc21.png)

**Comment by kevkevinpal** [comment]
But I'm going to close this issue and move it to sphinx-relay as it makes more sense to have it over there will link the new issue @Edvardoh

**Comment by kevkevinpal** [comment]
@Edvardoh new issue below
https://github.com/stakwork/sphinx-relay/issues/667
