### ISSUE TITLE
[Regression] Fix tickets page on person when selected

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#541]
this commit might help because it fixed the main page
https://github.com/stakwork/sphinx-tribes/commit/a71f19da90e33aaa20f51d0592395ff4000a1414

When we click on a person with a bounty created and then try to open the modal, it sometimes shows the wrong one. We want to fix that

**Comment by Marvel-Ib** [comment]
@kevkevinpal Do you know if there is a specific trigger that leads to the wrong one being shown because the page is working as expected on my end
