### ISSUE TITLE
Bounties - Issues found

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#600]
@pitoi @kevkevinpal I was testing Bounties page using Chrome on Windows and Safari on Imac, and found same issues.
Here are few of the major ones i found.

**Bounty creation**

- Not able to create bounty with github link - i get stuck at "Finish" button.
- When i created a bounty without github link, i was not able to invite or assign developer. Tried during creation process, and by editing already created bounty, but it did not work in both cases. Same happened when i tried to assign someone by editing one of my old bounties.
- Bounty detail page showing wrong image for tribe.

**Taking Bounty**

- Not able to generate invoice so i can take a bounty.

**Other Notes**

- Sometimes I was not able to open my profile on people page at all, or It may load but very slowly. When i was able to open it, there were no old bounties visible, tab was empty. Counter next to tab name still indicates 28 bounties.

![image](https://github.com/stakwork/sphinx-tribes/assets/13258550/e84a1705-4d0e-4b81-a443-8c7bbbf07f4e)

- In the list of opened bounties one of my old bounties is not showing my name or profile picture, while other does it properly

![image](https://github.com/stakwork/sphinx-tribes/assets/13258550/ef6b9632-1487-400e-a933-160a3fa2cde2)

**Comment by ecurrencyhodler** [comment]
Closing this issue since it's been resolved.
