### ISSUE TITLE
Seeking Advice from FOSS Mobile OS Expert

### ISSUE THREAD

**Issue by uncleJim21** [stakwork/sphinx-tribes#607]
We are seeking the advice of a mobile OS expert that can advise us on best practices for interoperability with privacy focused OS's such as Calyx or Graphene.

Ideal Candidate:
- Knows the landscape of open source mobile OS options
- Understands the trade offs strengths and weaknesses of each
- Has contributed to free and open source mobile OS projects
- Has used them personally
- Can communicate their knowledge in this field effectively

Key Deliverable
- 30 minute call with our team

**Comment by ecurrencyhodler** [comment]
This has been completed through an interview Jim has conducted. @uncleJim21 would you mind updating your bounty as well that it's been paid?
