### ISSUE TITLE
Stream Youtube Mp4 WHILE It's Downloading to S3

### ISSUE THREAD

**Issue by uncleJim21** [stakwork/sphinx-tribes#616]
**Currently:** the way we do things is:
1. User goes into a video
2. The client checks if we have a copy in S3
3. When we do not, the client requests that the tribes server downloads the Youtube video
4. In the meantime, we play back the youtube video using the non-native JS based plugin

**Our Goal:**
Instead of step 4, the tribes server provides a link where the client can stream the video through the native player instead of the JS plugin, even while the download to S3 is still occurring.

**Why are we doing this?**
We are getting away from the JS plugin library and the native player provides superior performance + feature sets.

**Future Dev After this Ticket**
Provide first user opportunity to stake sats to have it included in the second brain and earn sats back when other users consume the content (link: https://github.com/stakwork/sphinx-tribes/issues/617)

**Comment by uncleJim21** [comment]
[YTDL-example 2.zip](https://github.com/stakwork/sphinx-tribes/files/12751155/YTDL-example.2.zip)

@gonzaloaune this is the example I created with node that lets you set up a server that simply sends a streamable link from a dockerized node server. I tried it in flask and that was challenging to get all the dependencies correct but the bottom line is that it is possible :)

**Comment by gonzaloaune** [comment]
@uncleJim21 that's great! I wonder how youtube-dl does it to get that streamable link, maybe we can reproduce the steps? In any case I'm tagging here @Edvardoh who's in charge of our roadmap at Stak so we know where to put it for when the time comes.

**Comment by uncleJim21** [comment]
@gonzaloaune My guess would be that it actually spins up a headless browser analyzes it and intercepts the temporary link that YouTube supplies.

At any rate this is a quite useful module in general but especially for our goal of phasing out non-native players in the apps. I could also see it being a powerful building block in use cases like feeding it into transcription engines for further use :)

**Comment by Edvardoh** [comment]
Hey Jim, appreciate the work you've done here, and it sounds like a great feature for the apps. But tbh, it's probably better to keep this in the Sphinx backend rather than a Stakwork Workflow to support streaming.

I passed it over to @tomsmith8 to work into Sphinx roadmap - do you think we could get this built with a bounty, using your node example?

**Comment by tomsmith8** [comment]
@uncleJim21 If it can be done via a bounty let's try that so lets spec out a bounty ticket together. It can always be picked up internally too.

**Comment by tomsmith8** [comment]
**Update:** After chatting with Paul we're putting this on pause for the time being.
