### ISSUE TITLE
Remove the middle arrows when editing a bounty

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-tribes#632]
Task

When editing a bounty the middle arrows which usually allow you to move between tickets still exist, although they do not do anything.

These should be removed when editing a single bounty.

![Image](https://user-images.githubusercontent.com/142233216/264625399-1b00e61b-2331-4a71-aa91-3c7a7c724a50.png)

**Comment by ecurrencyhodler** [comment]
@Marvel-Ib can you comment here so I can assign this issue to you?

**Comment by ecurrencyhodler** [comment]
Closed by ##719

**Comment by ecurrencyhodler** [comment]
Re-opening as it the arrows still need to be removed from the front page of the bounty.

**Comment by ecurrencyhodler** [comment]
@Marvel-Ib Following up. Do you think you can address the arrows when editing a bounty on the front page?
