### ISSUE TITLE
UI Improvement while entering sats (Add Commas)

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-tribes#634]
Task

When typing in Sats, it would be nice to have commas dividers appearing so it's easier to read.

E.g 1,000 & 10,000 & 100,000 1,000,000

As the user types, the commas should be placed in the correct spot.

![Image](https://user-images.githubusercontent.com/142233216/264628069-ccaf61c7-5d5f-499c-965c-fa0eac964909.png)

**Comment by ecurrencyhodler** [comment]
@Marvel-Ib can you comment here so I can assign it to you?

**Comment by Marvel-Ib** [comment]
sure

**Comment by kevkevinpal** [comment]
this should be closed now!
