### ISSUE TITLE
Deleting a bounty should trigger a warning modal to confirm

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-tribes#636]
**Task**

When tapping the option to 'delete' a Bounty, it instantly deletes the Bounty, which could be annoying if accidentally pressed.

We should present the user with a warning modal to confirm that they are sure they want to remove the bounty.

**Comment by Antanasijevic** [comment]
@tomsmith8 We actually have a design for this, you can check out demo in this ticket 
https://github.com/stakwork/sphinx-tribes/issues/395

Let me know if changes are needed so i can prepare final version

**Comment by Antanasijevic** [comment]
@ecurrencyhodler Final Figma Design assets can be found on this page

https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/People.Sphinx-FINAL-DESIGNS?type=design&node-id=7578%3A678&mode=design&t=VYCDnrEKu69YyxL8-1


Video Preview
https://user-images.githubusercontent.com/13258550/207885417-feec3edd-6ad0-4893-8a0f-f8ea4dd582d1.mp4

**Comment by Antanasijevic** [comment]
@ecurrencyhodler When i made this layout last year, Paul had this note:

"This looks good. For future releases, we should notify the developer if it's been assigned already. For completed bounties, the option should be to hide the bounty vs delete."

We can discuss these options next.

**Comment by ecurrencyhodler** [comment]
Okay. For now we should probably add a restriction to not be able to delete assigned or completed bounties.

**Comment by maradondt** [comment]
I'd take it
