### ISSUE TITLE
Remove description default where description is showing for every tile

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#643]
When a user is created their description for some reason is set as "description" in the db we should stop that from happening

![Screenshot 2023-09-06 at 4 48 20 PM](https://github.com/stakwork/sphinx-tribes/assets/15950706/1c1e099b-ec5d-4ac0-9ab5-408763ee8e2c)

### Acceptance Criteria

- [ ] Test this on Chrome
- [ ] Post a video of you creating a profile, going to the people page, and showing that the profile description is not set to "description" by default.

**Comment by kevkevinpal** [comment]
This may need to be cleaned up in the db and in the frontend code

**Comment by ecurrencyhodler** [comment]
Let's handle cleaning up the database separate. The focus of this ticket is to remove the description default where "description" is showing for every tile when a profile gets created.

**Comment by gouravmpk** [comment]
Please assign @ecurrencyhodler

**Comment by ecurrencyhodler** [comment]
@kevkevinpal can you take a crack at the backend now that #992 is done?
