### ISSUE TITLE
LNURL isn't working on the bounties website

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#649]
I am unable to log-in to the bounties website (https://community.sphinx.chat/tickets) using LNURL and wallet of satoshi.

https://github.com/stakwork/sphinx-tribes/assets/32662508/5770323b-9fbd-4f34-9283-cbc9c2eac32e

**Comment by kevkevinpal** [comment]
Some times I am able to get a proper URL and sign in with zues but see this

But for this issue @elraphty lets try to add some error handling to show an error message if we get an empty value/string for the qr code, not sure if its just showing a partial URL in the qr code


![Screenshot 2023-09-11 at 9 43 58 AM](https://github.com/stakwork/sphinx-tribes/assets/15950706/daf93149-9c0a-4055-9018-dcd8bff8cf56)


![Screenshot 2023-09-11 at 9 43 43 AM](https://github.com/stakwork/sphinx-tribes/assets/15950706/0df29428-c814-4f81-b0d6-79f268709397)

**Comment by ecurrencyhodler** [comment]
#651 is the first pass at fixing this issue.

**Comment by ecurrencyhodler** [comment]
Testing on https://people-test.sphinx.chat/tickets, I'm able to log in. However I get a weird error message from wallet of satoshi saying that there was a problem with lnurl.

Also when I sign out and I try to log back in, it shows an empty lnurl again. It only works again when we  refresh the page.

**Comment by kevkevinpal** [comment]
This is ther error I see on zues in a zip cause the screen shot was too large for github

[sphinx.mon.11.sep.03.26.40.jpg.zip](https://github.com/stakwork/sphinx-tribes/files/12580084/sphinx.mon.11.sep.03.26.40.jpg.zip)

**Comment by ecurrencyhodler** [comment]
The current version in staging allows someone to log in via LNURL. There is a tiny error message that pops up though because we aren't running our own lnurl server. We can tackle this in a separate issue.

Here's the post from raphael explaining the issue.
<img width="609" alt="Screenshot 2023-09-11 at 9 03 03 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/1a12a17a-e258-4cea-b24b-43efddbf1dba">

**Comment by ecurrencyhodler** [comment]
This has been closed by: #661 #660 #656 #663
