### ISSUE TITLE
Unable to delete bounties

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#650]
I am unable to delete a bounty. 

https://github.com/stakwork/sphinx-tribes/assets/32662508/8d3b20f6-17f7-483e-b68e-14c40066dca8

**Comment by ecurrencyhodler** [comment]
Here is the specific bounty that is persisting. 
https://community.sphinx.chat/tickets?owner_id=021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b&created=1694451587

**Comment by ecurrencyhodler** [comment]
This would be a nice stretch goal: https://github.com/orgs/stakwork/projects/24/views/1?pane=issue&itemId=37341699

**Comment by Marvel-Ib** [comment]
I will take this @ecurrencyhodler

**Comment by ecurrencyhodler** [comment]
Hey @Marvel-Ib do you know approximately when you might have some time to address this issue? Would it be possible to take a look maybe over the weekend or early next monday?

**Comment by ecurrencyhodler** [comment]
Hi @Marvel-Ib it actually this was already fixed. But we have several other bounties available if you were interested!

Let me know if you want to take one: https://community.sphinx.chat/tickets

**Comment by ecurrencyhodler** [comment]
Closed by #690
