### ISSUE TITLE
Intro message on sphinx doesn't go through

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#653]
If I reach out to bounty poster, my initial message doesn’t go through. Instead I receive a "generic.error" message. A connection does appear inside the Friends section of Sphinx though.

EDIT: This seems to occur when I attempt to connect with someone on sphinx using the QR code.

https://github.com/stakwork/sphinx-tribes/assets/32662508/25627f3f-c6dd-456a-a867-36eb8c2d0d6d

**Comment by ecurrencyhodler** [comment]
This appears to be a sphinx chat problem. Not a bounties problem.

**Comment by ecurrencyhodler** [comment]
Addressed by: https://github.com/stakwork/sphinx-relay/pull/768

Needs one more in the mac-repo.

**Comment by tomastiminskas** [comment]
@uncleJim21 do you think you can handle this on iOS and Mac?

**Comment by uncleJim21** [comment]
@tomastiminskas sure

**Comment by ecurrencyhodler** [comment]
Thanks a lot @uncleJim21!! And appreciate you @tomastiminskas chiming in.

Also dropping this issue which I think is what ya'll are talking about: https://github.com/stakwork/sphinx-ios/issues/290

**Comment by ecurrencyhodler** [comment]
Okay it also looks like there's another issue for mac: https://github.com/stakwork/sphinx-mac/issues/126

Jim will be taking both.
