### ISSUE TITLE
Sharing a bounty on twitter partially works

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#654]
Sharing a bounty on twitter works but has a couple of kinks:

- [x] Hashtag is says "undefined"
- [x] url to bounty is incorrect

https://github.com/stakwork/sphinx-tribes/assets/32662508/c5cef6f1-d11b-4f0d-99d8-cfedaa003f52

**Comment by maradondt** [comment]
I'll take it

**Comment by ecurrencyhodler** [comment]
Closed by #677
