### ISSUE TITLE
Scrolling to the bottom of the page loads new bounties but gets rid of the ones showing before

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#657]
https://user-images.githubusercontent.com/15950706/267373428-f80dcbe9-5d48-4962-9ae0-7d05d37740ad.mov

**Comment by maradondt** [comment]
take it

**Comment by ecurrencyhodler** [comment]
Hi @maradondt! Just wondering how this PR is coming along. Let me know if you need more info.

**Comment by maradondt** [comment]
Hi @ecurrencyhodler I took some day off, today gonna do this pr
