### ISSUE TITLE
Unable to unassign a bounty taker from a bounty

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#659]
I am unable to unassign a bounty taker from a bounty. I tried clicking on the "x" next to the bounty taker as well as editing the bounty, removing the bounty taker, and saving it.

https://github.com/stakwork/sphinx-tribes/assets/32662508/b1fa60ee-5124-46ec-ab41-e302552d6a40

**Comment by maradondt** [comment]
take it
