### ISSUE TITLE
Jitsi recordings are stopping after 10 minutes

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-tribes#667]
**Expected behaviour**

- When recording, Jitsi records the whole call.

**Current behaviour**

- Jitsi recordings are stopping after 10 minutes.

**Acceptance Criteria**

- Recording don't stop unless manually stopped
- Recordings should last the whole time users are on the call
- 10m issue is fixed

**Comment by akarales** [comment]
Hey I would like to ask you some questions about this issue. Pertaining to any error logs that may have been captured from the message server nodes around the time the problems occurred.

**Comment by turizspace** [comment]
is this still open for the bounty collection

**Comment by ecurrencyhodler** [comment]
Hi sorry. no it's not. We've discovered the issue and have resolved it. Are you familiar with swift? We have lots of swift bitcoin bounties for you if you are.

**Comment by turizspace** [comment]
@ecurrencyhodler where are they posted at i take a look ?

**Comment by ecurrencyhodler** [comment]
You can find them at this page: https://community.sphinx.chat/org/bounties/clf6qmo4nncmf23du7ng

Are you on sphinx chat? i can help you get a connection code to sign up if you don't.

BTW How did you hear about our project?

**Comment by turizspace** [comment]
@ecurrencyhodler i got a link off Nostr searching for bounties . that's how i got to the sphinx community and saw your entry as well ! 

I'm not on sphinx yet would like to joinand explore opportunities

**Comment by ecurrencyhodler** [comment]
Oh wow. Do you know who's account? No worries if not!

Awesome okay follow the instructions for this [FAQ](https://docs.google.com/document/d/16NQ4SM4ptP4Lz5JKERAagdNw3GFRVv9eshMZ_oU-MVw/edit?usp=sharing). You can use this sphinx code to join:

connect::relay.swarm4.sphinx.chat::02d14e01adcf94dbf2a0ca8d511b83923d97abe2472da04976a765b080db32e56e

**Comment by turizspace** [comment]
It was a blockstream note . that's how I found out about the community at sphinx. Will join with invite! Thank you

**Comment by ecurrencyhodler** [comment]
Awesome! If you could replay back with your sphinx name when you do that'll help! Also let me know if there's a specific bounty that sticks out to you. :)

**Comment by turizspace** [comment]
@ecurrencyhodler the invite didn't work

**Comment by ecurrencyhodler** [comment]
@turizspace are you on iOS? If so, can you make sure you're using testflight and not the app store version?

**Comment by ecurrencyhodler** [comment]
Can you sign in here? https://community.sphinx.chat/bounties
