### ISSUE TITLE
Clicking bounty on profile page goes to assigned users page and removes edit button

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#674]
https://github.com/stakwork/sphinx-tribes/assets/15950706/5f031965-a878-4d5f-8a3e-645c27e8533c

**Comment by ecurrencyhodler** [comment]
Thanks kev for submitting this issue! To add further context just in case: the expected outcome of clicking on a bounty inside the profile page is for the bounty to fully expand and persist. This is the same behavior as on the bounties page. 

Also the background of the profile page on the tickets tab should also stick.

Basically this screenshot:
<img width="797" alt="Screenshot 2023-09-13 at 6 23 33 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/15e0421f-1ef0-4e88-9bcf-f38f9cd23ed2">

**Comment by kevkevinpal** [comment]
This is happening on both the assigned and my bounties tabs FYI @elraphty
