### ISSUE TITLE
Left arrow on bounties page doesn't work.

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#685]
# Expected function
When I click on the left arrow on a bounty, I want to see the previous bounty as listed in the bounty overview page.

# What happens
Nothing happens when I click on the left arrow on a bounty. I am able to successfully see the next bounty if I click the right arrow.

https://github.com/stakwork/sphinx-tribes/assets/32662508/9630cffb-fb47-4c96-a535-c94cd2b2082e

**Comment by ecurrencyhodler** [comment]
@Marvel-Ib can you comment on this issue so I can assign it to you?

**Comment by ecurrencyhodler** [comment]
Closed byy #718

**Comment by ecurrencyhodler** [comment]
@Marvel-Ib are you on sphinx chat? Or do you have a lightning address I can send your awards to?

**Comment by Marvel-Ib** [comment]
@ecurrencyhodler  yes I am. It has been a while I logged in tho. I will log in noq
