### ISSUE TITLE
removing hard coded value in frontend

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#687]
We had a hardcoded value for the URL to get to the bounty from a twitter post we would want to not hard code that

https://github.com/stakwork/sphinx-tribes/pull/677/files#r1326520387

**Comment by ecurrencyhodler** [comment]
Hi @maradondt thanks for picking this up. Would you mind commenting here so I can assign this to you?

**Comment by maradondt** [comment]
> Hi @maradondt thanks for picking this up. Would you mind commenting here so I can assign this to you?

shure
