### ISSUE TITLE
Fix swarm 4 and create new connection strings

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#700]
So right now swarm 4 is working but the app frontend is not because the incorrect auth_token is being used, so 

1)I have to open the db retrieve the correct auth_token then 
2) decode from base64 
3) do this with `echo <keyinb64>  | base64 --decode`
4) replace in vol/stack/config.json the auth token
5 ) `./stop.sh relay`
6) `./restart.sh`
7) then it should be working on app.swarm4.sphinx.chat
8 ). now we need to set our user as admin

and that's where I'm stuck now

**Comment by kevkevinpal** [comment]
Was able to get this working closing
