### ISSUE TITLE
Enable sphinx code generation on mobile

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#704]
Right now, someone without a sphinx code can get one hosted by stakwork through the website. This feature is currently unavailable for mobile browsers. Rather than generating a QR code it points to the landing page to download the app. 

https://github.com/stakwork/sphinx-tribes/assets/32662508/fb74dc40-ae2b-426a-b816-701a53357236

What people should see is this flow which is already live on desktop:

https://github.com/stakwork/sphinx-tribes/assets/32662508/c262a8db-87f3-456c-9368-93addccad987

**Comment by ecurrencyhodler** [comment]
There is a [500k sat](https://community.sphinx.chat/tickets?owner_id=021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b&created=1695411402) bounty for this issue.

**Comment by ecurrencyhodler** [comment]
@maradondt would you mind commenting so I can assign this to you?

**Comment by maradondt** [comment]
sure
