### ISSUE TITLE
Add Step 1 and Step 2 to this screen.

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#705]
When I tap "get sphinx", I'm taken to this screen:
<img width="1028" alt="get sphinx" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/8cf5cb89-1e5f-45a1-a695-624c425d44aa">

We should add the text: Step 1 and Step 2 for clarity
<img width="575" alt="update" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/f8fee7ea-9bbc-4628-8ce0-55df9cd83cc1">

**Comment by deeksharungta** [comment]
Hey, I want to work on this issue. Could you please consider assigning it to me.

**Comment by ecurrencyhodler** [comment]
Hi @deeksharungta! We would love to have you contribute. 

There are two paths for a user who is not logged into the platform:
1. Click on "get sphinx" on the top right of the website (https://community.sphinx.chat/tickets)
2. Click on "Post a Bounty" on the left hand side of the website

Also are you familiar with Bitcoin and have a lightning wallet? If so, we can create a bounty for this issue for 100,000 satoshis which is approximately $26 USD. Is this something you'd be interested in?

**Comment by ecurrencyhodler** [comment]
Hi @deeksharungta! Following up here. Do you think you'll be able to take on this issue in the next couple of days?

**Comment by deeksharungta** [comment]
> Hi @deeksharungta! Following up here. Do you think you'll be able to take on this issue in the next couple of days?

Yes, I'm on it.
