### ISSUE TITLE
fix unassign user on backend

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#711]
Linking this because this is where it was partially fixed on the frontend

https://github.com/stakwork/sphinx-tribes/pull/709

**Comment by ecurrencyhodler** [comment]
How high a priority should this be @kevkevinpal? If I unassign someone on the front end while this isn't addressed, will it break anything?

**Comment by ecurrencyhodler** [comment]
This issue will make DB look ugly but makes no impact on the front end.
