### ISSUE TITLE
Text on mobile for "get sphinx" is not correctly sized.

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#752]
After #744, the text on mobile is not sized correctly. 
![IMG_3522](https://github.com/stakwork/sphinx-tribes/assets/32662508/3dd3c955-25fd-41d3-9a3c-7a6084d01158)

**Comment by ecurrencyhodler** [comment]
@maradondt would you mind resolve this as a fast follow?

**Comment by maradondt** [comment]
yeah, sure

**Comment by ecurrencyhodler** [comment]
Actually it looks like the issue was "key" instead of the icon. Maradondt's pr fixes that.
