### ISSUE TITLE
Close "Edit Bounty" window after clicking save. Return back to bounty with updated details.

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#760]
Currently when we edit a bounty and click to save our changes, nothing happens. 
https://github.com/stakwork/sphinx-tribes/assets/32662508/da463fdb-b4c3-44b5-acb7-277a0b6536c6

We should return the user back to the bounty page with updated information

**Comment by maradondt** [comment]
I'll take it too

**Comment by ecurrencyhodler** [comment]
This issue is available and has a [bounty.](https://community.sphinx.chat/tickets?owner_id=021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b&created=1696005540)

**Comment by dranoid** [comment]
I'll like to take it

**Comment by ecurrencyhodler** [comment]
Awesome @dranoid! I'll assign this to you. Are you on our [bounties website](https://community.sphinx.chat/bounties) as well? If so, I can assign the bounty for you and you can earn 300k sats (~80 USD).

**Comment by dranoid** [comment]
I'm not on the bounty website yet and I'm not too sure on how to register but I'll start with the task regardless

**Comment by ecurrencyhodler** [comment]
Okay all good. Thanks for taking this on.

If you want to get paid in bitcoin for your work, follow these steps:

1. DL sphinx chat on your phone: https://buy.sphinx.chat/
2. Ping me for a code to join (can be on github or [twitter](https://twitter.com/ecurrencyhodler))
3. Then go to this website to create a profile here by clicking "sign in": https://community.sphinx.chat/bounties

**Comment by ecurrencyhodler** [comment]
Hey @dranoid! Just wanted to follow up on this issue. How is it coming along? Do you know what you might be able to submit a PR for it?

**Comment by dranoid** [comment]
Hey @ecurrencyhodle! I had some difficulties with my laptop but it's sorted now. The issue is going along well, I'll soon be done.

**Comment by ecurrencyhodler** [comment]
Okay! copy and paste this code as a new user: connect::relay.swarm4.sphinx.chat::039e545d0d3d81228ed157b65141d837f196deae7fcc16520c1d2be5d539e224cf


Then sign up for a profile here: https://community.sphinx.chat/bounties

**Comment by ecurrencyhodler** [comment]
Thanks for submitting the PR! Great job creating a profile too. I also assigned the ticket to you on our [website](https://community.sphinx.chat/bounty/460).

Payouts will be sent straight to your sphinx chat app once we merge the pr. From there you can send it to an exchange like river financial or kraken to sell it into fiat.
