### ISSUE TITLE
Update "Add New Member" to Org Modal

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#764]
When adding a new member to an organization, they should be given full permissions at first. They can update the member's user permission after they've been added in the organization admin panel. See #772 for context. 

Use mediaquery and complete this issue for both mobile and desktop. We have designs for desktop but not for mobile specifically. That being said they should be similar. Ping @ecurrencyhodler if you have questions.

This first image we can reuse a lot of the same code that we currently have to "invite a developer" to a bounty. But make sure the dimensions, words, and everything else matches [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=9191%3A23156&mode=design&t=Gk5aWFS57j6HnKjZ-1) in dev mode.

![Image](https://github.com/stakwork/sphinx-tribes/assets/32662508/79e22a26-03c4-474e-ab5f-b51aefc1728b)

![Image](https://github.com/stakwork/sphinx-tribes/assets/32662508/95e0b70a-5f5c-4596-86a5-f244bcecfb8b)

For this section, the following permissions should be pre-selected: Manage bounties, fund organizaiton, withdraw from organization, and view txn history.

![Image](https://github.com/stakwork/sphinx-tribes/assets/32662508/31bed82f-3934-469f-bc52-7fbb4bca2b8c)

[Here's the link to figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=9191%3A23156&mode=design&t=EIRa1IRHZqFxiytM-1)
Also can use dev mode to copy/paste code: https://www.figma.com/dev-mode/

**Comment by kevkevinpal** [comment]
I was thinking instead of adding the users pubkey we can also search the users since we have all the people. It would be more user friendly than finding a pubkey and pasting it. Kinda like how we have the assign bounty flow

**Comment by ecurrencyhodler** [comment]
I like that idea a lot. The more we can abstract away from the pubkey the better. Is it titled "username" on our website? I can't tell cuz edit profile is currently broken. :(
