### ISSUE TITLE
Track metrics in the bounties platform (Postgres)

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#768]
I'd like for us to start tracking key events. This will require more scope but here are a few to start:

Feature brief: Bounties are new way of working, so we want to learn as much as we can about the process of creating and completing bounties. Metrics provide a top down factual view of results. User interviews would provide more qualitative information.

Architecture: Redis vs. gocache?

### Metrics v1
- [x] When a bounty is posted
https://github.com/stakwork/sphinx-tribes/blob/master/db/structs.go#L345
- [x]  When someone is assigned a bounty
check if were using this currently?
https://github.com/stakwork/sphinx-tribes/blob/master/db/structs.go#L360
- [x] When someone is paid
_I think a new field may need to be added, we might want to distinguish between paid through an org/the platform or just marked paid_
- [x] When an org is created
https://github.com/stakwork/sphinx-tribes/blob/master/db/structs.go#L406C2-L406C2
- [x] Amount in a bounty
- [x] Total amount paid over "x" period of time
- [x] Total bounties paid over "x" period of time
- [x] Total bounties assigned over "x" period of time
- [x] Total bounties posted over "x" period of time
- [x] % of bounties completed over "x" period of time
- [x] % of bounties paid over over "x" period of time

### v.2 for super admin
- [ ] Time to value for bounty provider: From account creation to pay out.
   _make query to lookup from bounties table backwards for their owner_id=pubkey and paid=true and then take the paid date - profile creation date_
- [ ] Time to value for bounty hunter: From account creation to getting paid.
   _make query to lookup from bounties table backwards for their assigne_pubkey=pubkey and paid=true and then take the paid date - profile creation date_

**Comment by ecurrencyhodler** [comment]
@kevkevinpal Based on our convo today, is there a basic strategy around how we would want to implement this? Are we going to go with redis or gocash?

**Comment by kevkevinpal** [comment]
> @kevkevinpal Based on our convo today, is there a basic strategy around how we would want to implement this? Are we going to go with redis or gocash?

with my convo with Gonza we can use the interface with gocache to either use redis if we provide the env vars or fall back to a local gocache if a redis instance is not defined in the env vars

**Comment by elraphty** [comment]
Figma design https://www.figma.com/file/jM4BZzPfN8K5tAUbl7gGoO/People.Sphinx-%5BDRAFTS%5D?type=design&node-id=6636-19632&mode=design&t=MnYGEQAd9Ae3jmJY-0

**Comment by ecurrencyhodler** [comment]
@elraphty Here's an image of the things we'll be tracking in the main dashboard of the super admin which will be our v1. 
![Dashboard 3](https://github.com/stakwork/sphinx-tribes/assets/32662508/a3329e1a-a8cf-4bf8-8444-5ad91e1a7031)

I'll leave more details in this ticket #778 which is still being scoped. Final wireframes are almost there.

**Comment by ecurrencyhodler** [comment]
<img width="568" alt="Screenshot 2023-11-21 at 12 52 08 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/e78b65a9-b318-4a5a-ba6b-65ad1613e1e0">
@elraphty one more update. These are the specific data we will need to track in v1.

In the front end, we will need to easily sort across timestamps specifically of bounties being paid. 
But let's also make sure we are able to filter when a bounty is posted. I may need that in the future.

**Comment by ecurrencyhodler** [comment]
@elraphty sorry. Can we add one more field to track? Date bounty was assigned.
