### ISSUE TITLE
Update user roles modals

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#773]
This is what the viewer will see when the user clicks settings which is the "gear icon" under **users** in the organization panel. They should be logged in. 

Profile pictures get pulled from website profiles in the people page. Make sure the appropriate permissions are also adjusted:

- [ ] Manage organization -> able to edit organization (access to edit button)
- [ ] Manage bounties -> able to assign a bounty to org, edit bounty, delete bounty, (un)assign bounty hunter, pay out a bounty. If this is unchecked, the user must see a greyed out pay button when attempting to pay a bounty.
- [ ] Fund organization -> able to fund the organization with bitcoin (access to fund button)
- [ ] Withdraw from organization -> able to withdraw from the organization (access to withdraw button)
- [ ] View transaction history -> able to view txn history (access to history button)
- [ ] Update members -> able to adjust user permissions for members in the organization (access to ⚙️ button)

Use mediaquery and complete this issue for both mobile and desktop. We have designs for desktop but not for mobile specifically. That being said they should be similar. Ping @ecurrencyhodler if you have questions.

![Image](https://github.com/stakwork/sphinx-tribes/assets/32662508/66f3d62d-afa9-4439-954c-67391f2490f6)

Link to [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/People.Sphinx-FINAL-DESIGNS?type=design&node-id=7776%3A6788&mode=design&t=5xwTTOxdkzEqe94W-1).

After that, the users inside the admin view of the organization tab must be updated. The first image below, the user has view txn history and user management permissions only:

![My Profile - Organization Detail - Restricted option 1 (1)](https://github.com/stakwork/sphinx-tribes/assets/32662508/1316175f-08cd-4e07-84d9-3999f30a9643)

The image below shows someone with no user permissions
![My Profile - Organization Detail- Restricted option 2](https://github.com/stakwork/sphinx-tribes/assets/32662508/121bda7f-a7f2-4998-8e98-dace66180a92)

Link to [figma.](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/People.Sphinx-FINAL-DESIGNS?type=design&node-id=7722%3A1113&mode=design&t=5xwTTOxdkzEqe94W-1)

Lastly a user should not be able to manage their own permissions. So add a tooltip when they try to manage their own.

![Image](https://github.com/stakwork/sphinx-tribes/assets/32662508/ba866ea2-e5fb-4151-bc1e-75c7b774c79f)

**Comment by cosmicpotato137** [comment]
finished updating user roles modal. Happy to keep tinkering with the org edit page. I think the MVP is done although it doesn't look like the figma.

**Comment by ecurrencyhodler** [comment]
@cosmicpotato137 Yup you're right. We currently have an mvp to add an org but not to actually edit one. Why don't you give https://github.com/orgs/stakwork/projects/24?pane=issue&itemId=40386330 a shot? It'll require knowing how to leverage the meme server which is where we host media like photos and videos. We'll also need to carefully handle orgs that already have logos uploaded to them via url. But we can discuss that on a stand up. Comment on that issue if you want to take it.

**Comment by ecurrencyhodler** [comment]
@cosmicpotato137 Thanks for submitting your PR #837. 

The last part of this bounty still remains unaddressed wrt to the fact that a user should be unable to manage their own permissions. This is handled in two ways. I should've been more explicit about this apologies. I will issue a separate bounty for this.

As you can see in the picture below, a member of an org can see all members associated with the org at any time. If there are multiple members in an org, the settings icon isn't visible for the user that is logged in. The person who is logged in should also be the first person listed as a member in the org. 

![My Profile - Organization Detail - Restricted option 1](https://github.com/stakwork/sphinx-tribes/assets/32662508/63bd1856-4d16-47f5-a00b-69d5b33561e5)

If there is only one person in the org, both the settings icon and the delete button are visible but greyed. 

![Image](https://github.com/stakwork/sphinx-tribes/assets/32662508/ba866ea2-e5fb-4151-bc1e-75c7b774c79f)

**Comment by ecurrencyhodler** [comment]
Closing this as it's addressed by #837. Remaining issues will be addressed in #888

**Comment by cosmicpotato137** [comment]
@ecurrencyhodler Thanks for the update, and sorry about that! I thought you meant that the owner wasn't allowed to manage their own permissions.

**Comment by ecurrencyhodler** [comment]
I should've been more explicit. Review the issue I created and let me know if there's an ambiguity I can clarify.
