### ISSUE TITLE
Add the following coding language and categories to the bounties website

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#779]
Add the following coding languages to the bounties website. This should be visible when adding a bounty, in the filters in the main homepage (https://community.sphinx.chat/tickets), and also when editing a bounty:

- Ruby
- Python
- Postgres
- Elastic search

<img width="697" alt="coding lang" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/dbb2f19e-fe10-47be-8e9d-743ac8718435">

These are for frameworks / libraries, Ruby on Rails, React for stakwork

Also add "Design" to category section.
<img width="700" alt="category" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/1dc7be37-3c7f-41c7-8ca2-7ff6d7c36376">

**Comment by cosmicpotato137** [comment]
I can take this.

**Comment by cosmicpotato137** [comment]
Is there an easy way to log in as a fake user when running locally? I'm still familiarizing myself with everything.

**Comment by ecurrencyhodler** [comment]
> Is there an easy way to log in as a fake user when running locally? I'm still familiarizing myself with everything.

@elraphty @kevkevinpal any advice on this?

**Comment by cosmicpotato137** [comment]
Figured it out! Just needed to reread the README
