### ISSUE TITLE
Small typing issue when creating an invoice for the organisation budget

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-tribes#784]
As per Loom, when initially typing, we should override the value.

Currently it keeps '0' in the front.

https://www.loom.com/share/e13aba65dc824a8d89bac5f579a3d3e0?sid=de547e7b-41fb-476e-854d-3bb5e0fbdcce

**Comment by ecurrencyhodler** [comment]
Hey tom. Thanks for reporting this. I'm going to include this in the scope for #766

**Comment by ecurrencyhodler** [comment]
This has been resolved by #864
