### ISSUE TITLE
Add "route hint" to copy button on a person's profile

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#788]
The route hint isn't included when I click "copy" on my profile. The routehint should also be included.
https://github.com/stakwork/sphinx-tribes/assets/32662508/4dea98f0-6897-4015-ad08-d5ce0bea3636

**Comment by Marvel-Ib** [comment]
@ecurrencyhodler @kevkevinpal  . the route hint is undefined most times as it is empty. So if added it will just be showing undefined.

**Comment by ecurrencyhodler** [comment]
Thanks marvel for taking this one. 

When a route hint is not available, can we just display the public key? That would be ideal.

**Comment by ecurrencyhodler** [comment]
>so basically if there is a route hint available i should add it. but if not i should just copy the public key.

Yes that's correct.

Like this. Here is mine for an example: 021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b:02736e7dad83d7205826649fc17db672ce08f8e87a2b47c7785ccbf79f24e91db0:1099755618305

**Comment by Marvel-Ib** [comment]
ok perfect .. that works
