### ISSUE TITLE
Delete specific profile, org, and tickets

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#797]
@kevkevin can we delete this profile (https://people-test.sphinx.chat/p/02c87de4005ec7d6256be1a018c9693ab18ec595d87cded5fdcff72c86466059b6/organizations)

This org (https://people-test.sphinx.chat/p/02c87de4005ec7d6256be1a018c9693ab18ec595d87cded5fdcff72c86466059b6/organizations)

These tickets:
1. community.sphinx.chat/tickets?owner_id=02c87de4005ec7d6256be1a018c9693ab18ec595d87cded5fdcff72c86466059b6&created=1695844685
2. https://community.sphinx.chat/p/02c87de4005ec7d6256be1a018c9693ab18ec595d87cded5fdcff72c86466059b6/wanted/444/1

**Comment by KevKevin** [comment]
Hi, I think I'm not the right "KevKevin", maybe you want @kevkevinpal

**Comment by ecurrencyhodler** [comment]
SORRY @KevKevin !
