### ISSUE TITLE
Update UI for redeeming a code

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#809]
Right now when I redeem a code for a sphinx chat through the website, it looks really messy. The first screen looks fine, it's the second screen below that looks messy. This is triggered when someone taps on the "Get sphinx" button when they are not signed in:

<img width="1194" alt="Screenshot 2023-10-11 at 12 39 43 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/5acf7f28-7348-42ea-b021-dc5ad7912830">

<img width="1107" alt="Screenshot 2023-10-11 at 12 22 03 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/eeea5fa8-725b-4e29-8351-aec7c075bf64">

Let's clean this up by adding the following screens. First is if there is a code for us to display:
<img width="624" alt="Screenshot 2023-10-11 at 12 35 59 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/2780d3c2-0846-4f2c-b2c7-b767af895170">

Next is if there is no code for us to display:
<img width="703" alt="Screenshot 2023-10-11 at 12 38 29 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/9c38f767-a565-4050-b996-e9fef8e1303e">

**Comment by cosmicpotato137** [comment]
Hey, happy to take this on!

**Comment by ecurrencyhodler** [comment]
Closed by #813

**Comment by cosmicpotato137** [comment]
Taking way longer than expected. Part of it is me getting used to things, but there's also some conflicts with the left and right arrow buttons when opening the edit window. I'll push what I have so far, but it still needs some tweaking and formatting.
