### ISSUE TITLE
When clicking on profile, default to organizations tab

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#818]
Right now when I click on the profile, it defaults going to the badges tab. Let's default to the organization tab.

https://github.com/stakwork/sphinx-tribes/assets/32662508/23e79666-6c04-48b2-9036-42cc60a1d550

**Comment by VinayK2003** [comment]
Can i work on this issue?? Please assign this to me!

**Comment by ecurrencyhodler** [comment]
Yes of course! Thank you so much!

**Comment by ecurrencyhodler** [comment]
@VinayK2003 just following up here. How is this going?

**Comment by VividhPandey003** [comment]
Hey is this still up for grabs?

**Comment by ecurrencyhodler** [comment]
Hi @VividhPandey003. It is! Will you be able to take a look at it this coming week? If so, I'll assign it to you.

**Comment by VividhPandey003** [comment]
Yes, sure. You can assign it to me. I'll make a PR max by this week.

**Comment by ecurrencyhodler** [comment]
Amazing!  I'll create a bounty for you as well for 100,000 sats. :)

**Comment by ecurrencyhodler** [comment]
Here is the [bounty](https://community.sphinx.chat/bounty/688). Download [Sphinx Chat](https://buy.sphinx.chat/) and ping me for an invitation code. 

Then create a profile on [the website](https://community.sphinx.chat/bounty/688) and I'll assign the bounty to you.

**Comment by VividhPandey003** [comment]
Thanks, I already am a part of the program., "coderturtle" is my id name on sphinx

**Comment by ecurrencyhodler** [comment]
Awesome! Assigned the bounty to you.

**Comment by VividhPandey003** [comment]
hey @ecurrencyhodler , could you please check your twitter once.

**Comment by ecurrencyhodler** [comment]
Responded.

**Comment by VividhPandey003** [comment]
@ecurrencyhodler Made a PR, please review it
