### ISSUE TITLE
Add User - Updated Flow

### ISSUE THREAD

**Issue by Antanasijevic** [stakwork/sphinx-tribes#822]
@ecurrencyhodler @pitoi Here is a updated flow, where user will be assigned roles after entering a pubkey. 
Do you think something like this will work?

https://github.com/stakwork/sphinx-tribes/assets/13258550/c1720b27-3b80-4e0a-a579-b46cea9d6928

**Comment by ecurrencyhodler** [comment]
I love this. Only feedback is to enable full permissions by default. I'll add this to the ticket #764
