### ISSUE TITLE
Return user to the same page they were on before they edited a bounty

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#850]
When I'm looking at the bounties associated with an organization and edit a bounty, it takes me back to the home page. Whatever page the user is in whether it is viewing the organization page or from their profile, they user should be returned back to the original page they were on prior to editing the bounty. 

https://github.com/stakwork/sphinx-tribes/assets/32662508/10ebd992-b714-45ea-b9fc-136e17e79cf6

**Comment by dranoid** [comment]
Hey @ecurrencyhodler, I'd like to take this on
