### ISSUE TITLE
Remove restriction of paying out a bounty when staking time expires

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#865]
Tom S is unable to pay a bounty due to this error message:
Bounty Commitment Sats have expired.
<img width="420" alt="bug" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/78966353-5a3a-41d8-9ced-4765086351de">

https://community.sphinx.chat/bounty/596

### Context
This message appears when a bounty hunter claiming a bounty stakes sats but then the staking expires. If a bounty provider tries to pay the bounty, they are prevented from doing so.

Rather than preventing payment, we should just remove the restriction for payment when time expires. The reason is because the bounty provider still has to take the initiative to pay the hunter out. So there is no need to restrict the payment.

**Comment by kevkevinpal** [comment]
we should add another button to keep the user on the bounty

**Comment by ecurrencyhodler** [comment]
Rather than adding a button, we will remove the restriction of the payment.
