### ISSUE TITLE
Copy button in a bounty inside the assigned bounty tab copies wrong url

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#884]
The copy button when looking at a bounty from the assigned bounty tab copies the wrong url.

This is the bounty: https://people-test.sphinx.chat/p/021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b/usertickets/334/1

This is the url that is copied: 
https://people-test.sphinx.chat/p/021ae436bcd40ca21396e59be8cdb5a707ceacdb35c1d2c5f23be7584cab29c40b/usertickets/334/1

It should end with the url https://people-test.sphinx.chat/bounty/XXX.

### Acceptance Criteria

- [ ] Test on desktop in Chrome 
- [ ] Test on mobile in Chrome
- [ ] Show screen recording of copy and paste with correct url

**Comment by dylanbathurst** [comment]
Fixed the issue with this PR https://github.com/stakwork/sphinx-tribes/pull/906
