### ISSUE TITLE
Skills aren't being saved and displayed on bounties

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#886]
When a skill is saved when you create or edit a bounty, it doesn't appear on the bounty on the home page. 

It also isn't appearing inside the edit bounty page where selected skills should be displayed.

https://github.com/stakwork/sphinx-tribes/assets/32662508/099e835d-5478-463a-ab8e-4e7ef8848555

### Acceptance criteria

- [ ] Tested saving it on Chrome and seeing it in the home page when creating a bounty.
- [ ] Tested saving it on Chrome and seeing it in the home page after editing a bounty.
- [ ] Tested saving it on Chrome and seeing it inside the edit bounty page.
- [ ] Post a recording or screenshots of the skill being saved and displayed.

**Comment by tobi-bams** [comment]
@ecurrencyhodler the `skills` filter you are seeing on both screens, is to help filter developers based on skills.

When you select `javascript` it means you want to see Develops with `Javascript` skills.

To add skills to a bounty, we do that with the `coding language` drop-down in step 2 of creating a bounty

**Comment by ecurrencyhodler** [comment]
Okay that's good to know. As discussed on our call, the issue still persists when I select the skill in the right area. Thanks for investigating tobi.
