### ISSUE TITLE
Unable to close the "user permission" modal.

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#887]
In staging, I am unable to close the user permission modal.

https://github.com/stakwork/sphinx-tribes/assets/32662508/214d0972-9d74-479e-a95b-faec03c9fd1d

### Acceptance criteria

- [ ] Test closing modal on Chrome
- [ ] Post screen recording of modal closing

**Comment by ecurrencyhodler** [comment]
@cosmicpotato137 can you take a look at this issue? It's related to the pr you submitted. Thanks!

**Comment by cosmicpotato137** [comment]
@ecurrencyhodler yes, I'm on it!

**Comment by cosmicpotato137** [comment]
@ecurrencyhodler I've pulled the most recent changes from sphinx-tribes, and am unable to reproduce the bug. Do you have any more info about this?

**Comment by ecurrencyhodler** [comment]
Oh interesting. @elraphty was this you? Did you address this issue?

**Comment by kevkevinpal** [comment]
I'm not seeing this issue either
