### ISSUE TITLE
Restrict logged-in user and organize users in an organization

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#888]
A user should be unable to manage their own permissions. This is handled in two ways. I should've been more explicit about this apologies. I will issue a separate bounty for this.

As you can see in the picture below, a member of an org can see all members associated with the org at any time. If there are multiple members in an org, the settings icon is greyed for the user that is logged in. 

The members should be listed by the date they joined. 

Lastly a member should not be able to update any of the settings or remove the creator of the organization at any point in time. 

![My Profile - Organization Detail - Restricted option 1 (1)](https://github.com/stakwork/sphinx-tribes/assets/32662508/96af28f7-7aa1-4cb3-b392-b1c607537242)

If there is only one person in the org, both the settings icon and the delete button are visible but greyed. 

![Image](https://github.com/stakwork/sphinx-tribes/assets/32662508/ba866ea2-e5fb-4151-bc1e-75c7b774c79f)

### Acceptance criteria

- [ ] Test on Chrome that a logged-in user is able to view themselves in an organization as a member.
- [ ] Test on Chrome that a logged-in user sees a greyed gear icon for themselves if there are multiple members. The delete button is still visible and functions as they are able to remove themselves from an org if they choose if they are able to manage memebers.
- [ ] Test on Chrome that a logged-in user is able to see a greyed out gear and delete button if they are the only person in the organization.
- [ ] A member should view a greyed out gear and delete button for the creator  (AKA the Admin) of the organization at all times.
- [ ] Post screenshots of these three scenarios in your PR

_Originally posted by @ecurrencyhodler in https://github.com/stakwork/sphinx-tribes/issues/773#issuecomment-1796601002_

**Comment by ecurrencyhodler** [comment]
@cosmicpotato137 can you comment here so i can assign this issue to you?

**Comment by cosmicpotato137** [comment]
@ecurrencyhodler I can take this. Would you be able to add me to a testing organization to preview my changes?

**Comment by ecurrencyhodler** [comment]
Yup will do!

**Comment by ecurrencyhodler** [comment]
You should be in org "Bitcoin"

**Comment by ecurrencyhodler** [comment]
Let's add this to your list today too @elraphty https://github.com/stakwork/sphinx-tribes/issues/935

**Comment by ecurrencyhodler** [comment]
We are updating this ticket. Admin of an org will never be displayed in any scenario. Code to make this work is a lot. Plus other platforms hide the admin. 

Also if there is one visible member, they will be able to remove themselves from the org. What is important is that the creator of an org is unable to remove themselves because it's possible for an org to have 0 members in it.
