### ISSUE TITLE
Fix styling issues for the bounties home page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#889]
Fix spacing under the title and border of the title.

<img width="681" alt="Screenshot 2023-11-06 at 2 29 11 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/4eda8db3-7f8b-422e-bf3d-323ea40debce">

### Acceptance criteria

- [ ] Test on chrome
- [ ] Post screenshot of changes in the PR

**Comment by VividhPandey003** [comment]
Hey is this issue still up for grabs?

**Comment by ecurrencyhodler** [comment]
Will address this with homepage revamp.
