### ISSUE TITLE
Tweaks for txn history PR

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#892]
<img width="1276" alt="Screenshot 2023-11-06 at 6 19 06 PM" src="https://user-images.githubusercontent.com/32662508/280901041-592a7972-5877-4a3e-8c07-cc6442d64839.png">

- [x] The date seems to pull the time the bounty was created but we need it to display the time it was paid. Also it'd be great if we can get the format in MM/DD/YYYY. 
- [x] The width of the transaction screen seems significantly thinner than what I see in [figma here](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=7836%3A13059&mode=design&t=4Vx0NlcvO1Dc4TGj-1). Let's widen it.
- [x] The "x" to close the screen is on the top right corner when it should be moved down a bit more according to the figma design.
- [x] We are missing deposits.
- [x] Update fonts, margins, and paddings according to figma.

_Originally posted by @ecurrencyhodler in https://github.com/stakwork/sphinx-tribes/issues/863#issuecomment-1797240679_

**Comment by tobi-bams** [comment]
@elraphty I will need you to make changes from the backend for the first task

**Comment by tobi-bams** [comment]
@ecurrencyhodler just calling your attention to the fact that, the width I used is the same width used in the figma design if you inspect it. But I can definitely add more width to make it look better.

**Comment by tobi-bams** [comment]
Also, @elraphty please can we get the migration for previous depost???

**Comment by ecurrencyhodler** [comment]
@tobi-bams thanks tobi about the figma comment. Let me check with milan.

**Comment by ecurrencyhodler** [comment]
@tobi-bams okay Milan checked on staging. He says width is good but to also check fonts, margins, paddings, etc, according to figma.

**Comment by tobi-bams** [comment]
@ecurrencyhodler I just created a PR for this, please can you create another Issue for Raphael so he returns the date that payments were made and not the date a bounty was created

**Comment by ecurrencyhodler** [comment]
Okay I will do that.
