### ISSUE TITLE
Refine designs of organization tab based on exact figma requirements

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#895]
Currently our organization tab looks like this: 
<img width="1237" alt="Screenshot 2023-11-07 at 1 54 00 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/3fab5a2d-4401-4cad-8951-c674f3905f97">

However it is off from what we have in figma: 
![My Profile - Organization Detail (2)](https://github.com/stakwork/sphinx-tribes/assets/32662508/f88c3a21-f34b-4caa-a8ea-88c141c25f75)

Update the organization tab with the proper dimensions including font, spacing, margins, colored buttons that are outlined in [figma](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=7719%3A14643&mode=design&t=Q6UM5yFEuKA6wvsT-1).

Use [dev mode](https://www.figma.com/dev-mode/) to assist you with this issue.

### Acceptance Criteria

- [ ] I have tested this in Chrome desktop and the design matches figma exactly according to dev mode.
- [ ] I have posted a screenshot in my PR

**Comment by Jeezman** [comment]
@ecurrencyhodler kindly assign this to me @jeezman

**Comment by ecurrencyhodler** [comment]
Absolutely! I'll assign the bounty as well. Thanks @Jeezman! https://community.sphinx.chat/bounty/654
