### ISSUE TITLE
Org  Roles and Bounty Payment Updates

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#898]
- An org user should not be able to add a role to another user that they don't have
- Add a Payment date field when a bounty payment is made
- Bounty Balance should be updated when a user tries to pay with the total bounty budget.

**Comment by ecurrencyhodler** [comment]
Hey Raph! Thanks for opening this issue. Let's add these items from #893 

- [ ] When a user has "manage members" enabled in permissions but doesn't another permission enabled, they shouldn't be able to add this permission to other members. Example: They have "manage members" perms but not "pay bounty", they should not be able to enable "pay bounty" for another user.
- [ ]  When a user is first added to an organization, they should be added with out "manage members" enabled.
- [ ]  A member should not be able to manage the permissions of the creator of an org (aka admin) in any situation.
