### ISSUE TITLE
[Bounty Homepage-Signed Out] Unit tests for filters

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#901]
Create a unit test for the home page for filters in the following areas listed below. We are starting with this one as it is small and to test the process:

- I should be able view my filtering options when I click on filter
- I should be able to filter open, assigned, paid
- I should be able to filter based on various skills provided in the filter

Keep unit tests in the area of where the code is for this feature. 

### Details
Here is the base ticket components: https://github.com/stakwork/sphinx-tribes/blob/db2d4e33f88d649ed00017d9a29b418dcc0be23f/frontend/app/src/pages/tickets/Tickets.tsx

The search is located here: https://github.com/stakwork/sphinx-tribes/blob/9b14decdb7903d9136cf03f3927aa295775c57d0/frontend/app/src/people/widgetViews/BountyHeader.tsx

The utils file for the filter search is located here:
https://github.com/stakwork/sphinx-tribes/blob/3aec26fd7ec1ec0233ac7fd60abdef7b358c3127/frontend/app/src/people/utils/filterValidation.ts

The active list function 

```
  const activeList = [...listSource[selectedWidget]].filter(({ body }: any) => {
    const value = { ...body };
    return (
      bountyHeaderFilter(props?.checkboxIdToSelectedMap, value?.paid, !!value?.assignee) &&
      bountyHeaderLanguageFilter(value?.codingLanguage, props?.checkboxIdToSelectedMapLanguage)
    );
  });

```

In the WidgetSwitchViewer.tsx, the following file handles the display of tickets:
https://github.com/stakwork/sphinx-tribes/blob/db2d4e33f88d649ed00017d9a29b418dcc0be23f/frontend/app/src/people/widgetViews/WidgetSwitchViewer.tsx

### Sample unit test pr
You can use [this file](https://github.com/stakwork/sphinx-tribes/pull/924/files#diff-f0b89b46db1ba9b81c6e2fd8c8e460a298afa01e7c265986dedcac378deabb44) as a template.

### Acceptance criteria

- [ ] Unit test for activeList function and the functions in filterValidation.ts
- [ ] Unit test for bountyHeaderLanguageFilter function
- [ ] Unit test for bountyHeaderFilter function
- [ ] Run unit test with wrong data intentionally to see if it fails
- [ ] Run unit tests with right data to see if it passes

**Comment by kevkevinpal** [comment]
write a unit tests which has an object we need to sort through with at least 4 different categories and the test should be able to sort and get the correct out put for each category we pick.

We should use that function for our sorting

but we don't need to do this testing if we're sorting from the backend side which I'm not sure of

**Comment by ecurrencyhodler** [comment]
Okay what goes to the backend is search, but filters are handled in the front end so we can test for that.

**Comment by ecurrencyhodler** [comment]
@cosmicpotato137 can you comment here so I can assign to you?

**Comment by cosmicpotato137** [comment]
yes, I can take this!

**Comment by cosmicpotato137** [comment]
Quick question: how do we run unit tests? Is there a way to run specific test files?

**Comment by ecurrencyhodler** [comment]
@kevkevinpal Q for you ^^

**Comment by kevkevinpal** [comment]
> Quick question: how do we run unit tests? Is there a way to run specific test files?

ya you should be able to run it with `yarn run test-jest`

you can see the command defined in the `package.json` file here https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/package.json#L21

**Comment by cosmicpotato137** [comment]
@kevkevinpal I am unable to run jest-test. Failing with the following error: 

```
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 
```
