### ISSUE TITLE
Adjust lightning deposit modal

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#907]
Right now for the lightning deposit modal, the format of 0:00 is not kept. 

<img width="1161" alt="Screenshot 2023-11-08 at 1 59 37 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/7cb96eb5-03cd-4eb0-9af3-39312ed2a8f5">

Also the modal after the time out expires needs to be updated from this:
<img width="1160" alt="Screenshot 2023-11-08 at 1 59 44 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/157cb177-7786-43a9-8268-3ede9163d176">

To this. Let's use bolded text and have it centered vertically and horizontally inside the modal. No specific requirement on font size, just make sure it is large enough to read: 
<img width="1160" alt="Screenshot 2023-11-08 at 1 59 44 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/381cb03f-b83a-4de0-bf27-93ad405a6c6e">

### Acceptance criteria

- [ ] I have tested this on desktop Chrome
- [ ] I have posted screenshots of the timer format and session expired screen

**Comment by tobi-bams** [comment]
@ecurrencyhodler I guess this should be fixed with this PR: https://github.com/stakwork/sphinx-tribes/pull/882

**Comment by ecurrencyhodler** [comment]
Yeah that makes sense. Is that okay tobi?

**Comment by tobi-bams** [comment]
Yes it is, just I might need to add the recent requirement  of adding `00:00:09`

**Comment by ecurrencyhodler** [comment]
@tobi-bams Just to make sure we're on the same page, it should have the format MM:SS.
