### ISSUE TITLE
Homepage isn't showing all the bounties

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#908]
Homepage isn't showing all the bounties that we have. I tried it with a filter and without a filter. The "load more" button stops appearing after a while. For example here is one bounty that doesn't appear: https://community.sphinx.chat/bounty/370

**With a filter of open bounties**

https://github.com/stakwork/sphinx-tribes/assets/32662508/2f78c524-3e54-4a1e-9fd9-2f6f94fdff72

**Without a filter**

https://github.com/stakwork/sphinx-tribes/assets/32662508/97b67d79-6460-4ba5-93e6-64971ab8e892

### Acceptance criteria

- [ ] I've tested on chrome desktop without a filter
- [ ] I've tested on chrome desktop with a filter
- [ ] I've posted a video of both these scenarios

**Comment by Marvel-Ib** [comment]
@ecurrencyhodler  i would like to take this

**Comment by ecurrencyhodler** [comment]
Okay. I've assigned the issue and bounty to you.
