### ISSUE TITLE
Replace deleted bounty screen at urls when bounties have been deleted

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#916]
Currently if a bounty gets deleted and a user goes to the url of the bounty page, it displays the bounty home page. Here is an example of a url of a bounty that was deleted: https://community.sphinx.chat/bounty/623

Instead let's replace it with this generic screen:
![Delete Bounty - Bounty deleted (1)](https://github.com/stakwork/sphinx-tribes/assets/32662508/1caf2291-28d6-4f21-8794-e4249c1aa665)

You can find it in [figma here.](https://www.figma.com/file/1aL3lgG5Rpkti4b0j42fwf/Bounties---FINAL-DESIGNS?type=design&node-id=8919%3A5238&mode=design&t=6qs2wBIWxBhfZb0J-1)

### Acceptance Criteria

- [ ] I have tested this on desktop Chrome
- [ ] I have posted video recording in my PR
- [ ] I have followed the code available in figma set in dev mode.

**Comment by gouravmpk** [comment]
[
  {
    "bounty": {
      "id": 633,
      "owner_id": "022b0eb6eac43c0b7e56dc8b6e8205f735a80966521f553db56deff197b0035a7f",
      "paid": true,
      "show": false,
      .
      .
      .
    },
    "assignee": {
      "id": 201,
      .
      .
      "deleted": false,                         **I think this should be True when it comes from API to achieve the desired result **
      "last_login": 1700554428,
      "owner_route_hint": "02736e7dad83d7205826649fc17db672ce08f8e87a2b47c7785ccbf79f24e91db0:1099754176513",
      "github_issues": null
    },
    "owner": {

      "extras": null,
      "github_issues": null
    },
    "organization": {
      "uuid": "",
      "name": "",
      "img": ""
    }
  }
]

**Comment by ecurrencyhodler** [comment]
@gouravmpk try this one: https://community.sphinx.chat/bounty/623

**Comment by ecurrencyhodler** [comment]
Closed by #1033
