### ISSUE TITLE
Remove assigning to self functionality

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#918]
After several user interviews, allowing a hunter to assign a bounty to themselves has created confusion. The two most recent ones are with Steven Rooke and also Ekep.

From a hunter's perspective:
1. They believe that once they assign a bounty to themselves they can start working on the issue. This may not be the case because the provider may have someone else in mind or isn't even getting notified that the bounty has been taken.  
2. They also assume they can mark the bounty as completed or even pay the bounty out themselves since they were able to assign the bounty.

From a bounty providers perspective:
1. They may not be aware a bounty has been assigned to a hunter and may have someone else in mind.
2. It also takes away the opportunity for the provider and hunter to communicate in the beginning of this process. We've seen that the greatest chance for success for bounties is for these two parties to communicate in some shape or form during this process.

In light of this we should remove this feature. How we remove it will need to be scoped out.

**Comment by Marvel-Ib** [comment]
@ecurrencyhodler  
https://github.com/stakwork/sphinx-tribes/pull/921
