### ISSUE TITLE
Save profile width randomly adjusts in edit mode.

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#926]
When I edit my profile and type in a 0 or remove values in the bounty price area, the screen width randomly changes. 

https://github.com/stakwork/sphinx-tribes/assets/32662508/c8ff5fd9-1507-43e0-bb3f-592b8177e7a0

Fix it so that the width doesn't change when there is a 0 or no value in the "Price to Meet" section. 

### Acceptance Criteria

- [ ] I have tested in chrome desktop
- [ ] I have posted a video of changes being saved
- [ ] I have posted a video of width not changing (Can be in same videO).

**Comment by Loicbtc** [comment]
I can fix the width randomly changing in edit mode
