### ISSUE TITLE
I'm unable to view the edit button of a bounty I posted  on the home page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#927]
I'm unable to view the edit button of a bounty I posted  on the home page. 

https://github.com/stakwork/sphinx-tribes/assets/32662508/626f5d0d-9952-4b5b-833f-d6ed6ae53858

### Acceptance criteria

1. Tested on chrome desktop
2. posted video showing you can edit bounty from home page.

**Comment by kevkevinpal** [comment]
hmm was there some sort of regression?

**Comment by ecurrencyhodler** [comment]
@kevkevinpal yeah. Raph is taking a look.
