### ISSUE TITLE
Unable to click on or close txn the history pop-up

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#928]
I'm unable to click on or close txn history pop-up.
https://github.com/stakwork/sphinx-tribes/assets/32662508/bc24f465-f7af-4c05-a48a-63fe3d70bc76

When I try to refresh, i get an error saying that the site is unresponsive and to exit or wait.

**Comment by ecurrencyhodler** [comment]
I'm worried this is a larger issue. We saw something similar for the user roles earlier but it mysteriously disappeared. #887

**Comment by tobi-bams** [comment]
@elraphty The issue here I guess is that we are making a lot API calls once the Organization page is mounted.

We are polling the `payment` `budget` `invoice count` `polling invoices` continually....

that's why we are getting this error: **unresponsive and to exit or wait.**
