### ISSUE TITLE
Implement unit tests for the bounties home page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#934]
Let's use this ticket to keep track of the various areas on the home page we have to create unit tests for.

### View
**View home page**
I should be able to view the listed bounties when I'm signed out

- I should be able to view all bounties created by a specific organization
- I should be able to view the listed people when I'm signed out
- I should be able to load more bounties
- I should be able to view the Login button
- I should be able to view the Get Sphinx button
- I should be able to view the Leaderboard and Post bounty button
#955

- Create a mock for the user's local storage, here's an example of mocking local storage Local Storage Mock.
- Mock the ui.meInfo data in store/ui.ts
- Be able to create and delete mock ui.meinfo.
#972 

- I should be able to test that the signed-in user details are persisted in the local storage
- I should be able to test that when signed out the user data is deleted
- I should be able to test that signed-in user details can be displayed such as the name and pubkey.
- I should be able to test that a signed-in user can update their details
- I should be able to test that a signed-in user can make an API request without getting a 401 (unauthorized error)
- I should be able to test that when a user is signed out, a user will get a 401 error if they make an API call
#971

**Filter**
- I should be able view my filtering options when I click on filter
- I should be able to filter open, assigned, paid
- I should be able to filter based on various skills provided in the filter 
#901 

## Signed in perspective
**View signed in home page**
- I should be able to view the Get Sphinx button
- I should not be able to view the Sign in button
- I should be able to view the signed-in user's image

### Bounty Creation

- Create a mock for bounties array save to local storage [peopleBounties Mock](https://robertmarshall.dev/blog/how-to-mock-local-storage-in-jest-tests/). Look at https://github.com/stakwork/sphinx-tribes/pull/995 for mocking of localstorage
- Be able to add a bounty
- Be able to update a bounty
- And also be able to delete a bounty
#996

**Comment by kevkevinpal** [comment]
https://github.com/stakwork/sphinx-tribes/issues/955
