### ISSUE TITLE
Enable right clicking to open bounty in a new window

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#942]
Right now we are unable to right click on a bounty on the homepage to open the bounty in a new window. The option to open in a new tab is not displayed in the menu.
https://github.com/stakwork/sphinx-tribes/assets/32662508/178e7c25-27b3-4971-a3c4-b9dfea38e47c

Enable this functionality on the home page (https://community.sphinx.chat/bounties), in the signed in profile page when looking at both bounties and assigned bounties tab, and finally inside of an org view page(EG https://community.sphinx.chat/org/bounties/ck95pe04nncjnaefo08g) 

### Acceptance

- [ ] Test on Chrome
- [ ] Post video of opening a bounty in the 4 areas (home page, profile: bounties, profile: assigned, and org page).

**Comment by Ekep-Obasi** [comment]
@pitoi 
I'd like to work on this

**Comment by ecurrencyhodler** [comment]
We discussed this issue on standup. One thing we realized is that bounties are being displayed as images. That is why the options in the menu have "save as". We may need to include a way to link out a bounty in some way.

**Comment by ecurrencyhodler** [comment]
Closed by #991
