### ISSUE TITLE
Create common component/function for toasts

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-tribes#947]
Create a common component or function to send out success and failure toasts.

https://github.com/stakwork/sphinx-tribes/pull/909#discussion_r1392807186

### Acceptance Criteria

- [ ] Test on Chrome to ensure there are no breaking changes
- [ ] Post a video showing a success toast

**Comment by gouravmpk** [comment]
@kevkevinpal  I saw there was already code added for addErrorToast 😅

**Comment by kevkevinpal** [comment]
ohh yea this should be good to close now thanks @gouravmpk
