### ISSUE TITLE
Disable automatic close for bounty creation modal

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#949]
**Describe the bug**
When someone is creating a bounty and clicks outside of the modal, all progress is lost.

When someone highlights a text and unclicks outside of the modal, all progress is lost.

**Expected behavior**
Modal shouldn't automatically disappear. We should disable automatic close for this modal. If it's easier, we can turn it off when simply looking at a bounty and not editing it as well.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video if it is a change in the front end

**Comment by VividhPandey003** [comment]
Hey could you please tell me the tech stack which'll be reqd for this

**Comment by VividhPandey003** [comment]
Hey @ecurrencyhodler , I wanted to get a clarification regarding this issue. Do we want the PostBounty modal to not lose data when clicking outside or just disabling autoclose when I click outside the modal by mistake

**Comment by VividhPandey003** [comment]
@ecurrencyhodler Could you please review this once.
