### ISSUE TITLE
[Bounty Homepage-Signed Out] Create unit tests for Homepage from signed-out perspective pt.1

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#955]
Create unit tests for the home page signed-out perspective in the following areas listed below:

- I should be able to view the listed bounties when I'm signed out
- I should be able to view all bounties created by a specific organization
- I should be able to view the listed people when I'm signed out
- I should be able to load more bounties

**Details**

Create mock endpoints using sinon js [Sinon npm URL](https://www.npmjs.com/package/sinon), here's an example of how to make mock API endpoints with sinon [Sinon Stub tutorial](https://mherman.org/blog/stubbing-http-requests-with-sinon/)

```
describe('GET /api/v1/movies/:id', () => {
  it('should respond with a single movie', (done) => {
    const obj = movies.single.success;
    this.get.yields(null, obj.res, JSON.stringify(obj.body));
    request.get(`${base}/api/v1/movies/4`, (err, res, body) => {
      res.statusCode.should.equal(200);
      res.headers['content-type'].should.contain('application/json');
      body = JSON.parse(body);
      body.status.should.eql('success');
      body.data[0].should.include.keys(
        'id', 'name', 'genre', 'rating', 'explicit'
      );
      body.data[0].name.should.eql('The Land Before Time');
      done();
    });
  });

  it('should throw an error if the movie does not exist', (done) => {
    const obj = movies.single.failure;
    this.get.yields(null, obj.res, JSON.stringify(obj.body));
    request.get(`${base}/api/v1/movies/999`, (err, res, body) => {
      res.statusCode.should.equal(404);
      res.headers['content-type'].should.contain('application/json');
      body = JSON.parse(body);
      body.status.should.eql('error');
      body.message.should.eql('That movie does not exist.');
      done();
    });
  });
});
```

Look in the store/main.ts file for all the required endpoints [link main.ts file, that houses all the API calls](https://github.com/stakwork/sphinx-tribes/blob/c51b46e3cd6beeece07ed2f4dce1aa23811f1fdf/frontend/app/src/store/main.ts)

### Acceptance Criteria
- Create a mock endpoint for getting all bounties endpoint, the endpoint should have pagination. Look at ```getPeopleBounties()``` function in store.ts.
- Create a mock endpoint for get all people endpoint. Look at the ```getPeople()``` function in store.ts
- Create a mock endpoint to get organization bounties. Look at the ```getOrganizationBounties()``` function in store.ts 
- Create a mock endpoint to load more bounties. Look at the  ```getPeopleBounties()``` function in store.ts, and add the pagination query.

**Comment by kevkevinpal** [comment]
I haven't used Sinon before but it looks good to me to use to mock out API calls, would be useful to have these to help test the frontend

**Comment by cosmicpotato137** [comment]
I can take this!

**Comment by ecurrencyhodler** [comment]
Cosmic won't be able to take this after all and is open to be taken.

**Comment by gouravmpk** [comment]
Please assign

**Comment by gouravmpk** [comment]
@elraphty I'm trying this but there are too many endpoints to test it will take some time

**Comment by ecurrencyhodler** [comment]
I'll add another 100,000 to the bounty.

**Comment by Khaalid-oh** [comment]
Can you assign this to me?

**Comment by kevkevinpal** [comment]
> Can you assign this to me?

added you to the bounty aswell let me know if you're running into any issues

**Comment by gouravmpk** [comment]
> > Can you assign this to me?
> 
> added you to the bounty aswell let me know if you're running into any issues

Sure

**Comment by ManyRios** [comment]
Can help with this too?

**Comment by ecurrencyhodler** [comment]
Hey manny this is for saif! Try to find another one from the bounty homepage: https://community.sphinx.chat/bounties

**Comment by Khaalid-oh** [comment]
> > Can you assign this to me?
> 
> added you to the bounty aswell let me know if you're running into any issues

Alright, will do. Thanks

**Comment by Khaalid-oh** [comment]
I created a PR for the Unit Test: https://github.com/stakwork/sphinx-tribes/pull/1226

**Comment by wright-eric** [comment]
@kevkevinpal  Please let me know if any help is needed. Or if this is open for assignment.  (Just adding myself to the queue here)

**Comment by ecurrencyhodler** [comment]
It's yours @wright-eric
