### ISSUE TITLE
Fix bad UI in profile section

### ISSUE THREAD

**Issue by VividhPandey003** [stakwork/sphinx-tribes#957]
**Describe the bug**
Right now, when one wants edit their profile, the UI is not aligned well.

![PHOTO-2023-11-17-00-15-13](https://github.com/stakwork/sphinx-tribes/assets/91251535/d720f704-fde7-45d4-903a-54c8481c0cfe)
Github profile link as well as user input needs to be in the same X-axis.

![PHOTO-2023-11-17-00-15-47](https://github.com/stakwork/sphinx-tribes/assets/91251535/209d0c45-eb1d-46eb-b03f-463bd858b904)
Same goes for twitter id as well.

![PHOTO-2023-11-17-00-16-20](https://github.com/stakwork/sphinx-tribes/assets/91251535/0f59e194-3d5c-4521-bcdb-a601ece393b6)
The dropdown menu is not appropriate wrt the question. 

From E: @VividhPandey003 Let's remove this section completely.

**Expected behavior**
Characters should be aligned inside the boxes.

**Desktop (please complete the following information):**
 - Browser - Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video if it is a change in the front end

**Comment by VividhPandey003** [comment]
I would like to work on this issue.

**Comment by ecurrencyhodler** [comment]
He is busy with school but will take a look hopefully before dec.

**Comment by VividhPandey003** [comment]
> He is busy with school but will take a look hopefully before dec.

Thank you

**Comment by VividhPandey003** [comment]
Update: Working on it

**Comment by VividhPandey003** [comment]
@ecurrencyhodler As for removing the github repositories section, I have commented out the part of code in schema. To completely removed it we would need to remove other parts of it as well in AboutView. Just wanted a confirmation on this.

Thanks
