### ISSUE TITLE
Return user back to organization page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#961]
**Describe the bug**
When someone is on the organization page and clicks on a bounty, the page auto-defaults back to the home page.

This is the url you see in the video: https://community.sphinx.chat/org/bounties/ck9drb84nncjnaefo090

https://github.com/stakwork/sphinx-tribes/assets/32662508/c48ac2f7-df75-4d96-a86d-f5b88631791b

**Expected behavior**
When a user closes the bounty, they should be returned back to the same url.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot or video if it is a change in the front end

**Comment by ecurrencyhodler** [comment]
Hi @Jeezman can you comment here so I can assign it to you?

**Comment by Jeezman** [comment]
@ecurrencyhodler I already self assigned

**Comment by ecurrencyhodler** [comment]
I meant the GitHub issue. :)
