### ISSUE TITLE
[Bounty Homepage-Signed In] Create unit tests for Homepage from a signed-out perspective pt.2

### ISSUE THREAD

**Issue by elraphty** [stakwork/sphinx-tribes#971]
Use the mock data from #972, create mock endpoints, and create
unit tests for the home page signed-out perspective in the following areas listed below:

- I should be able to test that the signed-in user details are persisted in the local storage
- I should be able to test that when signed out the user data is deleted
- I should be able to test that signed-in user details can be displayed such as the name and pubkey.
- I should be able to test that a signed-in user can update their details
- I should be able to test that a signed-in user can make an API request without getting a 401 (unauthorized error)
- I should be able to test that when a user is signed out, a user will get a 401 error if they make an API call

### Mock an API Call
Here's an example of how to mock an API call with SinonJs

[Sinon Stub tutorial](https://mherman.org/blog/stubbing-http-requests-with-sinon/)

```
describe('GET /api/v1/movies/:id', () => {
  it('should respond with a single movie', (done) => {
    const obj = movies.single.success;
    this.get.yields(null, obj.res, JSON.stringify(obj.body));
    request.get(`${base}/api/v1/movies/4`, (err, res, body) => {
      res.statusCode.should.equal(200);
      res.headers['content-type'].should.contain('application/json');
      body = JSON.parse(body);
      body.status.should.eql('success');
      body.data[0].should.include.keys(
        'id', 'name', 'genre', 'rating', 'explicit'
      );
      body.data[0].name.should.eql('The Land Before Time');
      done();
    });
  });

  it('should throw an error if the movie does not exist', (done) => {
    const obj = movies.single.failure;
    this.get.yields(null, obj.res, JSON.stringify(obj.body));
    request.get(`${base}/api/v1/movies/999`, (err, res, body) => {
      res.statusCode.should.equal(404);
      res.headers['content-type'].should.contain('application/json');
      body = JSON.parse(body);
      body.status.should.eql('error');
      body.message.should.eql('That movie does not exist.');
      done();
    });
  });
});
```

### Acceptance Criteria
Create a test that confirms that the details of a mocked signed user can be viewed, test for:

- [ ] Test for user unique name
- [ ] Test for user pubkey
- [ ] Test that the details of a mocked signout user will be empty

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler 
Could you please assign task to me?

**Comment by ecurrencyhodler** [comment]
@Ekep-Obasi another person asked for this. Let me circle back to you in two days if he doesn't respond

**Comment by Ekep-Obasi** [comment]
Alright @ecurrencyhodler
