### ISSUE TITLE
[Bounty Homepage-Signed In] Create mock data for unit tests on homepage

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#972]
Create mock data for unit tests on the homepage:

- Create a mock for the user's local storage, here's an example of mocking local storage [Local Storage Mock](https://robertmarshall.dev/blog/how-to-mock-local-storage-in-jest-tests/).
- Mock the ui.meInfo data in [store/ui.ts](https://github.com/stakwork/sphinx-tribes/blob/70462c0b4e1ef0d7a9e2e54653364589ed2cb06b/frontend/app/src/store/ui.ts)
- Be able to create and delete mock ui.meinfo.

### Info interface to mock the data
This is what is saved in local storage.

```
export interface MeInfo {
  id?: number;
  pubkey: string;
  uuid?: string;
  owner_pubkey?: string;
  owner_route_hint?: string;
  photo_url: string;
  alias: string;
  img?: string;
  owner_alias?: string;
  github_issues?: any[];
  route_hint: string;
  contact_key: string;
  price_to_meet: number;
  jwt: string;
  tribe_jwt: string;
  url: string;
  description: string;
  verification_signature: string;
  twitter_confirmed?: boolean;
  extras: Extras;
  isSuperAdmin: boolean;
  websocketToken?: string;
}
```

The ```saveProfile``` function in the [store/main.ts](https://github.com/stakwork/sphinx-tribes/blob/4de7b2884b2870c6f53e7220e7b8c9645deaefb9/frontend/app/src/store/main.ts) creates an endpoint that saves or update a user profile, then save the user details to local storage. Make an unauthorized mock call to the endpoint, then save the profile to local storage, also test that user details can be updated using the same endpoint by passing user data with an existing ID and a different description.

The ```saveBounty``` function in the [store/main.ts](https://github.com/stakwork/sphinx-tribes/blob/4de7b2884b2870c6f53e7220e7b8c9645deaefb9/frontend/app/src/store/main.ts) creates an authorized API using [SinonJS](https://www.npmjs.com/package/sinon) call to the create bounty endpoint. Make an authorized mock call to the endpoint, and it should return bounty data, also make an unauthorized call to the endpoint, and it should return a 401 error.

### Acceptance criteria

- [ ] Create a mock for the user's local storage
- [ ] Mock the ui.meInfo data in store/ui.ts
- [ ] Create and delete mock ui.meinfo

**Comment by Jeezman** [comment]
@ecurrencyhodler taking this on
