### ISSUE TITLE
Add asterisk next to bounty Title and Category

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#983]
Currently there is no asterisk to identify the necessary categories to move to the next step. Let's add the asterisk.

<img width="522" alt="Screenshot 2023-11-22 at 12 23 16 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/a72e9d1e-4425-4bb7-b702-de2467995fa9">

### Acceptance Criteria

- [ ] I've tested the bounty creation process to make sure nothing has been broken
- [ ] I've posted a screenshot displaying the asterisk

**Comment by gouravmpk** [comment]
Assign

**Comment by gouravmpk** [comment]
https://github.com/stakwork/sphinx-tribes/assets/20900042/369028a1-d5d0-4103-8abf-25cb5dcc8aca

**Comment by gouravmpk** [comment]
@ecurrencyhodler do you want to see * at all time even after The Bounty Title , Github URL and Category has something

**Comment by ecurrencyhodler** [comment]
@gouravmpk Yes.

**Comment by gouravmpk** [comment]
Okay on step 2 GitHub issue url 
Do you want that to be mandatory?

**Comment by ecurrencyhodler** [comment]
@gouravmpk No.

**Comment by gouravmpk** [comment]
https://github.com/stakwork/sphinx-tribes/issues/983
[✅ ] I've tested the bounty creation process to make sure nothing has been broken
[✅ ] I've posted a screenshot displaying the asterisk
Video:

https://github.com/stakwork/sphinx-tribes/assets/20900042/75bbbda4-5385-40f6-9121-d81cdc9918d4

@ecurrencyhodler

**Comment by ecurrencyhodler** [comment]
Perfect. LGTM. Let's get a code review. Thanks.

**Comment by ecurrencyhodler** [comment]
Closed by #992
