### ISSUE TITLE
Add Pay Button on Mobile

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#985]
**Describe the feature**

If a bounty is associated with an organization and assigned a hunter, display the pay bounty button and also enable its functionality. The user must be logged into mobile and also have the permission "manage bounty" in order to view the button.

The picture below is not pixel perfect but a wireframe. Make sure the size and shape of the pay button is the same as the other button "view tribe". But the color should be blue, the same color you would see when viewing on desktop.

<img width="313" alt="Screenshot 2023-11-22 at 1 24 21 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/1d3c0a6c-ac5f-4a27-b9b7-8f1037e5306c">

**Smartphone (please complete the following information):**
 - Device: Iphone or Android
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a screenshot

**Comment by Jeezman** [comment]
@ecurrencyhodler kindly assign this to me

**Comment by ecurrencyhodler** [comment]
Thanks! This is a really helpful one when providers are not at their desktop.

**Comment by ecurrencyhodler** [comment]
We also use mediaquery for desktop/mobile.

**Comment by Jeezman** [comment]
@ecurrencyhodler PR is up for this -> https://github.com/stakwork/sphinx-tribes/pull/1104
