### ISSUE TITLE
Add filter to people page

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#986]
Add a filter to the people page: https://community.sphinx.chat/p

This filter should access the skills people have saved on their profile. When a filter is selected, the page should dynamically display the people that meet the selected criteria. The logic will be "and" instead of "or". Therefore when multiple skills are selected, only those who fit all the specified criteria are selected. What should NOT happen is "or" where all people who have any of the skills selected appear.

**Initial state of website**
<img width="1222" alt="Screenshot 2023-11-22 at 8 43 50 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/49c845a3-2c58-4781-a021-39576c710aab">

Now see the filter is to the left of the search bar.
<img width="746" alt="Screenshot 2023-11-22 at 1 38 09 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/e89c9a57-e8a9-481c-9f43-de882b841512">

When selected, a drop down menu should appear:
<img width="744" alt="Screenshot 2023-11-22 at 1 38 51 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/e8cc57e3-7c45-47ed-9828-c59e74445e2d">

But make sure you follow the same drop shadow effect that we have enabled on the bounty homepage. It should be the same style minus the "status" section. The width should also be smaller.
<img width="748" alt="Screenshot 2023-11-22 at 1 38 32 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/55286fb5-7ff7-4f9d-886f-5802bd6d1a0b">

### Acceptance Criteria

- [ ] I have tested on Chrome
- [ ] I have posted a video of me clicking on the filter, selecting 1 skill, and the people page dynamically changing.
- [ ] I have posted a video of me clicking on the filter, selecting 2 skills, and the people page dynamically changing.

**Comment by Ekep-Obasi** [comment]
@ecurrencyhodler 

Could you please assign this issue to me?

**Comment by ecurrencyhodler** [comment]
Closed by #1048
