### ISSUE TITLE
Enable filtering of skills on homepage

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#987]
**Describe the bug**
Currently, I am unable to view bounties on the bounty homepage if I select a filter of a skill. It works when I select a status.

https://github.com/stakwork/sphinx-tribes/assets/32662508/69268cfc-3d04-4740-8381-402cda617947

**Expected behavior**
When I select a skill in the filter, the page should dynamically display bounties that meet the criteria. The logic for this will be "and" instead of "or". This logic is different from the one specified in the people page in issue #986. So if multiple skills are selected, any bounty with any of the skills tagged should be displayed. 

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video of me selecting one skill (javascript) in the filter and the homepage dynamically displaying the bounties
- [ ] I have posted a video of me selecting one skill (javascript + typescript) in the filter and the homepage dynamically displaying the bounties using "or" logic.

**Comment by VividhPandey003** [comment]
Can I work on this issue.

**Comment by ecurrencyhodler** [comment]
Assigned the bounty and issue to you!

**Comment by ecurrencyhodler** [comment]
@VividhPandey003 you have two other pending issues. Can you address this? Once you do we can circle back to this one.

**Comment by VividhPandey003** [comment]
Sure, this also works. Thanks. I'll be working on those issues soon.

**Comment by VividhPandey003** [comment]
@ecurrencyhodler could you please tell me about the complexity of this issue.

**Comment by ecurrencyhodler** [comment]
This should be medium complexity. It should be related to activelist. 

It's located in this file: https://github.com/stakwork/sphinx-tribes/blob/db2d4e33f88d649ed00017d9a29b418dcc0be23f/frontend/app/src/people/widgetViews/WidgetSwitchViewer.tsx

And here's the function:
```
const activeList = [...listSource[selectedWidget]].filter(({ body }: any) => {
    const value = { ...body };
    return (
      bountyHeaderFilter(props?.checkboxIdToSelectedMap, value?.paid, !!value?.assignee) &&
      bountyHeaderLanguageFilter(value?.codingLanguage, props?.checkboxIdToSelectedMapLanguage)
    );
  });
  ```
  
I'm also going to reduce the bounty amount on this down to 300,000 since we helped locate the issue.

**Comment by VividhPandey003** [comment]
Okay, Thanks. Working on it

**Comment by Vayras** [comment]
hi @ecurrencyhodler Is this issue available to work on ? , I think I can Implement this as I have worked on something similar to this. let me know , Thanks

**Comment by ecurrencyhodler** [comment]
I assigned issue and bounty to you!

**Comment by Vayras** [comment]
@ecurrencyhodler is this issue assigned to @VividhPandey003 ?

**Comment by ecurrencyhodler** [comment]
Oops @Vayras yes to vividh. Sorry.

**Comment by Vayras** [comment]
No problem, :)

**Comment by VividhPandey003** [comment]
@elraphty Could we please connect once if you might be free for this issue.
