### ISSUE TITLE
Add asterisk to step 3 of bounty creation process

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#988]
**Describe the bug**
There is no asterisk next to the word "Description" indicating a required field on step 3.
<img width="526" alt="Screenshot 2023-11-22 at 1 58 26 PM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/7c5d3372-fe99-4660-ba62-e9a7a933c8f4">

**Expected behavior**
Add an asterisk to Description under the following conditions:
1. Bounty is being created
2. User is on step 3
3. There is no github link included in step 2

If there is a github included in step 2, then the asterisk is not needed and shouldn't be displayed.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video of creating a bounty without a github link in step 2 and it displaying an asterisk next to description. (You can use this link: https://github.com/stakwork/sphinx-tribes/issues/987)
- [ ] I have posted a video of creating a bounty with a github link in step 2 and there is no asterisk next to description.

**Comment by gouravmpk** [comment]
Assign

**Comment by gouravmpk** [comment]
#988
[✅ ] I have tested on Chrome desktop
[✅ ] I have posted a video of creating a bounty without a github link in step 2 and it displaying an asterisk next to description. 
[✅ ] I have posted a video of creating a bounty with a github link in step 2 and there is no asterisk next to description.

Video:

https://github.com/stakwork/sphinx-tribes/assets/20900042/75bbbda4-5385-40f6-9121-d81cdc9918d4

@ecurrencyhodler

**Comment by ecurrencyhodler** [comment]
Thanks for posting a video! In the future you only need to do it in your PR. Great job.

**Comment by ecurrencyhodler** [comment]
Closed by https://github.com/stakwork/sphinx-tribes/pull/992
