### ISSUE TITLE
Set bounty homepage to default to open bounties using filter

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#997]
Right now the bounty homepage defaults to all bounties. Let's default to just only open bounties to make it easier for hunters to find bounties.

We already have a filtering system. Let's use it and set that as the default. No design or UI changes are necessary. Make sure it matches the look of the screenshot below.
<img width="1396" alt="default" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/0e6add99-e3af-4697-9065-67c3309807bb">

Also notice that when someone clicks on the filter, they'll see that the "open" filter is explicitly marked. 
<img width="1406" alt="filter" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/60d3ad45-2028-45d3-9a66-c0605d414ac6">

**Comment by gouravmpk** [comment]
Please assign

**Comment by gouravmpk** [comment]
This is Done Please check PR : https://github.com/stakwork/sphinx-tribes/pull/1022
@ecurrencyhodler

**Comment by ecurrencyhodler** [comment]
Closed by #1032
