### ISSUE TITLE
Fix url regression in org url page when viewing a bounty.

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#998]
**Describe the bug**
When viewing the org bounty page viewing a specific bounty, the url has switched to https://people-test.sphinx.chat/org/bounty/789 instead of https://people-test.sphinx.chat/bounty/789.

When https://people-test.sphinx.chat/org/bounty/789 is entered independently, this sends people to a 404 page. 
<img width="714" alt="Screenshot 2023-11-25 at 11 55 37 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/62b418b5-ae0f-4ef2-8da6-7582186d4a2a">

This was most likely introduced by #966 

Let's have it so that when I click to view a bounty, the correct url is displayed: https://people-test.sphinx.chat/bounty/789.

**Comment by ecurrencyhodler** [comment]
@Jeezman looks like we missed this during testing. Would you be able to take a look at this?

**Comment by gouravmpk** [comment]
Assign
Is it fine ??
@ecurrencyhodler 
https://github.com/stakwork/sphinx-tribes/assets/20900042/eb5edf18-c306-4d41-ac9c-f8342c4d9a85

**Comment by ecurrencyhodler** [comment]
@gouravmpk The video shows you are on the home page not viewing from an organization page. This issue is specifically discussing looking at a bounty from an organization page.

**Comment by gouravmpk** [comment]
What's the flow of the UI?
Can you tell me !
so that I can check if this change works or not

**Comment by ecurrencyhodler** [comment]
@gouravmpk Let's have @Jeezman handle this because he has more context. You can work on a different bounty!
